import { useState, type FormEvent } from "react";
import type { DemoProduct } from "../types";
import { demoStore } from "../storage";
import { normalizePhone, validName } from "../mock-ai";

export function TransactionModal({ mode, product, need, onClose, onSuccess }: { mode:"lead"|"quote"|"appointment"; product?:DemoProduct; need:string; onClose:()=>void; onSuccess:(text:string)=>void }) {
  const [name,setName]=useState(""); const [phone,setPhone]=useState(""); const [quantity,setQuantity]=useState(1); const [date,setDate]=useState(""); const [time,setTime]=useState("09:00"); const [channel,setChannel]=useState("Điện thoại"); const [error,setError]=useState("");
  const title=mode==="lead"?"Chuyển nhân viên tư vấn":mode==="quote"?"Yêu cầu báo giá":"Đặt lịch tư vấn";
  const submit=(e:FormEvent)=>{e.preventDefault(); const normalized=normalizePhone(phone); if(!validName(name)){setError("Vui lòng nhập họ tên hợp lệ.");return} if(!normalized){setError("Số điện thoại Việt Nam chưa hợp lệ.");return} const now=new Date().toISOString(); if(mode==="appointment"&&(!date||new Date(`${date}T${time}`)<=new Date())){setError("Vui lòng chọn thời gian trong tương lai.");return} if(mode==="lead") demoStore.addLead({id:`LEAD-${Date.now().toString().slice(-6)}`,name:name.trim(),phone:normalized,need,product:product?.productName,status:"new",createdAt:now}); if(mode==="quote"&&product) demoStore.addQuotation({id:`BG-${Date.now().toString().slice(-6)}`,product:product.productName,quantity,customerName:name.trim(),phone:normalized,total:product.price*quantity,status:"submitted",createdAt:now}); if(mode==="appointment") demoStore.addAppointment({id:`LH-${Date.now().toString().slice(-6)}`,customerName:name.trim(),phone:normalized,date,time,channel,status:"scheduled",createdAt:now}); onSuccess(mode==="lead"?"Đã ghi nhận thông tin. Nhân viên tư vấn sẽ liên hệ sớm.":mode==="quote"?"Đã tạo yêu cầu báo giá. Giá hiển thị chỉ mang tính tham khảo.":"Đã đặt lịch tư vấn thành công."); onClose(); };
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4" role="dialog" aria-modal="true" aria-labelledby="transaction-title"><form onSubmit={submit} className="w-full max-w-lg space-y-4 rounded-2xl bg-white p-6 shadow-xl"><div><p className="text-sm font-semibold text-blue-700">Thông tin liên hệ</p><h2 id="transaction-title" className="text-xl font-bold">{title}</h2><p className="mt-1 text-xs text-amber-700">Không nhập dữ liệu cá nhân thật vào bản demo.</p></div>{product&&<div className="rounded-lg bg-slate-50 p-3 text-sm"><strong>{product.productName}</strong>{mode==="quote"&&<p className="mt-1 text-blue-700">Tạm tính: {(product.price*quantity).toLocaleString("vi-VN")}đ</p>}</div>}<label className="block text-sm font-medium">Họ tên<input value={name} onChange={e=>setName(e.target.value)} className="mt-1 h-10 w-full rounded-md border px-3" required /></label><label className="block text-sm font-medium">Số điện thoại<input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="0912 345 678" className="mt-1 h-10 w-full rounded-md border px-3" required /></label>{mode==="quote"&&<label className="block text-sm font-medium">Số lượng<input type="number" min={1} max={999} value={quantity} onChange={e=>setQuantity(Number(e.target.value))} className="mt-1 h-10 w-full rounded-md border px-3" /></label>}{mode==="appointment"&&<div className="grid grid-cols-2 gap-3"><label className="text-sm font-medium">Ngày<input type="date" value={date} onChange={e=>setDate(e.target.value)} className="mt-1 h-10 w-full rounded-md border px-2" /></label><label className="text-sm font-medium">Giờ<input type="time" value={time} onChange={e=>setTime(e.target.value)} className="mt-1 h-10 w-full rounded-md border px-2" /></label><label className="col-span-2 text-sm font-medium">Hình thức<select value={channel} onChange={e=>setChannel(e.target.value)} className="mt-1 h-10 w-full rounded-md border px-2"><option>Điện thoại</option><option>Email</option><option>Zalo</option><option>Video call</option><option>Tư vấn trực tiếp</option></select></label></div>}{error&&<p role="alert" className="text-sm text-rose-600">{error}</p>}<div className="flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-lg border px-4 py-2 text-sm font-semibold">Hủy</button><button type="submit" className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white">Xác nhận</button></div></form></div>;
}
