import { CicHistoryLog } from './types';

export const mockHistoryLogs: CicHistoryLog[] = [
  {
    id: 'log_1001',
    created_time: '2026-08-02 18:25:12',
    username: 'admin_cic',
    user_fullname: 'Nguyễn Văn Quản Trị',
    type: 'Update',
    service_name: 'Permission Management',
    description: 'Cập nhật phân quyền thành công cho tài khoản minh_bien (Trần Biên Minh). Đã cấp quyền chỉnh sửa field Description và Title.',
    ip_address: '113.190.232.45',
    user_agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
    published: true,
    request_data: { userId: 'usr_002', grantedTaskIds: ['tsk_news_edit', 'tsk_prod_edit'] },
    response_data: { status: 200, message: 'Permissions updated successfully' },
  },
  {
    id: 'log_1002',
    created_time: '2026-08-02 17:40:05',
    username: 'phuong_kinhdoanh',
    user_fullname: 'Phạm Mai Phương',
    type: 'Create',
    service_name: 'Product Catalog',
    description: 'Thêm mới phần mềm "CIC-SAP2000 Enterprise v25" vào hệ thống danh mục sản phẩm phần mềm xây dựng.',
    ip_address: '14.225.21.109',
    user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/127.0.0.0',
    published: true,
    request_data: { product_code: 'PROD_SAP2000_E25', category: 'Phần mềm Kết cấu' },
    response_data: { status: 201, message: 'Product created successfully' },
  },
  {
    id: 'log_1003',
    created_time: '2026-08-02 16:15:30',
    username: 'system_bot',
    user_fullname: 'Hệ thống Tự động CIC',
    type: 'Expired',
    service_name: 'License Manager',
    description: 'Khóa bản quyền dùng thử phần mềm CIC-GeoStructure của tài khoản demo_user_99 do đã hết hạn 30 ngày dùng thử.',
    ip_address: '127.0.0.1',
    user_agent: 'CIC-CronWorker/2.1',
    published: true,
    request_data: { target_account: 'demo_user_99', license_type: 'TRIAL' },
    response_data: { action: 'DISABLE_KEY', expired_at: '2026-08-02T16:00:00Z' },
  },
  {
    id: 'log_1004',
    created_time: '2026-08-02 15:02:11',
    username: 'hoang_kythuat',
    user_fullname: 'Lê Huy Hoàng',
    type: 'Warning',
    service_name: 'Product Catalog',
    description: 'Cảnh báo: Dữ liệu tải lên cho file hướng dẫn sử dụng CIC-ETABS v21 vượt quá dung lượng cho phép (120MB > 100MB). Đã nén tự động trước khi lưu.',
    ip_address: '27.72.60.18',
    user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Edge/126.0.0.0',
    published: false,
    request_data: { file_name: 'CIC_ETABS_v21_UserManual.pdf', original_size_mb: 120.4 },
    response_data: { compress_ratio: '35%', final_size_mb: 78.2 },
  },
  {
    id: 'log_1005',
    created_time: '2026-08-02 14:10:00',
    username: 'unknown_guest',
    user_fullname: 'Khách chưa định danh',
    type: 'Error',
    service_name: 'Authentication API',
    description: 'Thất bại: Đăng nhập sai mật khẩu quá 5 lần từ địa chỉ IP. Tài khoản admin_cic đã tự động bị khóa tạm thời trong 15 phút.',
    ip_address: '185.220.101.5',
    user_agent: 'Python-urllib/3.10',
    published: false,
    request_data: { target_user: 'admin_cic', failed_attempts: 5 },
    response_data: { status: 401, error: 'TOO_MANY_FAILED_ATTEMPTS', lock_minutes: 15 },
  },
  {
    id: 'log_1006',
    created_time: '2026-08-02 11:30:45',
    username: 'phuong_kinhdoanh',
    user_fullname: 'Phạm Mai Phương',
    type: 'Delete',
    service_name: 'Static Pages',
    description: 'Xóa trang tĩnh tạm ngưng sử dụng "Quy trình đăng ký tài khoản cũ 2024" khỏi hệ thống CMS.',
    ip_address: '14.225.21.109',
    user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/127.0.0.0',
    published: true,
    request_data: { page_id: 'page_old_reg_2024' },
    response_data: { status: 200, message: 'Page deleted successfully' },
  },
  {
    id: 'log_1007',
    created_time: '2026-08-02 09:00:12',
    username: 'minh_bien',
    user_fullname: 'Trần Biên Minh',
    type: 'Success',
    service_name: 'News & Media',
    description: 'Xuất bản bài viết tin tức mới: "CIC tổ chức Hội thảo Giải pháp BIM trong Công trình Giao thông Đô thị năm 2026".',
    ip_address: '113.190.112.80',
    user_agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Chrome/127.0.0.0',
    published: true,
    request_data: { article_id: 'art_881', title: 'Hội thảo Giải pháp BIM 2026' },
    response_data: { slug: 'hoi-thao-giai-phap-bim-2026', published_at: '2026-08-02T09:00:00Z' },
  },
  {
    id: 'log_1008',
    created_time: '2026-08-01 22:15:00',
    username: 'hoang_kythuat',
    user_fullname: 'Lê Huy Hoàng',
    type: 'Login',
    service_name: 'Authentication API',
    description: 'Đăng nhập hệ thống CMS thành công qua phương thức xác thực 2 lớp (2FA Authenticator).',
    ip_address: '27.72.60.18',
    user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    published: true,
    request_data: { auth_method: '2FA_TOTP' },
    response_data: { session_token: 'sess_998124_cic' },
  },
];
