import 'server-only';
import type { Sql } from 'postgres';
import type { CmsPrincipal } from '@/server/auth/guards';
import { AUDIT_ACTIONS,AUDIT_ENTITY_TYPES } from '@/server/audit/registry';
import { writeAuditEvent } from '@/server/audit/writer';
import { withTransaction } from '@/server/db/postgres';
import { moveServiceToTrash } from '@/features/trash/server/adapters/service';
import type { ServiceInput } from '../schemas/serviceInput';
import type { ServiceLocale } from '../types';
const tables=(locale:ServiceLocale)=>locale==='en'?{service:'cic_services_en',relation:'cic_services_products_rel_en',product:'cic_products_en'}:{service:'cic_services',relation:'cic_services_products_rel',product:'cic_products'};
const cleanHtml=(value:string)=>value.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/\son\w+\s*=\s*(['"]).*?\1/gi,'').replace(/javascript:/gi,'');
async function validate(sql:Sql,locale:ServiceLocale,id:number|null,input:ServiceInput){const t=tables(locale);if((await sql.unsafe(`SELECT 1 FROM ${t.service} WHERE lower(btrim(alias))=lower(btrim($1)) AND ($2::int IS NULL OR id<>$2)`,[input.alias,id])).length)throw new Error('Alias đã được dịch vụ khác sử dụng.');const ids=[...new Set(input.relatedProductIds)];if(ids.length&&(await sql.unsafe(`SELECT id FROM ${t.product} WHERE id=ANY($1::int[])`,[ids])).length!==ids.length)throw new Error('Sản phẩm liên quan không hợp lệ.');}
export async function saveService(locale:ServiceLocale,id:number|null,input:ServiceInput,actor:CmsPrincipal){return withTransaction(async sql=>{await validate(sql,locale,id,input);const t=tables(locale),before=id?(await sql.unsafe(`SELECT id,title,alias,published FROM ${t.service} WHERE id=$1 FOR UPDATE`,[id]))[0]:null;if(id&&!before)throw new Error('Không tìm thấy dịch vụ.');const values=[input.title,input.alias,input.summary,cleanHtml(input.content),input.tags,input.image,input.seoTitle,input.seoKeywords,input.seoDescription,input.published?1:0,input.ordering],columns=['title','alias','summary','content','tags','image','seo_title','seo_keyword','seo_description','published','ordering'];const rows=id?await sql.unsafe(`UPDATE ${t.service} SET ${columns.map((column,index)=>`${column}=$${index+1}`).join(',')},updated_time=now() WHERE id=$${values.length+1} RETURNING id,title`,[...values,id]):await sql.unsafe(`INSERT INTO ${t.service}(${columns.join(',')},created_time,updated_time) VALUES(${values.map((_,index)=>`$${index+1}`).join(',')},now(),now()) RETURNING id,title`,values);const row=rows[0];await sql.unsafe(`DELETE FROM ${t.relation} WHERE service_id=$1`,[row.id]);for(const[ordering,productId]of[...new Set(input.relatedProductIds)].entries())await sql.unsafe(`INSERT INTO ${t.relation}(service_id,product_id,ordering) VALUES($1,$2,$3)`,[row.id,productId,ordering]);await writeAuditEvent(actor,{action:id?AUDIT_ACTIONS.SERVICE_UPDATED:AUDIT_ACTIONS.SERVICE_CREATED,entityType:AUDIT_ENTITY_TYPES.SERVICE,entityId:String(row.id),entityTitle:String(row.title),module:'services',workspace:locale,result:'success',before,after:input},sql);return{id:String(row.id)};});}
export async function setServicesPublished(locale:ServiceLocale,ids:number[],published:boolean,actor:CmsPrincipal){return withTransaction(async sql=>{const rows=await sql.unsafe(`UPDATE ${tables(locale).service} SET published=$1,updated_time=now() WHERE id=ANY($2::int[]) RETURNING id,title`,[published?1:0,ids]);if(rows.length!==new Set(ids).size)throw new Error('Một hoặc nhiều dịch vụ không tồn tại.');for(const row of rows)await writeAuditEvent(actor,{action:AUDIT_ACTIONS.SERVICE_STATUS_CHANGED,entityType:AUDIT_ENTITY_TYPES.SERVICE,entityId:String(row.id),entityTitle:String(row.title),module:'services',workspace:locale,result:'success',after:{published}},sql);});}
export async function trashService(locale:ServiceLocale,id:number,actor:CmsPrincipal){return withTransaction(async sql=>{const moved=await moveServiceToTrash(sql,locale,id,actor.legacyUserId);await writeAuditEvent(actor,{action:AUDIT_ACTIONS.SERVICE_TRASHED,entityType:AUDIT_ENTITY_TYPES.SERVICE,entityId:String(id),entityTitle:moved.title,module:'services',workspace:locale,result:'success',after:{trashId:moved.trashId}},sql);return moved;});}
