/* eslint-disable @next/next/no-img-element */
import { Check, Crop, ExternalLink, FileText, History, Image as ImageIcon, Info, Layers, RefreshCw, Trash2, X } from 'lucide-react';
import type { ReactNode } from 'react';

import type { MediaAsset } from './types';

export type AssetDetailTab = 'details' | 'variants' | 'used_by' | 'versions' | 'activity';

export function AssetDetailHeader({ asset, canReplace, onReplace, onClose }: { asset: MediaAsset; canReplace: boolean; onReplace: () => void; onClose: () => void }) {
  return <div className="flex items-start justify-between gap-2 border-b border-slate-200 bg-slate-50 px-4 py-4 dark:border-slate-800 dark:bg-slate-850 sm:items-center sm:px-6"><div className="flex min-w-0 flex-1 items-center gap-3"><div className="w-9 h-9 rounded-xl bg-orange-100 dark:bg-orange-950 text-orange-600 dark:text-orange-300 flex items-center justify-center font-bold"><ImageIcon className="w-5 h-5" /></div><div className="min-w-0"><h2 className="max-w-md break-words text-base font-bold text-slate-900 line-clamp-3 dark:text-white sm:truncate">{asset.title}</h2><p className="text-xs text-slate-400 font-mono">{asset.filename}</p></div></div><div className="flex shrink-0 items-center gap-1 sm:gap-2"><button type="button" onClick={onReplace} disabled={!canReplace} className="flex min-h-11 items-center gap-1.5 rounded-xl bg-slate-100 px-3 py-1.5 text-xs font-bold text-slate-700 transition-colors hover:bg-slate-200 disabled:cursor-not-allowed disabled:opacity-50 dark:bg-slate-800 dark:text-slate-200 dark:hover:bg-slate-700"><RefreshCw className="w-3.5 h-3.5 text-orange-500" /> Replace File</button><button type="button" onClick={onClose} className="flex min-h-11 min-w-11 items-center justify-center text-slate-400 hover:text-slate-600 dark:hover:text-white rounded-xl transition-colors" aria-label="Đóng chi tiết Media"><X className="w-5 h-5" /></button></div></div>;
}

export function AssetPreviewSummary({ asset }: { asset: MediaAsset }) {
  return <div className="grid grid-cols-1 md:grid-cols-12 gap-6 bg-slate-50 dark:bg-slate-850 p-4 rounded-2xl border border-slate-200 dark:border-slate-800"><div className="md:col-span-6 aspect-16/10 bg-slate-900 rounded-xl overflow-hidden relative flex items-center justify-center group">{asset.type === 'document' ? <div className="text-center p-6 text-white"><FileText className="w-16 h-16 text-rose-400 mx-auto mb-2" /><p className="text-sm font-bold truncate max-w-xs">{asset.filename}</p><p className="text-xs text-slate-400">{asset.mime_type}</p></div> : asset.type === 'video' ? <video src={asset.url} controls className="w-full h-full object-contain" /> : <img src={asset.url} alt={asset.title} className="w-full h-full object-contain" />}<a href={asset.url} target="_blank" rel="noreferrer" className="absolute bottom-3 right-3 flex min-h-11 items-center gap-1 rounded-lg bg-slate-900/80 px-2.5 py-1 text-[11px] font-medium text-white backdrop-blur-xs hover:bg-slate-900"><ExternalLink className="w-3.5 h-3.5" /> Mở gốc</a></div><div className="md:col-span-6 flex flex-col justify-between space-y-3"><div><span className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Thông số kỹ thuật</span><div className="mt-2 grid grid-cols-2 gap-2 text-xs"><Summary label="Dung lượng" valueClassName="font-bold text-slate-800 dark:text-slate-200">{(asset.file_size_kb / 1024).toFixed(2)} MB</Summary><Summary label="Độ phân giải" valueClassName="font-bold text-slate-800 dark:text-slate-200 font-mono">{asset.width && asset.height ? `${asset.width} x ${asset.height}` : 'N/A'}</Summary><Summary label="MIME Type" valueClassName="font-mono text-[11px] font-medium text-slate-700 dark:text-slate-300">{asset.mime_type}</Summary><Summary label="Số nơi sử dụng" valueClassName="font-bold text-emerald-600 dark:text-emerald-400">{asset.used_by_count} vị trí</Summary></div></div><div className="pt-2 border-t border-slate-200 dark:border-slate-800 flex items-center justify-between text-xs text-slate-500"><div className="flex items-center gap-2"><img src={asset.owner_avatar} className="w-5 h-5 rounded-full" alt="" /><span>Đăng bởi {asset.owner_name}</span></div><span>{new Date(asset.created_at).toLocaleDateString('vi-VN')}</span></div></div></div>;
}

function Summary({ label, children, valueClassName }: { label: string; children: ReactNode; valueClassName: string }) {
  return <div className="bg-white dark:bg-slate-900 p-2.5 rounded-xl border border-slate-200 dark:border-slate-800"><span className="text-slate-400 text-[11px] block">{label}</span><span className={valueClassName}>{children}</span></div>;
}

export function AssetDetailNavigation({ activeTab, asset, onChange }: { activeTab: AssetDetailTab; asset: MediaAsset; onChange: (tab: AssetDetailTab) => void }) {
  const tabs = [{ id: 'details', label: 'Metadata & Accessible Alt', icon: Info }, { id: 'variants', label: 'Crop & Adaptive Variants', icon: Crop }, { id: 'used_by', label: `Nơi sử dụng (${asset.used_by_count})`, icon: Layers }, { id: 'versions', label: `Lịch sử phiên bản (${asset.versions.length})`, icon: History }] as const;
  return <div className="flex items-center gap-2 overflow-x-auto border-b border-slate-200 dark:border-slate-800 pb-2">{tabs.map((tab) => { const Icon = tab.icon; return <button key={tab.id} onClick={() => onChange(tab.id)} className={`flex min-h-11 shrink-0 items-center gap-1.5 rounded-xl px-3.5 py-2 text-xs font-bold transition-all ${activeTab === tab.id ? 'bg-orange-600 text-white shadow-xs' : 'text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800'}`}><Icon className="w-4 h-4" /><span>{tab.label}</span></button>; })}</div>;
}

export function AssetDetailFooter({ assetId, canEdit, canDelete, onClose, onDelete, onSave }: { assetId: string; canEdit: boolean; canDelete: boolean; onClose: () => void; onDelete: (id: string) => void; onSave: () => void }) {
  return <div className="p-4 border-t border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-850 flex flex-col-reverse items-stretch justify-between gap-2 pb-[max(1rem,env(safe-area-inset-bottom))] sm:flex-row sm:items-center"><button type="button" onClick={() => onDelete(assetId)} disabled={!canDelete} className="flex min-h-11 items-center gap-1.5 rounded-xl bg-rose-50 px-4 py-2 text-xs font-bold text-rose-600 transition-colors hover:bg-rose-100 disabled:cursor-not-allowed disabled:opacity-50 dark:bg-rose-950/40"><Trash2 className="w-4 h-4" /> Xóa tệp này</button><div className="flex items-center justify-end gap-2"><button type="button" onClick={onClose} className="min-h-11 px-4 py-2 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-300 hover:bg-slate-100 rounded-xl text-xs font-bold transition-colors">Hủy</button><button type="button" onClick={onSave} disabled={!canEdit} className="flex min-h-11 items-center gap-1.5 rounded-xl bg-orange-600 px-5 py-2 text-xs font-bold text-white shadow-xs transition-colors hover:bg-orange-700 disabled:cursor-not-allowed disabled:opacity-50"><Check className="w-4 h-4" /> Lưu Metadata</button></div></div>;
}
