import { MediaAsset, MediaAlbum, MediaFolder, MediaIssue } from './types';

export const MOCK_FOLDERS: MediaFolder[] = [
  { id: 'f_all', name: 'Tất cả thư mục', code_alias: 'root', icon: 'Folder', count: 48 },
  { id: 'f_products', name: 'Sản phẩm & Vật liệu', code_alias: 'products', icon: 'Package', count: 18 },
  { id: 'f_projects', name: 'Dự án & Công trình', code_alias: 'projects', icon: 'Building2', count: 12 },
  { id: 'f_banners', name: 'Marketing & Banners', code_alias: 'banners', icon: 'Image', count: 8 },
  { id: 'f_documents', name: 'Văn bản & Chứng nhận', code_alias: 'documents', icon: 'FileText', count: 5 },
  { id: 'f_events', name: 'Sự kiện & Văn hóa CIC', code_alias: 'events', icon: 'Calendar', count: 5 },
];

export const MOCK_ALBUMS: MediaAlbum[] = [
  {
    id: 'alb_01',
    title: 'Dự án thi công tiêu biểu 2025',
    code_alias: 'featured-projects-2025',
    description: 'Bộ sưu tập hình ảnh dự án cao ốc, cầu đường và hạ tầng kỹ thuật trọng điểm CIC tham gia cung cấp giải pháp.',
    cover_asset_id: 'ast_01',
    cover_asset_url: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?w=800&auto=format&fit=crop&q=80',
    asset_ids: ['ast_01', 'ast_02', 'ast_03', 'ast_07'],
    item_count: 4,
    display_order: 1,
    workflow_status: 'published',
    owner_name: 'Nguyễn Văn Minh',
    created_at: '2025-01-10T08:00:00Z',
    updated_at: '2025-02-15T14:30:00Z',
  },
  {
    id: 'alb_02',
    title: 'Hình ảnh nhà máy & Dây chuyền sản xuất',
    code_alias: 'factory-manufacturing-line',
    description: 'Hình ảnh trực quan về hệ thống tự động hóa và kho bãi lưu trữ phụ gia xây dựng đạt chuẩn ISO.',
    cover_asset_id: 'ast_04',
    cover_asset_url: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&auto=format&fit=crop&q=80',
    asset_ids: ['ast_04', 'ast_05'],
    item_count: 2,
    display_order: 2,
    workflow_status: 'published',
    owner_name: 'Trần Thị Mỹ',
    created_at: '2025-01-12T09:15:00Z',
    updated_at: '2025-01-20T11:00:00Z',
  },
  {
    id: 'alb_03',
    title: 'Chứng nhận chất lượng & Viện chuẩn hóa ISO',
    code_alias: 'iso-quality-certificates',
    description: 'Scan bản chứng chỉ ISO 9001:2015, chứng nhận kiểm định ASTM và chứng chỉ an toàn hóa chất.',
    cover_asset_id: 'ast_06',
    cover_asset_url: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=800&auto=format&fit=crop&q=80',
    asset_ids: ['ast_06'],
    item_count: 1,
    display_order: 3,
    workflow_status: 'published',
    owner_name: 'Lê Hoàng Nam',
    created_at: '2025-01-15T10:00:00Z',
    updated_at: '2025-01-15T10:00:00Z',
  },
  {
    id: 'alb_04',
    title: 'Sự kiện & Hội thảo Khoa học Kỹ thuật CIC',
    code_alias: 'cic-events-symposiums',
    description: 'Hình ảnh ghi lại từ các buổi tọa đàm chuyên đề phụ gia công nghệ cao cho bê tông cốt thép.',
    cover_asset_id: 'ast_08',
    cover_asset_url: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&auto=format&fit=crop&q=80',
    asset_ids: ['ast_08', 'ast_09'],
    item_count: 2,
    display_order: 4,
    workflow_status: 'published',
    owner_name: 'Nguyễn Văn Minh',
    created_at: '2025-02-01T13:20:00Z',
    updated_at: '2025-02-18T16:00:00Z',
  },
  {
    id: 'alb_05',
    title: 'Bộ sưu tập Hóa chất Chống thấm Chuyên dụng',
    code_alias: 'waterproofing-chemical-line',
    description: 'Hình ảnh chai, can, phuy và nhãn hàng hóa sản phẩm màng chống thấm polyurethane và màng bitum.',
    cover_asset_id: 'ast_10',
    cover_asset_url: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=800&auto=format&fit=crop&q=80',
    asset_ids: ['ast_10', 'ast_11'],
    item_count: 2,
    display_order: 5,
    workflow_status: 'published',
    owner_name: 'Phạm Thanh Hương',
    created_at: '2025-02-05T08:45:00Z',
    updated_at: '2025-02-12T15:10:00Z',
  },
  {
    id: 'alb_06',
    title: 'Hình ảnh Văn phòng & Nhân sự Tập đoàn CIC',
    code_alias: 'cic-office-culture',
    description: 'Bộ ảnh trụ sở chính, các phòng ban làm việc, phòng thí nghiệm R&D và tinh thần đội ngũ.',
    cover_asset_id: 'ast_12',
    cover_asset_url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&auto=format&fit=crop&q=80',
    asset_ids: ['ast_12'],
    item_count: 1,
    display_order: 6,
    workflow_status: 'published',
    owner_name: 'Nguyễn Văn Minh',
    created_at: '2025-02-10T10:30:00Z',
    updated_at: '2025-02-10T10:30:00Z',
  },
  {
    id: 'alb_07',
    title: 'Video Giới thiệu Doanh nghiệp & Năng lực Thi công',
    code_alias: 'corporate-showcase-videos',
    description: 'Các đoạn phim 4K giới thiệu toàn cảnh tập đoàn CIC, nhà máy và quy trình thi công thực địa.',
    cover_asset_id: 'ast_13',
    cover_asset_url: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800&auto=format&fit=crop&q=80',
    asset_ids: ['ast_13', 'ast_14'],
    item_count: 2,
    display_order: 7,
    workflow_status: 'published',
    owner_name: 'Lê Hoàng Nam',
    created_at: '2025-02-14T11:00:00Z',
    updated_at: '2025-02-20T09:30:00Z',
  },
  {
    id: 'alb_08',
    title: 'Phụ gia Bê tông Thế hệ Mới (Polycarboxylate)',
    code_alias: 'polycarboxylate-additives',
    description: 'Hình ảnh ứng dụng phụ gia giảm nước cao cấp trong bê tông thương phẩm và bê tông đúc sẵn.',
    cover_asset_id: 'ast_02',
    cover_asset_url: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&auto=format&fit=crop&q=80',
    asset_ids: ['ast_02', 'ast_03'],
    item_count: 2,
    display_order: 8,
    workflow_status: 'published',
    owner_name: 'Trần Thị Mỹ',
    created_at: '2025-02-16T14:15:00Z',
    updated_at: '2025-02-16T14:15:00Z',
  },
  {
    id: 'alb_09',
    title: 'Hồ sơ Năng lực & Tài liệu Kỹ thuật PDF 2025',
    code_alias: 'company-profile-technical-docs',
    description: 'Bộ Brochure, Catalogue tổng hợp và tài liệu chỉ dẫn thi công chi tiết.',
    cover_asset_id: 'ast_15',
    cover_asset_url: 'https://images.unsplash.com/photo-1568667256549-094345857637?w=800&auto=format&fit=crop&q=80',
    asset_ids: ['ast_15'],
    item_count: 1,
    display_order: 9,
    workflow_status: 'published',
    owner_name: 'Phạm Thanh Hương',
    created_at: '2025-02-18T08:00:00Z',
    updated_at: '2025-02-18T08:00:00Z',
  },
  {
    id: 'alb_10',
    title: 'Banner Chương trình Khuyến mãi & Tri ân Đối tác',
    code_alias: 'promotional-campaign-banners',
    description: 'Thiết kế đồ họa Banner web, Popup slide và ảnh truyền thông chiến dịch Q1/2025.',
    cover_asset_id: 'ast_16',
    cover_asset_url: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800&auto=format&fit=crop&q=80',
    asset_ids: ['ast_16'],
    item_count: 1,
    display_order: 10,
    workflow_status: 'published',
    owner_name: 'Nguyễn Văn Minh',
    created_at: '2025-02-20T10:00:00Z',
    updated_at: '2025-02-22T13:45:00Z',
  },
  {
    id: 'alb_11',
    title: 'Hoạt động Teambuilding & Thi đua Nội bộ',
    code_alias: 'teambuilding-internal-activities',
    description: 'Khoảnh khắc teambuilding bãi biển và trao giải thưởng cán bộ nhân viên xuất sắc.',
    cover_asset_id: 'ast_17',
    cover_asset_url: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop&q=80',
    asset_ids: ['ast_17'],
    item_count: 1,
    display_order: 11,
    workflow_status: 'draft',
    owner_name: 'Trần Thị Mỹ',
    created_at: '2025-02-24T09:00:00Z',
    updated_at: '2025-02-24T09:00:00Z',
  },
  {
    id: 'alb_12',
    title: 'Hệ thống Vữa Rót Không Co Nót & Keo Cấy Thép',
    code_alias: 'grout-rebar-anchoring',
    description: 'Ảnh thí nghiệm nén mẫu vữa và kiểm định lực kéo nhổ keo cấy thép tại phòng LAB.',
    cover_asset_id: 'ast_18',
    cover_asset_url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
    asset_ids: ['ast_18'],
    item_count: 1,
    display_order: 12,
    workflow_status: 'published',
    owner_name: 'Lê Hoàng Nam',
    created_at: '2025-02-25T14:00:00Z',
    updated_at: '2025-02-25T14:00:00Z',
  },
  {
    id: 'alb_13',
    title: 'Trải nghiệm Khách hàng & Phản hồi Thực tế (Testimonials)',
    code_alias: 'customer-case-studies',
    description: 'Hình ảnh ký kết hợp tác chiến lược và thư khen thưởng từ các chủ đầu tư lớn.',
    cover_asset_id: 'ast_19',
    cover_asset_url: 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=800&auto=format&fit=crop&q=80',
    asset_ids: ['ast_19'],
    item_count: 1,
    display_order: 13,
    workflow_status: 'published',
    owner_name: 'Phạm Thanh Hương',
    created_at: '2025-02-26T15:30:00Z',
    updated_at: '2025-02-26T15:30:00Z',
  },
  {
    id: 'alb_14',
    title: 'Lưu trữ Ảnh Tư liệu Lịch sử 15 Năm CIC',
    code_alias: 'cic-15-years-history-archives',
    description: 'Những hình ảnh ngày đầu thành lập công ty, hội đồng quản trị qua các thời kỳ.',
    cover_asset_id: 'ast_20',
    cover_asset_url: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&auto=format&fit=crop&q=80',
    asset_ids: ['ast_20'],
    item_count: 1,
    display_order: 14,
    workflow_status: 'published',
    owner_name: 'Nguyễn Văn Minh',
    created_at: '2025-02-27T10:00:00Z',
    updated_at: '2025-02-27T10:00:00Z',
  },
];

export const INITIAL_ASSETS: MediaAsset[] = [
  {
    id: 'ast_01',
    filename: 'du-an-cau-nhat-tan-cic-admixtures.jpg',
    title: 'Thi công bê tông Cầu Nhật Tân sử dụng phụ gia CIC',
    description: 'Hình ảnh công trình cầu Nhật Tân hoàn thiện kết cấu nhịp dầm bê tông cốt thép dự ứng lực.',
    type: 'image',
    mime_type: 'image/jpeg',
    url: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?w=400&auto=format&fit=crop&q=80',
    file_size_kb: 1420,
    width: 2400,
    height: 1600,
    alt_text: {
      vi: 'Ảnh toàn cảnh công trình Cầu Nhật Tân sử dụng phụ gia hóa chất CIC',
      en: 'Overview of Nhat Tan Bridge construction using CIC admixtures',
      ja: 'CIC添加剤を使用したニャッタン橋の建設概要',
    },
    caption: {
      vi: 'Cầu Nhật Tân - Công trình trọng điểm ứng dụng phụ gia siêu giảm nước CIC Polychem.',
      en: 'Nhat Tan Bridge - Key project applying CIC Polychem superplasticizers.',
    },
    credit_author: 'Ban Truyền thông CIC / Nhiếp ảnh gia Lê Tuấn',
    license_type: 'internal',
    folder_id: 'f_projects',
    folder_name: 'Dự án & Công trình',
    album_ids: ['alb_01'],
    tags: ['Cầu đường', 'Bê tông', 'Dự án 2025', 'Chủ lực'],
    used_by_count: 3,
    used_by_refs: [
      { id: 'u_1', entity_type: 'product', entity_title: 'Phụ gia giảm nước cao cấp CIC-Polychem 800', path: '/products/cic-polychem-800', updated_at: '2025-02-20' },
      { id: 'u_2', entity_type: 'news', entity_title: 'Tập đoàn CIC cung cấp 50.000 tấn phụ gia cho đại công trình hạ tầng', path: '/news/cic-cung-cap-phu-gia-ha-tang', updated_at: '2025-02-18' },
      { id: 'u_3', entity_type: 'static_page', entity_title: 'Trang Giới Thiệu Năng Lực Thi Công', path: '/gioi-thieu', updated_at: '2025-01-10' },
    ],
    workflow_status: 'ready',
    metadata_status: 'complete',
    variants: [
      { id: 'var_1', preset_name: 'original', width: 2400, height: 1600, format: 'webp', file_size_kb: 850, url: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?w=1200&auto=format&fit=crop&q=80', status: 'ready' },
      { id: 'var_2', preset_name: '16:9', width: 1920, height: 1080, format: 'webp', file_size_kb: 520, url: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?w=1000&auto=format&fit=crop&q=80', focal_point: { x: 50, y: 40 }, status: 'ready' },
    ],
    versions: [
      { version_number: 1.0, filename: 'du-an-cau-nhat-tan-v1.jpg', file_size_kb: 2100, replaced_by: 'Nguyễn Văn Minh', replaced_at: '2025-01-15T10:00:00Z', note: 'Nén chuẩn WebP và nâng độ nét', url: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?w=800' },
    ],
    owner_name: 'Nguyễn Văn Minh',
    owner_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    created_at: '2025-01-10T08:00:00Z',
    updated_at: '2025-02-20T14:30:00Z',
  },
  {
    id: 'ast_02',
    filename: 'be-tong-thuong-pham-tram-tron-cic.jpg',
    title: 'Trạm trộn bê tông thương phẩm kết hợp phụ gia CIC',
    description: 'Toàn cảnh trạm trộn bê tông 120m3/h vận hành liên tục.',
    type: 'image',
    mime_type: 'image/jpeg',
    url: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400&auto=format&fit=crop&q=80',
    file_size_kb: 1850,
    width: 2560,
    height: 1440,
    alt_text: {
      vi: 'Trạm trộn bê tông thương phẩm công suất cao',
      en: 'High capacity commercial concrete batching plant',
      ja: '',
    },
    caption: {
      vi: 'Trạm trộn tự động hóa 100% kết nối hệ thống đo lường phụ gia tự động.',
      en: '',
    },
    credit_author: 'Tập đoàn CIC',
    license_type: 'internal',
    folder_id: 'f_projects',
    folder_name: 'Dự án & Công trình',
    album_ids: ['alb_01', 'alb_08'],
    tags: ['Bê tông', 'Trạm trộn', 'Công nghiệp'],
    used_by_count: 2,
    used_by_refs: [
      { id: 'u_4', entity_type: 'product', entity_title: 'Phụ gia kéo dài thời gian ninh kết CIC-Retarder R2', path: '/products/cic-retarder-r2', updated_at: '2025-02-15' },
    ],
    workflow_status: 'ready',
    metadata_status: 'incomplete', // missing Japanese alt
    variants: [
      { id: 'var_3', preset_name: 'original', width: 2560, height: 1440, format: 'webp', file_size_kb: 920, url: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1000', status: 'ready' },
    ],
    versions: [],
    owner_name: 'Trần Thị Mỹ',
    owner_avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    created_at: '2025-01-12T09:15:00Z',
    updated_at: '2025-02-16T14:15:00Z',
  },
  {
    id: 'ast_03',
    filename: 'do-be-tong-san-nha-cao-tang.jpg',
    title: 'Thi công đổ bê tông sàn nhà cao tầng vị trí móng',
    description: 'Công nhân đang điều khiển vòi bơm bê tông có trộn phụ gia CIC bám dính tốt.',
    type: 'image',
    mime_type: 'image/jpeg',
    url: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=400&auto=format&fit=crop&q=80',
    file_size_kb: 980,
    width: 1920,
    height: 1280,
    alt_text: {
      vi: 'Thi công đổ bê tông móng tòa nhà thương mại',
      en: 'Pouring foundation concrete for commercial building',
      ja: '商業ビルの基礎コンクリート打設',
    },
    folder_id: 'f_projects',
    folder_name: 'Dự án & Công trình',
    album_ids: ['alb_01', 'alb_08'],
    tags: ['Thi công', 'Công trình', 'Bê tông móng'],
    used_by_count: 1,
    used_by_refs: [
      { id: 'u_5', entity_type: 'banner', entity_title: 'Banner trang chủ giải pháp thi công bê tông khối lớn', path: '/', updated_at: '2025-02-10' },
    ],
    workflow_status: 'ready',
    metadata_status: 'complete',
    variants: [],
    versions: [],
    owner_name: 'Lê Hoàng Nam',
    owner_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    created_at: '2025-01-14T11:00:00Z',
    updated_at: '2025-01-14T11:00:00Z',
  },
  {
    id: 'ast_04',
    filename: 'nha-may-san-xuat-phu-gia-cic-hung-yen.jpg',
    title: 'Toàn cảnh Nhà máy Sản xuất Phụ gia Hóa chất CIC Hưng Yên',
    description: 'Nhà máy diện tích 50.000m2 đạt chuẩn ISO 9001 và ISO 14001.',
    type: 'image',
    mime_type: 'image/jpeg',
    url: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=400&auto=format&fit=crop&q=80',
    file_size_kb: 2450,
    width: 3840,
    height: 2160,
    alt_text: {
      vi: 'Góc nhìn toàn cảnh nhà máy sản xuất hóa chất CIC',
      en: 'Panoramic view of CIC chemical manufacturing plant',
      ja: 'CIC化学製造工場の全景',
    },
    folder_id: 'f_products',
    folder_name: 'Sản phẩm & Vật liệu',
    album_ids: ['alb_02'],
    tags: ['Nhà máy', 'Hưng Yên', 'Sản xuất', 'ISO'],
    used_by_count: 4,
    used_by_refs: [
      { id: 'u_6', entity_type: 'static_page', entity_title: 'Trang Về Chúng Tôi', path: '/ve-chung-toi', updated_at: '2025-02-01' },
    ],
    workflow_status: 'ready',
    metadata_status: 'complete',
    variants: [],
    versions: [],
    owner_name: 'Trần Thị Mỹ',
    owner_avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    created_at: '2025-01-12T09:15:00Z',
    updated_at: '2025-01-20T11:00:00Z',
  },
  {
    id: 'ast_05',
    filename: 'robot-dong-gop-phuy-hoa-chat-tu-dong.jpg',
    title: 'Hệ thống Robot đóng gói phuy hóa chất tự động',
    description: 'Dây chuyền chiết rót và niêm phong phuy nhựa 200 lít bằng cánh tay robot ABB.',
    type: 'image',
    mime_type: 'image/jpeg',
    url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=400&auto=format&fit=crop&q=80',
    file_size_kb: 1650,
    width: 2560,
    height: 1700,
    alt_text: {
      vi: 'Cánh tay robot chiết rót hóa chất tự động hóa',
      en: 'Automated chemical filling robotic arm',
      ja: '',
    },
    folder_id: 'f_products',
    folder_name: 'Sản phẩm & Vật liệu',
    album_ids: ['alb_02'],
    tags: ['Robot', 'Tự động hóa', 'Dây chuyền'],
    used_by_count: 0, // Unused asset!
    used_by_refs: [],
    workflow_status: 'ready',
    metadata_status: 'incomplete',
    variants: [],
    versions: [],
    owner_name: 'Nguyễn Văn Minh',
    owner_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    created_at: '2025-01-16T14:00:00Z',
    updated_at: '2025-01-16T14:00:00Z',
  },
  {
    id: 'ast_06',
    filename: 'chung-chi-iso-9001-2015-cic-group.pdf',
    title: 'Chứng nhận Hệ thống Quản lý Chất lượng ISO 9001:2015',
    description: 'Bản Scan PDF chính thức chứng nhận đánh giá năng lực bởi tổ chức QUACERT.',
    type: 'document',
    mime_type: 'application/pdf',
    url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    thumbnail_url: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=400&auto=format&fit=crop&q=80',
    file_size_kb: 3200,
    alt_text: {
      vi: 'Bản scan Chứng chỉ ISO 9001:2015 Tập đoàn CIC',
      en: 'Scan copy of ISO 9001:2015 Certificate CIC Group',
      ja: 'CICグループのISO 9001:2015認証のスキャンコピー',
    },
    license_type: 'internal',
    folder_id: 'f_documents',
    folder_name: 'Văn bản & Chứng nhận',
    album_ids: ['alb_03'],
    tags: ['ISO', 'Chứng nhận', 'Chất lượng', 'PDF'],
    used_by_count: 2,
    used_by_refs: [
      { id: 'u_7', entity_type: 'static_page', entity_title: 'Trang Hồ Sơ Năng Lực & Chứng Nhận', path: '/chung-nhan', updated_at: '2025-02-05' },
    ],
    workflow_status: 'ready',
    metadata_status: 'complete',
    variants: [],
    versions: [],
    owner_name: 'Lê Hoàng Nam',
    owner_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    created_at: '2025-01-15T10:00:00Z',
    updated_at: '2025-01-15T10:00:00Z',
  },
  {
    id: 'ast_07',
    filename: 'du-an-metro-nhon-ga-ha-noi.jpg',
    title: 'Thi công tuyến đường sắt đô thị Nhổn - Ga Hà Nội',
    description: 'Vừa chống thấm vừa dầm cầu bê tông đường sắt cống ngầm.',
    type: 'image',
    mime_type: 'image/jpeg',
    url: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?w=400&auto=format&fit=crop&q=80',
    file_size_kb: 1350,
    width: 2000,
    height: 1333,
    alt_text: {
      vi: 'Đoạn đường sắt trên cao metro Hà Nội',
      en: 'Hanoi metro elevated railway section',
      ja: '',
    },
    folder_id: 'f_projects',
    folder_name: 'Dự án & Công trình',
    album_ids: ['alb_01'],
    tags: ['Metro', 'Đường sắt', 'Hà Nội'],
    used_by_count: 1,
    used_by_refs: [
      { id: 'u_8', entity_type: 'news', entity_title: 'Bài báo đưa tin dự án Metro sử dụng phụ gia CIC', path: '/news/metro-nhon-ga-ha-noi', updated_at: '2025-01-28' },
    ],
    workflow_status: 'ready',
    metadata_status: 'incomplete',
    variants: [],
    versions: [],
    owner_name: 'Nguyễn Văn Minh',
    owner_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    created_at: '2025-01-20T08:30:00Z',
    updated_at: '2025-01-20T08:30:00Z',
  },
  {
    id: 'ast_08',
    filename: 'hoi-thao-cong-nghe-phu-gia-be-tong-2025.jpg',
    title: 'Hội thảo Chuyên đề Công nghệ Phụ gia Bê tông Xanh 2025',
    description: 'Chuyên gia CIC thuyết trình trước 300 đại biểu và kỹ sư xây dựng.',
    type: 'image',
    mime_type: 'image/jpeg',
    url: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=400&auto=format&fit=crop&q=80',
    file_size_kb: 1950,
    width: 2800,
    height: 1867,
    alt_text: {
      vi: 'Hội thảo khoa học công nghệ phụ gia bê tông giảm phát thải carbon',
      en: 'Scientific conference on low carbon concrete additive technology',
      ja: '低炭素コンクリート添加剤技術に関する科学会議',
    },
    folder_id: 'f_events',
    folder_name: 'Sự kiện & Văn hóa CIC',
    album_ids: ['alb_04'],
    tags: ['Hội thảo', 'Kỹ thuật', 'Bê tông xanh'],
    used_by_count: 2,
    used_by_refs: [
      { id: 'u_9', entity_type: 'service', entity_title: 'Dịch vụ Tư vấn Giải pháp Kỹ thuật Bê tông', path: '/services/tu-van-ky-thuat', updated_at: '2025-02-12' },
    ],
    workflow_status: 'ready',
    metadata_status: 'complete',
    variants: [],
    versions: [],
    owner_name: 'Nguyễn Văn Minh',
    owner_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    created_at: '2025-02-01T13:20:00Z',
    updated_at: '2025-02-18T16:00:00Z',
  },
  {
    id: 'ast_09',
    filename: 'trao-giai-thuong-sang-tao-ky-thuat-cic.jpg',
    title: 'Trao giải thưởng Sáng tạo Kỹ thuật Hóa chất 2024',
    description: 'Ban Giám đốc trao bằng khen cho nhóm nghiên cứu R&D sản phẩm mới.',
    type: 'image',
    mime_type: 'image/jpeg',
    url: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=400&auto=format&fit=crop&q=80',
    file_size_kb: 1200,
    width: 2000,
    height: 1333,
    alt_text: {
      vi: 'Lễ trao giải sáng tạo R&D Tập đoàn CIC',
      en: 'CIC Group R&D innovation awards ceremony',
      ja: '',
    },
    folder_id: 'f_events',
    folder_name: 'Sự kiện & Văn hóa CIC',
    album_ids: ['alb_04'],
    tags: ['Giải thưởng', 'R&D', 'Sáng tạo'],
    used_by_count: 0,
    used_by_refs: [],
    workflow_status: 'ready',
    metadata_status: 'incomplete',
    variants: [],
    versions: [],
    owner_name: 'Trần Thị Mỹ',
    owner_avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    created_at: '2025-02-02T10:00:00Z',
    updated_at: '2025-02-02T10:00:00Z',
  },
  {
    id: 'ast_10',
    filename: 'keo-chong-tham-polyurethane-cic-seal.jpg',
    title: 'Sản phẩm Keo chống thấm Polyurethane CIC-Seal 500',
    description: 'Chụp sản phẩm studio chuẩn thương mại trên nền trắng.',
    type: 'image',
    mime_type: 'image/jpeg',
    url: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=400&auto=format&fit=crop&q=80',
    file_size_kb: 890,
    width: 1500,
    height: 1500,
    alt_text: {
      vi: 'Thùng keo chống thấm PU đàn hồi cao CIC-Seal 500',
      en: 'Bucket of high elasticity PU waterproofing sealant CIC-Seal 500',
      ja: '高弾性PU防水シーラントバケツ CIC-Seal 500',
    },
    folder_id: 'f_products',
    folder_name: 'Sản phẩm & Vật liệu',
    album_ids: ['alb_05'],
    tags: ['Chống thấm', 'Polyurethane', 'Hóa chất'],
    used_by_count: 5,
    used_by_refs: [
      { id: 'u_10', entity_type: 'product', entity_title: 'Sơn chống thấm PU co giãn cao CIC-Seal 500', path: '/products/cic-seal-500', updated_at: '2025-02-25' },
    ],
    workflow_status: 'ready',
    metadata_status: 'complete',
    variants: [],
    versions: [],
    owner_name: 'Phạm Thanh Hương',
    owner_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    created_at: '2025-02-05T08:45:00Z',
    updated_at: '2025-02-12T15:10:00Z',
  },
  {
    id: 'ast_11',
    filename: 'mang-chong-tham-khot-sau-dinh-cic.jpg',
    title: 'Màng chống thấm tự dính và khò nóng CIC-BitumFlex',
    description: 'Ảnh chi tiết bề mặt màng bitum cải tiến chống xé rách.',
    type: 'image',
    mime_type: 'image/jpeg',
    url: 'https://images.unsplash.com/photo-1590069261209-f8e9b8642343?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1590069261209-f8e9b8642343?w=400&auto=format&fit=crop&q=80',
    file_size_kb: 1120,
    width: 1920,
    height: 1080,
    alt_text: {
      vi: 'Cuộn màng chống thấm bitum mặt cát CIC',
      en: 'Sand surfaced bitumen waterproofing membrane roll',
      ja: '',
    },
    folder_id: 'f_products',
    folder_name: 'Sản phẩm & Vật liệu',
    album_ids: ['alb_05'],
    tags: ['Bitum', 'Màng chống thấm', 'Khò nóng'],
    used_by_count: 1,
    used_by_refs: [],
    workflow_status: 'ready',
    metadata_status: 'incomplete',
    variants: [],
    versions: [],
    owner_name: 'Phạm Thanh Hương',
    owner_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    created_at: '2025-02-08T11:00:00Z',
    updated_at: '2025-02-08T11:00:00Z',
  },
  {
    id: 'ast_12',
    filename: 'phong-thi-nghiem-rd-kiem-dinh-hoa-chat.jpg',
    title: 'Phòng Thí nghiệm R&D Kiểm định Hóa phẩm Xây dựng',
    description: 'Thiết bị đo độ nhớt, đo thời gian ninh kết và thử kéo nén tự động.',
    type: 'image',
    mime_type: 'image/jpeg',
    url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=400&auto=format&fit=crop&q=80',
    file_size_kb: 1780,
    width: 2560,
    height: 1440,
    alt_text: {
      vi: 'Kỹ sư phòng thí nghiệm CIC đang kiểm tra mẫu bê tông',
      en: 'CIC lab engineer testing concrete sample',
      ja: 'CICラボのエンジニアがコンクリートサンプルをテスト中',
    },
    folder_id: 'f_events',
    folder_name: 'Sự kiện & Văn hóa CIC',
    album_ids: ['alb_06'],
    tags: ['R&D', 'Phòng lab', 'Kỹ sư', 'Văn phòng'],
    used_by_count: 2,
    used_by_refs: [
      { id: 'u_11', entity_type: 'static_page', entity_title: 'Trang Trung Tâm R&D', path: '/rd-center', updated_at: '2025-02-14' },
    ],
    workflow_status: 'ready',
    metadata_status: 'complete',
    variants: [],
    versions: [],
    owner_name: 'Nguyễn Văn Minh',
    owner_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    created_at: '2025-02-10T10:30:00Z',
    updated_at: '2025-02-10T10:30:00Z',
  },
  {
    id: 'ast_13',
    filename: 'video-toan-canh-nha-may-cic-4k.mp4',
    title: 'Video 4K Toàn cảnh Nhà máy & Năng lực Sản xuất CIC 2025',
    description: 'Thước phim quay bằng Flycam chất lượng 4K UHD kéo dài 3 phút 45 giây.',
    type: 'video',
    mime_type: 'video/mp4',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=400&auto=format&fit=crop&q=80',
    file_size_kb: 48500, // 48.5 MB
    duration_sec: 225,
    width: 3840,
    height: 2160,
    alt_text: {
      vi: 'Video giới thiệu năng lực sản xuất phụ gia hóa chất bê tông CIC',
      en: 'Video introducing CIC concrete chemical additive production capacity',
      ja: 'CICコンクリート化学添加剤の生産能力を紹介するビデオ',
    },
    caption: {
      vi: 'Phim tư liệu 4K giới thiệu dây chuyền hiện đại tại Hưng Yên.',
      en: '',
    },
    folder_id: 'f_banners',
    folder_name: 'Marketing & Banners',
    album_ids: ['alb_07'],
    tags: ['Video', '4K', 'Flycam', 'Giới thiệu'],
    used_by_count: 1,
    used_by_refs: [
      { id: 'u_12', entity_type: 'content_block', entity_title: 'Khối Video Quảng Cáo Trang Chủ', path: '/', updated_at: '2025-02-21' },
    ],
    workflow_status: 'ready',
    metadata_status: 'complete',
    variants: [],
    versions: [],
    owner_name: 'Lê Hoàng Nam',
    owner_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    created_at: '2025-02-14T11:00:00Z',
    updated_at: '2025-02-20T09:30:00Z',
  },
  {
    id: 'ast_14',
    filename: 'video-huong-dan-thi-cong-chong-tham-san.mp4',
    title: 'Video Hướng dẫn Thi công Chống thấm Sàn Mái chi tiết',
    description: 'Các bước chuẩn bị bề mặt, quét lót và lăn 2 lớp phủ keo PU.',
    type: 'video',
    mime_type: 'video/mp4',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400&auto=format&fit=crop&q=80',
    file_size_kb: 32000,
    duration_sec: 180,
    width: 1920,
    height: 1080,
    alt_text: {
      vi: 'Video clip hướng dẫn thi công màng PU chống thấm',
      en: 'Instructional video for applying PU waterproofing membrane',
      ja: '',
    },
    folder_id: 'f_products',
    folder_name: 'Sản phẩm & Vật liệu',
    album_ids: ['alb_07'],
    tags: ['Video', 'Thi công', 'Hướng dẫn'],
    used_by_count: 2,
    used_by_refs: [
      { id: 'u_13', entity_type: 'product', entity_title: 'Sơn chống thấm PU co giãn cao CIC-Seal 500', path: '/products/cic-seal-500', updated_at: '2025-02-25' },
    ],
    workflow_status: 'ready',
    metadata_status: 'incomplete',
    variants: [],
    versions: [],
    owner_name: 'Nguyễn Văn Minh',
    owner_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    created_at: '2025-02-15T15:00:00Z',
    updated_at: '2025-02-15T15:00:00Z',
  },
  {
    id: 'ast_15',
    filename: 'catalogue-tong-hop-san-pham-cic-2025.pdf',
    title: 'Catalogue Tổng hợp Sản phẩm Hóa phẩm Xây dựng CIC 2025',
    description: 'Tài liệu 48 trang định dạng PDF chất lượng in ấn offset.',
    type: 'document',
    mime_type: 'application/pdf',
    url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    thumbnail_url: 'https://images.unsplash.com/photo-1568667256549-094345857637?w=400&auto=format&fit=crop&q=80',
    file_size_kb: 14500, // 14.5MB
    alt_text: {
      vi: 'Trang bìa Catalogue tổng hợp phụ gia xây dựng CIC 2025',
      en: 'Cover page of 2025 CIC construction additives catalog',
      ja: '2025年CIC建設用添加剤総合カタログの表紙',
    },
    folder_id: 'f_documents',
    folder_name: 'Văn bản & Chứng nhận',
    album_ids: ['alb_09'],
    tags: ['Catalogue', 'Brochure', 'Tài liệu PDF'],
    used_by_count: 3,
    used_by_refs: [
      { id: 'u_14', entity_type: 'static_page', entity_title: 'Trang Tải Tài Liệu Kỹ Thuật', path: '/tai-lieu', updated_at: '2025-02-22' },
    ],
    workflow_status: 'ready',
    metadata_status: 'complete',
    variants: [],
    versions: [],
    owner_name: 'Phạm Thanh Hương',
    owner_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    created_at: '2025-02-18T08:00:00Z',
    updated_at: '2025-02-18T08:00:00Z',
  },
  {
    id: 'ast_16',
    filename: 'banner-khuyen-mai-dau-xuan-2025.png',
    title: 'Banner Chương trình Khuyến mãi Tri ân Khách hàng Q1/2025',
    description: 'Thiết kế banner đồ họa hiển thị đầu trang web và popup thông báo.',
    type: 'image',
    mime_type: 'image/png',
    url: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=400&auto=format&fit=crop&q=80',
    file_size_kb: 2100,
    width: 1920,
    height: 600,
    alt_text: {
      vi: 'Banner khuyến mãi tri ân khách hàng mua hóa chất xây dựng CIC',
      en: 'Promotion banner thanking customers buying CIC chemical products',
      ja: '',
    },
    folder_id: 'f_banners',
    folder_name: 'Marketing & Banners',
    album_ids: ['alb_10'],
    tags: ['Banner', 'Khuyến mãi', 'Marketing'],
    used_by_count: 2,
    used_by_refs: [
      { id: 'u_15', entity_type: 'banner', entity_title: 'Banner Slider Khuyến Mãi Q1/2025', path: '/', updated_at: '2025-02-22' },
    ],
    workflow_status: 'ready',
    metadata_status: 'incomplete',
    variants: [],
    versions: [],
    owner_name: 'Nguyễn Văn Minh',
    owner_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    created_at: '2025-02-20T10:00:00Z',
    updated_at: '2025-02-22T13:45:00Z',
  },
  {
    id: 'ast_17',
    filename: 'teambuilding-bien-da-nang-cic-2024.jpg',
    title: 'Ảnh Kỷ niệm Teambuilding Bãi biển Đà Nẵng 2024',
    description: 'Tập thể cán bộ công nhân viên CIC xếp hình logo công ty trên bãi biển.',
    type: 'image',
    mime_type: 'image/jpeg',
    url: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=400&auto=format&fit=crop&q=80',
    file_size_kb: 1650,
    width: 2000,
    height: 1333,
    alt_text: {
      vi: 'Ảnh chụp teambuilding tập thể công ty CIC Đà Nẵng',
      en: 'CIC team building group photo in Da Nang',
      ja: '',
    },
    folder_id: 'f_events',
    folder_name: 'Sự kiện & Văn hóa CIC',
    album_ids: ['alb_11'],
    tags: ['Teambuilding', 'Đà Nẵng', 'Văn hóa'],
    used_by_count: 0,
    used_by_refs: [],
    workflow_status: 'ready',
    metadata_status: 'incomplete',
    variants: [],
    versions: [],
    owner_name: 'Trần Thị Mỹ',
    owner_avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    created_at: '2025-02-24T09:00:00Z',
    updated_at: '2025-02-24T09:00:00Z',
  },
  {
    id: 'ast_18',
    filename: 'vua-rot-khong-co-grout-cic-g60.jpg',
    title: 'Thí nghiệm kiểm định cường độ chịu nén vữa Grout G60',
    description: 'Mẫu vữa rót không co cường độ đạt 70 MPa sau 28 ngày.',
    type: 'image',
    mime_type: 'image/jpeg',
    url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=400&auto=format&fit=crop&q=80',
    file_size_kb: 1420,
    width: 1920,
    height: 1280,
    alt_text: {
      vi: 'Máy nén mẫu vữa rót không co cường độ cao',
      en: 'High strength non-shrink grout compression testing machine',
      ja: '',
    },
    folder_id: 'f_products',
    folder_name: 'Sản phẩm & Vật liệu',
    album_ids: ['alb_12'],
    tags: ['Vữa rót', 'Grout', 'Thí nghiệm'],
    used_by_count: 1,
    used_by_refs: [
      { id: 'u_16', entity_type: 'product', entity_title: 'Vữa rót không co cường độ cao CIC Grout G60', path: '/products/cic-grout-g60', updated_at: '2025-02-25' },
    ],
    workflow_status: 'ready',
    metadata_status: 'incomplete',
    variants: [],
    versions: [],
    owner_name: 'Lê Hoàng Nam',
    owner_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    created_at: '2025-02-25T14:00:00Z',
    updated_at: '2025-02-25T14:00:00Z',
  },
  {
    id: 'ast_19',
    filename: 'ky-ket-hop-tac-chien-luoc-cic-vinaconex.jpg',
    title: 'Lễ Ký kết Hợp tác Chiến lược CIC & Vinaconex',
    description: 'Chủ tịch HĐQT CIC và Tổng Giám đốc Vinaconex bắt tay ký kết.',
    type: 'image',
    mime_type: 'image/jpeg',
    url: 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=400&auto=format&fit=crop&q=80',
    file_size_kb: 1890,
    width: 2400,
    height: 1600,
    alt_text: {
      vi: 'Lễ ký kết hợp tác chiến lược cung ứng vật liệu phụ gia xây dựng',
      en: 'Signing ceremony for strategic cooperation in supplying construction additives',
      ja: '建設添加剤の供給に関する戦略的提携の調印式',
    },
    folder_id: 'f_events',
    folder_name: 'Sự kiện & Văn hóa CIC',
    album_ids: ['alb_13'],
    tags: ['Ký kết', 'Đối tác', 'Vinaconex'],
    used_by_count: 2,
    used_by_refs: [
      { id: 'u_17', entity_type: 'news', entity_title: 'Tin tức: CIC trở thành nhà cung cấp phụ gia chiến lược cho Vinaconex', path: '/news/cic-vinaconex-ky-ket', updated_at: '2025-02-26' },
    ],
    workflow_status: 'ready',
    metadata_status: 'complete',
    variants: [],
    versions: [],
    owner_name: 'Phạm Thanh Hương',
    owner_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    created_at: '2025-02-26T15:30:00Z',
    updated_at: '2025-02-26T15:30:00Z',
  },
  {
    id: 'ast_20',
    filename: 'tru-so-cic-ngay-dau-thanh-lap-2010.jpg',
    title: 'Trụ sở CIC ngày đầu thành lập năm 2010',
    description: 'Ảnh tư liệu lịch sử 15 năm phát triển của Tập đoàn CIC.',
    type: 'image',
    mime_type: 'image/jpeg',
    url: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&auto=format&fit=crop&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=400&auto=format&fit=crop&q=80',
    file_size_kb: 1250,
    width: 1800,
    height: 1200,
    alt_text: {
      vi: 'Ảnh tòa nhà trụ sở cũ CIC năm 2010',
      en: 'Old CIC headquarters building in 2010',
      ja: '',
    },
    folder_id: 'f_documents',
    folder_name: 'Văn bản & Chứng nhận',
    album_ids: ['alb_14'],
    tags: ['Lịch sử', '15 Năm', 'Tư liệu'],
    used_by_count: 1,
    used_by_refs: [
      { id: 'u_18', entity_type: 'static_page', entity_title: 'Trang Lịch Sử Hình Thành & Phát Triển', path: '/lich-su', updated_at: '2025-02-27' },
    ],
    workflow_status: 'ready',
    metadata_status: 'incomplete',
    variants: [],
    versions: [],
    owner_name: 'Nguyễn Văn Minh',
    owner_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    created_at: '2025-02-27T10:00:00Z',
    updated_at: '2025-02-27T10:00:00Z',
  },
];

export const MOCK_ISSUES: MediaIssue[] = [
  {
    id: 'iss_01',
    asset_id: 'ast_02',
    asset_name: 'be-tong-thuong-pham-tram-tron-cic.jpg',
    type: 'missing_alt',
    severity: 'medium',
    message: 'Thiếu Alt Text phiên bản tiếng Nhật (JA) cho asset.',
    created_at: '2025-02-16T14:15:00Z',
  },
  {
    id: 'ast_05',
    asset_id: 'ast_05',
    asset_name: 'robot-dong-gop-phuy-hoa-chat-tu-dong.jpg',
    type: 'duplicate',
    severity: 'low',
    message: 'Asset có tỷ lệ tương đồng 92% với một file ảnh khác trong thư mục Sản phẩm.',
    created_at: '2025-01-16T14:00:00Z',
  },
  {
    id: 'iss_03',
    asset_id: 'ast_13',
    asset_name: 'video-toan-canh-nha-may-cic-4k.mp4',
    type: 'large_filesize',
    severity: 'high',
    message: 'File video dung lượng 48.5MB vượt mức khuyến nghị (30MB). Nên tạo bản nén H.265 Web.',
    created_at: '2025-02-20T09:30:00Z',
  },
];
