import type { CmsLocale } from '../../data/CmsDataSource';
import type { FunctionSeoRecord } from './types';

const vi: FunctionSeoRecord[] = [
  {
    id: 'seo_products_home',
    routeKey: 'products_index',
    path: '/san-pham.html',
    module: 'products',
    view: 'home',
    label: 'Sản phẩm',
    intent: 'Danh mục sản phẩm & giải pháp công nghệ CIC',
    title: 'Sản phẩm phần mềm và giải pháp công nghệ | CIC',
    keywords: 'phần mềm xây dựng, sản phẩm CIC, phần mềm bản quyền',
    description: 'Khám phá danh mục phần mềm xây dựng, thiết bị và giải pháp công nghệ do CIC cung cấp chính hãng.',
    canonicalPath: '/san-pham.html',
    indexable: true,
    updatedAt: '2026-08-12T08:00:00.000Z',
    categoryPath: '/cms/product-settings?tab=categories',
    categoryPattern: '/san-pham.html?danhmuc={slug}',
    categoryOwner: 'Thiết lập sản phẩm → Danh mục sản phẩm',
    categoryStatus: 'available',
    detailPath: '/cms/products',
    detailPattern: '/san-pham/{slug}.html',
    detailOwner: 'Sản phẩm → Form chi tiết',
    detailStatus: 'available',
    facetLevels: [
      {
        id: 'facet_products_categories',
        number: '1.1',
        title: 'Danh mục sản phẩm',
        facetType: 'category',
        pattern: '/san-pham.html?danhmuc={slug}',
        owner: 'Thiết lập sản phẩm → Danh mục',
        status: 'available',
        href: '/cms/product-settings?tab=categories',
        description: 'Lọc sản phẩm theo danh mục chuyên ngành.',
        titleTemplate: '{Tên danh mục} - Phần mềm & Giải pháp | CIC',
        keywordsTemplate: '{Tên danh mục}, phần mềm xây dựng, CIC',
        descriptionTemplate: 'Tổng hợp các giải pháp, phần mềm chuyên dụng thuộc danh mục {Tên danh mục} do CIC phân phối chính hãng.',
      },
      {
        id: 'facet_products_brands',
        number: '1.2',
        title: 'Hãng sản xuất',
        facetType: 'brand',
        pattern: '/san-pham.html?hangsx={slug}',
        owner: 'Thiết lập sản phẩm → Hãng sản xuất',
        status: 'available',
        href: '/cms/product-settings?tab=brands',
        description: 'Lọc sản phẩm theo hãng công nghệ.',
        titleTemplate: 'Phần mềm & Thiết bị hãng {Tên hãng} chính hãng | CIC',
        keywordsTemplate: '{Tên hãng}, phần mềm {Tên hãng}, CIC',
        descriptionTemplate: 'Khám phá các sản phẩm phần mềm chính hãng từ nhà sản xuất {Tên hãng} được phân phối bởi CIC.',
      },
      {
        id: 'facet_products_applications',
        number: '1.3',
        title: 'Lĩnh vực ứng dụng',
        facetType: 'application',
        pattern: '/san-pham.html?ungdung={slug}',
        owner: 'Thiết lập sản phẩm → Lĩnh vực ứng dụng',
        status: 'available',
        href: '/cms/product-settings?tab=applications',
        description: 'Lọc sản phẩm theo ứng dụng chuyên môn.',
        titleTemplate: 'Giải pháp cho ứng dụng {Tên ứng dụng} | CIC',
        keywordsTemplate: '{Tên ứng dụng}, giải pháp ứng dụng, CIC',
        descriptionTemplate: 'Các phần mềm và công cụ kỹ thuật phục vụ bài toán {Tên ứng dụng}.',
      },
      {
        id: 'facet_products_types',
        number: '1.4',
        title: 'Loại sản phẩm',
        facetType: 'product_type',
        pattern: '/san-pham.html?loaisp={slug}',
        owner: 'Thiết lập sản phẩm → Loại sản phẩm',
        status: 'available',
        href: '/cms/product-settings?tab=product_types',
        description: 'Lọc sản phẩm theo hình thức.',
        titleTemplate: 'Danh mục {Tên loại sản phẩm} | CIC Technology',
        keywordsTemplate: '{Tên loại sản phẩm}, phần mềm bản quyền, CIC',
        descriptionTemplate: 'Danh sách các sản phẩm thuộc nhóm {Tên loại sản phẩm} chính hãng do CIC cung cấp.',
      },
    ],
  },
  {
    id: 'seo_news_home',
    routeKey: 'news_index',
    path: '/tin-tuc.html',
    module: 'news',
    view: 'home',
    label: 'Tin tức',
    intent: 'Tin tức doanh nghiệp và kiến thức ngành',
    title: 'Tin tức và góc nhìn công nghệ | CIC',
    keywords: 'tin tức CIC, công nghệ xây dựng, BIM',
    description: 'Tin tức CIC, xu hướng công nghệ, BIM và chuyển đổi số trong ngành xây dựng.',
    canonicalPath: '/tin-tuc.html',
    indexable: true,
    updatedAt: '2026-08-12T08:00:00.000Z',
    categoryPath: '/cms/news/categories',
    categoryPattern: '/tin-tuc/{slug}.html',
    categoryOwner: 'Tin tức → Quản lý danh mục',
    categoryStatus: 'available',
    detailPath: '/cms/news',
    detailPattern: '/tin-tuc/{slug}.html',
    detailOwner: 'Tin tức → Form bài viết',
    detailStatus: 'available',
  },
  {
    id: 'seo_events_home',
    routeKey: 'events_index',
    path: '/su-kien.html',
    module: 'event',
    view: 'home',
    label: 'Sự kiện',
    intent: 'Hội thảo, webinar và đào tạo',
    title: 'Sự kiện và hội thảo công nghệ | CIC',
    keywords: 'sự kiện CIC, hội thảo BIM, webinar',
    description: 'Danh sách sự kiện, hội thảo và webinar chuyên ngành do CIC tổ chức.',
    canonicalPath: '/su-kien.html',
    indexable: true,
    updatedAt: '2026-08-12T08:00:00.000Z',
    categoryPath: '',
    categoryPattern: '',
    categoryOwner: '',
    categoryStatus: 'missing',
    detailPath: '/cms/events',
    detailPattern: '/su-kien/{slug}.html',
    detailOwner: 'Sự kiện → Form chi tiết',
    detailStatus: 'available',
  },
  {
    id: 'seo_services_home',
    routeKey: 'services_index',
    path: '/dich-vu.html',
    module: 'services',
    view: 'home',
    label: 'Dịch vụ',
    intent: 'Năng lực tư vấn & dịch vụ',
    title: 'Dịch vụ tư vấn và chuyển đổi số | CIC',
    keywords: 'dịch vụ CIC, tư vấn BIM, chuyển đổi số',
    description: 'Các dịch vụ tư vấn BIM, chuyển đổi số, đào tạo và hỗ trợ kỹ thuật của CIC.',
    canonicalPath: '/dich-vu.html',
    indexable: true,
    updatedAt: '2026-08-12T08:00:00.000Z',
    categoryPath: '',
    categoryPattern: '',
    categoryOwner: '',
    categoryStatus: 'missing',
    detailPath: '/cms/services',
    detailPattern: '/dich-vu/{slug}.html',
    detailOwner: 'Dịch vụ → Form chi tiết',
    detailStatus: 'available',
  },
  {
    id: 'seo_projects_home',
    routeKey: 'projects_index',
    path: '/du-an.html',
    module: 'projects',
    view: 'home',
    label: 'Dự án',
    intent: 'Dự án & kinh nghiệm triển khai',
    title: 'Dự án tiêu biểu | CIC',
    keywords: 'dự án CIC, dự án BIM, chuyển đổi số',
    description: 'Các dự án tiêu biểu thể hiện năng lực tư vấn và triển khai công nghệ của CIC.',
    canonicalPath: '/du-an.html',
    indexable: true,
    updatedAt: '2026-08-12T08:00:00.000Z',
    categoryPath: '',
    categoryPattern: '',
    categoryOwner: '',
    categoryStatus: 'missing',
    detailPath: '',
    detailPattern: '/du-an/{slug}.html',
    detailOwner: 'Module Dự án chưa triển khai trong CMS',
    detailStatus: 'missing',
  },
];

const en: FunctionSeoRecord[] = vi.map((item) => ({
  ...item,
  id: `${item.id}_en`,
  path: `/en${item.path}`,
  canonicalPath: `/en${item.canonicalPath}`,
  title: `${item.label} | CIC`,
  keywords: '',
  description: `SEO metadata for ${item.label.toLowerCase()}.`,
  facetLevels: item.facetLevels?.map((facet) => ({
    ...facet,
    id: `${facet.id}_en`,
    pattern: `/en${facet.pattern}`,
    titleTemplate: `${facet.title} | CIC Technology`,
    descriptionTemplate: `Explore products filtered by ${facet.title.toLowerCase()} from CIC.`,
  })),
}));

export const functionSeoByLocale: Record<CmsLocale, FunctionSeoRecord[]> = { vi, en };
