import {
  ConfigScope,
  ConfigGroupDef,
  ConfigItem,
  ConfigValueRecord,
  ValidationIssue,
  ConfigDraft,
  ConfigVersionHistory,
  ConfigActivityLog,
} from './types';

export const configScopesMock: ConfigScope[] = [
  {
    id: 'global',
    name: 'Global Default Scope',
    domain: 'global-config.cic.internal',
    description: 'Cấu hình gốc cấp tập đoàn (Gốc kế thừa cho toàn bộ các Site)',
    badgeColor: 'bg-purple-500/10 text-purple-600 dark:text-purple-400 border-purple-500/20',
    isDefault: true,
    liveVersion: 'v2.4.0',
    draftVersion: 'v2.5.0-draft',
    lastPublished: '2026-07-15 10:00:00',
    issueCount: 0,
    overrideCount: 0,
  },
  {
    id: 'site_cic',
    name: 'Website Chính CIC Technology',
    domain: 'cic.com.vn',
    description: 'Trang chủ Doanh nghiệp, Giới thiệu, Sản phẩm & Tin tức CIC',
    badgeColor: 'bg-orange-500/10 text-orange-600 dark:text-orange-400 border-orange-500/20',
    liveVersion: 'v1.8.2',
    draftVersion: 'v1.9.0-draft',
    lastPublished: '2026-07-28 14:30:00',
    issueCount: 1,
    overrideCount: 18,
  },
  {
    id: 'site_enjicad',
    name: 'Portal enjiCAD Portal & Web CAD',
    domain: 'enjicad.vn',
    description: 'Cổng thông tin giải pháp CAD bản quyền & Tải phần mềm enjiCAD',
    badgeColor: 'bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-500/20',
    liveVersion: 'v2.1.0',
    draftVersion: 'v2.2.0-draft',
    lastPublished: '2026-07-30 09:15:00',
    issueCount: 2,
    overrideCount: 26,
  },
  {
    id: 'site_english',
    name: 'Global English Portal',
    domain: 'en.cic.com.vn',
    description: 'Cổng thông tin Quốc tế Tiếng Anh cho thị trường Châu Á - Thái Bình Dương',
    badgeColor: 'bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/20',
    liveVersion: 'v1.0.4',
    lastPublished: '2026-06-20 16:00:00',
    issueCount: 0,
    overrideCount: 8,
  },
];

export const configGroupsMock: ConfigGroupDef[] = [
  {
    id: 'general',
    title: 'Thương hiệu',
    description: 'Tên hệ thống, logo, favicon và tài nguyên thương hiệu đang được website sử dụng',
    iconName: 'Globe',
  },
  {
    id: 'seo',
    title: 'SEO mặc định',
    description: 'Title, description, social image và robots mặc định khi nội dung không có cấu hình riêng',
    iconName: 'Search',
  },
  {
    id: 'company',
    title: 'Doanh nghiệp & liên hệ',
    description: 'Thông tin pháp nhân và danh sách chi nhánh có địa chỉ, liên hệ, giờ làm việc, bản đồ riêng',
    iconName: 'Building2',
  },
  {
    id: 'footer_social',
    title: 'Footer & mạng xã hội',
    description: 'Bản quyền Copyright, Kênh Mạng xã hội (Zalo, FB, LinkedIn, YT), Chứng nhận BCT/ISO',
    iconName: 'Share2',
  },
  {
    id: 'measurement',
    title: 'Đo lường & tiếp thị',
    description: 'Mã định danh Google, Meta, TikTok và các nền tảng đo lường được website hỗ trợ; không nhập mã script.',
    iconName: 'BarChart3',
  },
  {
    id: 'error_page',
    title: 'Trang lỗi 404',
    description: 'Nội dung và hình ảnh trang không tìm thấy; giao diện được giữ cố định trong code.',
    iconName: 'FileWarning',
  },
  {
    id: 'media_assets',
    title: 'Media & tài liệu',
    description: 'Ảnh watermark, Tập tin tài liệu pháp lý, Catalogue mẫu & Ảnh mặc định fallback',
    iconName: 'FolderImage',
  },
  {
    id: 'integrations',
    title: 'Tích hợp & API secret',
    description: 'Cổng thanh toán, AI Studio / Gemini API, Zalo ZNS, Google OAuth & Webhooks (Bảo mật)',
    iconName: 'Key',
  },
  {
    id: 'email_notif',
    title: 'Email & thông báo',
    description: 'Cấu hình Máy chủ SMTP, Email gửi mặc định, Luồng nhận thông báo khách hàng & Webhook alert',
    iconName: 'Mail',
  },
  {
    id: 'advanced',
    title: 'Nâng cao & kỹ thuật',
    description: 'Bảo trì Chế độ Maintenance, Cache TTL, CORS, Giới hạn API Rate-limit & Tham số ngừng dùng',
    iconName: 'SlidersHorizontal',
  },
];

export const configItemsMock: ConfigItem[] = [
  // 1. General & Branding
  {
    id: 'gen_site_name',
    path: 'system.general.site_name',
    label: 'Tên Website / Portal',
    groupId: 'general',
    description: 'Tên hiển thị chính trên thanh tiêu đề trình duyệt và email thông báo',
    type: 'text',
    sensitivity: 'standard',
    isShared: true,
    placeholder: 'VD: CIC Technology & Consultancy',
  },
  {
    id: 'gen_tagline',
    path: 'system.general.tagline',
    label: 'Slogan / Khẩu hiệu Thương hiệu',
    groupId: 'general',
    description: 'Khẩu hiệu ngắn gọn xuất hiện dưới Logo hoặc Header',
    type: 'text',
    sensitivity: 'standard',
    isShared: true,
    placeholder: 'VD: Tiên phong Giải pháp Công nghệ Xây dựng & Kết cấu',
  },
  {
    id: 'gen_title_suffix',
    path: 'system.general.title_suffix',
    label: 'Đuôi tiêu đề trình duyệt',
    groupId: 'general',
    description: 'Phần tên thương hiệu được nối sau tiêu đề trang khi frontend hỗ trợ.',
    type: 'text',
    sensitivity: 'standard',
    isShared: true,
    placeholder: 'CIC',
    usedBy: ['Tiêu đề trình duyệt', 'SEO fallback'],
  },
  {
    id: 'gen_primary_logo',
    path: 'system.general.primary_logo',
    label: 'Logo Chính (Light Mode)',
    groupId: 'general',
    description: 'Ảnh Logo chính chuẩn Vector PNG/SVG hiển thị nền sáng',
    type: 'image',
    sensitivity: 'standard',
    isShared: true,
  },
  {
    id: 'gen_dark_logo',
    path: 'system.general.dark_logo',
    label: 'Logo Phụ (Dark Mode)',
    groupId: 'general',
    description: 'Ảnh Logo phiên bản hiển thị trên nền tối / Dark Theme',
    type: 'image',
    sensitivity: 'standard',
    isShared: true,
  },
  {
    id: 'gen_favicon',
    path: 'system.general.favicon',
    label: 'Favicon Icon (.ico / .png)',
    groupId: 'general',
    description: 'Biểu tượng nhỏ hiển thị trên tab trình duyệt (Kích thước 32x32px)',
    type: 'image',
    sensitivity: 'standard',
    isShared: true,
  },
  {
    id: 'gen_brand_color',
    path: 'system.general.brand_color',
    label: 'Màu Chủ đạo Thương hiệu (Hex Code)',
    groupId: 'general',
    description: 'Mã màu Hex chính dùng cho nút bấm, viền và điểm nhấn giao diện',
    type: 'text',
    sensitivity: 'standard',
    isShared: true,
    placeholder: '#ea580c',
  },
  {
    id: 'gen_default_lang',
    path: 'system.general.default_language',
    label: 'Ngôn ngữ Mặc định',
    groupId: 'general',
    description: 'Ngôn ngữ khởi tạo khi truy cập lần đầu',
    type: 'select',
    options: [
      { label: 'Tiếng Việt (VI)', value: 'vi' },
      { label: 'English (EN)', value: 'en' },
    ],
    sensitivity: 'standard',
    isShared: true,
  },

  // 2. SEO
  {
    id: 'seo_meta_title',
    path: 'system.seo.meta_title',
    label: 'Meta Title Mặc định',
    groupId: 'seo',
    description: 'Tiêu đề SEO trang chủ (Khuyên dùng 50-60 ký tự)',
    type: 'text',
    sensitivity: 'standard',
    isShared: false,
  },
  {
    id: 'seo_meta_description',
    path: 'system.seo.meta_description',
    label: 'Meta Description Mặc định',
    groupId: 'seo',
    description: 'Mô tả tóm tắt hiển thị trên kết quả tìm kiếm Google (120-160 ký tự)',
    type: 'textarea',
    sensitivity: 'standard',
    isShared: false,
  },
  {
    id: 'seo_og_image',
    path: 'system.seo.og_image',
    label: 'OpenGraph Share Image (1200x630px)',
    groupId: 'seo',
    description: 'Hình ảnh đại diện hiển thị khi chia sẻ link lên Zalo, Facebook, LinkedIn',
    type: 'image',
    sensitivity: 'standard',
    isShared: true,
  },
  {
    id: 'seo_ga_tracking_id',
    path: 'system.seo.ga_tracking_id',
    label: 'Google Analytics 4 Measurement ID',
    groupId: 'measurement',
    description: 'Mã theo dõi lượt truy cập (VD: G-XXXXXXXXXX)',
    type: 'text',
    sensitivity: 'standard',
    isShared: false,
    placeholder: 'G-1234567890',
    usedBy: ['Toàn website'],
  },
  {
    id: 'seo_gtm_id',
    path: 'system.seo.gtm_id',
    label: 'Google Tag Manager ID',
    groupId: 'measurement',
    description: 'Mã quản lý thẻ GTM (VD: GTM-XXXXXXX)',
    type: 'text',
    sensitivity: 'standard',
    isShared: false,
    placeholder: 'GTM-ABCDEF',
    usedBy: ['Toàn website'],
  },
  {
    id: 'seo_robots_txt',
    path: 'system.seo.robots_txt',
    label: 'Cấu hình File Robots.txt',
    groupId: 'seo',
    description: 'Nội dung quy định quyền thu thập dữ liệu của Googlebot/Bingbot',
    type: 'textarea',
    sensitivity: 'sensitive',
    isShared: false,
  },

  // 3. Corporate & Contact
  {
    id: 'comp_legal_name',
    path: 'system.company.legal_name',
    label: 'Tên Pháp nhân Công ty',
    groupId: 'company',
    description: 'Tên đầy đủ theo Giấy phép Đăng ký Kinh doanh',
    type: 'text',
    sensitivity: 'standard',
    isShared: true,
  },
  {
    id: 'comp_tax_id',
    path: 'system.company.tax_id',
    label: 'Mã số Thuế (MST)',
    groupId: 'company',
    description: 'Mã số thuế doanh nghiệp chính thức',
    type: 'text',
    sensitivity: 'standard',
    isShared: true,
  },
  {
    id: 'comp_branches',
    path: 'system.company.branches',
    label: 'Trụ sở & chi nhánh',
    groupId: 'company',
    description: 'Quản lý nhiều địa điểm; mỗi địa điểm có thông tin liên hệ và bản đồ riêng. Dữ liệu được lưu tại cic_branches, không đóng gói vào một config JSON.',
    type: 'list',
    sensitivity: 'standard',
    isShared: false,
    usedBy: ['Trang liên hệ', 'Footer'],
  },
  {
    id: 'comp_hotline',
    path: 'system.company.hotline',
    label: 'Số Hotline Tổng đài',
    groupId: 'company',
    description: 'Số điện thoại hiển thị trên Nút gọi điện Nhanh & Header',
    type: 'text',
    sensitivity: 'standard',
    isShared: true,
  },
  {
    id: 'comp_support_email',
    path: 'system.company.support_email',
    label: 'Email Hỗ trợ Khách hàng',
    groupId: 'company',
    description: 'Địa chỉ email công khai tiếp nhận yêu cầu báo giá',
    type: 'text',
    sensitivity: 'standard',
    isShared: true,
  },
  {
    id: 'comp_website_url',
    path: 'system.company.website_url',
    label: 'Website chính thức',
    groupId: 'company',
    description: 'Địa chỉ website công khai của doanh nghiệp.',
    type: 'text',
    sensitivity: 'standard',
    isShared: true,
    placeholder: 'https://www.cic.com.vn',
    usedBy: ['Footer', 'Trang liên hệ'],
  },
  {
    id: 'comp_public_email',
    path: 'system.company.public_email',
    label: 'Email công khai',
    groupId: 'company',
    description: 'Email hiển thị công khai; không dùng làm routing nội bộ.',
    type: 'text',
    sensitivity: 'standard',
    isShared: true,
    placeholder: 'info@cic.com.vn',
    usedBy: ['Footer', 'Trang liên hệ'],
  },

  // 4. Footer & Social
  {
    id: 'ft_copyright',
    path: 'system.footer.copyright_text',
    label: 'Dòng chữ Bản quyền Copyright',
    groupId: 'footer_social',
    description: 'Dòng thông báo bản quyền cuối trang Footer',
    type: 'text',
    sensitivity: 'standard',
    isShared: true,
  },
  {
    id: 'ft_social_zalo',
    path: 'system.footer.zalo_url',
    label: 'Đường dẫn Zalo OA / Chat',
    groupId: 'footer_social',
    description: 'Link tài khoản Zalo Official Account hoặc số chat trực tiếp',
    type: 'text',
    sensitivity: 'standard',
    isShared: true,
  },
  {
    id: 'ft_social_fb',
    path: 'system.footer.facebook_url',
    label: 'Đường dẫn Fanpage Facebook',
    groupId: 'footer_social',
    description: 'Link trang Fanpage chính thức',
    type: 'text',
    sensitivity: 'standard',
    isShared: true,
  },
  {
    id: 'ft_social_linkedin',
    path: 'system.footer.linkedin_url',
    label: 'Đường dẫn Trang LinkedIn',
    groupId: 'footer_social',
    description: 'Link trang doanh nghiệp LinkedIn',
    type: 'text',
    sensitivity: 'standard',
    isShared: true,
  },
  {
    id: 'ft_social_youtube',
    path: 'system.footer.youtube_url',
    label: 'Đường dẫn Kênh YouTube',
    groupId: 'footer_social',
    description: 'Link kênh YouTube đào tạo & hội thảo',
    type: 'text',
    sensitivity: 'standard',
    isShared: true,
  },
  {
    id: 'ft_bct_badge_url',
    path: 'system.footer.bct_badge_url',
    label: 'Link Đã Thông Báo Bộ Công Thương',
    groupId: 'footer_social',
    description: 'Đường dẫn xác minh Huy hiệu Bộ Công Thương (online.gov.vn)',
    type: 'text',
    sensitivity: 'standard',
    isShared: true,
  },

  // Measurement & marketing. The website owns provider scripts; CMS stores IDs only.
  {
    id: 'measure_google_ads', path: 'system.measurement.google_ads_id', label: 'Google Ads ID', groupId: 'measurement',
    description: 'Mã tài khoản Google Ads, ví dụ AW-123456789.', type: 'text', sensitivity: 'standard', isShared: false,
    placeholder: 'AW-123456789', usedBy: ['Toàn website'],
  },
  {
    id: 'measure_meta_pixel', path: 'system.measurement.meta_pixel_id', label: 'Meta / Facebook Pixel ID', groupId: 'measurement',
    description: 'Chỉ nhập Pixel ID, không dán mã JavaScript.', type: 'text', sensitivity: 'standard', isShared: false,
    placeholder: '123456789012345', usedBy: ['Toàn website'],
  },
  {
    id: 'measure_tiktok_pixel', path: 'system.measurement.tiktok_pixel_id', label: 'TikTok Pixel ID', groupId: 'measurement',
    description: 'Chỉ có hiệu lực khi adapter TikTok đã được frontend hỗ trợ.', type: 'text', sensitivity: 'standard', isShared: false,
    usedBy: ['Toàn website'],
  },
  {
    id: 'measure_linkedin', path: 'system.measurement.linkedin_partner_id', label: 'LinkedIn Partner ID', groupId: 'measurement',
    description: 'Mã LinkedIn Insight Tag; không nhập source code.', type: 'text', sensitivity: 'standard', isShared: false,
    usedBy: ['Toàn website'],
  },
  {
    id: 'measure_clarity', path: 'system.measurement.microsoft_clarity_id', label: 'Microsoft Clarity Project ID', groupId: 'measurement',
    description: 'Mã project dùng cho heatmap và session recording.', type: 'text', sensitivity: 'standard', isShared: false,
    usedBy: ['Toàn website'],
  },

  // Structured 404 content; no HTML is stored.
  {
    id: 'error_404_title', path: 'system.error404.title', label: 'Tiêu đề trang 404', groupId: 'error_page',
    description: 'Tiêu đề khi người dùng truy cập đường dẫn không tồn tại.', type: 'text', sensitivity: 'standard', isShared: false,
    placeholder: 'Không tìm thấy trang', usedBy: ['Trang 404'],
  },
  {
    id: 'error_404_description', path: 'system.error404.description', label: 'Mô tả trang 404', groupId: 'error_page',
    description: 'Nội dung hướng dẫn ngắn, không hỗ trợ HTML.', type: 'textarea', sensitivity: 'standard', isShared: false,
    usedBy: ['Trang 404'],
  },
  {
    id: 'error_404_image', path: 'system.error404.image', label: 'Ảnh minh họa 404', groupId: 'error_page',
    description: 'Chọn ảnh từ Thư viện Media.', type: 'image', sensitivity: 'standard', isShared: false,
    usedBy: ['Trang 404'],
  },
  {
    id: 'error_404_cta_label', path: 'system.error404.cta_label', label: 'Nội dung nút', groupId: 'error_page',
    description: 'Nhãn nút điều hướng trên trang 404.', type: 'text', sensitivity: 'standard', isShared: false,
    placeholder: 'Về trang chủ', usedBy: ['Trang 404'],
  },
  {
    id: 'error_404_cta_url', path: 'system.error404.cta_url', label: 'Đường dẫn của nút', groupId: 'error_page',
    description: 'Ưu tiên đường dẫn nội bộ bắt đầu bằng /.', type: 'text', sensitivity: 'standard', isShared: false,
    placeholder: '/', usedBy: ['Trang 404'],
  },

  // 5. Media & Assets
  {
    id: 'media_watermark_img',
    path: 'system.media.watermark_image',
    label: 'Ảnh Đóng dấu Bản quyền (Watermark Logo)',
    groupId: 'media_assets',
    description: 'Tự động chèn đóng dấu lên toàn bộ ảnh bài viết khi tải lên',
    type: 'image',
    sensitivity: 'standard',
    isShared: true,
  },
  {
    id: 'media_fallback_product',
    path: 'system.media.fallback_product_image',
    label: 'Ảnh Thay thế Sản phẩm (Fallback Image)',
    groupId: 'media_assets',
    description: 'Ảnh hiển thị mặc định khi sản phẩm chưa cập nhật hình đại diện',
    type: 'image',
    sensitivity: 'standard',
    isShared: true,
  },
  {
    id: 'media_terms_pdf',
    path: 'system.media.terms_pdf_document',
    label: 'Tệp PDF Điều khoản Bản quyền CIC (Legal File)',
    groupId: 'media_assets',
    description: 'Tệp PDF chính thức đính kèm trong các hợp đồng & đăng ký mua',
    type: 'file',
    sensitivity: 'standard',
    isShared: true,
  },

  // 6. Integrations & API Secrets (Protected)
  {
    id: 'int_gemini_api_key',
    path: 'system.integrations.gemini_api_key',
    label: 'Google Gemini AI Studio API Key',
    groupId: 'integrations',
    description: 'Mật khẩu API Key kết nối Trợ lý AI sinh nội dung & Chatbot CIC',
    type: 'secret',
    sensitivity: 'secret',
    isShared: false,
    impactDescription: 'Ảnh hưởng toàn bộ tính năng Trợ lý AI Chatbot & Gợi ý biên tập bài viết',
  },
  {
    id: 'int_zalo_zns_secret',
    path: 'system.integrations.zalo_zns_secret',
    label: 'Zalo ZNS Secret Key',
    groupId: 'integrations',
    description: 'Mã bí mật xác thực gửi tin nhắn thông báo tự động qua Zalo ZNS',
    type: 'secret',
    sensitivity: 'secret',
    isShared: false,
    impactDescription: 'Ảnh hưởng luồng tự động gửi SMS/Zalo báo giá cho Khách hàng',
  },
  {
    id: 'int_recaptcha_site_key',
    path: 'system.integrations.recaptcha_site_key',
    label: 'Google reCAPTCHA v3 Site Key',
    groupId: 'integrations',
    description: 'Khóa công khai dùng cho chống spam form liên hệ',
    type: 'text',
    sensitivity: 'standard',
    isShared: true,
  },
  {
    id: 'int_recaptcha_secret_key',
    path: 'system.integrations.recaptcha_secret_key',
    label: 'Google reCAPTCHA v3 Secret Key',
    groupId: 'integrations',
    description: 'Khóa bảo mật phía Server xác thực chống Spam Bot',
    type: 'secret',
    sensitivity: 'secret',
    isShared: false,
  },
  {
    id: 'int_vnpay_merchant_id',
    path: 'system.integrations.vnpay_merchant_id',
    label: 'VNPay Merchant TMN Code',
    groupId: 'integrations',
    description: 'Mã định danh đơn vị chấp nhận thanh toán VNPay QR',
    type: 'text',
    sensitivity: 'sensitive',
    isShared: false,
  },

  // 7. Email & Notifications
  {
    id: 'mail_smtp_host',
    path: 'system.email.smtp_host',
    label: 'Địa chỉ Máy chủ SMTP Mail',
    groupId: 'email_notif',
    description: 'Host máy chủ gửi email (VD: smtp.gmail.com hoặc mail.cic.com.vn)',
    type: 'text',
    sensitivity: 'sensitive',
    isShared: true,
    placeholder: 'smtp.gmail.com',
  },
  {
    id: 'mail_smtp_port',
    path: 'system.email.smtp_port',
    label: 'Cổng kết nối SMTP Port',
    groupId: 'email_notif',
    description: 'Cổng bảo mật SSL/TLS (Thường là 465 hoặc 587)',
    type: 'number',
    sensitivity: 'sensitive',
    isShared: true,
  },
  {
    id: 'mail_smtp_user',
    path: 'system.email.smtp_user',
    label: 'Tài khoản SMTP Username',
    groupId: 'email_notif',
    description: 'Tài khoản đăng nhập máy chủ email hệ thống',
    type: 'text',
    sensitivity: 'sensitive',
    isShared: true,
  },
  {
    id: 'mail_smtp_password',
    path: 'system.email.smtp_password',
    label: 'Mật khẩu SMTP Password (App Password)',
    groupId: 'email_notif',
    description: 'Mật khẩu kết nối máy chủ gửi thư tự động',
    type: 'secret',
    sensitivity: 'secret',
    isShared: true,
    impactDescription: 'Nếu mật khẩu sai, toàn bộ email xác nhận đăng ký & thông báo sẽ bị gián đoạn!',
  },
  {
    id: 'mail_from_name',
    path: 'system.email.from_name',
    label: 'Tên Người gửi Mặc định (Sender Name)',
    groupId: 'email_notif',
    description: 'Tên đại diện xuất hiện trong Hòm thư đến của Khách hàng',
    type: 'text',
    sensitivity: 'standard',
    isShared: true,
  },
  {
    id: 'mail_notification_recipients',
    path: 'system.email.notification_recipients',
    label: 'Danh sách Email Nhận Thông báo Yêu cầu Mới',
    groupId: 'email_notif',
    description: 'Danh sách các email phòng Kinh doanh nhận báo giá (cách nhau bởi dấu phẩy)',
    type: 'textarea',
    sensitivity: 'standard',
    isShared: false,
  },

  // 8. Advanced & Deprecated
  {
    id: 'adv_maintenance_mode',
    path: 'system.advanced.maintenance_mode',
    label: 'Kích hoạt Bật chế độ Bảo trì Hệ thống (Maintenance Mode)',
    groupId: 'advanced',
    description: 'Khi bật, người dùng ngoài sẽ thấy trang báo Bảo trì; chỉ Admin được đăng nhập',
    type: 'boolean',
    sensitivity: 'sensitive',
    isShared: false,
    impactDescription: 'CẢNH BÁO: Bật chế độ này sẽ tạm ngưng truy cập của người dùng toàn bộ Site này!',
  },
  {
    id: 'adv_cache_ttl_seconds',
    path: 'system.advanced.cache_ttl_seconds',
    label: 'Thời gian Lưu Cache Hệ thống (Cache TTL Seconds)',
    groupId: 'advanced',
    description: 'Thời gian lưu trữ dữ liệu tĩnh bộ nhớ đệm trước khi làm mới từ CSDL',
    type: 'number',
    unit: 'giây',
    sensitivity: 'sensitive',
    isShared: true,
  },
  {
    id: 'adv_cors_origins',
    path: 'system.advanced.cors_origins',
    label: 'Danh sách Tên miền CORS Đền cho phép API Access',
    groupId: 'advanced',
    description: 'Cấu hình bảo mật Cross-Origin Resource Sharing cho Web Client',
    type: 'textarea',
    sensitivity: 'sensitive',
    isShared: true,
  },
  {
    id: 'adv_legacy_flash_viewer',
    path: 'system.advanced.legacy_flash_viewer',
    label: 'Trình xem Flash Viewer Cũ (Ngừng hỗ trợ - Deprecated)',
    groupId: 'advanced',
    description: 'Cấu hình cũ từ hệ thống năm 2018; Đã ngừng hỗ trợ chính thức',
    type: 'boolean',
    sensitivity: 'standard',
    isShared: true,
    isDeprecated: true,
    deprecatedNote: 'Tham số này đã lỗi thời và sẽ bị xóa hoàn toàn ở phiên bản v3.0.',
  },
];

// Initial Values Matrix mapping [scopeId][settingId]
export const initialConfigValuesMock: Record<string, Record<string, ConfigValueRecord>> = {
  // GLOBAL DEFAULT SCOPE
  global: {
    gen_site_name: {
      settingId: 'gen_site_name',
      scopeId: 'global',
      liveValue: 'CIC Technology Tập đoàn',
      inheritanceState: 'default',
      effectiveValue: 'CIC Technology Tập đoàn',
      lastUpdatedBy: 'admin_cic',
      lastUpdatedAt: '2026-07-15 10:00:00',
    },
    gen_tagline: {
      settingId: 'gen_tagline',
      scopeId: 'global',
      liveValue: 'Tiên phong Giải pháp Công nghệ Xây dựng & Kết cấu',
      inheritanceState: 'default',
      effectiveValue: 'Tiên phong Giải pháp Công nghệ Xây dựng & Kết cấu',
      lastUpdatedBy: 'admin_cic',
      lastUpdatedAt: '2026-07-15 10:00:00',
    },
    gen_primary_logo: {
      settingId: 'gen_primary_logo',
      scopeId: 'global',
      liveValue: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&auto=format&fit=crop&q=80',
      inheritanceState: 'default',
      effectiveValue: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&auto=format&fit=crop&q=80',
      lastUpdatedBy: 'admin_cic',
      lastUpdatedAt: '2026-07-15 10:00:00',
    },
    gen_brand_color: {
      settingId: 'gen_brand_color',
      scopeId: 'global',
      liveValue: '#ea580c',
      inheritanceState: 'default',
      effectiveValue: '#ea580c',
      lastUpdatedBy: 'admin_cic',
      lastUpdatedAt: '2026-07-15 10:00:00',
    },
    gen_default_lang: {
      settingId: 'gen_default_lang',
      scopeId: 'global',
      liveValue: 'vi',
      inheritanceState: 'default',
      effectiveValue: 'vi',
      lastUpdatedBy: 'admin_cic',
      lastUpdatedAt: '2026-07-15 10:00:00',
    },
    seo_meta_title: {
      settingId: 'seo_meta_title',
      scopeId: 'global',
      liveValue: 'CIC Technology - Phần mềm Kỹ thuật & Tư vấn Xây dựng',
      inheritanceState: 'default',
      effectiveValue: 'CIC Technology - Phần mềm Kỹ thuật & Tư vấn Xây dựng',
      lastUpdatedBy: 'admin_cic',
      lastUpdatedAt: '2026-07-15 10:00:00',
    },
    seo_meta_description: {
      settingId: 'seo_meta_description',
      scopeId: 'global',
      liveValue: 'Công ty Cổ phần Công nghệ và Tư vấn CIC - Nhà phân phối chính thức CSI, Bentley, Plaxis, Midas và phát triển phần mềm EnjiCAD, Dự toán Escon.',
      inheritanceState: 'default',
      effectiveValue: 'Công ty Cổ phần Công nghệ và Tư vấn CIC - Nhà phân phối chính thức CSI, Bentley, Plaxis, Midas và phát triển phần mềm EnjiCAD, Dự toán Escon.',
      lastUpdatedBy: 'admin_cic',
      lastUpdatedAt: '2026-07-15 10:00:00',
    },
    comp_legal_name: {
      settingId: 'comp_legal_name',
      scopeId: 'global',
      liveValue: 'Công ty Cổ phần Công nghệ và Tư vấn CIC',
      inheritanceState: 'default',
      effectiveValue: 'Công ty Cổ phần Công nghệ và Tư vấn CIC',
      lastUpdatedBy: 'admin_cic',
      lastUpdatedAt: '2026-07-15 10:00:00',
    },
    comp_tax_id: {
      settingId: 'comp_tax_id',
      scopeId: 'global',
      liveValue: '0100107292',
      inheritanceState: 'default',
      effectiveValue: '0100107292',
      lastUpdatedBy: 'admin_cic',
      lastUpdatedAt: '2026-07-15 10:00:00',
    },
    comp_branches: {
      settingId: 'comp_branches',
      scopeId: 'global',
      liveValue: [
        {
          id: 'branch_hanoi', code: 'ha-noi', name: 'Trụ sở chính Hà Nội',
          address: 'Số 37 Lê Đại Hành, Phường Lê Đại Hành, Quận Hai Bà Trưng, Hà Nội',
          phone: '024 3976 1381', email: 'info@cic.com.vn', fax: '',
          workingHours: 'Thứ 2 - Thứ 6: 08:00 - 17:00', mapEmbedUrl: '',
          mapSearchQuery: 'CIC Technology 37 Lê Đại Hành Hà Nội',
          isHeadOffice: true, published: true, ordering: 0,
        },
        {
          id: 'branch_hcm', code: 'ho-chi-minh', name: 'Chi nhánh TP. Hồ Chí Minh',
          address: 'TP. Hồ Chí Minh', phone: '088 645 2020, 028 628 99022',
          email: 'cichcm@cic.com.vn', fax: '',
          workingHours: 'Thứ 2 - Thứ 6: 08:00 - 17:00', mapEmbedUrl: '',
          mapSearchQuery: 'CIC Technology Hồ Chí Minh',
          isHeadOffice: false, published: true, ordering: 1,
        },
      ],
      inheritanceState: 'default',
      effectiveValue: [
        {
          id: 'branch_hanoi', code: 'ha-noi', name: 'Trụ sở chính Hà Nội',
          address: 'Số 37 Lê Đại Hành, Phường Lê Đại Hành, Quận Hai Bà Trưng, Hà Nội',
          phone: '024 3976 1381', email: 'info@cic.com.vn', fax: '',
          workingHours: 'Thứ 2 - Thứ 6: 08:00 - 17:00', mapEmbedUrl: '',
          mapSearchQuery: 'CIC Technology 37 Lê Đại Hành Hà Nội',
          isHeadOffice: true, published: true, ordering: 0,
        },
        {
          id: 'branch_hcm', code: 'ho-chi-minh', name: 'Chi nhánh TP. Hồ Chí Minh',
          address: 'TP. Hồ Chí Minh', phone: '088 645 2020, 028 628 99022',
          email: 'cichcm@cic.com.vn', fax: '',
          workingHours: 'Thứ 2 - Thứ 6: 08:00 - 17:00', mapEmbedUrl: '',
          mapSearchQuery: 'CIC Technology Hồ Chí Minh',
          isHeadOffice: false, published: true, ordering: 1,
        },
      ],
      lastUpdatedBy: 'admin_cic',
      lastUpdatedAt: '2026-07-15 10:00:00',
    },
    comp_hotline: {
      settingId: 'comp_hotline',
      scopeId: 'global',
      liveValue: '024 3976 1381',
      inheritanceState: 'default',
      effectiveValue: '024 3976 1381',
      lastUpdatedBy: 'admin_cic',
      lastUpdatedAt: '2026-07-15 10:00:00',
    },
    comp_support_email: {
      settingId: 'comp_support_email',
      scopeId: 'global',
      liveValue: 'info@cic.com.vn',
      inheritanceState: 'default',
      effectiveValue: 'info@cic.com.vn',
      lastUpdatedBy: 'admin_cic',
      lastUpdatedAt: '2026-07-15 10:00:00',
    },
    ft_copyright: {
      settingId: 'ft_copyright',
      scopeId: 'global',
      liveValue: '© 2026 CIC Technology & Consultancy JSC. All Rights Reserved.',
      inheritanceState: 'default',
      effectiveValue: '© 2026 CIC Technology & Consultancy JSC. All Rights Reserved.',
      lastUpdatedBy: 'admin_cic',
      lastUpdatedAt: '2026-07-15 10:00:00',
    },
    ft_social_zalo: {
      settingId: 'ft_social_zalo',
      scopeId: 'global',
      liveValue: 'https://zalo.me/1727624419140352798',
      inheritanceState: 'default',
      effectiveValue: 'https://zalo.me/1727624419140352798',
      lastUpdatedBy: 'admin_cic',
      lastUpdatedAt: '2026-07-15 10:00:00',
    },
    ft_social_fb: {
      settingId: 'ft_social_fb',
      scopeId: 'global',
      liveValue: 'https://www.facebook.com/CICTechnologyandConsultancyVN',
      inheritanceState: 'default',
      effectiveValue: 'https://www.facebook.com/CICTechnologyandConsultancyVN',
      lastUpdatedBy: 'admin_cic',
      lastUpdatedAt: '2026-07-15 10:00:00',
    },
    int_gemini_api_key: {
      settingId: 'int_gemini_api_key',
      scopeId: 'global',
      liveValue: '[REDACTED]',
      inheritanceState: 'default',
      effectiveValue: '[REDACTED]',
      lastUpdatedBy: 'admin_cic',
      lastUpdatedAt: '2026-07-15 10:00:00',
      isMaskedSecret: true,
      isTestedOk: true,
      testLastRun: '2026-07-31 08:00:00',
    },
    mail_smtp_host: {
      settingId: 'mail_smtp_host',
      scopeId: 'global',
      liveValue: 'smtp.gmail.com',
      inheritanceState: 'default',
      effectiveValue: 'smtp.gmail.com',
      lastUpdatedBy: 'admin_cic',
      lastUpdatedAt: '2026-07-15 10:00:00',
    },
    mail_smtp_port: {
      settingId: 'mail_smtp_port',
      scopeId: 'global',
      liveValue: 587,
      inheritanceState: 'default',
      effectiveValue: 587,
      lastUpdatedBy: 'admin_cic',
      lastUpdatedAt: '2026-07-15 10:00:00',
    },
    mail_smtp_user: {
      settingId: 'mail_smtp_user',
      scopeId: 'global',
      liveValue: 'noreply@cic.com.vn',
      inheritanceState: 'default',
      effectiveValue: 'noreply@cic.com.vn',
      lastUpdatedBy: 'admin_cic',
      lastUpdatedAt: '2026-07-15 10:00:00',
    },
    mail_smtp_password: {
      settingId: 'mail_smtp_password',
      scopeId: 'global',
      liveValue: '[REDACTED]',
      inheritanceState: 'default',
      effectiveValue: '[REDACTED]',
      lastUpdatedBy: 'admin_cic',
      lastUpdatedAt: '2026-07-15 10:00:00',
      isMaskedSecret: true,
      isTestedOk: true,
      testLastRun: '2026-07-30 08:00:00',
    },
    mail_from_name: {
      settingId: 'mail_from_name',
      scopeId: 'global',
      liveValue: 'Hệ thống Khách hàng CIC Technology',
      inheritanceState: 'default',
      effectiveValue: 'Hệ thống Khách hàng CIC Technology',
      lastUpdatedBy: 'admin_cic',
      lastUpdatedAt: '2026-07-15 10:00:00',
    },
    adv_maintenance_mode: {
      settingId: 'adv_maintenance_mode',
      scopeId: 'global',
      liveValue: false,
      inheritanceState: 'default',
      effectiveValue: false,
      lastUpdatedBy: 'admin_cic',
      lastUpdatedAt: '2026-07-15 10:00:00',
    },
    adv_cache_ttl_seconds: {
      settingId: 'adv_cache_ttl_seconds',
      scopeId: 'global',
      liveValue: 3600,
      inheritanceState: 'default',
      effectiveValue: 3600,
      lastUpdatedBy: 'admin_cic',
      lastUpdatedAt: '2026-07-15 10:00:00',
    },
  },

  // WEBSITE CHÍNH SITE (cic.com.vn)
  site_cic: {
    gen_site_name: {
      settingId: 'gen_site_name',
      scopeId: 'site_cic',
      liveValue: 'CIC Technology - Giải pháp Xây dựng & Kết cấu',
      draftValue: 'CIC Technology - Cổng thông tin Doanh nghiệp & Giải pháp Kỹ thuật 2026',
      inheritanceState: 'overridden',
      inheritedFromScopeId: 'global',
      effectiveValue: 'CIC Technology - Giải pháp Xây dựng & Kết cấu',
      lastUpdatedBy: 'admin_cic',
      lastUpdatedAt: '2026-07-28 14:30:00',
    },
    gen_tagline: {
      settingId: 'gen_tagline',
      scopeId: 'site_cic',
      inheritanceState: 'inherited',
      inheritedFromScopeId: 'global',
      effectiveValue: 'Tiên phong Giải pháp Công nghệ Xây dựng & Kết cấu',
      lastUpdatedBy: 'admin_cic',
      lastUpdatedAt: '2026-07-15 10:00:00',
    },
    gen_primary_logo: {
      settingId: 'gen_primary_logo',
      scopeId: 'site_cic',
      inheritanceState: 'inherited',
      inheritedFromScopeId: 'global',
      effectiveValue: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&auto=format&fit=crop&q=80',
      lastUpdatedBy: 'admin_cic',
      lastUpdatedAt: '2026-07-15 10:00:00',
    },
    gen_brand_color: {
      settingId: 'gen_brand_color',
      scopeId: 'site_cic',
      liveValue: '#ea580c',
      inheritanceState: 'inherited',
      inheritedFromScopeId: 'global',
      effectiveValue: '#ea580c',
      lastUpdatedBy: 'admin_cic',
      lastUpdatedAt: '2026-07-15 10:00:00',
    },
    seo_meta_title: {
      settingId: 'seo_meta_title',
      scopeId: 'site_cic',
      liveValue: 'Trang chủ CIC Technology | Nhà Phân Phối Cấp 1 Phần mềm Xây dựng',
      draftValue: 'Trang chủ CIC Technology | Giải pháp BIM, CSI ETABS, SAP2000 & Plaxis',
      inheritanceState: 'overridden',
      inheritedFromScopeId: 'global',
      effectiveValue: 'Trang chủ CIC Technology | Nhà Phân Phối Cấp 1 Phần mềm Xây dựng',
      lastUpdatedBy: 'seo_specialist',
      lastUpdatedAt: '2026-07-28 11:20:00',
    },
    seo_meta_description: {
      settingId: 'seo_meta_description',
      scopeId: 'site_cic',
      liveValue: 'CIC Technology - Đơn vị hàng đầu Việt Nam cung cấp giải pháp phần mềm phân tích kết cấu ETABS, SAP2000, Plaxis, Bentley và dịch vụ tư vấn chuyển giao BIM.',
      inheritanceState: 'overridden',
      inheritedFromScopeId: 'global',
      effectiveValue: 'CIC Technology - Đơn vị hàng đầu Việt Nam cung cấp giải pháp phần mềm phân tích kết cấu ETABS, SAP2000, Plaxis, Bentley và dịch vụ tư vấn chuyển giao BIM.',
      lastUpdatedBy: 'seo_specialist',
      lastUpdatedAt: '2026-07-28 11:20:00',
    },
    comp_hotline: {
      settingId: 'comp_hotline',
      scopeId: 'site_cic',
      inheritanceState: 'inherited',
      inheritedFromScopeId: 'global',
      effectiveValue: '024 3976 1381',
      lastUpdatedBy: 'admin_cic',
      lastUpdatedAt: '2026-07-15 10:00:00',
    },
    int_gemini_api_key: {
      settingId: 'int_gemini_api_key',
      scopeId: 'site_cic',
      inheritanceState: 'inherited',
      inheritedFromScopeId: 'global',
      effectiveValue: '[REDACTED]',
      lastUpdatedBy: 'admin_cic',
      lastUpdatedAt: '2026-07-15 10:00:00',
      isMaskedSecret: true,
      isTestedOk: true,
      testLastRun: '2026-07-31 08:00:00',
    },
    mail_notification_recipients: {
      settingId: 'mail_notification_recipients',
      scopeId: 'site_cic',
      liveValue: 'sales@cic.com.vn, kinchdoanh@cic.com.vn, customer.care@cic.com.vn',
      inheritanceState: 'overridden',
      inheritedFromScopeId: 'global',
      effectiveValue: 'sales@cic.com.vn, kinchdoanh@cic.com.vn, customer.care@cic.com.vn',
      lastUpdatedBy: 'content_manager',
      lastUpdatedAt: '2026-07-20 15:10:00',
    },
    adv_maintenance_mode: {
      settingId: 'adv_maintenance_mode',
      scopeId: 'site_cic',
      liveValue: false,
      inheritanceState: 'inherited',
      inheritedFromScopeId: 'global',
      effectiveValue: false,
      lastUpdatedBy: 'admin_cic',
      lastUpdatedAt: '2026-07-15 10:00:00',
    },
  },

  // PORTAL ENJICAD (enjicad.vn)
  site_enjicad: {
    gen_site_name: {
      settingId: 'gen_site_name',
      scopeId: 'site_enjicad',
      liveValue: 'enjiCAD Portal - Phần mềm CAD Bản quyền Chi phí Tối ưu',
      inheritanceState: 'overridden',
      inheritedFromScopeId: 'global',
      effectiveValue: 'enjiCAD Portal - Phần mềm CAD Bản quyền Chi phí Tối ưu',
      lastUpdatedBy: 'product_owner',
      lastUpdatedAt: '2026-07-30 09:15:00',
    },
    gen_tagline: {
      settingId: 'gen_tagline',
      scopeId: 'site_enjicad',
      liveValue: 'Thay thế hoàn hảo cho AutoCAD - Bản quyền vĩnh viễn không phí hàng năm',
      inheritanceState: 'overridden',
      inheritedFromScopeId: 'global',
      effectiveValue: 'Thay thế hoàn hảo cho AutoCAD - Bản quyền vĩnh viễn không phí hàng năm',
      lastUpdatedBy: 'product_owner',
      lastUpdatedAt: '2026-07-30 09:15:00',
    },
    gen_brand_color: {
      settingId: 'gen_brand_color',
      scopeId: 'site_enjicad',
      liveValue: '#2563eb', // Blue brand color for enjiCAD
      inheritanceState: 'overridden',
      inheritedFromScopeId: 'global',
      effectiveValue: '#2563eb',
      lastUpdatedBy: 'product_owner',
      lastUpdatedAt: '2026-07-30 09:15:00',
    },
    cad_engine_version: {
      settingId: 'cad_engine_version',
      scopeId: 'site_enjicad',
      liveValue: 'v2.5.4-PRO-ENGINE',
      draftValue: 'v2.6.0-PRO-ENGINE-BETA',
      inheritanceState: 'overridden',
      inheritedFromScopeId: 'global',
      effectiveValue: 'v2.5.4-PRO-ENGINE',
      lastUpdatedBy: 'tech_lead',
      lastUpdatedAt: '2026-07-30 09:15:00',
    },
    cad_max_file_size_mb: {
      settingId: 'cad_max_file_size_mb',
      scopeId: 'site_enjicad',
      liveValue: 150,
      inheritanceState: 'overridden',
      inheritedFromScopeId: 'global',
      effectiveValue: 150,
      lastUpdatedBy: 'tech_lead',
      lastUpdatedAt: '2026-07-30 09:15:00',
    },
    cad_trial_days: {
      settingId: 'cad_trial_days',
      scopeId: 'site_enjicad',
      liveValue: 30,
      inheritanceState: 'overridden',
      inheritedFromScopeId: 'global',
      effectiveValue: 30,
      lastUpdatedBy: 'product_owner',
      lastUpdatedAt: '2026-07-30 09:15:00',
    },
    cad_enable_web_viewer: {
      settingId: 'cad_enable_web_viewer',
      scopeId: 'site_enjicad',
      liveValue: true,
      inheritanceState: 'overridden',
      inheritedFromScopeId: 'global',
      effectiveValue: true,
      lastUpdatedBy: 'tech_lead',
      lastUpdatedAt: '2026-07-30 09:15:00',
    },
    cad_notice_banner_text: {
      settingId: 'cad_notice_banner_text',
      scopeId: 'site_enjicad',
      liveValue: '🔥 Khuyến mãi Chào hè 2026: Ưu đãi 20% khi nâng cấp phiên bản enjiCAD Network v2.5 cho doanh nghiệp trên 10 Slot!',
      inheritanceState: 'overridden',
      inheritedFromScopeId: 'global',
      effectiveValue: '🔥 Khuyến mãi Chào hè 2026: Ưu đãi 20% khi nâng cấp phiên bản enjiCAD Network v2.5 cho doanh nghiệp trên 10 Slot!',
      lastUpdatedBy: 'product_owner',
      lastUpdatedAt: '2026-07-30 09:15:00',
    },
    int_gemini_api_key: {
      settingId: 'int_gemini_api_key',
      scopeId: 'site_enjicad',
      inheritanceState: 'inherited',
      inheritedFromScopeId: 'global',
      effectiveValue: '[REDACTED]',
      lastUpdatedBy: 'admin_cic',
      lastUpdatedAt: '2026-07-15 10:00:00',
      isMaskedSecret: true,
      isTestedOk: true,
      testLastRun: '2026-07-31 08:00:00',
    },
    mail_notification_recipients: {
      settingId: 'mail_notification_recipients',
      scopeId: 'site_enjicad',
      liveValue: 'enjicad.support@cic.com.vn, sales.enjicad@cic.com.vn',
      inheritanceState: 'overridden',
      inheritedFromScopeId: 'global',
      effectiveValue: 'enjicad.support@cic.com.vn, sales.enjicad@cic.com.vn',
      lastUpdatedBy: 'product_owner',
      lastUpdatedAt: '2026-07-25 10:00:00',
    },
  },

  // ENGLISH PORTAL (en.cic.com.vn)
  site_english: {
    gen_site_name: {
      settingId: 'gen_site_name',
      scopeId: 'site_english',
      liveValue: 'CIC Technology & Consultancy Global Portal',
      inheritanceState: 'overridden',
      inheritedFromScopeId: 'global',
      effectiveValue: 'CIC Technology & Consultancy Global Portal',
      lastUpdatedBy: 'intl_manager',
      lastUpdatedAt: '2026-06-20 16:00:00',
    },
    gen_default_lang: {
      settingId: 'gen_default_lang',
      scopeId: 'site_english',
      liveValue: 'en',
      inheritanceState: 'overridden',
      inheritedFromScopeId: 'global',
      effectiveValue: 'en',
      lastUpdatedBy: 'intl_manager',
      lastUpdatedAt: '2026-06-20 16:00:00',
    },
    seo_meta_title: {
      settingId: 'seo_meta_title',
      scopeId: 'site_english',
      liveValue: 'CIC Technology | Engineering Software & Structural Solutions Asia',
      inheritanceState: 'overridden',
      inheritedFromScopeId: 'global',
      effectiveValue: 'CIC Technology | Engineering Software & Structural Solutions Asia',
      lastUpdatedBy: 'intl_manager',
      lastUpdatedAt: '2026-06-20 16:00:00',
    },
  },
};

export const initialIssuesMock: ValidationIssue[] = [
  {
    id: 'issue_101',
    scopeId: 'site_enjicad',
    settingId: 'mail_smtp_password',
    settingLabel: 'Mật khẩu SMTP Password',
    groupId: 'email_notif',
    severity: 'critical',
    code: 'STALE_SMTP_TEST_FAILURE',
    message: 'Lần kiểm tra tự động kết nối máy chủ Mail SMTP vừa qua thất bại! Mật khẩu hoặc Cổng kết nối không khả dụng.',
    recommendation: 'Vào mục Email & Thông báo -> Kiểm tra lại mật khẩu ứng dụng SMTP hoặc thực hiện xoay mật khẩu mới.',
    createdAt: '2026-07-31 06:15:22',
  },
  {
    id: 'issue_102',
    scopeId: 'site_cic',
    settingId: 'adv_legacy_flash_viewer',
    settingLabel: 'Trình xem Flash Viewer Cũ',
    groupId: 'advanced',
    severity: 'warning',
    code: 'DEPRECATED_SETTING_OVERRIDDEN',
    message: 'Cài đặt Flash Viewer đã bị dừng hỗ trợ (Deprecated) nhưng vẫn đang được giữ giá trị Override riêng tại Site.',
    recommendation: 'Nên bấm "Reset to Inherited" để dừng sử dụng tham số này, tránh phát sinh lỗi tương thích hệ thống.',
    createdAt: '2026-07-29 14:10:00',
  },
  {
    id: 'issue_103',
    scopeId: 'site_enjicad',
    settingId: 'adv_cache_ttl_seconds',
    settingLabel: 'Thời gian Lưu Cache Hệ thống',
    groupId: 'advanced',
    severity: 'info',
    code: 'HIGH_RESOURCE_THRESHOLD',
    message: 'Thời gian lưu Cache 7200s cần theo dõi tài nguyên bộ nhớ đệm RAM server.',
    recommendation: 'Theo dõi tài nguyên bộ nhớ đệm RAM server nếu có nhiều lượt truy cập cùng lúc.',
    createdAt: '2026-07-30 09:20:00',
  },
];

export const initialDraftsMock: ConfigDraft[] = [
  {
    id: 'draft_site_cic_190',
    scopeId: 'site_cic',
    scopeName: 'Website Chính CIC Technology',
    versionNumber: 'v1.9.0-draft',
    status: 'draft',
    changedCount: 2,
    createdBy: 'seo_specialist',
    createdAt: '2026-07-28 11:20:00',
    updatedAt: '2026-07-28 11:25:00',
    changesSummary: [
      {
        settingId: 'gen_site_name',
        label: 'Tên Website / Portal',
        changeType: 'modified_value',
        oldValue: 'CIC Technology - Giải pháp Xây dựng & Kết cấu',
        newValue: 'CIC Technology - Cổng thông tin Doanh nghiệp & Giải pháp Kỹ thuật 2026',
      },
      {
        settingId: 'seo_meta_title',
        label: 'Meta Title Mặc định',
        changeType: 'modified_value',
        oldValue: 'Trang chủ CIC Technology | Nhà Phân Phối Cấp 1 Phần mềm Xây dựng',
        newValue: 'Trang chủ CIC Technology | Giải pháp BIM, CSI ETABS, SAP2000 & Plaxis',
      },
    ],
  },
  {
    id: 'draft_site_enjicad_220',
    scopeId: 'site_enjicad',
    scopeName: 'Portal enjiCAD Portal & Web CAD',
    versionNumber: 'v2.2.0-draft',
    status: 'draft',
    changedCount: 1,
    createdBy: 'tech_lead',
    createdAt: '2026-07-30 09:15:00',
    updatedAt: '2026-07-31 08:30:00',
    changesSummary: [
      {
        settingId: 'cad_engine_version',
        label: 'Phiên bản enjiCAD CAD Engine',
        changeType: 'modified_value',
        oldValue: 'v2.5.4-PRO-ENGINE',
        newValue: 'v2.6.0-PRO-ENGINE-BETA',
      },
    ],
  },
];

export const initialVersionsMock: ConfigVersionHistory[] = [
  {
    id: 'ver_cic_182',
    scopeId: 'site_cic',
    versionNumber: 'v1.8.2',
    publishedAt: '2026-07-28 14:30:00',
    publishedBy: 'admin_cic',
    releaseNotes: 'Cập nhật danh sách Email nhận thông báo phòng Kinh doanh & Nút Hotline mới.',
    changesCount: 2,
    status: 'active_live',
    changes: [
      {
        settingId: 'mail_notification_recipients',
        settingLabel: 'Danh sách Email Nhận Thông báo',
        oldValue: 'sales@cic.com.vn',
        newValue: 'sales@cic.com.vn, kinchdoanh@cic.com.vn, customer.care@cic.com.vn',
      },
      {
        settingId: 'comp_hotline',
        settingLabel: 'Số Hotline Tổng đài',
        oldValue: '024 3976 1000',
        newValue: '024 3976 1381',
      },
    ],
  },
  {
    id: 'ver_cic_181',
    scopeId: 'site_cic',
    versionNumber: 'v1.8.1',
    publishedAt: '2026-07-01 09:00:00',
    publishedBy: 'admin_cic',
    releaseNotes: 'Cập nhật lại mã theo dõi Google Analytics 4 chính thức.',
    changesCount: 1,
    status: 'archived_version',
    changes: [
      {
        settingId: 'seo_ga_tracking_id',
        settingLabel: 'Google Analytics 4 Measurement ID',
        oldValue: 'G-OLDTRACKING',
        newValue: 'G-1234567890',
      },
    ],
  },
  {
    id: 'ver_enjicad_210',
    scopeId: 'site_enjicad',
    versionNumber: 'v2.1.0',
    publishedAt: '2026-07-30 09:15:00',
    publishedBy: 'product_owner',
    releaseNotes: 'Nâng cấp lõi đồ họa enjiCAD CAD Engine v2.5.4-PRO & Banner Khuyến mãi Chào hè.',
    changesCount: 3,
    status: 'active_live',
    changes: [
      {
        settingId: 'cad_engine_version',
        settingLabel: 'Phiên bản enjiCAD CAD Engine',
        oldValue: 'v2.5.0',
        newValue: 'v2.5.4-PRO-ENGINE',
      },
      {
        settingId: 'cad_notice_banner_text',
        settingLabel: 'Thông báo Khuyến mại enjiCAD',
        oldValue: 'Chào mừng quý khách đến với enjiCAD',
        newValue: '🔥 Khuyến mãi Chào hè 2026: Ưu đãi 20% khi nâng cấp phiên bản enjiCAD Network v2.5!',
      },
    ],
  },
];

export const initialActivityLogsMock: ConfigActivityLog[] = [
  {
    id: 'act_001',
    timestamp: '2026-07-31 08:30:00',
    actor: 'tech_lead',
    scopeId: 'site_enjicad',
    scopeName: 'Portal enjiCAD Portal & Web CAD',
    action: 'save_draft',
    settingPath: 'system.enjicad.engine_version',
    details: 'Lưu bản nháp nâng cấp lõi enjiCAD sang v2.6.0-PRO-ENGINE-BETA',
    ipAddress: '118.70.182.95',
  },
  {
    id: 'act_002',
    timestamp: '2026-07-30 09:15:00',
    actor: 'product_owner',
    scopeId: 'site_enjicad',
    scopeName: 'Portal enjiCAD Portal & Web CAD',
    action: 'publish_version',
    details: 'Xuất bản chính thức Phiên bản cấu hình v2.1.0 (Atomic Publish thành công)',
    ipAddress: '118.70.182.95',
  },
  {
    id: 'act_003',
    timestamp: '2026-07-28 14:30:00',
    actor: 'admin_cic',
    scopeId: 'site_cic',
    scopeName: 'Website Chính CIC Technology',
    action: 'publish_version',
    details: 'Xuất bản cấu hình v1.8.2 cho Website Chính',
    ipAddress: '14.225.21.10',
  },
  {
    id: 'act_004',
    timestamp: '2026-07-25 16:00:00',
    actor: 'integration_admin',
    scopeId: 'global',
    scopeName: 'Global Default Scope',
    action: 'secret_rotated',
    settingPath: 'system.integrations.gemini_api_key',
    details: 'Xoay khóa bí mật API Key Gemini AI Studio thành công (Ghi log bảo mật, không lưu giá trị rõ)',
    ipAddress: '14.225.21.10',
  },
];
