import { NewsCategory, NewsArticle, RelatedProductItem, RelatedNewsItem } from './types';

export const mockNewsCategories: NewsCategory[] = [
  { id: 'cat_news_tech', name: 'Tin công nghệ & Phần mềm', slug: 'tin-cong-nghe-phan-mem' },
  { id: 'cat_news_events', name: 'Sự kiện & Hội thảo', slug: 'su-kien-hoi-thao' },
  { id: 'cat_news_projects', name: 'Dự án & Khách hàng', slug: 'du-an-khach-hang' },
  { id: 'cat_news_guides', name: 'Hướng dẫn & Kinh nghiệm', slug: 'huong-dan-kinh-nghiem' },
];

export const mockRelatedProducts: RelatedProductItem[] = [
  {
    id: 'prod_sap2000',
    name: 'Phần mềm Phân tích Kết cấu CIC-SAP2000 v25',
    code: 'SAP2000-V25',
    image: 'https://images.unsplash.com/photo-1581092921461-eab62e97a780?w=200&auto=format&fit=crop&q=80',
  },
  {
    id: 'prod_etabs',
    name: 'Phần mềm Thiết kế Nhà cao tầng CIC-ETABS v21',
    code: 'ETABS-V21',
    image: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=200&auto=format&fit=crop&q=80',
  },
  {
    id: 'prod_cicroad',
    name: 'Phần mềm Thiết kế Công trình Giao thông CIC-Road',
    code: 'CIC-ROAD-V22',
    image: 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=200&auto=format&fit=crop&q=80',
  },
  {
    id: 'prod_cubicost',
    name: 'Phần mềm Bóc tách Khối lượng & Dự toán Cubicost',
    code: 'CUBICOST-TAS',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=200&auto=format&fit=crop&q=80',
  },
];

export const mockArticles: NewsArticle[] = [
  {
    id: 'news_1001',
    title: 'CIC chính thức phát hành phần mềm CIC-SAP2000 v25 hỗ trợ tiêu chuẩn TCVN mới nhất',
    alias: 'cic-chinh-thuc-phat-hanh-phan-mem-cic-sap2000-v25',
    category_id: 'cat_news_tech',
    summary: 'Phiên bản v25 mang đến hơn 50 cải tiến vượt bậc về tính toán kết cấu công trình chịu tải trọng động lực học và tích hợp tiêu chuẩn thiết kế Việt Nam.',
    content: `<p>Ngày 01/08/2026, <strong>Công ty Cổ phần Công nghệ và Tư vấn CIC</strong> đã chính thức công bố phiên bản phần mềm <strong>CIC-SAP2000 v25</strong>. Đây là bước đột phá mới trong giải pháp phân tích kết cấu cho các kỹ sư xây dựng tại Việt Nam.</p><p>SAP2000 từ lâu đã trở thành công cụ đắc lực tiêu chuẩn trong ngành xây dựng. Với phiên bản v25, đội ngũ chuyên gia CIC đã tối ưu hóa thuật toán tính toán và cập nhật các mô đun tự động hóa kiểm tra ứng suất theo các quy chuẩn hiện hành.</p><h3>Các tính năng nổi bật trên phiên bản v25:</h3><ul><li>Tích hợp mô đun kiểm tra ứng suất tự động theo tiêu chuẩn TCVN 5574:2018 và TCVN 2737:2023.</li><li>Cải thiện tốc độ xử lý bài toán phần tử hữu hạn phi tuyến gấp 3 lần so với phiên bản trước.</li><li>Tự động xuất báo cáo thuyết minh kết cấu chuyên nghiệp sang định dạng Microsoft Word và PDF.</li><li>Hỗ trợ trao đổi dữ liệu BIM dạng mở IFC4 với các phần mềm Revit, Tekla và ArchiCAD.</li></ul><p>Quý khách hàng có nhu cầu tư vấn nâng cấp hoặc dùng thử phiên bản mới vui lòng liên hệ bộ phận kinh doanh CIC để được hỗ trợ trực tiếp.</p>`,
    image: 'https://images.unsplash.com/photo-1581092921461-eab62e97a780?w=800&auto=format&fit=crop&q=80',
    video: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    tags: ['SAP2000', 'KẾT CẤU', 'TCVN', 'CIC SOFTWARE', 'BIM'],
    news_related: ['news_1002'],
    products_related: ['prod_sap2000', 'prod_etabs'],
    start_time: '2026-08-01T08:00',
    end_time: '2026-12-31T23:59',
    is_hot: true,
    is_new: true,
    show_in_homepage: true,
    published: true,
    ordering: 1,
    seo_title: 'CIC phát hành phần mềm CIC-SAP2000 v25 chuẩn TCVN mới nhất',
    seo_keyword: 'SAP2000 v25, phan mem ket cau, TCVN 5574, CIC technology',
    seo_description: 'Phần mềm phân tích kết cấu CIC-SAP2000 v25 chính thức ra mắt với hơn 50 cải tiến vượt bậc hỗ trợ kỹ sư xây dựng Việt Nam.',
    created_time: '2026-08-01 09:15:00',
    updated_time: '2026-08-01 10:30:00',
  },
  {
    id: 'news_1002',
    title: 'Hội thảo Chuyển đổi số và Ứng dụng Mô hình BIM trong Công trình Xây dựng Đô thị 2026',
    alias: 'hoi-thao-chuyen-doi-so-va-ung-dung-mo-hinh-bim-2026',
    category_id: 'cat_news_events',
    summary: 'Sự kiện quy tụ hơn 300 chuyên gia, kiến trúc sư và đại diện các Ban Quản lý dự án hàng đầu toàn quốc trao đổi giải pháp quản lý dự án xây dựng thông minh.',
    content: `<p>Vừa qua tại Trung tâm Hội nghị Quốc gia Hà Nội, <strong>CIC Technology</strong> đã phối hợp cùng các đơn vị chuyên môn tổ chức thành công Hội thảo <em>"Chuyển đổi số và Ứng dụng Mô hình BIM 2026"</em>.</p><p>Hội thảo tập trung thảo luận các lộ trình áp dụng BIM bắt buộc đối với công trình cấp I và cấp đặc biệt theo quyết định của Thủ tướng Chính phủ. Đại diện CIC đã trình bày tham luận về giải pháp Quản lý dữ liệu công trình tập trung CDE (Common Data Environment).</p><h3>Nội dung trọng tâm hội thảo:</h3><ul><li>Lộ trình áp dụng BIM trong quản lý dự án đầu tư xây dựng công.</li><li>Tích hợp dữ liệu trắc địa GIS và mô hình BIM 3D/4D/5D.</li><li>Chia sẻ kinh nghiệm thực tế từ các chủ đầu tư lớn như Vingroup, Sun Group và Đèo Cả.</li></ul>`,
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&auto=format&fit=crop&q=80',
    video: 'https://www.youtube.com/watch?v=3JZ_D3ELwOQ',
    tags: ['BIM', 'HỘI THẢO', 'CHUYỂN ĐỔI SỐ', 'XÂY DỰNG', 'CDE'],
    news_related: ['news_1001'],
    products_related: ['prod_cubicost'],
    start_time: '2026-07-25T08:00',
    end_time: '2026-12-31T23:59',
    is_hot: false,
    is_new: true,
    show_in_homepage: true,
    published: true,
    ordering: 2,
    seo_title: 'Hội thảo Chuyển đổi số BIM 2026 do CIC phối hợp tổ chức',
    seo_keyword: 'Hội thảo BIM 2026, chuyen doi so xay dung, CDE, CIC',
    seo_description: 'Toàn cảnh Hội thảo Chuyển đổi số BIM 2026 với sự tham gia của hơn 300 chuyên gia xây dựng hàng đầu.',
    created_time: '2026-07-26 14:20:00',
  },
  {
    id: 'news_1003',
    title: 'Hướng dẫn cài đặt và kích hoạt bản quyền dùng thử CIC-Road v22 chi tiết từ A-Z',
    alias: 'huong-dan-cai-dat-va-kich-hoat-ban-quyen-dung-thu-cic-road-v22',
    category_id: 'cat_news_guides',
    summary: 'Bài viết hướng dẫn chi tiết từng bước tải về, cài đặt driver khóa cứng Sentinel và kích hoạt License Online 30 ngày cho phần mềm thiết kế đường.',
    content: `<p>Để giúp quý khách hàng và kỹ sư trải nghiệm đầy đủ các tính năng mạnh mẽ trên phần mềm thiết kế hạ tầng giao thông <strong>CIC-Road v22</strong>, bộ phận hỗ trợ kỹ thuật CIC xin gửi tới bài hướng dẫn từng bước cài đặt.</p><h3>Các bước thực hiện nhanh:</h3><ol><li><strong>Bước 1:</strong> Tải bộ cài đặt chính thức từ máy chủ CIC.</li><li><strong>Bước 2:</strong> Giải nén và chạy file <code>Setup.exe</code> dưới quyền Administrator.</li><li><strong>Bước 3:</strong> Cài đặt Sentinel Driver hỗ trợ nhận diện khóa cứng USB.</li><li><strong>Bước 4:</strong> Nhập mã kích hoạt dùng thử 30 ngày do bộ phận hỗ trợ cấp.</li></ol>`,
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
    video: '',
    tags: ['CIC-ROAD', 'HƯỚNG DẪN', 'LICENSE', 'CÀI ĐẶT', 'GIAO THÔNG'],
    news_related: [],
    products_related: ['prod_cicroad'],
    start_time: '2026-07-10T08:00',
    end_time: '2026-12-31T23:59',
    is_hot: false,
    is_new: false,
    show_in_homepage: false,
    published: true,
    ordering: 3,
    seo_title: 'Hướng dẫn cài đặt CIC-Road v22 dùng thử bản quyền 30 ngày',
    seo_keyword: 'huong dan cai dat CIC Road, dung thu CIC Road, license CIC',
    seo_description: 'Các bước tải và cài đặt nhanh phần mềm thiết kế đường CIC-Road v22 cho kỹ sư giao thông.',
    created_time: '2026-07-10 10:05:00',
  },
];
