import { NewsCategory, NewsArticle, RelatedProductItem } from './types';

export const mockNewsCategories: NewsCategory[] = [
  { id: 'cat_news_tech', name: 'Tin công nghệ & Phần mềm', title: 'Tin công nghệ và phần mềm', alias: 'tin-cong-nghe-phan-mem', count: 4, parent_id: null, ordering: 1, published: true, show_in_homepage: true, seo_title: 'Tin công nghệ và phần mềm | CIC', seo_keyword: 'tin công nghệ, phần mềm xây dựng, CIC', seo_description: 'Tin tức công nghệ và các sản phẩm phần mềm mới nhất từ CIC.', created_time: '2025-01-10T08:00:00.000Z' },
  { id: 'cat_news_events', name: 'Sự kiện & Hội thảo', title: 'Sự kiện và hội thảo', alias: 'su-kien-hoi-thao', count: 2, parent_id: null, ordering: 2, published: true, show_in_homepage: true, seo_title: 'Sự kiện và hội thảo | CIC', seo_keyword: 'sự kiện CIC, hội thảo công nghệ', seo_description: 'Thông tin sự kiện, hội thảo và webinar do CIC tổ chức hoặc đồng hành.', created_time: '2025-01-10T08:00:00.000Z' },
  { id: 'cat_news_projects', name: 'Dự án & Khách hàng', title: 'Dự án và khách hàng', alias: 'du-an-khach-hang', count: 1, parent_id: null, ordering: 3, published: true, show_in_homepage: false, seo_title: 'Dự án và khách hàng | CIC', seo_keyword: 'dự án CIC, khách hàng CIC', seo_description: 'Các dự án tiêu biểu và câu chuyện triển khai giải pháp cùng khách hàng CIC.', created_time: '2025-01-10T08:00:00.000Z' },
  { id: 'cat_news_guides', name: 'Hướng dẫn & Kinh nghiệm', title: 'Hướng dẫn và kinh nghiệm', alias: 'huong-dan-kinh-nghiem', count: 1, parent_id: 'cat_news_tech', ordering: 1, published: true, show_in_homepage: true, seo_title: 'Hướng dẫn và kinh nghiệm sử dụng phần mềm | CIC', seo_keyword: 'hướng dẫn phần mềm, kinh nghiệm sử dụng', seo_description: 'Hướng dẫn sử dụng phần mềm và kinh nghiệm ứng dụng giải pháp công nghệ CIC.', created_time: '2025-01-10T08:00:00.000Z' },
];

export const mockRelatedProducts: RelatedProductItem[] = [
  {
    id: 'prod_sap2000',
    name: 'Phần mềm Phân tích Kết cấu CIC-SAP2000 v25',
    code: 'SAP2000-V25',
    image: 'https://images.unsplash.com/photo-1581092921461-eab62e97a780?w=200&auto=format&fit=crop&q=80',
  },
  {
    id: 'prod_etabs',
    name: 'Phần mềm Thiết kế Nhà cao tầng CIC-ETABS v21',
    code: 'ETABS-V21',
    image: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=200&auto=format&fit=crop&q=80',
  },
  {
    id: 'prod_cicroad',
    name: 'Phần mềm Thiết kế Công trình Giao thông CIC-Road',
    code: 'CIC-ROAD-V22',
    image: 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=200&auto=format&fit=crop&q=80',
  },
  {
    id: 'prod_cubicost',
    name: 'Phần mềm Bóc tách Khối lượng & Dự toán Cubicost',
    code: 'CUBICOST-TAS',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=200&auto=format&fit=crop&q=80',
  },
];

export const mockArticles: NewsArticle[] = [
  {
    id: 'news_1001',
    title: 'CIC chính thức phát hành phần mềm CIC-SAP2000 v25 hỗ trợ tiêu chuẩn TCVN mới nhất',
    alias: 'cic-chinh-thuc-phat-hanh-phan-mem-cic-sap2000-v25',
    category_id: 'cat_news_tech',
    summary: 'Phiên bản v25 mang đến hơn 50 cải tiến vượt bậc về tính toán kết cấu công trình chịu tải trọng động lực học và tích hợp tiêu chuẩn thiết kế Việt Nam.',
    content: `<p>Ngày 01/08/2026, <strong>Công ty Cổ phần Công nghệ và Tư vấn CIC</strong> đã chính thức công bố phiên bản phần mềm <strong>CIC-SAP2000 v25</strong>. Đây là bước đột phá mới trong giải pháp phân tích kết cấu cho các kỹ sư xây dựng tại Việt Nam.</p><p>SAP2000 từ lâu đã trở thành công cụ đắc lực tiêu chuẩn trong ngành xây dựng. Với phiên bản v25, đội ngũ chuyên gia CIC đã tối ưu hóa thuật toán tính toán và cập nhật các mô đun tự động hóa kiểm tra ứng suất theo các quy chuẩn hiện hành.</p><h3>Các tính năng nổi bật trên phiên bản v25:</h3><ul><li>Tích hợp mô đun kiểm tra ứng suất tự động theo tiêu chuẩn TCVN 5574:2018 và TCVN 2737:2023.</li><li>Cải thiện tốc độ xử lý bài toán phần tử hữu hạn phi tuyến gấp 3 lần so với phiên bản trước.</li><li>Tự động xuất báo cáo thuyết minh kết cấu chuyên nghiệp sang định dạng Microsoft Word và PDF.</li><li>Hỗ trợ trao đổi dữ liệu BIM dạng mở IFC4 với các phần mềm Revit, Tekla và ArchiCAD.</li></ul><p>Quý khách hàng có nhu cầu tư vấn nâng cấp hoặc dùng thử phiên bản mới vui lòng liên hệ bộ phận kinh doanh CIC để được hỗ trợ trực tiếp.</p>`,
    image: 'https://images.unsplash.com/photo-1581092921461-eab62e97a780?w=800&auto=format&fit=crop&q=80',
    image_alt: 'Hình ảnh giao diện phần mềm CIC-SAP2000 v25',
    image_caption: 'Giao diện tính toán mô hình kết cấu 3D trên CIC-SAP2000 v25',
    video: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    tags: ['SAP2000', 'KẾT CẤU', 'TCVN', 'CIC SOFTWARE', 'BIM'],
    news_related: ['news_1002'],
    products_related: ['prod_sap2000', 'prod_etabs'],
    start_time: '2026-08-01T08:00',
    end_time: '2026-12-31T23:59',
    timezone: 'Asia/Ho_Chi_Minh (UTC+7)',
    is_hot: true,
    is_new: true,
    show_in_homepage: true,
    published: true,
    ordering: 1,
    author: {
      name: 'Nguyễn Văn Nam',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
      email: 'nam.nv@cic.com.vn',
    },
    seo_title: 'CIC phát hành phần mềm CIC-SAP2000 v25 chuẩn TCVN mới nhất',
    seo_keyword: 'SAP2000 v25, phan mem ket cau, TCVN 5574, CIC technology',
    seo_description: 'Phần mềm phân tích kết cấu CIC-SAP2000 v25 chính thức ra mắt với hơn 50 cải tiến vượt bậc hỗ trợ kỹ sư xây dựng Việt Nam.',
    working_version_number: 3,
    published_version_number: 3,
    has_unpublished_changes: false,
    versions: [
      {
        id: 'v1',
        version_number: 1,
        created_at: '2026-07-30 08:30:00',
        created_by: 'Nguyễn Văn Nam',
        note: 'Tạo bản nháp đầu tiên',
        title: 'CIC phát hành CIC-SAP2000 v25',
        summary: 'Bản nháp tóm tắt ban đầu',
      },
      {
        id: 'v2',
        version_number: 2,
        created_at: '2026-07-31 14:20:00',
        created_by: 'Lê Hoàng Long',
        note: 'Chỉnh sửa tóm tắt và bổ sung bảng tính năng',
        title: 'CIC phát hành phần mềm CIC-SAP2000 v25 chuẩn TCVN',
        summary: 'Bổ sung danh sách cải tiến về TCVN 5574:2018',
      },
      {
        id: 'v3',
        version_number: 3,
        created_at: '2026-08-01 09:15:00',
        created_by: 'Lê Hoàng Long',
        note: 'Xuất bản phiên bản chính thức v3',
        is_published_version: true,
        title: 'CIC chính thức phát hành phần mềm CIC-SAP2000 v25 hỗ trợ tiêu chuẩn TCVN mới nhất',
        summary: 'Phiên bản v25 mang đến hơn 50 cải tiến vượt bậc...',
      },
    ],
    activity_logs: [
      { id: 'act_1', timestamp: '2026-08-01 09:15:00', user: 'Lê Hoàng Long', action: 'Xuất bản', details: 'Bài viết đã được xuất bản' },
      { id: 'act_2', timestamp: '2026-07-31 16:00:00', user: 'Nguyễn Văn Nam', action: 'Lưu nháp', details: 'Cập nhật nội dung bản nháp' },
    ],
    quality_warnings: [],
    created_time: '2026-08-01 09:15:00',
    updated_time: '2026-08-01 10:30:00',
  },
  {
    id: 'news_1002',
    title: 'Hội thảo Chuyển đổi số và Ứng dụng Mô hình BIM trong Công trình Xây dựng Đô thị 2026',
    alias: 'hoi-thao-chuyen-doi-so-va-ung-dung-mo-hinh-bim-2026',
    category_id: 'cat_news_events',
    summary: 'Sự kiện quy tụ hơn 300 chuyên gia, kiến trúc sư và đại diện các Ban Quản lý dự án hàng đầu toàn quốc trao đổi giải pháp quản lý dự án xây dựng thông minh.',
    content: `<p>Vừa qua tại Trung tâm Hội nghị Quốc gia Hà Nội, <strong>CIC Technology</strong> đã phối hợp cùng các đơn vị chuyên môn tổ chức thành công Hội thảo <em>"Chuyển đổi số và Ứng dụng Mô hình BIM 2026"</em>.</p><p>Hội thảo tập trung thảo luận các lộ trình áp dụng BIM bắt buộc đối với công trình cấp I và cấp đặc biệt theo quyết định của Thủ tướng Chính phủ. Đại diện CIC đã trình bày tham luận về giải pháp Quản lý dữ liệu công trình tập trung CDE (Common Data Environment).</p><h3>Nội dung trọng tâm hội thảo:</h3><ul><li>Lộ trình áp dụng BIM trong quản lý dự án đầu tư xây dựng công.</li><li>Tích hợp dữ liệu trắc địa GIS và mô hình BIM 3D/4D/5D.</li><li>Chia sẻ kinh nghiệm thực tế từ các chủ đầu tư lớn như Vingroup, Sun Group và Đèo Cả.</li></ul>`,
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&auto=format&fit=crop&q=80',
    image_alt: 'Hội thảo BIM 2026 do CIC phối hợp tổ chức',
    video: 'https://www.youtube.com/watch?v=3JZ_D3ELwOQ',
    tags: ['BIM', 'HỘI THẢO', 'CHUYỂN ĐỔI SỐ', 'XÂY DỰNG', 'CDE'],
    news_related: ['news_1001'],
    products_related: ['prod_cubicost'],
    start_time: '2026-07-25T08:00',
    end_time: '2026-12-31T23:59',
    timezone: 'Asia/Ho_Chi_Minh (UTC+7)',
    is_hot: false,
    is_new: true,
    show_in_homepage: true,
    published: true,
    ordering: 2,
    author: {
      name: 'Trần Thị Mai',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
      email: 'mai.tt@cic.com.vn',
    },
    seo_title: 'Hội thảo Chuyển đổi số BIM 2026 do CIC phối hợp tổ chức',
    seo_keyword: 'Hội thảo BIM 2026, chuyen doi so xay dung, CDE, CIC',
    seo_description: 'Toàn cảnh Hội thảo Chuyển đổi số BIM 2026 với sự tham gia của hơn 300 chuyên gia xây dựng hàng đầu.',
    working_version_number: 2,
    published_version_number: 2,
    has_unpublished_changes: false,
    created_time: '2026-07-26 14:20:00',
  },
  {
    id: 'news_1003',
    title: 'Nghiên cứu ứng dụng trí tuệ nhân tạo AI trong tự động hóa bóc tách khối lượng dự toán công trình',
    alias: 'nghien-cuu-ung-dung-tri-tue-nhan-tao-ai-trong-boc-tach-khoi-luong',
    category_id: 'cat_news_tech',
    summary: 'Bài viết trình bày giải pháp AI tự động đọc bản vẽ CAD/PDF và kết xuất bảng khối lượng chi tiết theo chuẩn định mức Nhà nước.',
    content: `<p>Bộ phận R&D tại CIC Technology đang tiến hành thử nghiệm mô hình trí tuệ nhân tạo chuyên biệt cho ngành xây dựng Việt Nam...</p>`,
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=80',
    video: '',
    tags: ['AI', 'BÓC TÁCH KHỐI LƯỢNG', 'DỰ TOÁN', 'CUBICOST'],
    news_related: [],
    products_related: ['prod_cubicost'],
    start_time: '2026-08-05T08:00',
    end_time: '2026-12-31T23:59',
    timezone: 'Asia/Ho_Chi_Minh (UTC+7)',
    is_hot: true,
    is_new: true,
    show_in_homepage: false,
    published: false,
    ordering: 3,
    author: {
      name: 'Phạm Đức Huy',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
      email: 'huy.pd@cic.com.vn',
    },
    seo_title: 'Ứng dụng AI trong tự động hóa bóc tách khối lượng dự toán',
    seo_keyword: 'AI xay dung, boc tach khoi luong AI, du toan AI, CIC',
    seo_description: 'Giải pháp AI tiên phong đọc bản vẽ CAD/PDF và kết xuất khối lượng dự toán chuẩn xác.',
    working_version_number: 1,
    has_unpublished_changes: true,
    quality_warnings: ['Thiếu thẻ Alt cho hình ảnh đại diện'],
    created_time: '2026-08-03 10:00:00',
  },
  {
    id: 'news_1004',
    title: 'Báo cáo tổng kết giải pháp thiết kế công trình giao thông trọng điểm miền Nam năm 2026',
    alias: 'bao-cao-tong-ket-giai-phap-thiet-ke-cong-trinh-giao-thong-2026',
    category_id: 'cat_news_projects',
    summary: 'Cung cấp góc nhìn toàn diện về hạ tầng giao thông kết nối các tuyến cao tốc phía Nam và vai trò các phần mềm thiết kế CIC.',
    content: `<p>Báo cáo phân tích việc áp dụng hệ thống phần mềm CIC-Road và phần mềm hạ tầng cho chuỗi dự án cao tốc...</p>`,
    image: 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800&auto=format&fit=crop&q=80',
    video: '',
    tags: ['CAO TỐC', 'GIAO THÔNG', 'CIC-ROAD', 'DỰ ÁN'],
    news_related: [],
    products_related: ['prod_cicroad'],
    start_time: '2026-08-02T08:00',
    end_time: '2026-12-31T23:59',
    timezone: 'Asia/Ho_Chi_Minh (UTC+7)',
    is_hot: false,
    is_new: false,
    show_in_homepage: false,
    published: false,
    ordering: 4,
    author: {
      name: 'Nguyễn Văn Nam',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
      email: 'nam.nv@cic.com.vn',
    },
    seo_title: 'Báo cáo giải pháp thiết kế công trình giao thông 2026',
    seo_keyword: 'thiet ke cao toc, CIC road, cao toc mien nam',
    seo_description: 'Báo cáo ứng dụng phần mềm CIC trong thiết kế hạ tầng cao tốc khu vực phía Nam.',
    working_version_number: 2,
    has_unpublished_changes: true,
    quality_warnings: ['Cần bổ sung số liệu dự án'],
    created_time: '2026-08-02 11:30:00',
  },
  {
    id: 'news_1005',
    title: 'Thông báo lịch ra mắt và đào tạo trực tuyến tính năng mới trên phần mềm ETABS v21',
    alias: 'thong-bao-lich-ra-mat-va-dao-tao-truc-tuyen-etabs-v21',
    category_id: 'cat_news_events',
    summary: 'Chuỗi khóa đào tạo miễn phí 03 buổi dành cho khách hàng đăng ký sở hữu bản quyền ETABS v21 chính hãng.',
    content: `<p>Thưa Quý khách hàng, CIC xin trân trọng thông báo lịch đào tạo trực tuyến qua Zoom vào ngày 15/08/2026...</p>`,
    image: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&auto=format&fit=crop&q=80',
    video: '',
    tags: ['ETABS', 'ĐÀO TẠO', 'WEBINAR', 'KẾT CẤU'],
    news_related: [],
    products_related: ['prod_etabs'],
    start_time: '2026-08-15T09:00',
    end_time: '2026-08-20T17:00',
    timezone: 'Asia/Ho_Chi_Minh (UTC+7)',
    is_hot: true,
    is_new: true,
    show_in_homepage: true,
    published: false,
    ordering: 5,
    author: {
      name: 'Trần Thị Mai',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    },
    seo_title: 'Lịch đào tạo trực tuyến phần mềm ETABS v21 miễn phí',
    seo_keyword: 'dao tao ETABS v21, webinar ETABS, CIC training',
    seo_description: 'Đăng ký khóa đào tạo trực tuyến phần mềm ETABS v21 do chuyên gia CIC giảng dạy.',
    working_version_number: 1,
    published_version_number: 1,
    has_unpublished_changes: false,
    created_time: '2026-08-01 16:45:00',
  },
  {
    id: 'news_1006',
    title: 'Hướng dẫn cài đặt và kích hoạt bản quyền dùng thử CIC-Road v22 chi tiết từ A-Z',
    alias: 'huong-dan-cai-dat-va-kich-hoat-ban-quyen-dung-thu-cic-road-v22',
    category_id: 'cat_news_guides',
    summary: 'Bài viết hướng dẫn chi tiết từng bước tải về, cài đặt driver khóa cứng Sentinel và kích hoạt License Online 30 ngày cho phần mềm thiết kế đường.',
    content: `<p>Để giúp quý khách hàng và kỹ sư trải nghiệm đầy đủ các tính năng mạnh mẽ trên phần mềm thiết kế hạ tầng giao thông <strong>CIC-Road v22</strong>, bộ phận hỗ trợ kỹ thuật CIC xin gửi tới bài hướng dẫn từng bước cài đặt.</p><h3>Các bước thực hiện nhanh:</h3><ol><li><strong>Bước 1:</strong> Tải bộ cài đặt chính thức từ máy chủ CIC.</li><li><strong>Bước 2:</strong> Giải nén và chạy file <code>Setup.exe</code> dưới quyền Administrator.</li><li><strong>Bước 3:</strong> Cài đặt Sentinel Driver hỗ trợ nhận diện khóa cứng USB.</li><li><strong>Bước 4:</strong> Nhập mã kích hoạt dùng thử 30 ngày do bộ phận hỗ trợ cấp.</li></ol>`,
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
    video: '',
    tags: ['CIC-ROAD', 'HƯỚNG DẪN', 'LICENSE', 'CÀI ĐẶT', 'GIAO THÔNG'],
    news_related: [],
    products_related: ['prod_cicroad'],
    start_time: '2026-07-10T08:00',
    end_time: '2026-12-31T23:59',
    timezone: 'Asia/Ho_Chi_Minh (UTC+7)',
    is_hot: false,
    is_new: false,
    show_in_homepage: false,
    published: true,
    ordering: 6,
    author: {
      name: 'Phạm Đức Huy',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    },
    seo_title: 'Hướng dẫn cài đặt CIC-Road v22 dùng thử bản quyền 30 ngày',
    seo_keyword: 'huong dan cai dat CIC Road, dung thu CIC Road, license CIC',
    seo_description: 'Các bước tải và cài đặt nhanh phần mềm thiết kế đường CIC-Road v22 cho kỹ sư giao thông.',
    working_version_number: 1,
    published_version_number: 1,
    has_unpublished_changes: false,
    created_time: '2026-07-10 10:05:00',
  },
  {
    id: 'news_1007',
    title: '[Đã xóa] Bản nháp thử nghiệm bài viết khảo sát thị trường phần mềm kết cấu 2025',
    alias: 'ban-nhap-thu-nghiem-bai-viet-khao-sat-thi-truong-2025',
    category_id: 'cat_news_tech',
    summary: 'Bài viết lưu trong thùng rác thử nghiệm khôi phục.',
    content: `<p>Nội dung bản nháp thử nghiệm xóa...</p>`,
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&auto=format&fit=crop&q=80',
    video: '',
    tags: ['THỦ NHIỆM'],
    news_related: [],
    products_related: [],
    start_time: '2025-01-01T08:00',
    end_time: '2025-12-31T23:59',
    is_hot: false,
    is_new: false,
    show_in_homepage: false,
    published: false,
    ordering: 99,
    author: {
      name: 'Nguyễn Văn Nam',
    },
    seo_title: 'Thử nghiệm',
    seo_keyword: 'test',
    seo_description: 'test',
    working_version_number: 1,
    in_trash: true,
    deleted_at: '2026-08-02 15:10:00',
    created_time: '2025-12-20 09:00:00',
  },
];
