import { CicUser, AgencyOption, CategoryOption } from './types';

export const agenciesMock: AgencyOption[] = [
  { id: 'agency_hn', name: 'Trụ sở chính Hà Nội (HQ)', code: 'HN' },
  { id: 'agency_hcm', name: 'Chi nhánh TP. Hồ Chí Minh', code: 'HCM' },
  { id: 'agency_dn', name: 'Văn phòng Đại diện Đà Nẵng', code: 'DN' },
  { id: 'agency_ct', name: 'Văn phòng Đại diện Cần Thơ', code: 'CT' },
];

export const productCategoriesMock: CategoryOption[] = [
  { id: 'cat_p1', name: 'Phần mềm Phân tích Kết cấu (SAP2000, ETABS, SAFE)' },
  { id: 'cat_p2', name: 'Giải pháp Mô hình hóa thông tin BIM (Revit, Tekla)' },
  { id: 'cat_p3', name: 'Phần mềm Địa kỹ thuật & Mái dốc (Plaxis, GeoStudio)' },
  { id: 'cat_p4', name: 'Hệ thống Quản lý Đô thị & CAD (EnjiCAD, GIS)' },
  { id: 'cat_p5', name: 'Thiết bị Đo đạc & Trắc địa Công trình' },
  { id: 'cat_p6', name: 'Giải pháp Quản lý Chi phí & Dự toán (CostX)' },
];

export const newsCategoriesMock: CategoryOption[] = [
  { id: 'cat_n1', name: 'Tin tức Doanh nghiệp CIC' },
  { id: 'cat_n2', name: 'Sự kiện & Hội thảo Công nghệ' },
  { id: 'cat_n3', name: 'Kiến thức Kỹ thuật & Hướng dẫn' },
  { id: 'cat_n4', name: 'Thông cáo Báo chí & Bản quyền' },
  { id: 'cat_n5', name: 'Dự án & Khách hàng Tiêu biểu' },
];

export const cicUsersMock: CicUser[] = [
  {
    id: 'usr_001',
    username: 'admin_cic',
    email: 'admin@cic.com.vn',
    fname: 'Quản Trị',
    lname: 'Nguyễn Văn',
    full_name: 'Nguyễn Văn Quản Trị',
    phone: '0912 345 678',
    country: 'Việt Nam',
    address: '37 Lê Thanh Nghị, Hai Bà Trưng, Hà Nội',
    summary: 'Quản trị viên hệ thống cấp cao phụ trách toàn bộ hệ thống CMS.',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    published: true,
    ordering: 1,
    agencies: ['agency_hn'],
    products_categories: ['cat_p1', 'cat_p2', 'cat_p3', 'cat_p4'],
    news_categories: ['cat_n1', 'cat_n2', 'cat_n3', 'cat_n4'],
    status_online: true,
    created_time: '2025-01-15 08:30:00',
    updated_time: '2026-07-30 14:22:10',
    last_visit_time: '2026-08-02 09:15:00',
    nums_visit: 1240,
  },
  {
    id: 'usr_002',
    username: 'minh_bien',
    email: 'minh.bien@cic.com.vn',
    fname: 'Minh',
    lname: 'Trần Biên',
    full_name: 'Trần Biên Minh',
    phone: '0988 123 456',
    country: 'Việt Nam',
    address: '180 Cao Thắng, Phường 12, Quận 10, TP.HCM',
    summary: 'Biên tập viên phòng Truyền thông & Quảng bá giải pháp phần mềm.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    published: true,
    ordering: 2,
    agencies: ['agency_hcm'],
    products_categories: ['cat_p1', 'cat_p2'],
    news_categories: ['cat_n1', 'cat_n2', 'cat_n5'],
    status_online: true,
    created_time: '2025-03-20 10:12:45',
    updated_time: '2026-07-28 16:05:00',
    last_visit_time: '2026-08-02 08:40:12',
    nums_visit: 580,
  },
  {
    id: 'usr_003',
    username: 'hoang_kythuat',
    email: 'hoang.tech@cic.com.vn',
    fname: 'Hoàng',
    lname: 'Lê Huy',
    full_name: 'Lê Huy Hoàng',
    phone: '0903 888 999',
    country: 'Việt Nam',
    address: '25 Nguyễn Tri Phương, Thanh Khê, Đà Nẵng',
    summary: 'Chuyên gia hỗ trợ kỹ thuật và đào tạo chuyển giao phần mềm CSI & Plaxis.',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    published: true,
    ordering: 3,
    agencies: ['agency_dn'],
    products_categories: ['cat_p3', 'cat_p4', 'cat_p5'],
    news_categories: ['cat_n3'],
    status_online: false,
    created_time: '2025-06-10 15:45:12',
    updated_time: '2026-07-25 11:30:00',
    last_visit_time: '2026-08-01 17:20:00',
    nums_visit: 310,
  },
  {
    id: 'usr_004',
    username: 'phuong_kinhdoanh',
    email: 'phuong.sales@cic.com.vn',
    fname: 'Phương',
    lname: 'Pham Mai',
    full_name: 'Phạm Mai Phương',
    phone: '0934 567 890',
    country: 'Việt Nam',
    address: 'Tòa nhà CIC, Phường 1, Cần Thơ',
    summary: 'Chuyên viên quản lý đăng ký báo giá và liên hệ khách hàng khu vực Miền Tây.',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    published: false,
    ordering: 4,
    agencies: ['agency_ct'],
    products_categories: ['cat_p1', 'cat_p6'],
    news_categories: ['cat_n4'],
    status_online: false,
    created_time: '2025-09-01 09:00:00',
    updated_time: '2026-06-15 14:00:00',
    last_visit_time: '2026-07-10 10:15:00',
    nums_visit: 142,
  },
];
