import { EventCategory, EventItem, RelatedProductItem } from './types';

export const mockEventCategories: EventCategory[] = [
  { id: 'cat_ev_conference', name: 'Hội thảo & Diễn đàn', slug: 'hoi-thao-dien-dan' },
  { id: 'cat_ev_training', name: 'Đào tạo & Tập huấn', slug: 'dao-tao-tap-huan' },
  { id: 'cat_ev_expo', name: 'Triển lãm & Demo', slug: 'trien-lam-demo' },
  { id: 'cat_ev_webinar', name: 'Webinar Trực tuyến', slug: 'webinar-truc-tuyen' },
];

export const mockEventProducts: RelatedProductItem[] = [
  {
    id: 'prod_sap2000',
    name: 'Phần mềm Phân tích Kết cấu CIC-SAP2000 v25',
    code: 'SAP2000-V25',
    image: 'https://images.unsplash.com/photo-1581092921461-eab62e97a780?w=200&auto=format&fit=crop&q=80',
  },
  {
    id: 'prod_etabs',
    name: 'Phần mềm Thiết kế Nhà cao tầng CIC-ETABS v21',
    code: 'ETABS-V21',
    image: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=200&auto=format&fit=crop&q=80',
  },
  {
    id: 'prod_cubicost',
    name: 'Phần mềm Dự toán & Bóc tách Khối lượng Cubicost',
    code: 'CUBICOST-TAS',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=200&auto=format&fit=crop&q=80',
  },
];

export const mockEvents: EventItem[] = [
  {
    id: 'ev_1001',
    title: 'Hội thảo Chuyển đổi số & Ứng dụng Giải pháp Mô hình hóa BIM trong Xây dựng Đô thị 2026',
    alias: 'hoi-thao-chuyen-doi-so-va-ung-dung-mo-hinh-bim-2026',
    category_id: 'cat_ev_conference',
    summary: 'Sự kiện thường niên lớn nhất của CIC quy tụ hơn 500 chuyên gia, kiến trúc sư và đại diện Ban Quản lý Dự án chia sẻ lộ trình áp dụng BIM bắt buộc.',
    content: `<p>Nhằm đáp ứng lộ trình áp dụng Mô hình thông tin công trình (BIM) bắt buộc cho các dự án đầu tư xây dựng công theo Nghị định của Chính phủ, <strong>Công ty Cổ phần Công nghệ và Tư vấn CIC</strong> phối hợp cùng Hiệp hội Xây dựng Việt Nam tổ chức Diễn đàn Chuyển đổi số 2026.</p><h3>Nội dung chương trình chi tiết:</h3><ul><li><strong>08:00 - 08:30:</strong> Đón tiếp đại biểu và đăng ký tham dự.</li><li><strong>08:30 - 09:30:</strong> Tham luận: Lộ trình triển khai CDE & BIM trong dự án hạ tầng giao thông trọng điểm.</li><li><strong>09:30 - 10:45:</strong> Demo thực tế giải pháp CIC-SAP2000 v25 & Cubicost TAS/TRB.</li><li><strong>10:45 - 11:45:</strong> Tọa đàm Q&A cùng đại diện Bộ Xây dựng và các chuyên gia hàng đầu.</li></ul><p>Quý đối tác và khách hàng tham dự sẽ nhận ngay tài liệu hướng dẫn chuẩn và voucher ưu đãi 20% khi mua bản quyền phần mềm CIC.</p>`,
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&auto=format&fit=crop&q=80',
    time_event: '2026-08-20T08:00',
    end_time: '2026-08-20T17:00',
    place: 'Trung tâm Hội nghị Quốc gia, Số 57 Phạm Hùng, Quận Nam Từ Liêm, Thành phố Hà Nội',
    specific_time: '08:00 - 17:00 ngày 20/08/2026',
    chu_de: 'BIM & Digital Transformation in Construction 2026',
    link_dangky: 'https://cic.com.vn/su-kien/dang-ky-hoi-thao-bim-2026',
    event_related: ['ev_1002'],
    news_related: ['news_1001', 'news_1002'],
    products_related: ['prod_sap2000', 'prod_cubicost'],
    is_new: true,
    is_hot: true,
    show_in_home: true,
    published: true,
    ordering: 1,
    seo_title: 'Hội thảo Chuyển đổi số & BIM 2026 - Công ty CIC Technology',
    seo_keyword: 'Hoi thao BIM 2026, Chuyen doi so xay dung, CIC conference, SAP2000 v25',
    seo_description: 'Tham gia Diễn đàn Chuyển đổi số và Ứng dụng BIM 2026 tại Hà Nội do CIC tổ chức với hơn 500 chuyên gia.',
    created_time: '2026-07-28 09:30:00',
    updated_time: '2026-07-29 14:15:00',
  },
  {
    id: 'ev_1002',
    title: 'Khóa Đào tạo Chuyên sâu Phân tích Kết cấu Phi tuyến với CIC-SAP2000 & ETABS v21',
    alias: 'khoa-dao-tao-chuyen-sau-phan-tich-ket-cau-phi-tuyen-sap2000-etabs',
    category_id: 'cat_ev_training',
    summary: 'Chương trình huấn luyện kỹ sư kết cấu thực hành giải bài toán động lực học, chịu tải trọng động đất và xuất kết quả thuyết minh đạt chuẩn TCVN.',
    content: `<p>Khóa đào tạo 3 ngày được giảng dạy trực tiếp bởi các Chuyên gia Kỹ thuật Kết cấu của CIC với hơn 15 năm kinh nghiệm thực chiến tại các dự án nhà cao tầng và cầu vượt biển.</p><h3>Đối tượng tham gia:</h3><p>Kỹ sư thiết kế kết cấu, chủ trì bộ môn, giảng viên các trường đại học khối kỹ thuật xây dựng.</p>`,
    image: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&auto=format&fit=crop&q=80',
    time_event: '2026-09-05T08:30',
    end_time: '2026-09-07T16:30',
    place: 'Phòng Lab Kỹ thuật 402, Tòa nhà CIC Building, Số 37 Lê Thanh Nghị, Quận Hai Bà Trưng, Hà Nội',
    specific_time: '08:30 - 16:30 các ngày thứ 6, thứ 7 và Chủ Nhật',
    chu_de: 'Structural Nonlinear Analysis Training',
    link_dangky: 'https://cic.com.vn/dao-tao/khoa-hoc-sap2000-etabs-2026',
    event_related: ['ev_1001'],
    news_related: ['news_1001'],
    products_related: ['prod_sap2000', 'prod_etabs'],
    is_new: true,
    is_hot: false,
    show_in_home: true,
    published: true,
    ordering: 2,
    seo_title: 'Khóa đào tạo tính toán kết cấu phi tuyến SAP2000 & ETABS - CIC',
    seo_keyword: 'dao tao SAP2000, ETABS v21, ky su ket cau, TCVN 5574',
    seo_description: 'Khóa huấn luyện chuyên sâu thực hành phân tích kết cấu công trình chịu tải trọng động đất cùng chuyên gia CIC.',
    created_time: '2026-07-25 11:20:00',
  },
  {
    id: 'ev_1003',
    title: 'Webinar Trực tuyến: Tối ưu hóa Khối lượng và Dự toán Công trình Xây dựng với Cubicost',
    alias: 'webinar-truc-tuyen-toi-uu-hoa-khoi-luong-du-toan-cubicost',
    category_id: 'cat_ev_webinar',
    summary: 'Buổi chia sẻ trực tuyến qua Zoom hướng dẫn tự động hóa 80% thời gian bóc tách khối lượng bê tông, cốt thép và hoàn thiện từ mô hình 3D.',
    content: `<p>Bóc tách khối lượng luôn là khâu tốn nhiều thời gian và dễ phát sinh sai sót trong công tác lập dự toán. Webinar trực tuyến này sẽ trình bày giải pháp giải quyết triệt để bài toán này.</p>`,
    image: 'https://images.unsplash.com/photo-1588196749597-9ff075ee6b5b?w=800&auto=format&fit=crop&q=80',
    time_event: '2026-09-15T14:00',
    end_time: '2026-09-15T16:30',
    place: 'Trực tuyến qua Zoom Meeting & LiveStream Fanpage CIC Technology',
    specific_time: '14:00 - 16:30 Chiều Thứ Ba',
    chu_de: 'Automated Quantity Takeoff with Cubicost',
    link_dangky: 'https://zoom.us/webinar/register/cic-cubicost-2026',
    event_related: [],
    news_related: [],
    products_related: ['prod_cubicost'],
    is_new: false,
    is_hot: true,
    show_in_home: false,
    published: true,
    ordering: 3,
    seo_title: 'Webinar Tự động hóa bóc tách khối lượng công trình Cubicost',
    seo_keyword: 'Webinar Cubicost, boc tach khoi luong, du toan xay dung, CIC Zoom',
    seo_description: 'Đăng ký tham dự Webinar miễn phí tự động hóa bóc tách khối lượng bê tông cốt thép với Cubicost.',
    created_time: '2026-07-15 16:45:00',
  },
];
