import type { DemoProduct, LegalDocument } from "./types";

export const demoProducts: DemoProduct[] = [
  { id:"p1", productCode:"MK-BOSCH-001", productName:"Máy khoan bê tông Bosch GBH 2-26", category:"Máy khoan", brand:"Bosch", description:"Máy khoan bê tông cho công trình và sửa chữa.", useCase:"Khoan bê tông, khoan tường và đục nhẹ", power:"800W", weight:"2.9kg", price:2950000, unit:"Chiếc", stock:12, warranty:"12 tháng", standards:"An toàn điện IEC" },
  { id:"p2", productCode:"MK-MAKITA-002", productName:"Máy khoan động lực Makita M8103K", category:"Máy khoan", brand:"Makita", description:"Máy khoan nhỏ gọn cho công việc dân dụng.", useCase:"Khoan tường, gỗ và kim loại", power:"710W", weight:"2.1kg", price:1890000, unit:"Chiếc", stock:4, warranty:"12 tháng", standards:"An toàn điện IEC" },
  { id:"p3", productCode:"MK-DEWALT-003", productName:"Máy khoan bê tông Dewalt D25133K", category:"Máy khoan", brand:"Dewalt", description:"Máy khoan ba chế độ hiệu suất cao.", useCase:"Khoan và đục bê tông chuyên nghiệp", power:"800W", weight:"2.6kg", price:3390000, unit:"Chiếc", stock:0, warranty:"36 tháng", standards:"CE" },
  { id:"p4", productCode:"MC-BOSCH-004", productName:"Máy cắt sắt Bosch GCO 14-24", category:"Máy cắt", brand:"Bosch", description:"Máy cắt sắt công suất lớn cho xưởng và công trường.", useCase:"Cắt thép hình và ống kim loại", power:"2400W", weight:"17kg", price:4650000, unit:"Chiếc", stock:7, warranty:"12 tháng", standards:"An toàn máy công nghiệp" },
  { id:"p5", productCode:"MD-BOSCH-005", productName:"Máy đo khoảng cách Bosch GLM 40", category:"Máy đo khoảng cách", brand:"Bosch", description:"Máy đo laser nhỏ gọn, phạm vi 40 mét.", useCase:"Đo hiện trạng và bóc tách công trình", power:"Pin AAA", weight:"0.1kg", price:2250000, unit:"Chiếc", stock:15, warranty:"12 tháng", standards:"Laser Class 2" },
  { id:"p6", productCode:"MD-LEICA-006", productName:"Máy đo khoảng cách Leica Disto D2", category:"Máy đo khoảng cách", brand:"Leica", description:"Máy đo laser chính xác có Bluetooth.", useCase:"Đo chuyên nghiệp và truyền dữ liệu", power:"Pin AAA", weight:"0.1kg", price:4950000, unit:"Chiếc", stock:3, warranty:"24 tháng", standards:"Laser Class 2" },
  { id:"p7", productCode:"BH-3M-007", productName:"Mũ bảo hộ 3M H-700", category:"Thiết bị bảo hộ", brand:"3M", description:"Mũ bảo hộ nhẹ có núm vặn điều chỉnh.", useCase:"Bảo vệ đầu tại công trường", power:"—", weight:"0.35kg", price:420000, unit:"Chiếc", stock:38, warranty:"6 tháng", standards:"ANSI Z89.1" },
  { id:"p8", productCode:"DC-STANLEY-008", productName:"Bộ dụng cụ cầm tay Stanley 65 chi tiết", category:"Dụng cụ cầm tay", brand:"Stanley", description:"Bộ dụng cụ sửa chữa đa năng trong vali.", useCase:"Bảo trì và sửa chữa cơ bản", power:"—", weight:"6.2kg", price:2750000, unit:"Bộ", stock:9, warranty:"12 tháng", standards:"DIN" },
];

export const demoLegalDocuments: LegalDocument[] = [
  { id:"d1", title:"Nghị định về quản lý dự án đầu tư xây dựng", documentNumber:"15/2021/NĐ-CP", documentType:"Nghị định", article:"Điều 41", clause:"Khoản 1", text:"Điều kiện cấp giấy phép xây dựng được xem xét trên cơ sở hồ sơ, quy hoạch và mục đích sử dụng đất theo quy định.", status:"effective" },
  { id:"d2", title:"Luật Xây dựng 2014", documentNumber:"50/2014/QH13", documentType:"Luật", article:"Điều 89", clause:"Khoản 1", text:"Công trình xây dựng phải có giấy phép xây dựng do cơ quan nhà nước có thẩm quyền cấp, trừ trường hợp được miễn.", status:"effective" },
  { id:"d3", title:"Nghị định quản lý dự án đầu tư xây dựng cũ", documentNumber:"59/2015/NĐ-CP", documentType:"Nghị định", article:"Điều 10", clause:"Khoản 2", text:"Nội dung mô phỏng của văn bản đã hết hiệu lực.", status:"expired", replacement:"Nghị định 15/2021/NĐ-CP" },
  { id:"d4", title:"Luật sửa đổi, bổ sung một số điều của Luật Xây dựng", documentNumber:"62/2020/QH14", documentType:"Luật", article:"Điều 1", clause:"Khoản 30", text:"Sửa đổi và bổ sung quy định về cấp giấy phép xây dựng và quản lý trật tự xây dựng.", status:"effective" },
  { id:"d5", title:"Quy chuẩn kỹ thuật quốc gia về an toàn trong thi công xây dựng", documentNumber:"QCVN 18:2021/BXD", documentType:"Quy chuẩn", article:"Mục 2.1", clause:"—", text:"Tổ chức, cá nhân tham gia thi công phải thực hiện các biện pháp bảo đảm an toàn lao động.", status:"effective" },
];

export const demoScenarios = ["Tôi cần máy khoan bê tông dưới 3 triệu.", "So sánh hai sản phẩm đầu tiên.", "Sản phẩm thứ hai còn hàng không?", "Điều kiện cấp phép xây dựng là gì?", "Tôi muốn nhân viên tư vấn.", "Tôi muốn báo giá 10 sản phẩm.", "Tôi muốn được gọi lại vào chiều mai."];
