"use client";
import {FormEvent,useState} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {apiRequest} from "@/lib/api";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
type Prompt={id:string;key:string;name:string;content:string;is_active:boolean};
const empty={key:"",name:"",content:"",is_active:true};
export default function PromptsPage(){const qc=useQueryClient();const [form,setForm]=useState(empty);const [editing,setEditing]=useState<string|null>(null);const q=useQuery<Prompt[]>({queryKey:["prompts"],queryFn:()=>apiRequest("/system/prompts")});const save=useMutation({mutationFn:()=>apiRequest(editing?`/system/prompts/${editing}`:"/system/prompts",{method:editing?"PUT":"POST",body:JSON.stringify(form)}),onSuccess:()=>{setForm(empty);setEditing(null);void qc.invalidateQueries({queryKey:["prompts"]})}});const submit=(e:FormEvent)=>{e.preventDefault();save.mutate()};return <main className="mx-auto max-w-7xl space-y-6 p-6"><header><p className="text-xs font-bold uppercase text-blue-700">Cấu hình AI</p><h1 className="text-2xl font-bold">Prompt AI</h1></header><form onSubmit={submit} className="space-y-3 rounded-2xl border bg-white p-5"><div className="grid gap-3 md:grid-cols-2"><Input placeholder="Mã: product_advice" value={form.key} onChange={e=>setForm({...form,key:e.target.value})} required/><Input placeholder="Tên prompt" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></div><Textarea className="min-h-40" placeholder="Nội dung chỉ dẫn cho AI" value={form.content} onChange={e=>setForm({...form,content:e.target.value})} required/><div className="flex gap-2"><Button disabled={save.isPending}>{editing?"Lưu thay đổi":"Tạo prompt"}</Button>{editing&&<Button type="button" variant="outline" onClick={()=>{setEditing(null);setForm(empty)}}>Hủy</Button>}</div></form><div className="grid gap-3">{q.data?.map(p=><article key={p.id} className="rounded-xl border bg-white p-4"><div className="flex justify-between"><div><h2 className="font-bold">{p.name}</h2><code className="text-xs text-blue-700">{p.key}</code></div><div className="flex gap-2"><button className="rounded border px-3 text-xs font-bold" onClick={()=>{setEditing(p.id);setForm({key:p.key,name:p.name,content:p.content,is_active:p.is_active})}}>Sửa</button><button className="rounded border px-3 text-xs font-bold text-rose-700" onClick={()=>apiRequest(`/system/prompts/${p.id}`,{method:"DELETE"}).then(()=>qc.invalidateQueries({queryKey:["prompts"]}))}>Xóa</button></div></div><p className="mt-3 whitespace-pre-wrap text-sm text-slate-600">{p.content}</p></article>)}</div></main>}
