import 'server-only';
import { getPostgresClient } from '@/server/db/postgres';
import type { PublicProductContactMap,PublicProductContacts,SalesOwnerAssignments,SalesOwnerItem,SalesOwnerLocale,SalesOwnerModuleData } from '../types';

const table=(locale:SalesOwnerLocale)=>locale==='en'?'cic_business_en':'cic_business';
const products=(locale:SalesOwnerLocale)=>locale==='en'?'cic_products_en':'cic_products';
export const parseLegacyIds=(value:unknown):string[]=>[...new Set(String(value??'').split(',').map(v=>v.trim()).filter(v=>/^\d+$/.test(v)))];
const assignments=(row:Record<string,unknown>):SalesOwnerAssignments=>({contact:parseLegacyIds(row.lienhe),sales:parseLegacyIds(row.lienhe_kd),technical:parseLegacyIds(row.lienhe_kt),northSales:parseLegacyIds(row.lienhe_kdmb),southSales:parseLegacyIds(row.lienhe_kdmn)});
const map=(row:Record<string,unknown>,valid:Set<string>):SalesOwnerItem=>{const a=assignments(row);const all=[...a.contact,...a.sales,...a.technical,...a.northSales,...a.southSales];return{id:String(row.id),name:String(row.name??''),alias:String(row.alias??''),phone:String(row.phone??''),skype:String(row.Skype??''),zalo:String(row.Zalo??''),ordering:Number(row.ordering??0),published:Number(row.published)===1,createdTime:row.created_time==null?null:new Date(String(row.created_time)).toISOString(),updatedTime:row.updated_time==null?null:new Date(String(row.updated_time)).toISOString(),assignments:a,usageCount:new Set(all).size,orphanProductIds:[...new Set(all.filter(id=>!valid.has(id)))]};};
export async function getCmsSalesOwners(locale:SalesOwnerLocale){const sql=getPostgresClient(),source=table(locale),productTable=products(locale);const [rows,productRows]=await Promise.all([sql.unsafe(`SELECT id,name,alias,phone,"Skype","Zalo",ordering,published,created_time,updated_time,lienhe,lienhe_kd,lienhe_kt,lienhe_kdmb,lienhe_kdmn FROM ${source} ORDER BY ordering,id`),sql.unsafe(`SELECT id,name,published FROM ${productTable} ORDER BY name,id`)]);const valid=new Set(productRows.map(r=>String(r.id)));return{items:rows.map(r=>map(r as Record<string,unknown>,valid)),products:productRows.map(r=>({id:String(r.id),name:String(r.name??''),published:Number(r.published)===1}))};}
export async function getSalesOwnerModuleData():Promise<SalesOwnerModuleData>{const [vi,en]=await Promise.all([getCmsSalesOwners('vi'),getCmsSalesOwners('en')]);return{vi,en};}
export async function getPublicProductContacts(productId:number,locale:SalesOwnerLocale='vi'):Promise<PublicProductContacts>{const sql=getPostgresClient(),source=table(locale);const rows=await sql.unsafe(`SELECT id,name,phone,lienhe,lienhe_kd,lienhe_kt,lienhe_kdmb,lienhe_kdmn FROM ${source} WHERE published=1 ORDER BY ordering,id`);const contact=(key:string)=>rows.filter(r=>parseLegacyIds(r[key]).includes(String(productId))).map(r=>({id:String(r.id),name:String(r.name??''),phone:String(r.phone??'')}));return{contact:contact('lienhe'),sales:contact('lienhe_kd'),technical:contact('lienhe_kt'),northSales:contact('lienhe_kdmb'),southSales:contact('lienhe_kdmn')};}
export async function listPublicProductContacts(locale:SalesOwnerLocale='vi'):Promise<PublicProductContactMap>{const sql=getPostgresClient(),source=table(locale);const rows=await sql.unsafe(`SELECT id,name,phone,lienhe,lienhe_kd,lienhe_kt,lienhe_kdmb,lienhe_kdmn FROM ${source} WHERE published=1 ORDER BY ordering,id`);const result:Record<string,{contact:{id:string;name:string;phone:string}[];sales:{id:string;name:string;phone:string}[];technical:{id:string;name:string;phone:string}[];northSales:{id:string;name:string;phone:string}[];southSales:{id:string;name:string;phone:string}[]}>= {};const mapping=[['contact','lienhe'],['sales','lienhe_kd'],['technical','lienhe_kt'],['northSales','lienhe_kdmb'],['southSales','lienhe_kdmn']] as const;for(const row of rows){const person={id:String(row.id),name:String(row.name??''),phone:String(row.phone??'')};for(const[key,column]of mapping)for(const productId of parseLegacyIds(row[column])){result[productId]??={contact:[],sales:[],technical:[],northSales:[],southSales:[]};result[productId][key].push(person);}}return result;}
