import 'server-only';
import type { Sql } from 'postgres';
import { moveSalesOwnerToTrash } from '@/features/trash/server/adapters/sales-owner';
import { AUDIT_ACTIONS,AUDIT_ENTITY_TYPES } from '@/server/audit/registry';
import { writeAuditEvent } from '@/server/audit/writer';
import type { CmsPrincipal } from '@/server/auth/guards';
import { withTransaction } from '@/server/db/postgres';
import type { SalesOwnerInput } from '../schemas/salesOwnerInput';
import type { SalesOwnerLocale } from '../types';
import { parseLegacyIds } from './queries';

const table=(l:SalesOwnerLocale)=>l==='en'?'cic_business_en':'cic_business';const products=(l:SalesOwnerLocale)=>l==='en'?'cic_products_en':'cic_products';
const fields={contact:'lienhe',sales:'lienhe_kd',technical:'lienhe_kt',northSales:'lienhe_kdmb',southSales:'lienhe_kdmn'} as const;
const csv=(ids:number[])=>ids.length?`,`+ids.join(',')+`,`:'';
async function validate(sql:Sql,locale:SalesOwnerLocale,id:number|null,input:SalesOwnerInput){const source=table(locale);if((await sql.unsafe(`SELECT 1 FROM ${source} WHERE lower(btrim(alias))=lower(btrim($1)) AND ($2::int IS NULL OR id<>$2) LIMIT 1`,[input.alias,id])).length)throw new Error('Tên hiệu đã được người phụ trách khác sử dụng.');const old=id?(await sql.unsafe(`SELECT lienhe,lienhe_kd,lienhe_kt,lienhe_kdmb,lienhe_kdmn FROM ${source} WHERE id=$1`,[id]))[0]:null;const requested=[...new Set(Object.values(input.assignments).flat())];if(!requested.length)return;const validRows=await sql.unsafe(`SELECT id FROM ${products(locale)} WHERE id=ANY($1::int[])`,[requested]);const valid=new Set(validRows.map(r=>Number(r.id)));for(const [key,column] of Object.entries(fields) as [keyof typeof fields,string][]){const preserved=new Set(parseLegacyIds(old?.[column]).map(Number));for(const productId of input.assignments[key])if(!valid.has(productId)&&!preserved.has(productId))throw new Error(`Sản phẩm ID ${productId} không tồn tại trong workspace ${locale.toUpperCase()}.`);}}
export async function saveSalesOwner(locale:SalesOwnerLocale,id:number|null,input:SalesOwnerInput,actor:CmsPrincipal){return withTransaction(async sql=>{await validate(sql,locale,id,input);const source=table(locale);const before=id?(await sql.unsafe(`SELECT id,name,alias,phone,"Skype","Zalo",ordering,published,lienhe,lienhe_kd,lienhe_kt,lienhe_kdmb,lienhe_kdmn FROM ${source} WHERE id=$1 FOR UPDATE`,[id]))[0]:null;if(id&&!before)throw new Error('Không tìm thấy người phụ trách.');const a=input.assignments;const values=[input.name,input.alias,input.phone,input.skype,input.zalo,input.ordering,input.published?1:0,csv(a.contact),csv(a.sales),csv(a.technical),csv(a.northSales),csv(a.southSales)];const rows=id?await sql.unsafe(`UPDATE ${source} SET name=$1,alias=$2,phone=$3,"Skype"=$4,"Zalo"=$5,ordering=$6,published=$7,lienhe=$8,lienhe_kd=$9,lienhe_kt=$10,lienhe_kdmb=$11,lienhe_kdmn=$12,updated_time=now() WHERE id=$13 RETURNING id,name`,[...values,id]):await sql.unsafe(`INSERT INTO ${source}(name,alias,phone,"Skype","Zalo",ordering,published,lienhe,lienhe_kd,lienhe_kt,lienhe_kdmb,lienhe_kdmn,created_time,updated_time) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,now(),now()) RETURNING id,name`,values);const row=rows[0];await writeAuditEvent(actor,{action:id?AUDIT_ACTIONS.SALES_OWNER_UPDATED:AUDIT_ACTIONS.SALES_OWNER_CREATED,entityType:AUDIT_ENTITY_TYPES.SALES_OWNER,entityId:String(row.id),entityTitle:String(row.name),module:'product_settings',workspace:locale,result:'success',before,after:input},sql);return{id:String(row.id)};});}
export async function setSalesOwnersPublished(locale:SalesOwnerLocale,ids:number[],published:boolean,actor:CmsPrincipal){return withTransaction(async sql=>{const rows=await sql.unsafe(`UPDATE ${table(locale)} SET published=$1,updated_time=now() WHERE id=ANY($2::int[]) RETURNING id,name`,[published?1:0,ids]);if(rows.length!==ids.length)throw new Error('Một hoặc nhiều người phụ trách không tồn tại.');for(const row of rows)await writeAuditEvent(actor,{action:AUDIT_ACTIONS.SALES_OWNER_STATUS_CHANGED,entityType:AUDIT_ENTITY_TYPES.SALES_OWNER,entityId:String(row.id),entityTitle:String(row.name),module:'product_settings',workspace:locale,result:'success',after:{published}},sql);});}
export async function trashSalesOwner(locale:SalesOwnerLocale,id:number,actor:CmsPrincipal){return withTransaction(async sql=>{const moved=await moveSalesOwnerToTrash(sql,locale,id,actor.legacyUserId);await writeAuditEvent(actor,{action:AUDIT_ACTIONS.SALES_OWNER_TRASHED,entityType:AUDIT_ENTITY_TYPES.SALES_OWNER,entityId:String(id),entityTitle:moved.title,module:'product_settings',workspace:locale,result:'success',after:{trashId:moved.trashId}},sql);return moved;});}
