import { ServiceItem, ServiceGroup, ServiceActivityLog, ServiceVersion, ServiceUsedByReference, ServiceRelatedContact } from './types';

export const serviceGroupsMock: ServiceGroup[] = [
  {
    id: 'grp_01',
    name: 'Tư vấn & Chuyển giao BIM',
    code: 'GR-BIM',
    description: 'Dịch vụ tư vấn lộ trình chuyển đổi số BIM và đào tạo phần mềm Autodesk/CSI',
    display_order: 1,
    status: 'active',
  },
  {
    id: 'grp_02',
    name: 'Khảo sát & Thử nghiệm Công trình',
    code: 'GR-KS',
    description: 'Dịch vụ đo đạc, kiểm định công trình và khảo sát địa chất chuyên sâu',
    display_order: 2,
    status: 'active',
  },
  {
    id: 'grp_03',
    name: 'Đào tạo & Cấp chứng chỉ Chuyên môn',
    code: 'GR-ĐT',
    description: 'Đào tạo sử dụng phần mềm kết cấu, dự toán ESCON và BIM Manager',
    display_order: 3,
    status: 'active',
  },
  {
    id: 'grp_04',
    name: 'Bảo trì & Tối ưu hóa Phần mềm Bản quyền',
    code: 'GR-BT',
    description: 'Bảo trì hệ thống License mạng, nâng cấp phiên bản và hỗ trợ kỹ thuật 24/7',
    display_order: 4,
    status: 'active',
  },
];

export const mockServicesData: ServiceItem[] = [
  {
    id: 'srv_101',
    code: 'DV-BIM-01',
    title: 'Tư vấn Lộ trình Chuyển đổi số BIM ISO 19650 cho Doanh nghiệp Xây dựng',
    slug: 'tu-van-lo-trinh-chuyen-doi-so-bim-iso-19650',
    summary: 'Tư vấn toàn diện việc áp dụng quy trình BIM chuẩn quốc tế ISO 19650, xây dựng khung EIR/BEP và tích hợp môi trường dữ liệu chung CDE cho các chủ đầu tư và tư vấn thiết kế.',
    group_id: 'grp_01',
    group_name: 'Tư vấn & Chuyển giao BIM',
    scope: 'Toàn quốc & Tập đoàn FDI',
    business_relation: 'Dịch vụ độc lập & Đi kèm gói phần mềm',
    description: `<p>Dịch vụ tư vấn triển khai BIM của CIC giúp doanh nghiệp chuẩn hóa quy trình làm việc theo chuẩn ISO 19650. Chúng tôi đồng hành cùng khách hàng từ khâu đánh giá năng lực hiện trạng (BIM Maturity Assessment), xây dựng tài liệu BEP/EIR đến việc chuẩn hóa thư viện mẫu Revit và phần mềm quản lý dự án.</p>
    <h4>Các nội dung trọng tâm:</h4>
    <ul>
      <li>Xây dựng quy trình trao đổi dữ liệu CDE (Autodesk Construction Cloud / ACC)</li>
      <li>Chuẩn hóa thư viện đối tượng BIM 3D/4D/5D</li>
      <li>Đào tạo nhân sự vai trò BIM Manager và BIM Coordinator</li>
    </ul>`,
    benefits_process: 'Giảm 35% xung đột bản vẽ trên công trường, rút ngắn 20% tiến độ lập hồ sơ thi công, kiểm soát chi phí tức thời qua mô hình 5D.',
    supplementary_content: 'Hỗ trợ đánh giá lại sau 6 tháng bàn giao. Đi kèm chứng chỉ tư vấn quy trình do CIC cấp.',
    thumbnail_url: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=500&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b7?w=1200&auto=format&fit=crop&q=80',
    video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    media_alt: 'Hình ảnh tư vấn mô hình BIM ISO 19650 tại CIC Technology',
    cta_label: 'Đăng ký Tư vấn 1:1',
    cta_link: '/lien-he?service=DV-BIM-01',
    owner_id: 'usr_002',
    owner_name: 'Trần Văn Mạnh',
    owner_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    owner_email: 'manh.tv@cic.com.vn',
    request_routing: 'Bộ phận Tư vấn BIM (bim_consulting@cic.com.vn)',
    meta_title: 'Tư vấn Lộ trình Chuyển đổi số BIM ISO 19650 | CIC Technology',
    meta_description: 'Dịch vụ tư vấn chuyển đổi số BIM ISO 19650 hàng đầu Việt Nam của CIC. Hỗ trợ chuẩn hóa CDE, EIR, BEP cho hạ tầng & dân dụng.',
    meta_keywords: 'BIM, ISO 19650, CDE, Tư vấn BIM, ACC, Revit, CIC',
    og_image: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&auto=format&fit=crop&q=80',
    quality_score: 95,
    editorial_status: 'published',
    service_status: 'active',
    locales: { vi: 'complete', en: 'complete', ja: 'outdated' },
    site: 'cic.com.vn',
    placement: ['home_featured', 'services_page'],
    display_order: 1,
    publish_at: '2026-01-15 08:00:00',
    created_at: '2026-01-10 09:30:00',
    updated_at: '2026-07-28 14:20:00',
    updated_by: 'Trần Văn Mạnh',
    version_count: 4,
    working_version_exists: false,
    used_by_count: 5,
    open_contacts_count: 3,
  },
  {
    id: 'srv_102',
    code: 'DV-KS-02',
    title: 'Khảo sát Quét Mây Điểm 3D Laser Scanning & Dựng Mô hình As-Built',
    slug: 'khao-sat-quet-may-diem-3d-laser-scanning',
    summary: 'Sử dụng máy quét Laser 3D độ chính xác cao thu thập dữ liệu Point Cloud công trình hiện hữu, phục vụ công tác số hóa, cải tạo di tích và dựng mô hình hoàn công As-Built.',
    group_id: 'grp_02',
    group_name: 'Khảo sát & Thử nghiệm Công trình',
    scope: 'Toàn quốc',
    business_relation: 'Dịch vụ kỹ thuật chuyên sâu',
    description: `<p>Trang thiết bị 3D Laser Scanner hiện đại cho phép chụp lại hình học toàn bộ công trình với sai số dưới 1mm. Dữ liệu Point Cloud thu được xử lý trên phần mềm Leica Cyclone và Autodesk Recap trước khi đưa vào Revit/ArchiCAD để dựng bản vẽ hoàn công.</p>`,
    benefits_process: 'Độ chính xác milimet, không phá hủy kết cấu, thu thập dữ liệu nhanh gấp 10 lần phương pháp đo đạc truyền thống.',
    supplementary_content: 'Xuất file định dạng .RCP, .E57, .PTS và mô hình .RVT chuẩn LOD 300 - 400.',
    thumbnail_url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=500&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=1200&auto=format&fit=crop&q=80',
    media_alt: 'Quét 3D Laser Scanning công trình thực tế',
    cta_label: 'Yêu cầu Báo giá Khảo sát',
    cta_link: '/lien-he?service=DV-KS-02',
    owner_id: 'usr_003',
    owner_name: 'Nguyễn Thị Bích',
    owner_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    owner_email: 'bich.nt@cic.com.vn',
    request_routing: 'Phòng Đo đạc & Khảo sát (survey@cic.com.vn)',
    meta_title: 'Dịch vụ Quét 3D Laser Scanning & Dựng As-Built | CIC',
    meta_description: 'Số hóa công trình bằng công nghệ 3D Laser Scanning Point Cloud chính xác cao. Dựng mô hình Revit As-Built chuyên nghiệp.',
    meta_keywords: '3D Laser Scanning, Point Cloud, As-Built, Scan to BIM, CIC',
    og_image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
    quality_score: 88,
    editorial_status: 'published',
    service_status: 'active',
    locales: { vi: 'complete', en: 'complete' },
    site: 'cic.com.vn',
    placement: ['services_page'],
    display_order: 2,
    publish_at: '2026-02-01 10:00:00',
    created_at: '2026-01-20 11:15:00',
    updated_at: '2026-07-25 09:10:00',
    updated_by: 'Nguyễn Thị Bích',
    version_count: 2,
    working_version_exists: false,
    used_by_count: 3,
    open_contacts_count: 2,
  },
  {
    id: 'srv_103',
    code: 'DV-DT-03',
    title: 'Khóa Đào tạo Chuyên sâu Phần mềm Tính toán Kết cấu CSI SAP2000 & ETABS',
    slug: 'khoa-dao-tao-phan-mem-ket-cau-csi-etabs-sap2000',
    summary: 'Chương trình đào tạo chính hãng từ nhà phân phối ủy quyền CSI Việt Nam. Cấp chứng chỉ hoàn thành khóa học từ hãng Computers and Structures, Inc. (USA).',
    group_id: 'grp_03',
    group_name: 'Đào tạo & Cấp chứng chỉ Chuyên môn',
    scope: 'Trực tiếp & Online',
    business_relation: 'Gói đi kèm phần mềm bản quyền',
    description: `<p>Khóa học trang bị cho kỹ sư kết cấu kỹ năng dựng mô hình nhà cao tầng, phân tích tải trọng động đất theo TCVN 9386:2012 / Eurocode, phân tích phi tuyến P-Delta và thiết kế cốt thép tự động.</p>`,
    benefits_process: 'Học viên thực hành trực tiếp trên dự án thực tế, được chuyên gia CIC hướng dẫn trực tiếp và nhận License sử dụng trong 3 tháng.',
    supplementary_content: 'Lịch học linh hoạt ca tối hoặc cuối tuần. Hỗ trợ giải đáp thắc mắc trọn đời sau khóa học.',
    thumbnail_url: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=500&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=1200&auto=format&fit=crop&q=80',
    media_alt: 'Lớp đào tạo ETABS v21 chính hãng tại trung tâm CIC',
    cta_label: 'Đăng ký Lớp học Ngay',
    cta_link: '/dao-tao/etabs-sap2000',
    owner_id: 'usr_004',
    owner_name: 'Vũ Quốc Huy',
    owner_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    owner_email: 'huy.vq@cic.com.vn',
    request_routing: 'Trung tâm Đào tạo Kỹ thuật CIC (training@cic.com.vn)',
    meta_title: 'Đào tạo Phần mềm Kết cấu ETABS & SAP2000 Chính hãng | CIC',
    meta_description: 'Khóa học ETABS, SAP2000 chính hãng do CIC chứng nhận. Cấp chứng chỉ quốc tế CSI USA cho kỹ sư kết cấu.',
    meta_keywords: 'Đào tạo ETABS, SAP2000, CSI Training, Chứng chỉ CSI, CIC',
    og_image: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800&auto=format&fit=crop&q=80',
    quality_score: 92,
    editorial_status: 'published',
    service_status: 'active',
    locales: { vi: 'complete', en: 'outdated' },
    site: 'cic.com.vn',
    placement: ['home_featured', 'services_page'],
    display_order: 3,
    publish_at: '2026-03-01 08:30:00',
    created_at: '2026-02-15 14:00:00',
    updated_at: '2026-07-30 16:45:00',
    updated_by: 'Vũ Quốc Huy',
    version_count: 5,
    working_version_exists: true,
    used_by_count: 7,
    open_contacts_count: 5,
  },
  {
    id: 'srv_104',
    code: 'DV-BT-04',
    title: 'Dịch vụ Bảo trì & Quản lý License Mạng Phần mềm CAD/BIM Tập trung',
    slug: 'bao-tri-quan-ly-license-mang-cad-bim',
    summary: 'Giải pháp cấu hình server License FlexLM/NLS, theo dõi thời gian thực suất dùng phần mềm EnjiCAD, Revit, PLAXIS và tối ưu hóa chi phí bản quyền doanh nghiệp.',
    group_id: 'grp_04',
    group_name: 'Bảo trì & Tối ưu hóa Phần mềm Bản quyền',
    scope: 'Toàn quốc',
    business_relation: 'Dịch vụ gia hạn định kỳ hàng năm',
    description: `<p>Đảm bảo hệ thống bản quyền phần mềm hoạt động thông suốt không gián đoạn. Hỗ trợ khắc phục lỗi khóa cứng USB, cài đặt máy chủ License Server và xử lý xung đột mạng LAN/WAN.</p>`,
    benefits_process: 'Cam kết SLA khắc phục sự cố trong 2 giờ làm việc, báo cáo thống kê hiệu suất sử dụng license hàng tháng.',
    supplementary_content: 'Bao gồm cập nhật miễn phí các bản patch vá lỗi hotfix từ nhà sản xuất.',
    thumbnail_url: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=500&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=1200&auto=format&fit=crop&q=80',
    media_alt: 'Bảo trì server license phần mềm tại doanh nghiệp',
    cta_label: 'Liên hệ Gói Bảo trì',
    cta_link: '/lien-he?service=DV-BT-04',
    owner_id: 'usr_002',
    owner_name: 'Trần Văn Mạnh',
    owner_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    owner_email: 'manh.tv@cic.com.vn',
    request_routing: 'Bộ phận Hỗ trợ Kỹ thuật & License (support@cic.com.vn)',
    meta_title: 'Quản lý & Bảo trì License Mạng Phần mềm Bản quyền | CIC',
    meta_description: 'Dịch vụ bảo trì và tối ưu license FlexLM, NLS cho doanh nghiệp dùng EnjiCAD, Autodesk, CSI, Bentley Systems.',
    meta_keywords: 'Bảo trì License, FlexLM, Network License, Cài đặt phần mềm, CIC',
    og_image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=80',
    quality_score: 82,
    editorial_status: 'approved',
    service_status: 'active',
    locales: { vi: 'complete', en: 'missing' },
    site: 'cic.com.vn',
    placement: ['services_page'],
    display_order: 4,
    created_at: '2026-03-20 10:20:00',
    updated_at: '2026-07-29 11:00:00',
    updated_by: 'Trần Văn Mạnh',
    version_count: 3,
    working_version_exists: false,
    used_by_count: 2,
    open_contacts_count: 1,
  },
  {
    id: 'srv_105',
    code: 'DV-KS-05',
    title: 'Kiểm định Chất lượng Công trình & Mô phỏng Tương tác Đất - Kết cấu Geotechnical',
    slug: 'kiem-dinh-chat-luong-cong-trinh-geotechnical',
    summary: 'Đánh giá an toàn chịu lực tòa nhà, kiểm định sự cố nứt gãy và phân tích địa kỹ thuật phức tạp bằng phần mềm PLAXIS 2D/3D & GeoStudio.',
    group_id: 'grp_02',
    group_name: 'Khảo sát & Thử nghiệm Công trình',
    scope: 'Miền Bắc & Miền Trung',
    business_relation: 'Dịch vụ dự án',
    description: `<p>CIC sở hữu đội ngũ chuyên gia hàng đầu về địa kỹ thuật và thí nghiệm vật liệu. Chúng tôi cung cấp báo cáo đánh giá biến dạng hố đào sâu, ổn định mái dốc và nguy cơ trượt lở đất cho các công trình hạ tầng giao thông.</p>`,
    benefits_process: 'Cung cấp báo cáo tính toán đối chứng đạt tiêu chuẩn nghiệm thu của Bộ Xây dựng.',
    supplementary_content: 'Hồ sơ năng lực kiểm định xây dựng hạng 1 do Sở Xây Dựng Hà Nội cấp.',
    thumbnail_url: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b7?w=500&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1200&auto=format&fit=crop&q=80',
    media_alt: 'Kiểm định kết cấu và tính toán địa kỹ thuật PLAXIS 3D',
    cta_label: 'Gửi Yêu cầu Kiểm định',
    cta_link: '/lien-he?service=DV-KS-05',
    owner_id: 'usr_003',
    owner_name: 'Nguyễn Thị Bích',
    owner_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    owner_email: 'bich.nt@cic.com.vn',
    request_routing: 'Phòng Thử nghiệm & Kiểm định (testing@cic.com.vn)',
    meta_title: 'Kiểm định Kết cấu & Mô phỏng Địa kỹ thuật PLAXIS | CIC',
    meta_description: 'Kiểm định an toàn công trình, phân tích ổn định hố đào sâu PLAXIS 3D. Đội ngũ kỹ sư cấp 1 uy tín.',
    meta_keywords: 'Kiểm định công trình, PLAXIS 3D, 地质, GeoStudio, CIC',
    og_image: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b7?w=800&auto=format&fit=crop&q=80',
    quality_score: 76,
    editorial_status: 'pending',
    service_status: 'active',
    locales: { vi: 'complete', en: 'missing' },
    site: 'cic.com.vn',
    placement: ['services_page'],
    display_order: 5,
    created_at: '2026-04-10 16:00:00',
    updated_at: '2026-07-31 08:00:00',
    updated_by: 'Nguyễn Thị Bích',
    version_count: 2,
    working_version_exists: true,
    used_by_count: 1,
    open_contacts_count: 4,
  },
  {
    id: 'srv_106',
    code: 'DV-DT-06',
    title: 'Đào tạo Lập Dự toán & Quản lý Chi phí Xây dựng với Phần mềm ESCON 2026',
    slug: 'dao-tao-du-toan-quan-ly-chi-phi-escon-2026',
    summary: 'Huấn luyện kỹ năng tra cứu đơn giá, định mức mới theo Thông tư Bộ Xây dựng, lập dự toán chi phí đầu tư và quyết toán công trình trên phần mềm ESCON.',
    group_id: 'grp_03',
    group_name: 'Đào tạo & Cấp chứng chỉ Chuyên môn',
    scope: 'Toàn quốc',
    business_relation: 'Đào tạo ứng dụng',
    description: `<p>Khóa học dành cho kỹ sư QS, cán bộ phòng Kế hoạch - Bán hàng và Ban quản lý dự án. Học viên được cập nhật bộ định mức định kỳ mới nhất và phương pháp xác định giá ca máy, định mức nhân công.</p>`,
    benefits_process: 'Cấp chứng nhận hoàn thành khóa dự toán ESCON có giá trị tuyển dụng toàn quốc.',
    supplementary_content: 'Tặng kèm bộ tài nguyên định mức 63 tỉnh thành năm 2026.',
    thumbnail_url: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=500&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&auto=format&fit=crop&q=80',
    media_alt: 'Đào tạo phần mềm dự toán ESCON tại văn phòng CIC',
    cta_label: 'Đăng ký Khóa Dự toán',
    cta_link: '/dao-tao/escon',
    owner_id: 'usr_004',
    owner_name: 'Vũ Quốc Huy',
    owner_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    owner_email: 'huy.vq@cic.com.vn',
    request_routing: 'Trung tâm Đào tạo Kỹ thuật CIC (training@cic.com.vn)',
    meta_title: 'Đào tạo Lập Dự toán Xây dựng ESCON 2026 | CIC',
    meta_description: 'Khóa học lập dự toán công trình xây dựng bằng phần mềm ESCON. Cập nhật định mức Thông tư Bộ Xây dựng mới nhất.',
    meta_keywords: 'Đào tạo dự toán, ESCON, Định mức xây dựng, QS, CIC',
    og_image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&auto=format&fit=crop&q=80',
    quality_score: 90,
    editorial_status: 'published',
    service_status: 'active',
    locales: { vi: 'complete', en: 'outdated' },
    site: 'cic.com.vn',
    placement: ['services_page'],
    display_order: 6,
    publish_at: '2026-05-01 09:00:00',
    created_at: '2026-04-20 13:45:00',
    updated_at: '2026-07-20 10:15:00',
    updated_by: 'Vũ Quốc Huy',
    version_count: 3,
    working_version_exists: false,
    used_by_count: 4,
    open_contacts_count: 2,
  },
  {
    id: 'srv_107',
    code: 'DV-BIM-07',
    title: 'Dịch vụ Dựng & Kiểm tra Xung đột Mô hình BIM 3D/4D/5D (Clash Detection)',
    slug: 'dich-vu-dung-kiem-tra-xung-dot-mo-hinh-bim-3d-4d-5d',
    summary: 'Phát hiện sớm hàng ngàn điểm va chạm giữa hệ thống ME, Kết cấu và Kiến trúc bằng phần mềm Autodesk Navisworks Manage trước khi thi công ngoài hiện trường.',
    group_id: 'grp_01',
    group_name: 'Tư vấn & Chuyển giao BIM',
    scope: 'Toàn quốc',
    business_relation: 'Dịch vụ Outsource Kỹ thuật',
    description: `<p>CIC nhậnOutsource dựng mô hình BIM Kiến trúc, Kết cấu, MEP từ bản vẽ 2D AutoCAD. Sử dụng Navisworks Manage và Solibri Model Checker để lập báo cáo Clash Matrix chi tiết kèm tọa độ không gian.</p>`,
    benefits_process: 'Tránh lãng phí vật tư tháo dỡ lại trên công trường, lập mô phỏng tiến độ thi công 4D sinh động.',
    supplementary_content: 'Cam kết bảo mật 100% bản quyền thiết kế dự án theo hợp đồng NDA.',
    thumbnail_url: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=500&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=1200&auto=format&fit=crop&q=80',
    media_alt: 'Kiểm tra xung đột mô hình BIM trên Navisworks',
    cta_label: 'Gửi Hồ sơ Dự án Báo giá',
    cta_link: '/lien-he?service=DV-BIM-07',
    owner_id: 'usr_002',
    owner_name: 'Trần Văn Mạnh',
    owner_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    owner_email: 'manh.tv@cic.com.vn',
    request_routing: 'Bộ phận Outsource BIM (bim_outsource@cic.com.vn)',
    meta_title: 'Dịch vụ Dựng Mô hình BIM & Kiểm tra Xung đột Clash Detection | CIC',
    meta_description: 'Kiểm tra va chạm mô hình BIM 3D MEP, Kiến trúc, Kết cấu bằng Navisworks. Rút ngắn thời gian thi công dự án.',
    meta_keywords: 'BIM Outsource, Clash Detection, Navisworks, 4D BIM, CIC',
    og_image: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&auto=format&fit=crop&q=80',
    quality_score: 85,
    editorial_status: 'draft',
    service_status: 'inactive',
    locales: { vi: 'complete', en: 'missing' },
    site: 'cic.com.vn',
    placement: [],
    display_order: 7,
    created_at: '2026-06-01 14:00:00',
    updated_at: '2026-07-15 11:20:00',
    updated_by: 'Trần Văn Mạnh',
    version_count: 1,
    working_version_exists: false,
    used_by_count: 0,
    open_contacts_count: 0,
  },
  {
    id: 'srv_108',
    code: 'DV-BT-08',
    title: 'Chuyển đổi & Chuẩn hóa Hệ thống Bản vẽ CAD sang EnjiCAD Doanh nghiệp',
    slug: 'chuyen-doi-chuan-hoa-ban-ve-cad-sang-enjicad',
    summary: 'Dịch vụ chuyển đổi hàng loạt tập tin .DWG, lisp lệnh và template bản vẽ công ty sang phần mềm thay thế EnjiCAD tiết kiệm 70% chi phí bản quyền.',
    group_id: 'grp_04',
    group_name: 'Bảo trì & Tối ưu hóa Phần mềm Bản quyền',
    scope: 'Doanh nghiệp & Tập đoàn',
    business_relation: 'Dịch vụ chuyển đổi công nghệ',
    description: `<p>Hỗ trợ các doanh nghiệp tư vấn thiết kế chuyển đổi mượt mà từ AutoCAD sang EnjiCAD. Viết lại các LISP lệnh đặc thù, chuyển đổi font chữ VNI/TCVN3 sang Unicode và tối ưu hóa hệ thống máy in plot style.</p>`,
    benefits_process: 'Đảm bảo 100% bản vẽ tương thích hoàn hảo, không lặp lại lỗi font chữ hay vỡ nét in.',
    supplementary_content: 'Miễn phí trải nghiệm thử nghiệm 30 ngày cho toàn bộ phòng thiết kế.',
    thumbnail_url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=500&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=1200&auto=format&fit=crop&q=80',
    media_alt: 'Chuyển đổi bản vẽ CAD sang EnjiCAD Enterprise',
    cta_label: 'Đăng ký Chuyển đổi EnjiCAD',
    cta_link: '/enjicad-migration',
    owner_id: 'usr_002',
    owner_name: 'Trần Văn Mạnh',
    owner_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    owner_email: 'manh.tv@cic.com.vn',
    request_routing: 'Bộ phận Giải pháp CAD (enjicad@cic.com.vn)',
    meta_title: 'Chuyển đổi Bản vẽ CAD sang EnjiCAD Tiết kiệm Chi phí | CIC',
    meta_description: 'Chuyển đổi hệ thống DWG, LISP, Template bản vẽ sang EnjiCAD. Tương thích 100% AutoCAD, tiết kiệm 70% bản quyền.',
    meta_keywords: 'EnjiCAD, DWG Migration, CAD License, AutoCAD thay thế, CIC',
    og_image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
    quality_score: 65, // Low quality score example
    editorial_status: 'draft',
    service_status: 'inactive',
    locales: { vi: 'complete', en: 'missing' },
    site: 'cic.com.vn',
    placement: [],
    display_order: 8,
    created_at: '2026-06-15 09:30:00',
    updated_at: '2026-07-20 15:10:00',
    updated_by: 'Trần Văn Mạnh',
    version_count: 1,
    working_version_exists: false,
    quality_warning: 'Nội dung mô tả chi tiết dưới 300 từ. Cần bổ sung thêm thông tin SEO Meta Keywords.',
    used_by_count: 0,
    open_contacts_count: 0,
  },
  {
    id: 'srv_109',
    code: 'DV-DT-09',
    title: 'Đào tạo & Hướng dẫn Đo bóc Khối lượng Mô hình BIM (5D BIM Quantity Takeoff)',
    slug: 'dao-tao-do-boc-khoi-luong-mo-hinh-bim-5d',
    summary: 'Chương trình đào tạo kỹ năng trích xuất tự động khối lượng bê tông, cốt thép, MEP từ mô hình Revit/Navisworks liên kết dữ liệu trực tiếp sang bảng dự toán.',
    group_id: 'grp_03',
    group_name: 'Đào tạo & Cấp chứng chỉ Chuyên môn',
    scope: 'Trực tuyến toàn quốc',
    business_relation: 'Khóa học chuyên đề',
    description: `<p>Khóa học giúp rút ngắn 80% thời gian đo bóc khối lượng công trình thủ công. Học viên nắm vững kỹ thuật đặt mã Schedule trong Revit, ánh xạ mã hiệu định mức và xuất báo cáo Excel chuẩn hóa.</p>`,
    benefits_process: 'Tránh bỏ sót khối lượng cốt thép, chính xác từng cấu kiện hình học phức tạp.',
    supplementary_content: 'Hỗ trợ video quay lại buổi học trọn đời.',
    thumbnail_url: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=500&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&auto=format&fit=crop&q=80',
    media_alt: 'Trích xuất khối lượng 5D BIM trên phần mềm',
    cta_label: 'Đăng ký Lớp 5D BIM',
    cta_link: '/dao-tao/5d-bim',
    owner_id: 'usr_004',
    owner_name: 'Vũ Quốc Huy',
    owner_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    owner_email: 'huy.vq@cic.com.vn',
    request_routing: 'Trung tâm Đào tạo Kỹ thuật CIC (training@cic.com.vn)',
    meta_title: 'Đào tạo Đo bóc Khối lượng 5D BIM Revit & Navisworks | CIC',
    meta_description: 'Trích xuất khối lượng dự toán tự động từ mô hình BIM 3D. Khóa học chuyên sâu cho QS và BIM Manager.',
    meta_keywords: '5D BIM, Quantity Takeoff, Revit Schedule, QTO, CIC',
    og_image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&auto=format&fit=crop&q=80',
    quality_score: 94,
    editorial_status: 'published',
    service_status: 'archived',
    locales: { vi: 'complete', en: 'complete' },
    site: 'cic.com.vn',
    placement: [],
    display_order: 9,
    publish_at: '2025-11-01 08:00:00',
    created_at: '2025-10-15 10:00:00',
    updated_at: '2026-05-10 14:00:00',
    updated_by: 'Vũ Quốc Huy',
    version_count: 6,
    working_version_exists: false,
    used_by_count: 2,
    open_contacts_count: 0,
  }
];

export const mockServiceActivityLogs: ServiceActivityLog[] = [
  {
    id: 'act_01',
    service_id: 'srv_101',
    user_name: 'Trần Văn Mạnh',
    user_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    action_type: 'publish',
    description: 'Đã xuất bản phiên bản v1.4 dịch vụ "Tư vấn Lộ trình Chuyển đổi số BIM ISO 19650"',
    created_at: '2026-07-28 14:20:00',
  },
  {
    id: 'act_02',
    service_id: 'srv_101',
    user_name: 'Nguyễn Văn Quản Trị',
    user_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    action_type: 'activate',
    description: 'Đã kích hoạt trạng thái Service Status "Active" trên toàn hệ thống website',
    created_at: '2026-07-28 14:22:15',
  },
  {
    id: 'act_03',
    service_id: 'srv_103',
    user_name: 'Vũ Quốc Huy',
    user_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    action_type: 'update',
    description: 'Tạo bản thảo làm việc (Working Draft v2.1) bổ sung khung thời gian khai giảng lớp học mới',
    created_at: '2026-07-30 16:45:00',
  },
  {
    id: 'act_04',
    service_id: 'srv_105',
    user_name: 'Nguyễn Thị Bích',
    user_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    action_type: 'submit',
    description: 'Gửi yêu cầu phê duyệt nội dung bài viết dịch vụ Kiểm định địa kỹ thuật PLAXIS',
    created_at: '2026-07-31 08:00:00',
  },
];

export const mockServiceVersions: ServiceVersion[] = [
  {
    id: 'ver_101_4',
    service_id: 'srv_101',
    version_number: 4,
    title: 'Tư vấn Lộ trình Chuyển đổi số BIM ISO 19650 cho Doanh nghiệp Xây dựng',
    editorial_status: 'published',
    service_status: 'active',
    updated_by: 'Trần Văn Mạnh',
    updated_at: '2026-07-28 14:20:00',
    change_log: 'Cập nhật tiêu chuẩn ISO 19650:2026 và bổ sung quy trình tích hợp ACC',
    is_published_version: true,
  },
  {
    id: 'ver_101_3',
    service_id: 'srv_101',
    version_number: 3,
    title: 'Tư vấn Lộ trình Chuyển đổi số BIM ISO 19650 cho Doanh nghiệp',
    editorial_status: 'published',
    service_status: 'active',
    updated_by: 'Trần Văn Mạnh',
    updated_at: '2026-04-12 10:15:00',
    change_log: 'Bổ sung thông tin chứng chỉ hoàn thành quy trình do CIC cấp',
    is_published_version: false,
  },
  {
    id: 'ver_101_2',
    service_id: 'srv_101',
    version_number: 2,
    title: 'Tư vấn Chuyển đổi số BIM cho Chủ đầu tư',
    editorial_status: 'published',
    service_status: 'active',
    updated_by: 'Trần Văn Mạnh',
    updated_at: '2026-02-01 09:00:00',
    change_log: 'Sửa đổi cấu trúc các giai đoạn triển khai CDE',
    is_published_version: false,
  },
];

export const mockServiceUsedByReferences: ServiceUsedByReference[] = [
  {
    id: 'ref_01',
    service_id: 'srv_101',
    source_type: 'menu',
    source_title: 'Menu chính > Dịch vụ > Tư vấn BIM ISO 19650',
    source_url: '/dich-vu/tu-van-bim',
    status: 'active',
  },
  {
    id: 'ref_02',
    service_id: 'srv_101',
    source_type: 'home_block',
    source_title: 'Khối Trang chủ > Top Dịch vụ Nổi bật CIC',
    source_url: '/',
    status: 'active',
  },
  {
    id: 'ref_03',
    service_id: 'srv_101',
    source_type: 'landing_page',
    source_title: 'Landing Page Giải pháp BIM Cho Tập đoàn',
    source_url: '/giai-phap-bim-enterprise',
    status: 'active',
  },
  {
    id: 'ref_04',
    service_id: 'srv_103',
    source_type: 'menu',
    source_title: 'Menu chính > Đào tạo > Khóa học ETABS & SAP2000',
    source_url: '/dao-tao/etabs-sap2000',
    status: 'active',
  },
];

export const mockServiceRelatedContacts: ServiceRelatedContact[] = [
  {
    id: 'cnt_01',
    service_id: 'srv_101',
    customer_name: 'Nguyễn Tiến Dũng',
    customer_email: 'dung.nt@coteccons.vn',
    customer_phone: '0908 123 456',
    company_name: 'Coteccons Corp',
    subject: 'Đăng ký tư vấn chuyển đổi số BIM ISO 19650 cho khối dự án cao ốc',
    status: 'unread',
    created_at: '2026-07-31 08:30:00',
  },
  {
    id: 'cnt_02',
    service_id: 'srv_101',
    customer_name: 'Phạm Minh Châu',
    customer_email: 'chau.pm@fecon.com.vn',
    customer_phone: '0912 888 999',
    company_name: 'Fecon Infrastructure',
    subject: 'Hỏi về chi phí tư vấn quy trình CDE và đào tạo BIM Coordinator',
    status: 'processing',
    created_at: '2026-07-30 15:40:00',
  },
  {
    id: 'cnt_03',
    service_id: 'srv_103',
    customer_name: 'Lê Hoàng Nam',
    customer_email: 'nam.lh@vinaconex.vn',
    customer_phone: '0983 555 777',
    company_name: 'Vinaconex 1',
    subject: 'Đăng ký 5 suất lớp đào tạo ETABS v21 nâng cao ca tối',
    status: 'unread',
    created_at: '2026-07-31 09:15:00',
  },
];
