import { StaffUser, TranslationItem } from './types';

export const MOCK_LOCALIZATION_STAFF: StaffUser[] = [
  {
    id: 'usr_trans_1',
    name: 'Đặng Mai Chi',
    role: 'translator',
    email: 'mai.chi@cic.com.vn',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr_trans_2',
    name: 'Lê Hoàng Long',
    role: 'translator',
    email: 'hoang.long@cic.com.vn',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr_rev_1',
    name: 'Phạm Vũ Bảo Châu',
    role: 'reviewer',
    email: 'bao.chau@cic.com.vn',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr_mgr_1',
    name: 'Trần Văn Hùng',
    role: 'manager',
    email: 'hung.tran@cic.com.vn',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr_admin',
    name: 'Super Admin CIC',
    role: 'admin',
    email: 'admin@cic.com.vn',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80',
  },
];

export const CURRENT_LOCALIZATION_USER_ID = 'usr_trans_1'; // Đặng Mai Chi (Translator)

// Generate rich mock items reflecting 79 frontend strings, 90 backend strings (44 missing EN), and content items
export const INITIAL_TRANSLATION_ITEMS: TranslationItem[] = [
  // ==========================================
  // 1. FRONTEND UI STRINGS (79 items total representation)
  // ==========================================
  {
    id: 'str_fe_001',
    key: 'frontend.header.nav_products',
    item_type: 'ui_string',
    scope: 'frontend',
    module_name: 'Header & Navigation',
    source_text: 'Sản phẩm & Giải pháp Phần mềm CAD/BIM',
    target_text: 'CAD/BIM Software Products & Solutions',
    source_locale: 'vi',
    target_locale: 'en',
    status: 'complete',
    assignee_id: 'usr_trans_1',
    assignee_name: 'Đặng Mai Chi',
    assignee_avatar: MOCK_LOCALIZATION_STAFF[0].avatar,
    reviewer_id: 'usr_rev_1',
    reviewer_name: 'Phạm Vũ Bảo Châu',
    reviewer_avatar: MOCK_LOCALIZATION_STAFF[2].avatar,
    updated_at: '2026-08-01 10:30',
    source_updated_at: '2026-07-25 09:00',
    context_description: 'Menu chính hiển thị trên thanh điều hướng topbar của website.',
    screen_usage: 'Website Header Dropdown Menu',
    screenshot_url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&auto=format&fit=crop&q=80',
    placeholders: [],
    comments: [],
    history: [
      { id: 'h1', timestamp: '2026-08-01 10:30', actor_name: 'Phạm Vũ Bảo Châu', event_type: 'completed', description: 'Đã duyệt bản dịch hoàn tất' }
    ]
  },
  {
    id: 'str_fe_002',
    key: 'frontend.cart.item_count_summary',
    item_type: 'ui_string',
    scope: 'frontend',
    module_name: 'Checkout & Cart',
    source_text: 'Bạn đang có {count} sản phẩm phần mềm bản quyền trong giỏ hàng',
    target_text: 'You have {count} licensed software items in your cart',
    source_locale: 'vi',
    target_locale: 'en',
    status: 'complete',
    assignee_id: 'usr_trans_1',
    assignee_name: 'Đặng Mai Chi',
    assignee_avatar: MOCK_LOCALIZATION_STAFF[0].avatar,
    reviewer_id: 'usr_rev_1',
    reviewer_name: 'Phạm Vũ Bảo Châu',
    reviewer_avatar: MOCK_LOCALIZATION_STAFF[2].avatar,
    updated_at: '2026-08-02 14:15',
    source_updated_at: '2026-07-20 11:00',
    context_description: 'Thông báo số lượng sản phẩm ở trang thanh toán.',
    screen_usage: 'Cart Summary Banner',
    placeholders: ['{count}'],
    comments: [],
    history: []
  },
  {
    id: 'str_fe_003',
    key: 'frontend.product.license_type_network',
    item_type: 'ui_string',
    scope: 'frontend',
    module_name: 'Sản phẩm & Giá',
    source_text: 'Giấy phép bản quyền mạng (Network License) cho {max_users} người dùng đồng thời',
    target_text: 'Network Concurrent License for {max_users} simultaneous users',
    source_locale: 'vi',
    target_locale: 'en',
    status: 'in_progress',
    assignee_id: 'usr_trans_1',
    assignee_name: 'Đặng Mai Chi',
    assignee_avatar: MOCK_LOCALIZATION_STAFF[0].avatar,
    reviewer_id: 'usr_rev_1',
    reviewer_name: 'Phạm Vũ Bảo Châu',
    reviewer_avatar: MOCK_LOCALIZATION_STAFF[2].avatar,
    due_date: '2026-08-06',
    updated_at: '2026-08-03 16:40',
    source_updated_at: '2026-07-30 08:30',
    context_description: 'Mô tả loại license trên trang chi tiết sản phẩm EnjiCAD / ETABS.',
    screen_usage: 'Product Specification Table',
    placeholders: ['{max_users}'],
    comments: [
      {
        id: 'c1',
        author_id: 'usr_trans_1',
        author_name: 'Đặng Mai Chi',
        author_avatar: MOCK_LOCALIZATION_STAFF[0].avatar,
        content: 'Nên dùng cụm "Network Concurrent License" hay "Floating License"?',
        created_at: '2026-08-03 16:42',
        type: 'general'
      }
    ],
    history: []
  },
  {
    id: 'str_fe_004',
    key: 'frontend.search.placeholder_filter',
    item_type: 'ui_string',
    scope: 'frontend',
    module_name: 'Tìm kiếm & Bộ lọc',
    source_text: 'Tìm kiếm theo tên phần mềm, hãng sản xuất (CSI, Bentley, Autodesk)...',
    previous_source_text: 'Tìm kiếm phần mềm theo tên...',
    target_text: 'Search by software name, vendor (CSI, Bentley, Autodesk)...',
    source_locale: 'vi',
    target_locale: 'en',
    status: 'outdated',
    assignee_id: 'usr_trans_1',
    assignee_name: 'Đặng Mai Chi',
    assignee_avatar: MOCK_LOCALIZATION_STAFF[0].avatar,
    reviewer_id: 'usr_rev_1',
    reviewer_name: 'Phạm Vũ Bảo Châu',
    reviewer_avatar: MOCK_LOCALIZATION_STAFF[2].avatar,
    updated_at: '2026-08-03 09:10',
    source_updated_at: '2026-08-03 09:00',
    context_description: 'Nguồn vừa cập nhật thêm danh sách hãng sản xuất (CSI, Bentley, Autodesk). Cần kiểm tra lại bản dịch tiếng Anh.',
    screen_usage: 'Global Search Bar',
    placeholders: [],
    comments: [],
    history: [
      {
        id: 'h_out1',
        timestamp: '2026-08-03 09:00',
        actor_name: 'Trần Văn Hùng',
        event_type: 'source_updated',
        description: 'Nguồn tiếng Việt thay đổi, đánh dấu bản dịch lỗi thời (Outdated)',
        old_value: 'Tìm kiếm phần mềm theo tên...',
        new_value: 'Tìm kiếm theo tên phần mềm, hãng sản xuất (CSI, Bentley, Autodesk)...'
      }
    ]
  },
  {
    id: 'str_fe_005',
    key: 'frontend.contact.success_dialog_title',
    item_type: 'ui_string',
    scope: 'frontend',
    module_name: 'Form liên hệ',
    source_text: 'Cảm ơn ông/bà {contact_name}! Yêu cầu báo giá đã được chuyển tới chuyên viên tư vấn.',
    target_text: 'Thank you {contact_name}! Your quote request has been forwarded to our technical specialist.',
    source_locale: 'vi',
    target_locale: 'en',
    status: 'review',
    assignee_id: 'usr_trans_2',
    assignee_name: 'Lê Hoàng Long',
    assignee_avatar: MOCK_LOCALIZATION_STAFF[1].avatar,
    reviewer_id: 'usr_rev_1',
    reviewer_name: 'Phạm Vũ Bảo Châu',
    reviewer_avatar: MOCK_LOCALIZATION_STAFF[2].avatar,
    due_date: '2026-08-05',
    updated_at: '2026-08-03 11:20',
    source_updated_at: '2026-07-28 14:00',
    context_description: 'Pop-up xác nhận gửi liên hệ thành công.',
    screen_usage: 'Contact Form Success Modal',
    placeholders: ['{contact_name}'],
    comments: [],
    history: [
      { id: 'h_sub1', timestamp: '2026-08-03 11:20', actor_name: 'Lê Hoàng Long', event_type: 'submitted_review', description: 'Đã gửi duyệt bản dịch' }
    ]
  },

  // ==========================================
  // 2. BACKEND API & SYSTEM STRINGS (90 items total representation with 44 MISSING EN)
  // ==========================================
  // Sample Missing EN Backend Strings (Representing the 44 missing strings in total)
  {
    id: 'str_be_001',
    key: 'backend.err.license_key_expired',
    item_type: 'ui_string',
    scope: 'backend',
    module_name: 'Authentication & Licensing API',
    source_text: 'Khóa kích hoạt phần mềm đã hết hạn sử dụng. Vui lòng liên hệ trung tâm CIC để gia hạn.',
    target_text: '', // MISSING EN
    source_locale: 'vi',
    target_locale: 'en',
    status: 'missing',
    assignee_id: 'usr_trans_1',
    assignee_name: 'Đặng Mai Chi',
    assignee_avatar: MOCK_LOCALIZATION_STAFF[0].avatar,
    reviewer_id: 'usr_rev_1',
    reviewer_name: 'Phạm Vũ Bảo Châu',
    reviewer_avatar: MOCK_LOCALIZATION_STAFF[2].avatar,
    due_date: '2026-08-07',
    updated_at: '2026-07-28 10:00',
    source_updated_at: '2026-07-28 10:00',
    context_description: 'Mã lỗi 403 API trả về khi license của khách hàng quá hạn.',
    screen_usage: 'API Response JSON message',
    placeholders: [],
    comments: [],
    history: []
  },
  {
    id: 'str_be_002',
    key: 'backend.email.quote_received_subject',
    item_type: 'ui_string',
    scope: 'backend',
    module_name: 'Email Service',
    source_text: '[CIC] Xác nhận đã nhận yêu cầu báo giá phần mềm {product_name} - Mã REQ-{request_id}',
    target_text: '', // MISSING EN
    source_locale: 'vi',
    target_locale: 'en',
    status: 'missing',
    assignee_id: 'usr_trans_1',
    assignee_name: 'Đặng Mai Chi',
    assignee_avatar: MOCK_LOCALIZATION_STAFF[0].avatar,
    reviewer_id: 'usr_rev_1',
    reviewer_name: 'Phạm Vũ Bảo Châu',
    reviewer_avatar: MOCK_LOCALIZATION_STAFF[2].avatar,
    due_date: '2026-08-07',
    updated_at: '2026-07-28 10:00',
    source_updated_at: '2026-07-28 10:00',
    context_description: 'Tiêu đề email tự động phản hồi cho khách hàng đăng ký sản phẩm.',
    screen_usage: 'SMTP Autoresponder Header',
    placeholders: ['{product_name}', '{request_id}'],
    comments: [],
    history: []
  },
  {
    id: 'str_be_003',
    key: 'backend.err.duplicate_tax_code',
    item_type: 'ui_string',
    scope: 'backend',
    module_name: 'Customer Service API',
    source_text: 'Mã số thuế doanh nghiệp {tax_code} đã tồn tại trong hệ thống quản lý CIC.',
    target_text: '', // MISSING EN
    source_locale: 'vi',
    target_locale: 'en',
    status: 'missing',
    assignee_id: 'usr_trans_2',
    assignee_name: 'Lê Hoàng Long',
    assignee_avatar: MOCK_LOCALIZATION_STAFF[1].avatar,
    reviewer_id: 'usr_rev_1',
    reviewer_name: 'Phạm Vũ Bảo Châu',
    reviewer_avatar: MOCK_LOCALIZATION_STAFF[2].avatar,
    due_date: '2026-08-08',
    updated_at: '2026-07-28 10:00',
    source_updated_at: '2026-07-28 10:00',
    context_description: 'Lỗi trùng mã số thuế khi doanh nghiệp đăng ký tài khoản portal.',
    screen_usage: 'Registration Validation Error',
    placeholders: ['{tax_code}'],
    comments: [],
    history: []
  },
  {
    id: 'str_be_004',
    key: 'backend.err.insufficient_permission',
    item_type: 'ui_string',
    scope: 'backend',
    module_name: 'Security & Access Control',
    source_text: 'Tài khoản của bạn không có quyền thực hiện thao tác xóa danh mục phần mềm này.',
    target_text: '', // MISSING EN
    source_locale: 'vi',
    target_locale: 'en',
    status: 'missing',
    assignee_id: 'usr_trans_1',
    assignee_name: 'Đặng Mai Chi',
    assignee_avatar: MOCK_LOCALIZATION_STAFF[0].avatar,
    reviewer_id: 'usr_rev_1',
    reviewer_name: 'Phạm Vũ Bảo Châu',
    reviewer_avatar: MOCK_LOCALIZATION_STAFF[2].avatar,
    updated_at: '2026-07-28 10:00',
    source_updated_at: '2026-07-28 10:00',
    context_description: 'Mã lỗi 403 Forbidden khi thao tác sai vai trò.',
    screen_usage: 'RBAC Security Middleware',
    placeholders: [],
    comments: [],
    history: []
  },
  {
    id: 'str_be_005',
    key: 'backend.system.maintenance_mode',
    item_type: 'ui_string',
    scope: 'backend',
    module_name: 'System Core',
    source_text: 'Hệ thống máy chủ CIC đang bảo trì định kỳ từ {start_time} đến {end_time}. Rất tiếc vì sự bất tiện này.',
    target_text: 'CIC Server system is undergoing scheduled maintenance from {start_time} to {end_time}. We apologize for the inconvenience.',
    source_locale: 'vi',
    target_locale: 'en',
    status: 'complete',
    assignee_id: 'usr_trans_1',
    assignee_name: 'Đặng Mai Chi',
    assignee_avatar: MOCK_LOCALIZATION_STAFF[0].avatar,
    reviewer_id: 'usr_rev_1',
    reviewer_name: 'Phạm Vũ Bảo Châu',
    reviewer_avatar: MOCK_LOCALIZATION_STAFF[2].avatar,
    updated_at: '2026-07-29 15:00',
    source_updated_at: '2026-07-20 09:00',
    context_description: 'Thông báo ngắt kết nối hệ thống khi nâng cấp hạ tầng Cloud.',
    screen_usage: 'System Maintenance Screen',
    placeholders: ['{start_time}', '{end_time}'],
    comments: [],
    history: []
  },

  // Additional Missing EN Backend Strings simulation
  ...Array.from({ length: 40 }).map((_, index) => {
    const num = index + 5;
    const modules = ['Auth API', 'Billing Service', 'Catalog API', 'Storage Engine', 'CRM Connector', 'Workflow Engine'];
    const selectedMod = modules[index % modules.length];
    return {
      id: `str_be_missing_${num}`,
      key: `backend.${selectedMod.toLowerCase().replace(/\s+/g, '_')}.message_${num}`,
      item_type: 'ui_string' as const,
      scope: 'backend' as const,
      module_name: selectedMod,
      source_text: `Thông báo hệ thống backend chuỗi ${num}: Thao tác dữ liệu xử lý không thành công do máy chủ phản hồi quá thời gian quy định (${num}ms).`,
      target_text: '', // MISSING EN
      source_locale: 'vi' as const,
      target_locale: 'en' as const,
      status: 'missing' as const,
      assignee_id: index % 2 === 0 ? 'usr_trans_1' : 'usr_trans_2',
      assignee_name: index % 2 === 0 ? 'Đặng Mai Chi' : 'Lê Hoàng Long',
      assignee_avatar: index % 2 === 0 ? MOCK_LOCALIZATION_STAFF[0].avatar : MOCK_LOCALIZATION_STAFF[1].avatar,
      reviewer_id: 'usr_rev_1',
      reviewer_name: 'Phạm Vũ Bảo Châu',
      reviewer_avatar: MOCK_LOCALIZATION_STAFF[2].avatar,
      due_date: '2026-08-10',
      updated_at: '2026-07-31 10:00',
      source_updated_at: '2026-07-31 10:00',
      context_description: `Thông điệp lỗi backend tự động mã hóa chuỗi API #${num}`,
      screen_usage: 'Backend Middleware API Exception',
      placeholders: [],
      comments: [],
      history: []
    };
  }),

  // ==========================================
  // 3. CONTENT ITEMS (Nội dung tin tức, sản phẩm, dịch vụ với Shared Field vs Localized Field)
  // ==========================================
  {
    id: 'cnt_news_101',
    key: 'content.news.item_101',
    item_type: 'content',
    scope: 'content_module',
    module_name: 'Tin tức & Bài viết',
    source_text: 'Xu hướng chuyển đổi số và ứng dụng phần mềm BIM trong xây dựng hạ tầng 2026',
    target_text: 'Digital Transformation Trends and BIM Software Application in Infrastructure Construction 2026',
    source_locale: 'vi',
    target_locale: 'en',
    status: 'complete',
    assignee_id: 'usr_trans_1',
    assignee_name: 'Đặng Mai Chi',
    assignee_avatar: MOCK_LOCALIZATION_STAFF[0].avatar,
    reviewer_id: 'usr_rev_1',
    reviewer_name: 'Phạm Vũ Bảo Châu',
    reviewer_avatar: MOCK_LOCALIZATION_STAFF[2].avatar,
    updated_at: '2026-08-01 16:30',
    source_updated_at: '2026-07-28 11:20',
    context_description: 'Bài viết tiêu điểm ngành xây dựng năm 2026.',
    screen_usage: 'News Article Detail Page (EN)',
    is_shared_field: true,
    shared_field_info: 'Dữ liệu dùng chung (Tác giả, Ngày đăng, Danh mục, Lượt xem) được sửa trực tiếp tại Module Tin tức. Chỉ dịch Tiêu đề, Tóm tắt và Nội dung bài viết.',
    placeholders: [],
    comments: [],
    history: []
  },
  {
    id: 'cnt_prod_202',
    key: 'content.product.item_202',
    item_type: 'content',
    scope: 'content_module',
    module_name: 'Sản phẩm CAD/BIM',
    source_text: 'Phần mềm EnjiCAD v2.5 Network - Giải pháp thay thế AutoCAD tối ưu chi phí doanh nghiệp',
    target_text: 'EnjiCAD v2.5 Network Software - Cost-effective AutoCAD Alternative for Enterprises',
    source_locale: 'vi',
    target_locale: 'en',
    status: 'in_progress',
    assignee_id: 'usr_trans_1',
    assignee_name: 'Đặng Mai Chi',
    assignee_avatar: MOCK_LOCALIZATION_STAFF[0].avatar,
    reviewer_id: 'usr_rev_1',
    reviewer_name: 'Phạm Vũ Bảo Châu',
    reviewer_avatar: MOCK_LOCALIZATION_STAFF[2].avatar,
    due_date: '2026-08-05',
    updated_at: '2026-08-03 14:00',
    source_updated_at: '2026-08-01 09:00',
    context_description: 'Nội dung giới thiệu sản phẩm phần mềm EnjiCAD phiên bản tiếng Anh.',
    screen_usage: 'Product Detail Page (EN)',
    is_shared_field: true,
    shared_field_info: 'Mã sản phẩm (SKU: ENJ-NET-2026), Giá bán lẻ (28,500,000 VNĐ) là Dữ liệu dùng chung. Bạn chỉ dịch các trường Tên sản phẩm EN, Mô tả tính năng EN.',
    placeholders: [],
    comments: [
      {
        id: 'c2',
        author_id: 'usr_trans_1',
        author_name: 'Đặng Mai Chi',
        author_avatar: MOCK_LOCALIZATION_STAFF[0].avatar,
        content: 'Đã hoàn thành dịch tiêu đề và 3 tính năng chính, còn phần bảng so sánh thông số đang hoàn thiện.',
        created_at: '2026-08-03 14:05',
        type: 'general'
      }
    ],
    history: []
  },
  {
    id: 'cnt_serv_303',
    key: 'content.service.item_303',
    item_type: 'content',
    scope: 'content_module',
    module_name: 'Dịch vụ tư vấn',
    source_text: 'Dịch vụ Đào tạo & Chuyển giao Công nghệ BIM tiêu chuẩn ISO 19650',
    target_text: '', // MISSING EN
    source_locale: 'vi',
    target_locale: 'en',
    status: 'missing',
    assignee_id: 'usr_trans_2',
    assignee_name: 'Lê Hoàng Long',
    assignee_avatar: MOCK_LOCALIZATION_STAFF[1].avatar,
    reviewer_id: 'usr_rev_1',
    reviewer_name: 'Phạm Vũ Bảo Châu',
    reviewer_avatar: MOCK_LOCALIZATION_STAFF[2].avatar,
    due_date: '2026-08-08',
    updated_at: '2026-08-02 08:00',
    source_updated_at: '2026-08-02 08:00',
    context_description: 'Trang giới thiệu dịch vụ đào tạo tư vấn doanh nghiệp.',
    screen_usage: 'Services Listing & Detail (EN)',
    is_shared_field: true,
    shared_field_info: 'Hãng chứng nhận (BSI), Thời lượng khóa học là Dữ liệu dùng chung.',
    placeholders: [],
    comments: [],
    history: []
  }
];
