import { ContactRequest, StaffMember } from './types';

export const MOCK_STAFF_MEMBERS: StaffMember[] = [
  {
    id: 'usr_sales_1',
    name: 'Nguyễn Văn Minh',
    email: 'minh.nguyen@cic.com.vn',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    role: 'sales',
    team: 'Sales CAD/BIM',
    active_cases_count: 8,
  },
  {
    id: 'usr_sales_2',
    name: 'Trần Hoài Nam',
    email: 'nam.tran@cic.com.vn',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    role: 'sales',
    team: 'Sales Structural',
    active_cases_count: 12,
  },
  {
    id: 'usr_support_1',
    name: 'Phạm Thị Hương',
    email: 'huong.pham@cic.com.vn',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80',
    role: 'support',
    team: 'Customer Care',
    active_cases_count: 5,
  },
  {
    id: 'usr_tech_1',
    name: 'Vũ Quốc Huy',
    email: 'huy.vu@cic.com.vn',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
    role: 'support',
    team: 'Tech Support',
    active_cases_count: 4,
  },
  {
    id: 'usr_mgr_1',
    name: 'Lê Hoàng Anh',
    email: 'anh.le@cic.com.vn',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&auto=format&fit=crop&q=80',
    role: 'manager',
    team: 'Management',
    active_cases_count: 0,
  },
];

export const INITIAL_CONTACT_REQUESTS: ContactRequest[] = [
  {
    id: 'REQ-2026-0891',
    source: 'product_registration',
    form_title: 'Đăng ký nhận báo giá & dùng thử EnjiCAD Network',
    sender_name: 'Trần Văn Quốc',
    sender_email: 'quoc.tv@vinaconex.com.vn',
    sender_phone: '0912345678',
    sender_company: 'Tổng Công ty CP Vinaconex (Ban Dự án 2)',
    sender_address: 'Tòa nhà Vinaconex, 34 Láng Hạ, Đống Đa, Hà Nội',
    request_subject: 'Xin báo giá gói 15 License EnjiCAD Pro v2.5 Mạng LAN',
    request_content:
      'Kính gửi Bộ phận Kinh doanh CIC,\n\nCông ty chúng tôi đang chuẩn bị đầu tư chuẩn hóa bản quyền CAD cho các kỹ sư kết cấu. Rất mong quý công ty gửi báo giá chi tiết cho 15 license dạng Network Key, kèm theo lịch hỗ trợ training cắm khóa cứng ESCON và cấp chứng nhận học viên.',
    sender_ip: '118.70.182.95',
    page_url: 'https://cic.com.vn/products/enjicad-pro-network',
    created_at: '2026-08-04T07:15:00Z',
    status: 'in_progress',
    priority: 'urgent',
    owner_id: 'usr_sales_1',
    owner_name: 'Nguyễn Văn Minh',
    owner_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    assigned_team: 'Sales CAD/BIM',
    sla_deadline: '2026-08-04T11:15:00Z',
    sla_status: 'near_overdue',
    tags: ['Báo giá lớn', 'Vinaconex', 'EnjiCAD', 'License Network'],
    related_object: {
      id: 'prd_enjicad',
      type: 'product',
      title: 'Phần mềm EnjiCAD Pro v2.5 Network Edition',
      code: 'CAD-ENJ-NET',
      thumbnail: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=300&auto=format&fit=crop&q=80',
      category_name: 'Phần mềm Thiết kế CAD/BIM',
    },
    internal_notes: [
      {
        id: 'note_101',
        author_id: 'usr_sales_1',
        author_name: 'Nguyễn Văn Minh',
        author_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
        content: 'Đã gọi điện trao đổi sơ bộ với anh Quốc. Anh yêu cầu gửi bảng so sánh tính năng giữa EnjiCAD Pro và AutoCAD 2026 trước 11h sáng nay.',
        is_pinned: true,
        created_at: '2026-08-04T07:45:00Z',
      },
    ],
    timeline: [
      {
        id: 'tl_1',
        timestamp: '2026-08-04T07:15:00Z',
        actor_name: 'Hệ thống (Web Frontend)',
        event_type: 'created',
        description: 'Tiếp nhận yêu cầu tự động từ Form Báo giá EnjiCAD',
      },
      {
        id: 'tl_2',
        timestamp: '2026-08-04T07:20:00Z',
        actor_name: 'Lê Hoàng Anh',
        event_type: 'assigned',
        description: 'Phân công yêu cầu cho Nguyễn Văn Minh (Sales CAD/BIM)',
        old_value: 'Unassigned',
        new_value: 'Nguyễn Văn Minh',
      },
      {
        id: 'tl_3',
        timestamp: '2026-08-04T07:45:00Z',
        actor_name: 'Nguyễn Văn Minh',
        event_type: 'note_added',
        description: 'Đã ghi chú kết quả cuộc gọi phản hồi đầu tiên',
      },
    ],
    is_unread: false,
    is_starred: true,
  },
  {
    id: 'REQ-2026-0890',
    source: 'product_registration',
    form_title: 'Đăng ký tư vấn giải pháp CSI ETABS Ultimate',
    sender_name: 'Phạm Hồng Thái',
    sender_email: 'thai.ph@nagecco.com.vn',
    sender_phone: '0988776655',
    sender_company: 'Công ty Cổ phần Tư vấn Xây dựng NAGECCO',
    sender_address: 'Tầng 8, Tòa nhà CDC, 25 Lê Đại Hành, Hai Bà Trưng, Hà Nội',
    request_subject: 'Cần nâng cấp license CSI ETABS v20 lên CSI ETABS Ultimate v22',
    request_content:
      'Chào CIC, NAGECCO đang muốn mua bổ sung 3 bản nâng cấp ETABS Ultimate để phục vụ thẩm tra kết cấu nhà cao tầng >40 tầng tại TPHCM. Nhờ tư vấn chính sách giảm giá cho khách hàng thân thiết.',
    sender_ip: '14.225.10.42',
    page_url: 'https://cic.com.vn/products/csi-etabs-ultimate',
    created_at: '2026-08-04T06:30:00Z',
    status: 'assigned',
    priority: 'high',
    owner_id: 'usr_sales_2',
    owner_name: 'Trần Hoài Nam',
    owner_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    assigned_team: 'Sales Structural',
    sla_deadline: '2026-08-04T08:30:00Z',
    sla_status: 'overdue',
    tags: ['NAGECCO', 'CSI ETABS', 'Upgrade'],
    related_object: {
      id: 'prd_etabs',
      type: 'product',
      title: 'Phần mềm CSI ETABS Ultimate v22',
      code: 'CSI-ETB-ULT',
      thumbnail: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=300&auto=format&fit=crop&q=80',
      category_name: 'Phần mềm Tính toán Kết cấu',
    },
    internal_notes: [],
    timeline: [
      {
        id: 'tl_10',
        timestamp: '2026-08-04T06:30:00Z',
        actor_name: 'Hệ thống (Web Frontend)',
        event_type: 'created',
        description: 'Tự động ghi nhận yêu cầu từ Landing page CSI ETABS',
      },
      {
        id: 'tl_11',
        timestamp: '2026-08-04T06:35:00Z',
        actor_name: 'Trần Hoài Nam',
        event_type: 'assigned',
        description: 'Đã nhận việc (Claim) từ hàng chờ Chưa phân công',
      },
    ],
    is_unread: true,
  },
  {
    id: 'REQ-2026-0889',
    source: 'general_contact',
    form_title: 'Form Liên hệ chung toàn hệ thống',
    sender_name: 'Nguyễn Thị Mai',
    sender_email: 'mai.nt@hoabinhgroup.vn',
    sender_phone: '0903112233',
    sender_company: 'Tập đoàn Xây dựng Hòa Bình',
    request_subject: 'Hỏi về tài khoản cấp chứng chỉ hoàn thành khóa học BIM Manager 2026',
    request_content:
      'Kính chào CIC Support, Tôi đã tham gia khóa đào tạo BIM Manager do CIC tổ chức tuần trước nhưng chưa nhận được email cấp chứng chỉ số dạng PDF. Xin vui lòng kiểm tra hỗ trợ giúp tôi.',
    sender_ip: '113.161.42.11',
    page_url: 'https://cic.com.vn/lien-he',
    created_at: '2026-08-04T05:10:00Z',
    status: 'new',
    priority: 'normal',
    assigned_team: 'Customer Care',
    sla_deadline: '2026-08-04T13:10:00Z',
    sla_status: 'on_time',
    tags: ['Đào tạo', 'Chứng chỉ', 'Hòa Bình Group'],
    internal_notes: [],
    timeline: [
      {
        id: 'tl_20',
        timestamp: '2026-08-04T05:10:00Z',
        actor_name: 'Hệ thống (Web Frontend)',
        event_type: 'created',
        description: 'Tiếp nhận thư từ Form Liên hệ chung /lien-he',
      },
    ],
    is_unread: true,
  },
  {
    id: 'REQ-2026-0888',
    source: 'technical_support',
    form_title: 'Yêu cầu Hỗ trợ Kỹ thuật & Khóa cứng',
    sender_name: 'Hoàng Minh Đức',
    sender_email: 'duc.hm@cienco4.vn',
    sender_phone: '0934567890',
    sender_company: 'Tập đoàn CIENCO4',
    request_subject: 'Lỗi không nhận USB Hardlock ESCON 2026 khi cắm vào máy trạm Windows 11',
    request_content:
      'Khóa USB màu đỏ của chúng tôi cắm vào máy tính báo đèn nhấp nháy liên tục nhưng mở phần mềm ESCON lên vẫn báo "Cannot find Sentinel Key". Nhờ anh chị bộ phận kỹ thuật hướng dẫn gấp qua UltraViewer.',
    sender_ip: '27.72.100.15',
    page_url: 'https://cic.com.vn/ho-tro-ky-thuat',
    created_at: '2026-08-04T04:00:00Z',
    status: 'in_progress',
    priority: 'high',
    owner_id: 'usr_tech_1',
    owner_name: 'Vũ Quốc Huy',
    owner_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
    assigned_team: 'Tech Support',
    sla_deadline: '2026-08-04T08:00:00Z',
    sla_status: 'overdue',
    tags: ['Khóa cứng USB', 'Sentinel Driver', 'ESCON', 'CIENCO4'],
    related_object: {
      id: 'prd_escon',
      type: 'product',
      title: 'Phần mềm Tính toán Móng cọc ESCON 2026',
      code: 'STRUCT-ESC-26',
      thumbnail: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=300&auto=format&fit=crop&q=80',
      category_name: 'Phần mềm Kết cấu Hạ tầng',
    },
    internal_notes: [
      {
        id: 'note_201',
        author_id: 'usr_tech_1',
        author_name: 'Vũ Quốc Huy',
        author_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
        content: 'Đã kết nối UltraViewer ID 48 920 112. Phát hiện driver Sentinel v7.5 bị Windows Defender block. Đã add Exclusion và khởi động lại dịch vụ.',
        created_at: '2026-08-04T04:45:00Z',
      },
    ],
    timeline: [
      {
        id: 'tl_30',
        timestamp: '2026-08-04T04:00:00Z',
        actor_name: 'Hệ thống (Web Frontend)',
        event_type: 'created',
        description: 'Tự động tạo phiếu Hỗ trợ kỹ thuật',
      },
      {
        id: 'tl_31',
        timestamp: '2026-08-04T04:10:00Z',
        actor_name: 'Vũ Quốc Huy',
        event_type: 'assigned',
        description: 'Tiếp nhận phiếu xử lý kỹ thuật',
      },
    ],
    is_unread: false,
  },
  {
    id: 'REQ-2026-0887',
    source: 'service_inquiry',
    form_title: 'Đăng ký Khảo sát Dịch vụ Chống thấm Công trình',
    sender_name: 'Lê Tuấn Kiệt',
    sender_email: 'kiet.lt@coteccons.vn',
    sender_phone: '0977889900',
    sender_company: 'Công ty Cổ phần Xây dựng Coteccons',
    request_subject: 'Yêu cầu đội ngũ kỹ sư CIC khảo sát thực địa nứt sàn tầng hầm B2',
    request_content:
      'Dự án nhà cao tầng khu vực Nam Từ Liêm đang bị hiện tượng rò rỉ nước ngầm tại mạch ngừng thi công tầng hầm B2. Đề nghị CIC cử chuyên gia mang thiết bị siêu âm bê tông đến khảo sát và đưa ra giải pháp chống thấm bơm keo PU.',
    sender_ip: '113.190.220.88',
    page_url: 'https://cic.com.vn/services/chong-tham-cong-trinh',
    created_at: '2026-08-03T16:20:00Z',
    status: 'resolved',
    priority: 'urgent',
    owner_id: 'usr_support_1',
    owner_name: 'Phạm Thị Hương',
    owner_avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80',
    assigned_team: 'Customer Care',
    sla_deadline: '2026-08-04T08:20:00Z',
    sla_status: 'on_time',
    resolved_at: '2026-08-04T02:10:00Z',
    resolution_summary: 'Đã hoàn tất lên phương án khảo sát ngày 05/08 và chuyển hồ sơ kỹ thuật cho Ban Chống thấm CIC triển khai hợp đồng khảo sát.',
    tags: ['Chống thấm', 'Khảo sát', 'Coteccons'],
    related_object: {
      id: 'srv_chongtham',
      type: 'service',
      title: 'Dịch vụ Khảo sát & Chống thấm Công trình',
      code: 'SRV-WATERPROOF',
      thumbnail: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?w=300&auto=format&fit=crop&q=80',
      category_name: 'Dịch vụ Kỹ thuật Xây dựng',
    },
    internal_notes: [
      {
        id: 'note_301',
        author_id: 'usr_support_1',
        author_name: 'Phạm Thị Hương',
        author_avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80',
        content: 'Đã làm việc xong với Trưởng phòng Kỹ thuật Chống thấm - KTS Bùi Việt Cường. Hai bên thống nhất hẹn lịch khảo sát sáng thứ Tư.',
        created_at: '2026-08-04T02:00:00Z',
      },
    ],
    timeline: [
      {
        id: 'tl_40',
        timestamp: '2026-08-03T16:20:00Z',
        actor_name: 'Hệ thống (Web Frontend)',
        event_type: 'created',
        description: 'Đăng ký dịch vụ khảo sát mới từ website',
      },
      {
        id: 'tl_41',
        timestamp: '2026-08-04T02:10:00Z',
        actor_name: 'Phạm Thị Hương',
        event_type: 'status_changed',
        description: 'Chuyển trạng thái sang "Đã giải quyết"',
        old_value: 'In progress',
        new_value: 'Resolved',
      },
    ],
    is_unread: false,
  },
  {
    id: 'REQ-2026-0886',
    source: 'general_contact',
    form_title: 'Thư Rác Tự Động (Spam Bot Detection)',
    sender_name: 'Seo Expert Crypto',
    sender_email: 'best-seo-rankings-2026@gmail-spam.com',
    sender_phone: '+1 800 999 8888',
    sender_company: 'Global Digital Rank Boost Ltd',
    request_subject: 'Guaranteed #1 Rank on Google Search for your website in 24 Hours!',
    request_content: 'Hi admin, We offer cheap SEO backlinks, guest posts, and crypto mining tokens. Click link to claim your $500 free credit bonus right now!',
    sender_ip: '185.220.101.5',
    page_url: 'https://cic.com.vn/lien-he',
    created_at: '2026-08-03T12:00:00Z',
    status: 'spam',
    priority: 'low',
    sla_deadline: '2026-08-04T12:00:00Z',
    sla_status: 'on_time',
    spam_reason: 'Tự động phát hiện bot spam quảng cáo SEO/Crypto nước ngoài',
    tags: ['Spam', 'Bot'],
    internal_notes: [],
    timeline: [
      {
        id: 'tl_50',
        timestamp: '2026-08-03T12:00:00Z',
        actor_name: 'Bộ lọc Spam AI System',
        event_type: 'marked_spam',
        description: 'Đã tự động lọc và di chuyển vào danh sách Spam/Rác',
      },
    ],
    is_unread: false,
  },
  {
    id: 'REQ-2026-0885',
    source: 'product_registration',
    form_title: 'Đăng ký tư vấn trùng lặp (Duplicate Entry)',
    sender_name: 'Trần Văn Quốc',
    sender_email: 'quoc.tv@vinaconex.com.vn',
    sender_phone: '0912345678',
    sender_company: 'Tổng Công ty CP Vinaconex',
    request_subject: 'Báo giá 15 License EnjiCAD (Gửi lại lần 2)',
    request_content: 'Tôi vừa gửi form cách đây 10 phút nhưng sợ bị thất lạc nên ấn submit lại. Mong công ty liên hệ gấp.',
    sender_ip: '118.70.182.95',
    page_url: 'https://cic.com.vn/products/enjicad-pro-network',
    created_at: '2026-08-04T07:25:00Z',
    status: 'duplicate',
    priority: 'low',
    owner_id: 'usr_sales_1',
    owner_name: 'Nguyễn Văn Minh',
    sla_deadline: '2026-08-04T15:25:00Z',
    sla_status: 'on_time',
    duplicate_of_id: 'REQ-2026-0891',
    tags: ['Trùng lặp', 'REQ-2026-0891'],
    internal_notes: [],
    timeline: [
      {
        id: 'tl_60',
        timestamp: '2026-08-04T07:28:00Z',
        actor_name: 'Nguyễn Văn Minh',
        event_type: 'status_changed',
        description: 'Đã liên kết đánh dấu trùng lặp với bản ghi gốc REQ-2026-0891',
      },
    ],
    is_unread: false,
  },
];
