import {
  PermissionTask,
  PermissionFunction,
  PermissionField,
  CmsUserPermissionTarget,
  UserPermissionState,
  CmsRole,
  RoleAssignment,
  PolicyIssue,
  AccessReview,
} from './types';

export const permissionUsersMock: CmsUserPermissionTarget[] = [
  {
    id: 'usr_001',
    username: 'admin_cic',
    fullName: 'Nguyễn Văn Quản Trị',
    email: 'admin@cic.com.vn',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    role: 'Super Administrator',
    department: 'Ban Giám Đốc',
  },
  {
    id: 'usr_002',
    username: 'minh_bien',
    fullName: 'Trần Biên Minh',
    email: 'minh.bien@cic.com.vn',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    role: 'Biên tập viên',
    department: 'Phòng Truyền thông',
  },
  {
    id: 'usr_003',
    username: 'hoang_kythuat',
    fullName: 'Lê Huy Hoàng',
    email: 'hoang.tech@cic.com.vn',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    role: 'Quản lý Kỹ thuật',
    department: 'Phòng Giải pháp phần mềm',
  },
  {
    id: 'usr_004',
    username: 'phuong_kinhdoanh',
    fullName: 'Phạm Mai Phương',
    email: 'phuong.sales@cic.com.vn',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    role: 'Chuyên viên Kinh doanh',
    department: 'Phòng Báo giá & Khách hàng',
  },
];

export const initialPermissionTasksMock: PermissionTask[] = [
  // PRODUCTS MODULE
  { id: 'tsk_prod_list', module: 'PRODUCTS', view: 'List', task: 'View Products List', description: 'Quyền xem danh sách tất cả sản phẩm phần mềm', published: true, ordering: 1 },
  { id: 'tsk_prod_add', module: 'PRODUCTS', view: 'List', task: 'Add New Product', description: 'Thêm mới thông tin sản phẩm phần mềm', published: true, ordering: 2 },
  { id: 'tsk_prod_edit', module: 'PRODUCTS', view: 'Detail', task: 'Edit Product Detail', description: 'Chỉnh sửa thông tin chi tiết sản phẩm', published: true, ordering: 3 },
  { id: 'tsk_prod_del', module: 'PRODUCTS', view: 'List', task: 'Delete Product', description: 'Xóa sản phẩm khỏi hệ thống', published: true, ordering: 4 },
  { id: 'tsk_prod_pub', module: 'PRODUCTS', view: 'List', task: 'Publish Product', description: 'Xuất bản sản phẩm trực tiếp ra website', published: true, ordering: 5 },

  // USERS MODULE
  { id: 'tsk_user_list', module: 'USERS', view: 'List', task: 'View Admin Users', description: 'Xem danh sách tài khoản người dùng quản trị', published: true, ordering: 6 },
  { id: 'tsk_user_add', module: 'USERS', view: 'Detail', task: 'Add Admin User', description: 'Tạo tài khoản quản trị mới', published: true, ordering: 7 },
  { id: 'tsk_user_edit', module: 'USERS', view: 'Detail', task: 'Edit Admin User', description: 'Sửa thông tin và phân quyền người dùng', published: true, ordering: 8 },
  { id: 'tsk_user_del', module: 'USERS', view: 'List', task: 'Delete Admin User', description: 'Xóa tài khoản khỏi CMS', published: true, ordering: 9 },

  // NEWS MODULE
  { id: 'tsk_news_list', module: 'NEWS', view: 'List', task: 'View Articles List', description: 'Xem danh sách bài viết & tin tức', published: true, ordering: 10 },
  { id: 'tsk_news_add', module: 'NEWS', view: 'Detail', task: 'Create Article', description: 'Soạn thảo bài viết tin tức mới', published: true, ordering: 11 },
  { id: 'tsk_news_edit', module: 'NEWS', view: 'Detail', task: 'Edit Article', description: 'Chỉnh sửa bài viết tin tức', published: true, ordering: 12 },
  { id: 'tsk_news_pub', module: 'NEWS', view: 'List', task: 'Publish Article', description: 'Đăng xuất bản bài viết tin tức', published: true, ordering: 13 },

  // BANNERS MODULE
  { id: 'tsk_banner_list', module: 'BANNERS', view: 'List', task: 'View Banners', description: 'Xem danh sách banner quảng cáo', published: true, ordering: 14 },
  { id: 'tsk_banner_edit', module: 'BANNERS', view: 'Detail', task: 'Manage Banners', description: 'Cấu hình và thêm mới slider banner', published: true, ordering: 15 },

  // SETTINGS MODULE
  { id: 'tsk_sett_view', module: 'SETTINGS', view: 'Global', task: 'View System Settings', description: 'Xem cấu hình chung hệ thống', published: true, ordering: 16 },
  { id: 'tsk_sett_edit', module: 'SETTINGS', view: 'Global', task: 'Update Configuration', description: 'Cập nhật tham số hệ thống & SEO', published: true, ordering: 17 },
];

export const permissionFunctionsMock: PermissionFunction[] = [
  // Products Functions
  { id: 'fn_p_v1', taskId: 'tsk_prod_list', code: 'FUN_PROD_FILTER', name: 'Sử dụng bộ lọc loại sản phẩm' },
  { id: 'fn_p_v2', taskId: 'tsk_prod_list', code: 'FUN_PROD_EXPORT', name: 'Xuất dữ liệu Excel / CSV' },
  { id: 'fn_p_a1', taskId: 'tsk_prod_add', code: 'FUN_PROD_DRAFT', name: 'Lưu bản nháp sản phẩm' },
  { id: 'fn_p_e1', taskId: 'tsk_prod_edit', code: 'FUN_PROD_QUICK_SAVE', name: 'Lưu thay đổi nhanh' },
  { id: 'fn_p_e2', taskId: 'tsk_prod_edit', code: 'FUN_PROD_DUPLICATE', name: 'Nhân bản dữ liệu sản phẩm' },
  { id: 'fn_p_p1', taskId: 'tsk_prod_pub', code: 'FUN_PROD_BATCH_PUB', name: 'Xuất bản hàng loạt' },

  // Users Functions
  { id: 'fn_u_v1', taskId: 'tsk_user_list', code: 'FUN_USER_SEARCH', name: 'Tìm kiếm người dùng nâng cao' },
  { id: 'fn_u_e1', taskId: 'tsk_user_edit', code: 'FUN_USER_PWD_RESET', name: 'Cấp lại mật khẩu tài khoản' },

  // News Functions
  { id: 'fn_n_a1', taskId: 'tsk_news_add', code: 'FUN_NEWS_IMAGE_UPLOAD', name: 'Tải ảnh bìa & media' },
  { id: 'fn_n_p1', taskId: 'tsk_news_pub', code: 'FUN_NEWS_SCHEDULE_PUB', name: 'Hẹn giờ xuất bản tự động' },
];

export const permissionFieldsMock: PermissionField[] = [
  // Products Fields
  { id: 'fld_p_name', moduleId: 'PRODUCTS', fieldCode: 'name', fieldName: 'Tên sản phẩm' },
  { id: 'fld_p_code', moduleId: 'PRODUCTS', fieldCode: 'code', fieldName: 'Mã phần mềm (SKU)' },
  { id: 'fld_p_price', moduleId: 'PRODUCTS', fieldCode: 'price', fieldName: 'Giá niêm yết / Báo giá' },
  { id: 'fld_p_desc', moduleId: 'PRODUCTS', fieldCode: 'description', fieldName: 'Mô tả chi tiết & Thông số' },
  { id: 'fld_p_thumb', moduleId: 'PRODUCTS', fieldCode: 'thumbnail', fieldName: 'Hình ảnh đại diện' },
  { id: 'fld_p_pub', moduleId: 'PRODUCTS', fieldCode: 'published', fieldName: 'Trạng thái Xuất bản' },
  { id: 'fld_p_ord', moduleId: 'PRODUCTS', fieldCode: 'ordering', fieldName: 'Thứ tự ưu tiên' },

  // Users Fields
  { id: 'fld_u_uname', moduleId: 'USERS', fieldCode: 'username', fieldName: 'Tên đăng nhập' },
  { id: 'fld_u_pwd', moduleId: 'USERS', fieldCode: 'password', fieldName: 'Mật khẩu' },
  { id: 'fld_u_email', moduleId: 'USERS', fieldCode: 'email', fieldName: 'Địa chỉ Email' },
  { id: 'fld_u_fname', moduleId: 'USERS', fieldCode: 'full_name', fieldName: 'Họ và tên' },
  { id: 'fld_u_phone', moduleId: 'USERS', fieldCode: 'phone', fieldName: 'Số điện thoại' },
  { id: 'fld_u_agency', moduleId: 'USERS', fieldCode: 'agencies', fieldName: 'Đơn vị phụ trách' },

  // News Fields
  { id: 'fld_n_title', moduleId: 'NEWS', fieldCode: 'title', fieldName: 'Tiêu đề bài viết' },
  { id: 'fld_n_content', moduleId: 'NEWS', fieldCode: 'content', fieldName: 'Nội dung HTML chi tiết' },
  { id: 'fld_n_seo', moduleId: 'NEWS', fieldCode: 'meta_seo', fieldName: 'Thẻ SEO Meta & Alt' },
];

export const initialUserPermissionsMock: Record<string, UserPermissionState> = {
  usr_001: {
    userId: 'usr_001',
    grantedTaskIds: initialPermissionTasksMock.map((t) => t.id),
    grantedFunctionIds: permissionFunctionsMock.map((f) => f.id),
    grantedFieldIds: permissionFieldsMock.map((f) => f.id),
  },
  usr_002: {
    userId: 'usr_002',
    grantedTaskIds: ['tsk_prod_list', 'tsk_prod_edit', 'tsk_news_list', 'tsk_news_add', 'tsk_news_edit', 'tsk_news_pub', 'tsk_banner_list', 'tsk_banner_edit'],
    grantedFunctionIds: ['fn_p_v1', 'fn_p_e1', 'fn_n_a1', 'fn_n_p1'],
    grantedFieldIds: ['fld_p_name', 'fld_p_desc', 'fld_p_thumb', 'fld_n_title', 'fld_n_content', 'fld_n_seo'],
  },
  usr_003: {
    userId: 'usr_003',
    grantedTaskIds: ['tsk_prod_list', 'tsk_prod_add', 'tsk_prod_edit', 'tsk_news_list'],
    grantedFunctionIds: ['fn_p_v1', 'fn_p_a1', 'fn_p_e1'],
    grantedFieldIds: ['fld_p_name', 'fld_p_code', 'fld_p_price', 'fld_p_desc', 'fld_p_thumb'],
  },
  usr_004: {
    userId: 'usr_004',
    grantedTaskIds: ['tsk_prod_list', 'tsk_news_list'],
    grantedFunctionIds: ['fn_p_v1'],
    grantedFieldIds: ['fld_p_name', 'fld_p_price'],
  },
};

export const cmsRolesMock: CmsRole[] = [
  {
    id: 'role_super_admin',
    name: 'Super Administrator',
    category: 'system',
    riskLevel: 'privileged',
    status: 'active',
    purpose: 'Quản trị viên toàn quyền điều hành hệ thống CMS, phân quyền và hạ tầng kỹ thuật',
    description: 'Có toàn quyền View, Create, Edit, Delete, Publish, Export, Configure đối với mọi module',
    owner: 'Hội đồng Quản trị CIC',
    reviewer: 'Security Lead',
    activeVersion: 3.0,
    versions: [
      {
        versionNumber: 3.0,
        createdTime: '2026-06-15 08:30:00',
        createdBy: 'admin_cic',
        status: 'active',
        changeNote: 'Bổ sung quyền quản trị AI Logic & Webhook Security Configuration',
        matrix: {
          PRODUCTS: { view: 'allowed', create: 'allowed', edit: 'allowed', delete: 'allowed', publish: 'allowed', export: 'allowed', configure: 'allowed' },
          USERS: { view: 'allowed', create: 'allowed', edit: 'allowed', delete: 'allowed', publish: 'allowed', export: 'allowed', configure: 'allowed' },
          NEWS: { view: 'allowed', create: 'allowed', edit: 'allowed', delete: 'allowed', publish: 'allowed', export: 'allowed', configure: 'allowed' },
          BANNERS: { view: 'allowed', create: 'allowed', edit: 'allowed', delete: 'allowed', publish: 'allowed', export: 'allowed', configure: 'allowed' },
          SETTINGS: { view: 'allowed', create: 'allowed', edit: 'allowed', delete: 'allowed', publish: 'allowed', export: 'allowed', configure: 'allowed' },
          ROLES: { view: 'allowed', create: 'allowed', edit: 'allowed', delete: 'allowed', publish: 'allowed', export: 'allowed', configure: 'allowed' },
        },
        scopes: [{ type: 'global', allowedValues: ['ALL'], description: 'Toàn bộ phạm vi chi nhánh & hệ thống' }],
      },
      {
        versionNumber: 2.0,
        createdTime: '2026-01-10 10:00:00',
        createdBy: 'admin_cic',
        status: 'superseded',
        changeNote: 'Cấu hình chuẩn hóa ban đầu cho năm 2026',
        matrix: {
          PRODUCTS: { view: 'allowed', create: 'allowed', edit: 'allowed', delete: 'allowed', publish: 'allowed' },
          USERS: { view: 'allowed', create: 'allowed', edit: 'allowed', delete: 'allowed' },
        },
        scopes: [{ type: 'global', allowedValues: ['ALL'], description: 'Toàn bộ phạm vi' }],
      },
    ],
    matrix: {
      PRODUCTS: { view: 'allowed', create: 'allowed', edit: 'allowed', delete: 'allowed', publish: 'allowed', export: 'allowed', configure: 'allowed' },
      USERS: { view: 'allowed', create: 'allowed', edit: 'allowed', delete: 'allowed', publish: 'allowed', export: 'allowed', configure: 'allowed' },
      NEWS: { view: 'allowed', create: 'allowed', edit: 'allowed', delete: 'allowed', publish: 'allowed', export: 'allowed', configure: 'allowed' },
      BANNERS: { view: 'allowed', create: 'allowed', edit: 'allowed', delete: 'allowed', publish: 'allowed', export: 'allowed', configure: 'allowed' },
      SETTINGS: { view: 'allowed', create: 'allowed', edit: 'allowed', delete: 'allowed', publish: 'allowed', export: 'allowed', configure: 'allowed' },
      ROLES: { view: 'allowed', create: 'allowed', edit: 'allowed', delete: 'allowed', publish: 'allowed', export: 'allowed', configure: 'allowed' },
    },
    scopes: [{ type: 'global', allowedValues: ['ALL'], description: 'Toàn hệ thống (Global Scope)' }],
    assignedUsersCount: 2,
    assignedGroupCount: 1,
    conflictIssuesCount: 0,
    updatedTime: '2026-06-15 08:30:00',
    updatedBy: 'admin_cic',
  },
  {
    id: 'role_sec_admin',
    name: 'Security & Access Admin',
    category: 'system',
    riskLevel: 'privileged',
    status: 'active',
    purpose: 'Chuyên viên quản trị bảo mật, kiểm tra Audit Log và cấp quyền tài khoản người dùng',
    description: 'Chuyên trách về tài khoản người dùng, ma trận phân quyền, nhật ký audit và chính sách an toàn thông tin',
    owner: 'Phòng An ninh Thông tin',
    reviewer: 'Super Administrator',
    activeVersion: 2.1,
    versions: [
      {
        versionNumber: 2.1,
        createdTime: '2026-07-01 14:00:00',
        createdBy: 'admin_cic',
        status: 'active',
        changeNote: 'Cập nhật quyền kiểm tra audit log và xác thực 2FA bắt buộc',
        matrix: {
          USERS: { view: 'allowed', create: 'allowed', edit: 'allowed', delete: 'allowed', export: 'allowed' },
          ROLES: { view: 'allowed', create: 'allowed', edit: 'allowed', configure: 'allowed' },
          SETTINGS: { view: 'allowed', edit: 'conditional', configure: 'allowed' },
          PRODUCTS: { view: 'allowed' },
          NEWS: { view: 'allowed' },
        },
        scopes: [{ type: 'global', allowedValues: ['ALL'], description: 'Phạm vi toàn hệ thống' }],
      },
    ],
    matrix: {
      USERS: { view: 'allowed', create: 'allowed', edit: 'allowed', delete: 'allowed', export: 'allowed' },
      ROLES: { view: 'allowed', create: 'allowed', edit: 'allowed', configure: 'allowed' },
      SETTINGS: { view: 'allowed', edit: 'conditional', configure: 'allowed' },
      PRODUCTS: { view: 'allowed' },
      NEWS: { view: 'allowed' },
    },
    scopes: [{ type: 'global', allowedValues: ['ALL'], description: 'Phạm vi toàn hệ thống' }],
    assignedUsersCount: 3,
    assignedGroupCount: 1,
    conflictIssuesCount: 0,
    updatedTime: '2026-07-01 14:00:00',
    updatedBy: 'admin_cic',
  },
  {
    id: 'role_content_editor',
    name: 'Content Manager / Editor',
    category: 'system',
    riskLevel: 'standard',
    status: 'active',
    purpose: 'Quản lý bài viết tin tức, danh mục sản phẩm và banner truyền thông trên hệ thống portal',
    description: 'Biên tập, chỉnh sửa và đăng xuất bản nội dung tin tức, sản phẩm trong phạm vi phân công',
    owner: 'Ban Truyền thông & Content',
    reviewer: 'Content Lead',
    activeVersion: 1.4,
    draftVersion: 1.5,
    versions: [
      {
        versionNumber: 1.5,
        createdTime: '2026-08-01 09:15:00',
        createdBy: 'minh_bien',
        status: 'draft',
        changeNote: 'Đang mở rộng quyền xuất bản tin tức theo lịch hẹn tự động (Draft version)',
        matrix: {
          PRODUCTS: { view: 'allowed', create: 'allowed', edit: 'allowed', publish: 'conditional', export: 'allowed' },
          NEWS: { view: 'allowed', create: 'allowed', edit: 'allowed', publish: 'allowed', export: 'allowed' },
          BANNERS: { view: 'allowed', create: 'allowed', edit: 'allowed', publish: 'allowed' },
          USERS: { view: 'allowed' },
        },
        scopes: [{ type: 'site', allowedValues: ['AG_HN', 'AG_HCM'], description: 'Áp dụng cho các chi nhánh Hà Nội & TP.HCM' }],
      },
      {
        versionNumber: 1.4,
        createdTime: '2026-05-10 11:20:00',
        createdBy: 'admin_cic',
        status: 'active',
        changeNote: 'Phiên bản đang phát hành sử dụng thực tế',
        matrix: {
          PRODUCTS: { view: 'allowed', create: 'allowed', edit: 'allowed', publish: 'conditional', export: 'allowed' },
          NEWS: { view: 'allowed', create: 'allowed', edit: 'allowed', publish: 'conditional' },
          BANNERS: { view: 'allowed', create: 'allowed', edit: 'allowed' },
          USERS: { view: 'allowed' },
        },
        scopes: [{ type: 'site', allowedValues: ['AG_HN', 'AG_HCM'], description: 'Áp dụng chi nhánh Hà Nội & TP.HCM' }],
      },
    ],
    matrix: {
      PRODUCTS: { view: 'allowed', create: 'allowed', edit: 'allowed', publish: 'conditional', export: 'allowed' },
      NEWS: { view: 'allowed', create: 'allowed', edit: 'allowed', publish: 'conditional' },
      BANNERS: { view: 'allowed', create: 'allowed', edit: 'allowed' },
      USERS: { view: 'allowed' },
    },
    scopes: [{ type: 'site', allowedValues: ['AG_HN', 'AG_HCM'], description: 'Chi nhánh Hà Nội & TP.HCM' }],
    assignedUsersCount: 8,
    assignedGroupCount: 2,
    reviewDueDays: 14,
    conflictIssuesCount: 0,
    updatedTime: '2026-05-10 11:20:00',
    updatedBy: 'admin_cic',
  },
  {
    id: 'role_south_editor',
    name: 'Chi nhánh Miền Nam - Editor',
    category: 'custom',
    riskLevel: 'standard',
    status: 'active',
    purpose: 'Dành riêng cho chuyên viên nội dung khu vực phía Nam (Văn phòng TP. Hồ Chí Minh)',
    description: 'Giới hạn phạm vi dữ liệu bài viết và sản phẩm thuộc Chi nhánh Miền Nam',
    owner: 'Trưởng chi nhánh TP.HCM',
    reviewer: 'Security Lead',
    activeVersion: 1.0,
    versions: [
      {
        versionNumber: 1.0,
        createdTime: '2026-04-05 16:45:00',
        createdBy: 'admin_cic',
        status: 'active',
        changeNote: 'Tạo vai trò tùy chỉnh cho Chi nhánh TP.HCM',
        matrix: {
          PRODUCTS: { view: 'allowed', create: 'allowed', edit: 'conditional' },
          NEWS: { view: 'allowed', create: 'allowed', edit: 'allowed', publish: 'conditional' },
          BANNERS: { view: 'allowed', create: 'allowed', edit: 'allowed', publish: 'allowed' },
        },
        scopes: [{ type: 'site', allowedValues: ['AG_HCM'], description: 'Chi nhánh TP.HCM (AG_HCM)' }],
      },
    ],
    matrix: {
      PRODUCTS: { view: 'allowed', create: 'allowed', edit: 'conditional' },
      NEWS: { view: 'allowed', create: 'allowed', edit: 'allowed', publish: 'conditional' },
      BANNERS: { view: 'allowed', create: 'allowed', edit: 'allowed', publish: 'allowed' },
    },
    scopes: [{ type: 'site', allowedValues: ['AG_HCM'], description: 'Chi nhánh TP.HCM (AG_HCM)' }],
    assignedUsersCount: 4,
    assignedGroupCount: 1,
    reviewDueDays: 30,
    conflictIssuesCount: 1,
    updatedTime: '2026-04-05 16:45:00',
    updatedBy: 'admin_cic',
  },
  {
    id: 'role_sales_pricing_mgr',
    name: 'Kinh doanh Báo giá Manager',
    category: 'custom',
    riskLevel: 'elevated',
    status: 'draft',
    purpose: 'Cấu hình giá niêm yết, chính sách chiết khấu và báo giá dự án phần mềm',
    description: 'Chuyên viên được phép xem và chỉnh sửa thông tin giá bán sản phẩm',
    owner: 'Giám đốc Kinh doanh',
    reviewer: 'Audit Officer',
    activeVersion: 1.0,
    draftVersion: 1.1,
    versions: [
      {
        versionNumber: 1.1,
        createdTime: '2026-08-02 11:00:00',
        createdBy: 'phuong_kinhdoanh',
        status: 'draft',
        changeNote: 'Dự thảo nâng cấp quyền xuất bản chính sách báo giá đặc thù',
        matrix: {
          PRODUCTS: { view: 'allowed', edit: 'allowed', publish: 'allowed', export: 'allowed' },
          NEWS: { view: 'allowed' },
          USERS: { view: 'allowed' },
        },
        scopes: [{ type: 'team', allowedValues: ['SALES_TEAM'], description: 'Phòng Kinh doanh & Dự án' }],
      },
      {
        versionNumber: 1.0,
        createdTime: '2026-03-20 10:00:00',
        createdBy: 'admin_cic',
        status: 'active',
        changeNote: 'Tạo vai trò ban đầu',
        matrix: {
          PRODUCTS: { view: 'allowed', edit: 'conditional', export: 'allowed' },
          NEWS: { view: 'allowed' },
        },
        scopes: [{ type: 'team', allowedValues: ['SALES_TEAM'], description: 'Phòng Kinh doanh' }],
      },
    ],
    matrix: {
      PRODUCTS: { view: 'allowed', edit: 'allowed', publish: 'allowed', export: 'allowed' },
      NEWS: { view: 'allowed' },
      USERS: { view: 'allowed' },
    },
    scopes: [{ type: 'team', allowedValues: ['SALES_TEAM'], description: 'Phòng Kinh doanh' }],
    assignedUsersCount: 3,
    assignedGroupCount: 1,
    conflictIssuesCount: 0,
    updatedTime: '2026-08-02 11:00:00',
    updatedBy: 'phuong_kinhdoanh',
  },
  {
    id: 'role_external_auditor',
    name: 'Auditor Độc lập (Chỉ xem)',
    category: 'custom',
    riskLevel: 'elevated',
    status: 'active',
    purpose: 'Dành cho đối tác kiểm toán độc lập tra cứu nhật ký audit và phân quyền hệ thống',
    description: 'Quyền xem duy nhất (Read-only) và xuất báo cáo kiểm toán, không có quyền tạo/sửa/xóa',
    owner: 'Ban Kiểm soát CIC',
    reviewer: 'Security Lead',
    activeVersion: 1.0,
    versions: [
      {
        versionNumber: 1.0,
        createdTime: '2026-02-15 15:30:00',
        createdBy: 'admin_cic',
        status: 'active',
        changeNote: 'Khởi tạo vai trò độc lập kiểm toán',
        matrix: {
          PRODUCTS: { view: 'allowed', export: 'allowed' },
          USERS: { view: 'allowed', export: 'allowed' },
          NEWS: { view: 'allowed', export: 'allowed' },
          SETTINGS: { view: 'allowed', export: 'allowed' },
          ROLES: { view: 'allowed', export: 'allowed' },
        },
        scopes: [{ type: 'global', allowedValues: ['ALL'], description: 'Toàn bộ dữ liệu hệ thống (Chỉ xem)' }],
      },
    ],
    matrix: {
      PRODUCTS: { view: 'allowed', export: 'allowed' },
      USERS: { view: 'allowed', export: 'allowed' },
      NEWS: { view: 'allowed', export: 'allowed' },
      SETTINGS: { view: 'allowed', export: 'allowed' },
      ROLES: { view: 'allowed', export: 'allowed' },
    },
    scopes: [{ type: 'global', allowedValues: ['ALL'], description: 'Toàn bộ dữ liệu hệ thống (Chỉ xem)' }],
    assignedUsersCount: 1,
    assignedGroupCount: 0,
    reviewDueDays: 45,
    conflictIssuesCount: 0,
    updatedTime: '2026-02-15 15:30:00',
    updatedBy: 'admin_cic',
  },
  {
    id: 'role_event_temp_2026',
    name: 'Role Tạm thời Sự kiện Tech 2026',
    category: 'custom',
    riskLevel: 'standard',
    status: 'archived',
    purpose: 'Vai trò tạm thời cấp cho cộng tác viên hội thảo công nghệ tháng 5/2026',
    description: 'Đã ngừng sử dụng và đưa vào lưu trữ (Archived) sau khi sự kiện kết thúc',
    owner: 'Phòng Truyền thông',
    reviewer: 'Security Lead',
    activeVersion: 1.0,
    versions: [
      {
        versionNumber: 1.0,
        createdTime: '2026-05-01 08:00:00',
        createdBy: 'admin_cic',
        status: 'superseded',
        changeNote: 'Lưu trữ vai trò do hết hạn sự kiện',
        matrix: {
          NEWS: { view: 'allowed', create: 'allowed' },
        },
        scopes: [{ type: 'ownership', allowedValues: ['SELF_ONLY'], description: 'Chỉ nội dung do chính tài khoản tạo' }],
      },
    ],
    matrix: {
      NEWS: { view: 'allowed', create: 'allowed' },
    },
    scopes: [{ type: 'ownership', allowedValues: ['SELF_ONLY'], description: 'Chỉ nội dung bản thân tạo' }],
    assignedUsersCount: 0,
    assignedGroupCount: 0,
    conflictIssuesCount: 0,
    updatedTime: '2026-05-31 18:00:00',
    updatedBy: 'admin_cic',
  },
];

export const roleAssignmentsMock: RoleAssignment[] = [
  {
    id: 'asg_001',
    userId: 'usr_001',
    username: 'admin_cic',
    userFullName: 'Nguyễn Văn Quản Trị',
    userEmail: 'admin@cic.com.vn',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    roleId: 'role_super_admin',
    roleName: 'Super Administrator',
    scopeSummary: 'Global System Scope',
    assignedAt: '2026-01-01 00:00:00',
    assignedBy: 'System Bootstrap',
  },
  {
    id: 'asg_002',
    userId: 'usr_002',
    username: 'minh_bien',
    userFullName: 'Trần Biên Minh',
    userEmail: 'minh.bien@cic.com.vn',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    roleId: 'role_content_editor',
    roleName: 'Content Manager / Editor',
    scopeSummary: 'Site: Chi nhánh Hà Nội & TP.HCM',
    assignedAt: '2026-02-10 09:30:00',
    assignedBy: 'admin_cic',
  },
  {
    id: 'asg_003',
    userId: 'usr_003',
    username: 'hoang_kythuat',
    userFullName: 'Lê Huy Hoàng',
    userEmail: 'hoang.tech@cic.com.vn',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    roleId: 'role_sec_admin',
    roleName: 'Security & Access Admin',
    scopeSummary: 'Global System Scope',
    assignedAt: '2026-03-15 14:20:00',
    assignedBy: 'admin_cic',
  },
  {
    id: 'asg_004',
    userId: 'usr_004',
    username: 'phuong_kinhdoanh',
    userFullName: 'Phạm Mai Phương',
    userEmail: 'phuong.sales@cic.com.vn',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    roleId: 'role_sales_pricing_mgr',
    roleName: 'Kinh doanh Báo giá Manager',
    scopeSummary: 'Team: Phòng Kinh doanh',
    assignedAt: '2026-04-01 10:00:00',
    assignedBy: 'admin_cic',
  },
  {
    id: 'asg_005',
    userId: 'usr_002',
    username: 'minh_bien',
    userFullName: 'Trần Biên Minh',
    userEmail: 'minh.bien@cic.com.vn',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    roleId: 'role_south_editor',
    roleName: 'Chi nhánh Miền Nam - Editor',
    scopeSummary: 'Chi nhánh TP.HCM (AG_HCM)',
    assignedAt: '2026-04-12 11:15:00',
    assignedBy: 'admin_cic',
  },
  {
    id: 'asg_006',
    userId: 'usr_003',
    username: 'hoang_kythuat',
    userFullName: 'Lê Huy Hoàng',
    userEmail: 'hoang.tech@cic.com.vn',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    roleId: 'role_external_auditor',
    roleName: 'Auditor Độc lập (Chỉ xem)',
    scopeSummary: 'Toàn hệ thống (Chỉ xem)',
    assignedAt: '2026-05-18 16:45:00',
    assignedBy: 'admin_cic',
  },
  {
    id: 'asg_007',
    userId: 'usr_004',
    username: 'phuong_kinhdoanh',
    userFullName: 'Phạm Mai Phương',
    userEmail: 'phuong.sales@cic.com.vn',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    roleId: 'role_content_editor',
    roleName: 'Content Manager / Editor',
    scopeSummary: 'Site: Chi nhánh Hà Nội',
    assignedAt: '2026-06-01 08:30:00',
    assignedBy: 'admin_cic',
  },
];

export const policyIssuesMock: PolicyIssue[] = [
  {
    id: 'iss_002',
    roleId: 'role_south_editor',
    roleName: 'Chi nhánh Miền Nam - Editor',
    severity: 'medium',
    type: 'overbroad',
    title: 'Phạm vi quyền hạn quá rộng (Overbroad Scope)',
    description: 'Vai trò dành cho chi nhánh nhưng lại có quyền Quản lý & Đăng xuất bản Banners trên phạm vi Toàn hệ thống (Global).',
    recommendation: 'Siết chặt Scope module BANNERS về chi nhánh TP.HCM (AG_HCM) để tránh đè giao diện chi nhánh khác.',
    detectedAt: '2026-07-28 09:12:00',
  },
];

export const accessReviewsMock: AccessReview[] = [
  {
    id: 'rev_001',
    roleId: 'role_south_editor',
    roleName: 'Chi nhánh Miền Nam - Editor',
    targetUserId: 'usr_002',
    targetUserName: 'Trần Biên Minh',
    reviewer: 'Security Lead',
    dueDate: '2026-07-29',
    status: 'pending',
    notes: 'Cần xác nhận lại danh sách chi nhánh phụ trách thuộc khu vực Miền Nam',
  },
  {
    id: 'rev_002',
    roleId: 'role_external_auditor',
    roleName: 'Auditor Độc lập (Chỉ xem)',
    targetUserId: 'usr_003',
    targetUserName: 'Lê Huy Hoàng',
    reviewer: 'Super Administrator',
    dueDate: '2026-07-20',
    status: 'pending',
    notes: 'Rà soát xem có cần thu hồi quyền Export báo cáo kiểm toán hệ thống không',
  },
  {
    id: 'rev_003',
    roleId: 'role_content_editor',
    roleName: 'Content Manager / Editor',
    targetUserId: 'usr_002',
    targetUserName: 'Trần Biên Minh',
    reviewer: 'Content Lead',
    dueDate: '2026-08-15',
    status: 'confirmed',
    notes: 'Đã hoàn tất rà soát định kỳ quý 3/2026, thông tin khớp đúng',
  },
];
