import React, { useState } from 'react';
import { Check, Shield, X } from 'lucide-react';
import type { CmsRole, MatrixAction, ModulePermissionMatrix, PermissionTask } from './types';
import { CmsButton } from '../../components/ui/CmsButton';

interface Props { isOpen: boolean; onClose: () => void; onSaveRole: (role: CmsRole, activateImmediately: boolean) => void | Promise<void>; roleToEdit: CmsRole | null; existingRoles: CmsRole[]; permissionTasks: PermissionTask[]; isSaving?: boolean }
const actions: { code: MatrixAction; label: string }[] = [{ code: 'view', label: 'Xem' }, { code: 'create', label: 'Tạo' }, { code: 'edit', label: 'Sửa' }, { code: 'publish', label: 'Xuất bản' }, { code: 'delete', label: 'Xóa' }, { code: 'export', label: 'Xuất' }, { code: 'configure', label: 'Cấu hình' }];

export const RoleEditorModal: React.FC<Props> = ({ isOpen, onClose, onSaveRole, roleToEdit, existingRoles, permissionTasks, isSaving = false }) => {
  const [name, setName] = useState(roleToEdit?.name ?? ''); const [description, setDescription] = useState(roleToEdit?.description ?? '');
  const [matrix, setMatrix] = useState<ModulePermissionMatrix>(roleToEdit?.matrix ?? {}); const [error, setError] = useState('');
  const modules = [...new Set(permissionTasks.map((task) => task.module.trim().toUpperCase()).filter(Boolean))];
  const toggle = (module: string, action: MatrixAction) => setMatrix((current) => ({ ...current, [module]: { ...current[module], [action]: current[module]?.[action] === 'allowed' ? 'denied' : 'allowed' } }));
  const save = () => {
    const trimmed = name.trim();
    if (trimmed.length < 2 || trimmed.length > 255) { setError('Tên vai trò phải có từ 2 đến 255 ký tự.'); return; }
    if (existingRoles.some((role) => role.id !== roleToEdit?.id && role.name.trim().toLowerCase() === trimmed.toLowerCase())) { setError('Tên vai trò đã tồn tại.'); return; }
    const now = new Date().toISOString();
    void onSaveRole({ id: roleToEdit?.id ?? `new_${Date.now()}`, name: trimmed, category: roleToEdit?.category ?? 'custom', riskLevel: roleToEdit?.riskLevel ?? 'standard', status: roleToEdit?.status ?? 'active', purpose: roleToEdit?.purpose ?? trimmed, description: description.trim(), owner: roleToEdit?.owner ?? 'Quản trị hệ thống', reviewer: roleToEdit?.reviewer ?? 'Quản trị hệ thống', activeVersion: 1, versions: roleToEdit?.versions ?? [], matrix, assignedUsersCount: roleToEdit?.assignedUsersCount ?? 0, assignedGroupCount: 0, conflictIssuesCount: 0, updatedTime: now, updatedBy: 'Hiện tại' }, true);
  };
  if (!isOpen) return null;
  return <div className="fixed inset-0 z-50 flex items-center justify-center overflow-y-auto bg-slate-950/60 p-3 sm:p-5" role="dialog" aria-modal="true" aria-labelledby="role-editor-title">
    <div className="my-auto flex max-h-[92vh] w-full max-w-5xl flex-col overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl dark:border-slate-800 dark:bg-slate-900">
      <header className="flex items-center justify-between border-b border-slate-200 px-5 py-4 dark:border-slate-800"><div className="flex min-w-0 items-center gap-3"><span className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-orange-50 text-orange-600 dark:bg-orange-950/40"><Shield className="size-5" /></span><div className="min-w-0"><h2 id="role-editor-title" className="font-bold text-slate-950 dark:text-white">{roleToEdit ? 'Chỉnh sửa vai trò' : 'Thêm vai trò'}</h2><p className="text-xs text-slate-500 dark:text-slate-400">Chọn thao tác được phép theo danh mục quyền PostgreSQL.</p></div></div><button type="button" onClick={onClose} disabled={isSaving} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800" aria-label="Đóng"><X className="size-5" /></button></header>
      <div className="overflow-y-auto p-5 sm:p-6"><div className="grid gap-4 sm:grid-cols-2"><label className="space-y-1.5 text-xs font-semibold text-slate-700 dark:text-slate-300"><span>Tên vai trò *</span><input value={name} maxLength={255} onChange={(event) => { setName(event.target.value); setError(''); }} className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-950 outline-none focus:border-orange-500 dark:border-slate-700 dark:bg-slate-950 dark:text-white" /></label><label className="space-y-1.5 text-xs font-semibold text-slate-700 dark:text-slate-300"><span>Mô tả</span><input value={description} maxLength={5000} onChange={(event) => setDescription(event.target.value)} className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-950 outline-none focus:border-orange-500 dark:border-slate-700 dark:bg-slate-950 dark:text-white" /></label></div>{error && <p role="alert" className="mt-2 text-xs font-semibold text-red-600">{error}</p>}
        <section className="mt-6"><h3 className="text-sm font-bold text-slate-950 dark:text-white">Quyền theo phân hệ</h3><p className="mb-3 mt-1 text-xs text-slate-500">Ô trống nghĩa là không được phép. Các phân hệ lấy từ danh mục task đang hoạt động.</p>{modules.length ? <div className="overflow-x-auto rounded-xl border border-slate-200 dark:border-slate-800"><table className="w-full min-w-[760px] text-left text-xs"><thead className="bg-slate-50 text-slate-500 dark:bg-slate-800/70"><tr><th className="px-4 py-3">Phân hệ</th>{actions.map((action) => <th key={action.code} className="px-3 py-3 text-center">{action.label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{modules.map((module) => <tr key={module}><th className="px-4 py-3 font-semibold text-slate-800 dark:text-slate-200">{module}</th>{actions.map((action) => { const checked = matrix[module]?.[action.code] === 'allowed'; return <td key={action.code} className="px-3 py-3 text-center"><button type="button" disabled={isSaving} onClick={() => toggle(module, action.code)} aria-pressed={checked} aria-label={`${action.label} ${module}`} className={`inline-flex size-7 items-center justify-center rounded-md border transition-colors ${checked ? 'border-orange-600 bg-orange-600 text-white' : 'border-slate-300 bg-white text-transparent hover:border-orange-400 dark:border-slate-700 dark:bg-slate-950'}`}>{checked && <Check className="size-4" />}</button></td>; })}</tr>)}</tbody></table></div> : <div className="rounded-xl border border-slate-200 p-5 text-sm text-slate-500">Chưa có task quyền đang hoạt động.</div>}</section>
      </div><footer className="flex justify-end gap-2 border-t border-slate-200 px-5 py-4 dark:border-slate-800"><CmsButton variant="secondary" size="sm" onClick={onClose} disabled={isSaving}>Hủy</CmsButton><CmsButton size="sm" onClick={save} disabled={isSaving}>{isSaving ? 'Đang lưu...' : 'Lưu vai trò'}</CmsButton></footer>
    </div>
  </div>;
};
