import { MenuGroup, MenuItem, ValidationIssue, MenuVersion, DiffChange, MenuActivityLog } from './types';

export const mockMenuGroups: MenuGroup[] = [
  {
    id: 'grp_header_main',
    code: 'NAV-HEADER-MAIN',
    name: 'Menu Chính Trang Chủ (Header Navigation)',
    site: 'cic.com.vn',
    locale: 'vi',
    position_code: 'main_header',
    max_depth: 3,
    live_version: 'v2.1.0',
    draft_version: 'v2.2.0-draft',
    editorial_status: 'draft',
    has_draft_changes: true,
    item_count: 24,
    issue_count: 2,
    updated_at: '2026-08-03 16:45:10',
    updated_by: 'Trần Văn Mạnh (Admin)',
  },
  {
    id: 'grp_footer_links',
    code: 'NAV-FOOTER-LINKS',
    name: 'Liên Kết Chân Trang (Footer Quick Links)',
    site: 'cic.com.vn',
    locale: 'vi',
    position_code: 'footer_links',
    max_depth: 2,
    live_version: 'v1.5.0',
    draft_version: 'v1.5.0',
    editorial_status: 'published',
    has_draft_changes: false,
    item_count: 18,
    issue_count: 0,
    updated_at: '2026-07-28 10:20:00',
    updated_by: 'Nguyễn Thị Bích (Editor)',
  },
  {
    id: 'grp_mobile_drawer',
    code: 'NAV-MOBILE-DRAWER',
    name: 'Menu Điều Hướng Di Động (Mobile Drawer)',
    site: 'cic.com.vn',
    locale: 'vi',
    position_code: 'mobile_drawer',
    max_depth: 2,
    live_version: 'v1.2.0',
    draft_version: 'v1.3.0-draft',
    editorial_status: 'draft',
    has_draft_changes: true,
    item_count: 12,
    issue_count: 1,
    updated_at: '2026-08-02 11:15:30',
    updated_by: 'Vũ Quốc Huy (Marketing)',
  },
  {
    id: 'grp_campaign_bim',
    code: 'NAV-CAMPAIGN-BIM2026',
    name: 'Menu Landing Page Chiến Dịch BIM ISO 19650',
    site: 'cic.com.vn',
    locale: 'vi',
 position_code: 'campaign_banner',
    max_depth: 1,
    live_version: 'v1.0.0',
    draft_version: 'v1.0.0',
    editorial_status: 'published',
    has_draft_changes: false,
    item_count: 7,
    issue_count: 0,
    updated_at: '2026-07-20 09:00:00',
    updated_by: 'Trần Văn Mạnh (Admin)',
  },
];

export const mockMenuItems: MenuItem[] = [
  // LEVEL 1: TRANG CHỦ
  {
    id: 'item_01',
    group_id: 'grp_header_main',
    parent_id: null,
    depth: 0,
    display_order: 1,
    label: 'Trang chủ',
    target_type: 'static_page',
    target_content_id: 'page_home',
    target_content_name: 'Trang chủ (Homepage)',
    url: '/',
    open_in_new_tab: false,
    icon_name: 'Home',
    is_visible: true,
    visibility_rule: 'all',
    link_health: 'valid',
    draft_status: 'unchanged',
  },

  // LEVEL 1: GIỚI THIỆU
  {
    id: 'item_02',
    group_id: 'grp_header_main',
    parent_id: null,
    depth: 0,
    display_order: 2,
    label: 'Giới thiệu',
    target_type: 'static_page',
    target_content_id: 'page_about',
    target_content_name: 'Giới thiệu về CIC',
    url: '/gioi-thieu',
    open_in_new_tab: false,
    icon_name: 'Building2',
    is_visible: true,
    visibility_rule: 'all',
    link_health: 'valid',
    draft_status: 'unchanged',
    children: [
      {
        id: 'item_02_1',
        group_id: 'grp_header_main',
        parent_id: 'item_02',
        depth: 1,
        display_order: 1,
        label: 'Về CIC Technology',
        target_type: 'static_page',
        url: '/gioi-thieu/ve-cic',
        open_in_new_tab: false,
        is_visible: true,
        visibility_rule: 'all',
        link_health: 'valid',
        draft_status: 'unchanged',
      },
      {
        id: 'item_02_2',
        group_id: 'grp_header_main',
        parent_id: 'item_02',
        depth: 1,
        display_order: 2,
        label: 'Lịch sử phát triển & Cột mốc 35 năm',
        target_type: 'static_page',
        url: '/gioi-thieu/lich-su',
        open_in_new_tab: false,
        is_visible: true,
        visibility_rule: 'all',
        link_health: 'valid',
        draft_status: 'unchanged',
      },
      {
        id: 'item_02_3',
        group_id: 'grp_header_main',
        parent_id: 'item_02',
        depth: 1,
        display_order: 3,
        label: 'Ban lãnh đạo & Đội ngũ chuyên gia',
        target_type: 'static_page',
        url: '/gioi-thieu/ban-lanh-dao',
        open_in_new_tab: false,
        is_visible: true,
        visibility_rule: 'all',
        link_health: 'valid',
        draft_status: 'unchanged',
      },
      {
        id: 'item_02_4',
        group_id: 'grp_header_main',
        parent_id: 'item_02',
        depth: 1,
        display_order: 4,
        label: 'Đối tác & Hãng phần mềm quốc tế',
        target_type: 'static_page',
        url: '/gioi-thieu/doi-tac',
        open_in_new_tab: false,
        is_visible: true,
        visibility_rule: 'all',
        link_health: 'valid',
        draft_status: 'added',
      },
    ],
  },

  // LEVEL 1: SẢN PHẨM & PHẦN MỀM (MEGA MENU)
  {
    id: 'item_03',
    group_id: 'grp_header_main',
    parent_id: null,
    depth: 0,
    display_order: 3,
    label: 'Sản phẩm & Giải pháp',
    target_type: 'product_catalog',
    target_content_name: 'Danh mục Sản phẩm Phần mềm Bản quyền',
    url: '/san-pham',
    open_in_new_tab: false,
    icon_name: 'Package',
    is_visible: true,
    visibility_rule: 'all',
    link_health: 'valid',
    draft_status: 'modified',
    children: [
      {
        id: 'item_03_1',
        group_id: 'grp_header_main',
        parent_id: 'item_03',
        depth: 1,
        display_order: 1,
        label: 'Phần mềm Kết cấu & Địa kỹ thuật',
        target_type: 'section_header',
        url: '/san-pham/ket-cau',
        open_in_new_tab: false,
        is_visible: true,
        visibility_rule: 'all',
        link_health: 'valid',
        draft_status: 'unchanged',
        children: [
          {
            id: 'item_03_1_1',
            group_id: 'grp_header_main',
            parent_id: 'item_03_1',
            depth: 2,
            display_order: 1,
            label: 'CSI ETABS Ultimate v21',
            target_type: 'product_catalog',
            target_content_id: 'prod_etabs',
            url: '/san-pham/csi-etabs-ultimate-v21',
            open_in_new_tab: false,
            is_visible: true,
            visibility_rule: 'all',
            link_health: 'valid',
            draft_status: 'unchanged',
          },
          {
            id: 'item_03_1_2',
            group_id: 'grp_header_main',
            parent_id: 'item_03_1',
            depth: 2,
            display_order: 2,
            label: 'CSI SAP2000 Advanced v25',
            target_type: 'product_catalog',
            target_content_id: 'prod_sap2000',
            url: '/san-pham/csi-sap2000-v25',
            open_in_new_tab: false,
            is_visible: true,
            visibility_rule: 'all',
            link_health: 'valid',
            draft_status: 'unchanged',
          },
          {
            id: 'item_03_1_3',
            group_id: 'grp_header_main',
            parent_id: 'item_03_1',
            depth: 2,
            display_order: 3,
            label: 'PLAXIS 3D Ultimate 2026',
            target_type: 'product_catalog',
            target_content_id: 'prod_plaxis',
            url: '/san-pham/plaxis-3d-ultimate-2026',
            open_in_new_tab: false,
            is_visible: true,
            visibility_rule: 'all',
            link_health: 'warning',
            link_health_message: 'Sản phẩm mới cập nhật giá, kiểm tra link canonical',
            draft_status: 'modified',
          },
        ],
      },
      {
        id: 'item_03_2',
        group_id: 'grp_header_main',
        parent_id: 'item_03',
        depth: 1,
        display_order: 2,
        label: 'Phần mềm Thiết kế CAD 2D/3D',
        target_type: 'section_header',
        url: '/san-pham/cad',
        open_in_new_tab: false,
        is_visible: true,
        visibility_rule: 'all',
        link_health: 'valid',
        draft_status: 'unchanged',
        children: [
          {
            id: 'item_03_2_1',
            group_id: 'grp_header_main',
            parent_id: 'item_03_2',
            depth: 2,
            display_order: 1,
            label: 'EnjiCAD Network Enterprise v2.5',
            target_type: 'product_catalog',
            target_content_id: 'prod_enjicad',
            url: '/san-pham/enjicad-network-enterprise-v25',
            open_in_new_tab: false,
            is_visible: true,
            visibility_rule: 'all',
            link_health: 'valid',
            draft_status: 'unchanged',
          },
          {
            id: 'item_03_2_2',
            group_id: 'grp_header_main',
            parent_id: 'item_03_2',
            depth: 2,
            display_order: 2,
            label: 'ZwCAD Pro 2026 Permanent',
            target_type: 'product_catalog',
            target_content_id: 'prod_zwcad',
            url: '/san-pham/zwcad-pro-2026',
            open_in_new_tab: false,
            is_visible: true,
            visibility_rule: 'all',
            link_health: 'valid',
            draft_status: 'added',
          },
        ],
      },
      {
        id: 'item_03_3',
        group_id: 'grp_header_main',
        parent_id: 'item_03',
        depth: 1,
        display_order: 3,
        label: 'Dự toán & Quản lý Chi phí Xây dựng',
        target_type: 'section_header',
        url: '/san-pham/du-toan',
        open_in_new_tab: false,
        is_visible: true,
        visibility_rule: 'all',
        link_health: 'valid',
        draft_status: 'unchanged',
        children: [
          {
            id: 'item_03_3_1',
            group_id: 'grp_header_main',
            parent_id: 'item_03_3',
            depth: 2,
            display_order: 1,
            label: 'Phần mềm Dự toán ESCON 2026',
            target_type: 'product_catalog',
            target_content_id: 'prod_escon',
            url: '/san-pham/du-toan-escon-2026',
            open_in_new_tab: false,
            is_visible: true,
            visibility_rule: 'all',
            link_health: 'valid',
            draft_status: 'unchanged',
          },
        ],
      },
    ],
  },

  // LEVEL 1: DỊCH VỤ & TƯ VẤN (DRAFT MOVED)
  {
    id: 'item_04',
    group_id: 'grp_header_main',
    parent_id: null,
    depth: 0,
    display_order: 4,
    label: 'Dịch vụ & Tư vấn BIM',
    target_type: 'service_catalog',
    target_content_name: 'Catalog Dịch vụ Chuyển đổi số & BIM',
    url: '/dich-vu',
    open_in_new_tab: false,
    icon_name: 'Layers',
    is_visible: true,
    visibility_rule: 'all',
    link_health: 'valid',
    draft_status: 'moved',
    children: [
      {
        id: 'item_04_1',
        group_id: 'grp_header_main',
        parent_id: 'item_04',
        depth: 1,
        display_order: 1,
        label: 'Tư vấn Lộ trình Chuyển đổi số BIM ISO 19650',
        target_type: 'service_catalog',
        target_content_id: 'srv_bim_iso',
        url: '/dich-vu/tu-van-lo-trinh-chuyen-doi-so-bim-iso-19650',
        open_in_new_tab: false,
        is_visible: true,
        visibility_rule: 'all',
        link_health: 'valid',
        draft_status: 'unchanged',
      },
      {
        id: 'item_04_2',
        group_id: 'grp_header_main',
        parent_id: 'item_04',
        depth: 1,
        display_order: 2,
        label: 'Đào tạo Chuyên sâu & Cấp chứng chỉ Chuyên gia BIM',
        target_type: 'service_catalog',
        target_content_id: 'srv_bim_training',
        url: '/dich-vu/dao-tao-chuyen-sau-cap-chung-chi-chuyen-gia-bim',
        open_in_new_tab: false,
        is_visible: true,
        visibility_rule: 'all',
        link_health: 'valid',
        draft_status: 'unchanged',
      },
      {
        id: 'item_04_3',
        group_id: 'grp_header_main',
        parent_id: 'item_04',
        depth: 1,
        display_order: 3,
        label: 'Thẩm tra & Đánh giá An toàn Kết cấu Công trình',
        target_type: 'service_catalog',
        target_content_id: 'srv_structural_review',
        url: '/dich-vu/tham-tra-danh-gia-an-toan-ket-cau-cong-trinh',
        open_in_new_tab: false,
        is_visible: true,
        visibility_rule: 'all',
        link_health: 'valid',
        draft_status: 'unchanged',
      },
    ],
  },

  // LEVEL 1: TIN TỨC & DỰ ÁN
  {
    id: 'item_05',
    group_id: 'grp_header_main',
    parent_id: null,
    depth: 0,
    display_order: 5,
    label: 'Tin tức & Dự án',
    target_type: 'news_category',
    url: '/tin-tuc',
    open_in_new_tab: false,
    icon_name: 'Newspaper',
    is_visible: true,
    visibility_rule: 'all',
    link_health: 'valid',
    draft_status: 'unchanged',
    children: [
      {
        id: 'item_05_1',
        group_id: 'grp_header_main',
        parent_id: 'item_05',
        depth: 1,
        display_order: 1,
        label: 'Tin công nghệ Xây dựng',
        target_type: 'news_category',
        url: '/tin-tuc/cong-nghe-xay-dung',
        open_in_new_tab: false,
        is_visible: true,
        visibility_rule: 'all',
        link_health: 'valid',
        draft_status: 'unchanged',
      },
      {
        id: 'item_05_2',
        group_id: 'grp_header_main',
        parent_id: 'item_05',
        depth: 1,
        display_order: 2,
        label: 'Dự án Tiêu biểu ứng dụng phần mềm',
        target_type: 'news_category',
        url: '/tin-tuc/du-an-tieu-bieu-old-path',
        open_in_new_tab: false,
        is_visible: true,
        visibility_rule: 'all',
        link_health: 'broken',
        link_health_message: '404 Not Found - Đường dẫn cũ chưa cập nhật slug mới (/tin-tuc/du-an-tieu-bieu)',
        draft_status: 'modified',
      },
    ],
  },

  // LEVEL 1: LIÊN HỆ
  {
    id: 'item_06',
    group_id: 'grp_header_main',
    parent_id: null,
    depth: 0,
    display_order: 6,
    label: 'Liên hệ & Báo giá',
    target_type: 'static_page',
    url: '/lien-he',
    open_in_new_tab: false,
    icon_name: 'PhoneCall',
    is_visible: true,
    visibility_rule: 'all',
    link_health: 'valid',
    draft_status: 'unchanged',
  },
];

export const mockValidationIssues: ValidationIssue[] = [
  {
    id: 'issue_101',
    item_id: 'item_05_2',
    item_label: 'Dự án Tiêu biểu ứng dụng phần mềm',
    severity: 'critical',
    code: 'broken_link',
    message: 'Lỗi liên kết Broken Link (404 Not Found): Đường dẫn /tin-tuc/du-an-tieu-bieu-old-path không tồn tại.',
    suggested_action: 'Cập nhật lại đường dẫn chuẩn sang "/tin-tuc/du-an-tieu-bieu" hoặc chọn danh mục tin tức từ bộ chọn.',
  },
];

export const mockMenuVersions: MenuVersion[] = [
  {
    version_id: 'ver_202',
    version_number: 2.2,
    group_id: 'grp_header_main',
    published_at: '2026-08-04 00:15:00 (Bản thảo Working Draft)',
    published_by: 'Trần Văn Mạnh (Admin)',
    change_summary: 'Thêm mục ZwCAD Pro 2026, cập nhật vị trí Dịch vụ BIM & điều chỉnh nhãn.',
    item_count: 24,
    is_current_live: false,
  },
  {
    version_id: 'ver_201',
    version_number: 2.1,
    group_id: 'grp_header_main',
    published_at: '2026-07-25 14:30:00 (Đang phát hành Live)',
    published_by: 'Nguyễn Thị Bích (Content Manager)',
    change_summary: 'Bổ sung danh mục Phần mềm Kết cấu & Địa kỹ thuật, cập nhật link tư vấn BIM.',
    item_count: 22,
    is_current_live: true,
  },
  {
    version_id: 'ver_200',
    version_number: 2.0,
    group_id: 'grp_header_main',
    published_at: '2026-06-15 09:10:00',
    published_by: 'Trần Văn Mạnh (Admin)',
    change_summary: 'Tái cấu trúc toàn bộ Header Menu chuẩn SEO ISO 19650.',
    item_count: 20,
    is_current_live: false,
  },
];

export const mockDiffChanges: DiffChange[] = [
  {
    id: 'diff_01',
    item_id: 'item_02_4',
    label: 'Đối tác & Hãng phần mềm quốc tế',
    change_type: 'added',
    new_path: 'Giới thiệu > Đối tác & Hãng phần mềm quốc tế',
    details: 'Mục mới tạo thêm thuộc nhóm Giới thiệu.',
  },
  {
    id: 'diff_02',
    item_id: 'item_03_2_2',
    label: 'ZwCAD Pro 2026 Permanent',
    change_type: 'added',
    new_path: 'Sản phẩm > Phần mềm CAD > ZwCAD Pro 2026 Permanent',
    details: 'Mục sản phẩm mới vừa được gắn vào menu phụ.',
  },
  {
    id: 'diff_03',
    item_id: 'item_04',
    label: 'Dịch vụ & Tư vấn BIM',
    change_type: 'moved',
    old_path: 'Vị trí thứ 3 (Trước Sản phẩm)',
    new_path: 'Vị trí thứ 4 (Sau Sản phẩm)',
    details: 'Di chuyển thứ tự hiển thị ưu tiên trên thanh Header Navigation.',
  },
  {
    id: 'diff_04',
    item_id: 'item_05_2',
    label: 'Dự án Tiêu biểu ứng dụng phần mềm',
    change_type: 'changed',
    old_path: 'Link: /tin-tuc/du-an',
    new_path: 'Link: /tin-tuc/du-an-tieu-bieu-old-path',
    details: 'Thay đổi đường dẫn liên kết tĩnh.',
  },
];

export const mockMenuActivityLogs: MenuActivityLog[] = [
  {
    id: 'log_m1',
    timestamp: '2026-08-03 16:45:10',
    user_name: 'Trần Văn Mạnh',
    user_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    action_type: 'add_item',
    description: 'Thêm mục menu con "ZwCAD Pro 2026 Permanent" vào danh mục Phần mềm CAD 2D/3D.',
  },
  {
    id: 'log_m2',
    timestamp: '2026-08-03 16:30:22',
    user_name: 'Trần Văn Mạnh',
    user_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    action_type: 'move_item',
    description: 'Thay đổi thứ tự hiển thị (Move Order) của mục "Dịch vụ & Tư vấn BIM" xuống vị trí thứ 4.',
  },
  {
    id: 'log_m3',
    timestamp: '2026-08-03 15:10:05',
    user_name: 'Nguyễn Thị Bích',
    user_avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    action_type: 'validate',
    description: 'Chạy kiểm tra tự động Link Health Checker: Phát hiện 1 lỗi Broken Link 404.',
  },
  {
    id: 'log_m4',
    timestamp: '2026-07-25 14:30:00',
    user_name: 'Nguyễn Thị Bích',
    user_avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    action_type: 'publish',
    description: 'Xuất bản (Publish) thành công phiên bản Live v2.1.0 cho Nhóm Menu Header chính.',
  },
];
