import { MenuGroup, MenuItem } from './types';

export const mockMenuGroups: MenuGroup[] = [
  {
    id: 'grp_header_main',
    name: 'Menu Chính Trang Chủ (Header Navigation)',
    published: true,
    ordering: 1,
  },
  {
    id: 'grp_footer_links',
    name: 'Liên Kết Chân Trang (Footer Quick Links)',
    published: true,
    ordering: 2,
  },
  {
    id: 'grp_mobile_drawer',
    name: 'Menu Điều Hướng Di Động (Mobile Drawer)',
    published: true,
    ordering: 3,
  },
  {
    id: 'grp_campaign_bim',
    name: 'Menu Landing Page Chiến Dịch BIM ISO 19650',
    published: true,
    ordering: 4,
  },
];

export const mockMenuItems: MenuItem[] = [
  // LEVEL 1: TRANG CHỦ
  {
    id: 'item_01',
    group_id: 'grp_header_main',
    parent_id: null,
    depth: 0,
    display_order: 1,
    label: 'Trang chủ',
    url: '/',
    open_in_new_tab: false,
    icon_name: 'Home',
    is_visible: true,
  },

  // LEVEL 1: GIỚI THIỆU
  {
    id: 'item_02',
    group_id: 'grp_header_main',
    parent_id: null,
    depth: 0,
    display_order: 2,
    label: 'Giới thiệu',
    url: '/gioi-thieu',
    open_in_new_tab: false,
    icon_name: 'Building2',
    is_visible: true,
    children: [
      {
        id: 'item_02_1',
        group_id: 'grp_header_main',
        parent_id: 'item_02',
        depth: 1,
        display_order: 1,
        label: 'Về CIC Technology',
        url: '/gioi-thieu/ve-cic',
        open_in_new_tab: false,
        is_visible: true,
      },
      {
        id: 'item_02_2',
        group_id: 'grp_header_main',
        parent_id: 'item_02',
        depth: 1,
        display_order: 2,
        label: 'Lịch sử phát triển & Cột mốc 35 năm',
        url: '/gioi-thieu/lich-su',
        open_in_new_tab: false,
        is_visible: true,
      },
      {
        id: 'item_02_3',
        group_id: 'grp_header_main',
        parent_id: 'item_02',
        depth: 1,
        display_order: 3,
        label: 'Ban lãnh đạo & Đội ngũ chuyên gia',
        url: '/gioi-thieu/ban-lanh-dao',
        open_in_new_tab: false,
        is_visible: true,
      },
      {
        id: 'item_02_4',
        group_id: 'grp_header_main',
        parent_id: 'item_02',
        depth: 1,
        display_order: 4,
        label: 'Đối tác & Hãng phần mềm quốc tế',
        url: '/gioi-thieu/doi-tac',
        open_in_new_tab: false,
        is_visible: true,
      },
    ],
  },

  // LEVEL 1: SẢN PHẨM & PHẦN MỀM (MEGA MENU)
  {
    id: 'item_03',
    group_id: 'grp_header_main',
    parent_id: null,
    depth: 0,
    display_order: 3,
    label: 'Sản phẩm & Giải pháp',
    url: '/san-pham',
    open_in_new_tab: false,
    icon_name: 'Package',
    is_visible: true,
    children: [
      {
        id: 'item_03_1',
        group_id: 'grp_header_main',
        parent_id: 'item_03',
        depth: 1,
        display_order: 1,
        label: 'Phần mềm Kết cấu & Địa kỹ thuật',
        url: '/san-pham/ket-cau',
        open_in_new_tab: false,
        is_visible: true,
        children: [
          {
            id: 'item_03_1_1',
            group_id: 'grp_header_main',
            parent_id: 'item_03_1',
            depth: 2,
            display_order: 1,
            label: 'CSI ETABS Ultimate v21',
            url: '/san-pham/csi-etabs-ultimate-v21',
            open_in_new_tab: false,
            is_visible: true,
          },
          {
            id: 'item_03_1_2',
            group_id: 'grp_header_main',
            parent_id: 'item_03_1',
            depth: 2,
            display_order: 2,
            label: 'CSI SAP2000 Advanced v25',
            url: '/san-pham/csi-sap2000-v25',
            open_in_new_tab: false,
            is_visible: true,
          },
          {
            id: 'item_03_1_3',
            group_id: 'grp_header_main',
            parent_id: 'item_03_1',
            depth: 2,
            display_order: 3,
            label: 'PLAXIS 3D Ultimate 2026',
            url: '/san-pham/plaxis-3d-ultimate-2026',
            open_in_new_tab: false,
            is_visible: true,
          },
        ],
      },
      {
        id: 'item_03_2',
        group_id: 'grp_header_main',
        parent_id: 'item_03',
        depth: 1,
        display_order: 2,
        label: 'Phần mềm Thiết kế CAD 2D/3D',
        url: '/san-pham/cad',
        open_in_new_tab: false,
        is_visible: true,
        children: [
          {
            id: 'item_03_2_1',
            group_id: 'grp_header_main',
            parent_id: 'item_03_2',
            depth: 2,
            display_order: 1,
            label: 'EnjiCAD Network Enterprise v2.5',
            url: '/san-pham/enjicad-network-enterprise-v25',
            open_in_new_tab: false,
            is_visible: true,
          },
          {
            id: 'item_03_2_2',
            group_id: 'grp_header_main',
            parent_id: 'item_03_2',
            depth: 2,
            display_order: 2,
            label: 'ZwCAD Pro 2026 Permanent',
            url: '/san-pham/zwcad-pro-2026',
            open_in_new_tab: false,
            is_visible: true,
          },
        ],
      },
      {
        id: 'item_03_3',
        group_id: 'grp_header_main',
        parent_id: 'item_03',
        depth: 1,
        display_order: 3,
        label: 'Dự toán & Quản lý Chi phí Xây dựng',
        url: '/san-pham/du-toan',
        open_in_new_tab: false,
        is_visible: true,
        children: [
          {
            id: 'item_03_3_1',
            group_id: 'grp_header_main',
            parent_id: 'item_03_3',
            depth: 2,
            display_order: 1,
            label: 'Phần mềm Dự toán ESCON 2026',
            url: '/san-pham/du-toan-escon-2026',
            open_in_new_tab: false,
            is_visible: true,
          },
        ],
      },
    ],
  },

  // LEVEL 1: DỊCH VỤ & TƯ VẤN
  {
    id: 'item_04',
    group_id: 'grp_header_main',
    parent_id: null,
    depth: 0,
    display_order: 4,
    label: 'Dịch vụ & Tư vấn BIM',
    url: '/dich-vu',
    open_in_new_tab: false,
    icon_name: 'Layers',
    is_visible: true,
    children: [
      {
        id: 'item_04_1',
        group_id: 'grp_header_main',
        parent_id: 'item_04',
        depth: 1,
        display_order: 1,
        label: 'Tư vấn Lộ trình Chuyển đổi số BIM ISO 19650',
        url: '/dich-vu/tu-van-lo-trinh-chuyen-doi-so-bim-iso-19650',
        open_in_new_tab: false,
        is_visible: true,
      },
      {
        id: 'item_04_2',
        group_id: 'grp_header_main',
        parent_id: 'item_04',
        depth: 1,
        display_order: 2,
        label: 'Đào tạo Chuyên sâu & Cấp chứng chỉ Chuyên gia BIM',
        url: '/dich-vu/dao-tao-chuyen-sau-cap-chung-chi-chuyen-gia-bim',
        open_in_new_tab: false,
        is_visible: true,
      },
      {
        id: 'item_04_3',
        group_id: 'grp_header_main',
        parent_id: 'item_04',
        depth: 1,
        display_order: 3,
        label: 'Thẩm tra & Đánh giá An toàn Kết cấu Công trình',
        url: '/dich-vu/tham-tra-danh-gia-an-toan-ket-cau-cong-trinh',
        open_in_new_tab: false,
        is_visible: true,
      },
    ],
  },

  // LEVEL 1: TIN TỨC & DỰ ÁN
  {
    id: 'item_05',
    group_id: 'grp_header_main',
    parent_id: null,
    depth: 0,
    display_order: 5,
    label: 'Tin tức & Dự án',
    url: '/tin-tuc',
    open_in_new_tab: false,
    icon_name: 'Newspaper',
    is_visible: true,
    children: [
      {
        id: 'item_05_1',
        group_id: 'grp_header_main',
        parent_id: 'item_05',
        depth: 1,
        display_order: 1,
        label: 'Tin công nghệ Xây dựng',
        url: '/tin-tuc/cong-nghe-xay-dung',
        open_in_new_tab: false,
        is_visible: true,
      },
      {
        id: 'item_05_2',
        group_id: 'grp_header_main',
        parent_id: 'item_05',
        depth: 1,
        display_order: 2,
        label: 'Dự án Tiêu biểu ứng dụng phần mềm',
        url: '/tin-tuc/du-an-tieu-bieu-old-path',
        open_in_new_tab: false,
        is_visible: true,
      },
    ],
  },

  // LEVEL 1: LIÊN HỆ
  {
    id: 'item_06',
    group_id: 'grp_header_main',
    parent_id: null,
    depth: 0,
    display_order: 6,
    label: 'Liên hệ & Báo giá',
    url: '/lien-he',
    open_in_new_tab: false,
    icon_name: 'PhoneCall',
    is_visible: true,
  },
];
