import { BannerCategory } from './types';

export const mockBannerCategories: BannerCategory[] = [
  {
    id: 'bcat_001',
    name: 'Banner Header Trang chủ (Super Top Leaderboard)',
    summary: 'Vị trí banner lớn ngay dưới thanh Menu chính trên trang chủ website CIC Technology, thu hút lượng hiển thị cao nhất.',
    width: 1200,
    height: 300,
    price: 5000000,
    days: 30,
    quantity: 3,
    link_post: 'https://cic.com.vn/lien-he-quang-cao?pos=header_top',
    published: true,
    ordering: 1,
    created_time: '2026-07-20 09:00:00',
    updated_time: '2026-07-28 14:30:00',
  },
  {
    id: 'bcat_002',
    name: 'Banner Sidebar Cột bên phải (Right Column Medium Rectangle)',
    summary: 'Hiển thị cố định tại cột bên phải của tất cả trang danh mục tin tức, sản phẩm và chi tiết bài viết.',
    width: 300,
    height: 250,
    price: 2500000,
    days: 30,
    quantity: 5,
    link_post: 'https://cic.com.vn/lien-he-quang-cao?pos=sidebar_right',
    published: true,
    ordering: 2,
    created_time: '2026-07-22 10:15:00',
    updated_time: '2026-07-29 11:20:00',
  },
  {
    id: 'bcat_003',
    name: 'Banner Xén giữa bài viết Tin tức (In-article Banner Banner Standard)',
    summary: 'Vị trí banner chèn tự động vào giữa nội dung chi tiết các bài báo kỹ thuật, thích hợp cho sự kiện & phần mềm mới.',
    width: 728,
    height: 90,
    price: 1800000,
    days: 15,
    quantity: 10,
    link_post: 'https://cic.com.vn/lien-he-quang-cao?pos=in_article',
    published: false,
    ordering: 3,
    created_time: '2026-07-25 15:45:00',
    updated_time: '2026-07-30 08:50:00',
  },
];
