// Mock data for Form Module

import { FormItem } from './types';
import { FormStatus } from '../shared/constants/statusTypes';
import { FieldType, FieldRoleType } from '../shared/constants/fieldTypes';

export const MOCK_FORMS: FormItem[] = [
  {
    id: 'form_001',
    adminName: 'Biểu mẫu - Tư vấn ERP',
    title: 'Đăng ký nhận tư vấn',
    description: 'Vui lòng để lại thông tin để đội ngũ TechAZ liên hệ',
    code: 'form_tuvan_erp',
    status: 'active',
    currentVersion: 2,
    fields: [
      {
        id: 'field_001',
        fieldKey: 'full_name',
        label: 'Họ và tên',
        fieldType: 'text',
        roleType: 'customer_name',
        placeholder: 'Nhập họ và tên của bạn',
        helpText: '',
        validation: { required: true, minLength: 2, maxLength: 100 },
        position: 1,
        isRequired: true,
        isLocked: true,
      },
      {
        id: 'field_002',
        fieldKey: 'email',
        label: 'Email',
        fieldType: 'email',
        roleType: 'email',
        placeholder: 'email@example.com',
        helpText: 'Chúng tôi sẽ gửi thông tin qua email này',
        validation: { required: true },
        position: 2,
        isRequired: true,
        isLocked: true,
      },
      {
        id: 'field_003',
        fieldKey: 'phone',
        label: 'Số điện thoại',
        fieldType: 'phone',
        roleType: 'phone',
        placeholder: '09xxxxxxxxx',
        helpText: '',
        validation: { required: true },
        position: 3,
        isRequired: true,
        isLocked: true,
      },
      {
        id: 'field_004',
        fieldKey: 'company',
        label: 'Công ty',
        fieldType: 'text',
        roleType: 'company',
        placeholder: 'Tên công ty của bạn',
        helpText: '',
        validation: { required: false },
        position: 4,
        isRequired: false,
        isLocked: false,
      },
      {
        id: 'field_005',
        fieldKey: 'message',
        label: 'Nhu cầu',
        fieldType: 'textarea',
        roleType: 'message',
        placeholder: 'Mô tả ngắn gọn nhu cầu của bạn',
        helpText: '',
        validation: { required: false, maxLength: 500 },
        position: 5,
        isRequired: false,
        isLocked: false,
      },
    ],
    submitConfig: {
      saveToDatabase: true,
      createCustomerRequest: true,
      sendAdminEmail: true,
      adminEmails: ['sales@techaz.com', 'support@techaz.com'],
      sendConfirmationEmail: true,
      confirmationEmailTemplate: 'vi-product_contact-customer',
      adminEmailTemplate: 'vi-product_contact-internal',
      successMessage: 'Cảm ơn bạn đã đăng ký. Chúng tôi sẽ liên hệ trong vòng 24h.',
      submitButtonText: 'Gửi yêu cầu tư vấn',
      webhookUrl: '',
      crmSyncEnabled: false,
    },
    stats: {
      submissions: 500,
      conversionRate: 5.2,
    },
    analytics: {
      impressions: 0,
      clicks: 500,
      ctr: 0,
      trend: 'up',
    },
    createdBy: 'Nguyễn Văn Minh',
    createdAt: '2026-01-10T08:30:00Z',
    updatedAt: '2026-02-01T10:15:00Z',
  },
  {
    id: 'form_002',
    adminName: 'Biểu mẫu - Báo giá',
    title: 'Nhận báo giá',
    description: 'Để lại thông tin để nhận báo giá chi tiết',
    code: 'form_baogia',
    status: 'active',
    currentVersion: 1,
    fields: [
      {
        id: 'field_006',
        fieldKey: 'full_name',
        label: 'Họ và tên',
        fieldType: 'text',
        roleType: 'customer_name',
        placeholder: '',
        helpText: '',
        validation: { required: true },
        position: 1,
        isRequired: true,
        isLocked: true,
      },
      {
        id: 'field_007',
        fieldKey: 'email',
        label: 'Email',
        fieldType: 'email',
        roleType: 'email',
        placeholder: '',
        helpText: '',
        validation: { required: true },
        position: 2,
        isRequired: true,
        isLocked: true,
      },
      {
        id: 'field_008',
        fieldKey: 'phone',
        label: 'Số điện thoại',
        fieldType: 'phone',
        roleType: 'phone',
        placeholder: '',
        helpText: '',
        validation: { required: true },
        position: 3,
        isRequired: true,
        isLocked: true,
      },
      {
        id: 'field_009',
        fieldKey: 'company',
        label: 'Công ty',
        fieldType: 'text',
        roleType: 'company',
        placeholder: '',
        helpText: '',
        validation: { required: true },
        position: 4,
        isRequired: true,
        isLocked: false,
      },
      {
        id: 'field_010',
        fieldKey: 'product_interest',
        label: 'Sản phẩm quan tâm',
        fieldType: 'select',
        roleType: 'other',
        placeholder: 'Chọn sản phẩm',
        helpText: '',
        validation: { required: true },
        options: [
          { value: 'intellicad', label: 'IntelliCAD' },
          { value: 'erp_solution', label: 'Giải pháp ERP' },
          { value: 'bim_solution', label: 'Giải pháp BIM' },
          { value: 'other', label: 'Khác' },
        ],
        position: 5,
        isRequired: true,
        isLocked: false,
      },
      {
        id: 'field_011',
        fieldKey: 'budget',
        label: 'Ngân sách dự kiến',
        fieldType: 'select',
        roleType: 'other',
        placeholder: 'Chọn mức ngân sách',
        helpText: '',
        validation: { required: false },
        options: [
          { value: 'under_50m', label: 'Dưới 50 triệu' },
          { value: '50m_100m', label: '50 - 100 triệu' },
          { value: '100m_500m', label: '100 - 500 triệu' },
          { value: 'over_500m', label: 'Trên 500 triệu' },
        ],
        position: 6,
        isRequired: false,
        isLocked: false,
      },
    ],
    submitConfig: {
      saveToDatabase: true,
      createCustomerRequest: true,
      sendAdminEmail: true,
      adminEmails: ['sales@techaz.com'],
      sendConfirmationEmail: true,
      confirmationEmailTemplate: 'vi-product_quote-customer',
      adminEmailTemplate: 'vi-product_quote-internal',
      successMessage: 'Chúng tôi sẽ gửi báo giá trong vòng 48h.',
      submitButtonText: 'Nhận báo giá',
      webhookUrl: '',
      crmSyncEnabled: false,
    },
    stats: {
      submissions: 300,
      conversionRate: 4.8,
    },
    analytics: {
      impressions: 0,
      clicks: 300,
      ctr: 0,
      trend: 'flat',
    },
    createdBy: 'Trần Thị Thu',
    createdAt: '2026-01-15T09:00:00Z',
    updatedAt: '2026-02-02T14:20:00Z',
  },
  {
    id: 'form_003',
    adminName: 'Biểu mẫu - Liên hệ',
    title: 'Liên hệ với chúng tôi',
    description: 'Form liên hệ chung',
    code: 'form_lienhe',
    status: 'active',
    currentVersion: 3,
    fields: [
      {
        id: 'field_012',
        fieldKey: 'full_name',
        label: 'Họ và tên',
        fieldType: 'text',
        roleType: 'customer_name',
        placeholder: '',
        helpText: '',
        validation: { required: true },
        position: 1,
        isRequired: true,
        isLocked: true,
      },
      {
        id: 'field_013',
        fieldKey: 'email',
        label: 'Email',
        fieldType: 'email',
        roleType: 'email',
        placeholder: '',
        helpText: '',
        validation: { required: true },
        position: 2,
        isRequired: true,
        isLocked: true,
      },
      {
        id: 'field_014',
        fieldKey: 'phone',
        label: 'Số điện thoại',
        fieldType: 'phone',
        roleType: 'phone',
        placeholder: '',
        helpText: '',
        validation: { required: false },
        position: 3,
        isRequired: false,
        isLocked: false,
      },
      {
        id: 'field_015',
        fieldKey: 'subject',
        label: 'Chủ đề',
        fieldType: 'select',
        roleType: 'other',
        placeholder: 'Chọn chủ đề',
        helpText: '',
        validation: { required: true },
        options: [
          { value: 'general', label: 'Tổng quan' },
          { value: 'support', label: 'Hỗ trợ kỹ thuật' },
          { value: 'sales', label: 'Bán hàng' },
          { value: 'partnership', label: 'Hợp tác' },
        ],
        position: 4,
        isRequired: true,
        isLocked: false,
      },
      {
        id: 'field_016',
        fieldKey: 'message',
        label: 'Nội dung',
        fieldType: 'textarea',
        roleType: 'message',
        placeholder: '',
        helpText: '',
        validation: { required: true, minLength: 10, maxLength: 1000 },
        position: 5,
        isRequired: true,
        isLocked: false,
      },
      {
        id: 'field_017',
        fieldKey: 'consent',
        label: 'Tôi đồng ý với chính sách bảo mật',
        fieldType: 'consent',
        roleType: 'other',
        placeholder: '',
        helpText: '',
        validation: { required: true },
        position: 6,
        isRequired: true,
        isLocked: false,
      },
    ],
    submitConfig: {
      saveToDatabase: true,
      createCustomerRequest: true,
      sendAdminEmail: true,
      adminEmails: ['info@techaz.com'],
      sendConfirmationEmail: true,
      confirmationEmailTemplate: 'vi-product_contact-customer',
      adminEmailTemplate: 'vi-product_contact-internal',
      successMessage: 'Cảm ơn bạn đã liên hệ. Chúng tôi sẽ phản hồi sớm.',
      submitButtonText: 'Gửi liên hệ',
      webhookUrl: '',
      crmSyncEnabled: false,
    },
    stats: {
      submissions: 300,
      conversionRate: 4.8,
    },
    analytics: {
      impressions: 0,
      clicks: 200,
      ctr: 0,
      trend: 'up',
    },
    createdBy: 'Lê Hoàng Nam',
    createdAt: '2026-01-20T10:30:00Z',
    updatedAt: '2026-02-03T11:45:00Z',
  },
  {
    id: 'form_004',
    adminName: 'Biểu mẫu - Đăng ký Demo',
    title: 'Đăng ký dùng thử',
    description: 'Đăng ký để trải nghiệm sản phẩm miễn phí',
    code: 'form_dangky_demo',
    status: 'draft',
    currentVersion: 1,
    fields: [
      {
        id: 'field_018',
        fieldKey: 'full_name',
        label: 'Họ và tên',
        fieldType: 'text',
        roleType: 'customer_name',
        placeholder: '',
        helpText: '',
        validation: { required: true },
        position: 1,
        isRequired: true,
        isLocked: false,
      },
      {
        id: 'field_019',
        fieldKey: 'email',
        label: 'Email công việc',
        fieldType: 'email',
        roleType: 'email',
        placeholder: '',
        helpText: 'Sử dụng email công việc để được duyệt nhanh hơn',
        validation: { required: true },
        position: 2,
        isRequired: true,
        isLocked: false,
      },
      {
        id: 'field_020',
        fieldKey: 'phone',
        label: 'Số điện thoại',
        fieldType: 'phone',
        roleType: 'phone',
        placeholder: '',
        helpText: '',
        validation: { required: true },
        position: 3,
        isRequired: true,
        isLocked: false,
      },
      {
        id: 'field_021',
        fieldKey: 'company',
        label: 'Công ty',
        fieldType: 'text',
        roleType: 'company',
        placeholder: '',
        helpText: '',
        validation: { required: true },
        position: 4,
        isRequired: true,
        isLocked: false,
      },
      {
        id: 'field_022',
        fieldKey: 'position',
        label: 'Chức vụ',
        fieldType: 'text',
        roleType: 'other',
        placeholder: '',
        helpText: '',
        validation: { required: false },
        position: 5,
        isRequired: false,
        isLocked: false,
      },
      {
        id: 'field_023',
        fieldKey: 'team_size',
        label: 'Quy mô team',
        fieldType: 'select',
        roleType: 'other',
        placeholder: '',
        helpText: '',
        validation: { required: false },
        options: [
          { value: '1_5', label: '1-5 người' },
          { value: '6_20', label: '6-20 người' },
          { value: '21_50', label: '21-50 người' },
          { value: 'over_50', label: 'Trên 50 người' },
        ],
        position: 6,
        isRequired: false,
        isLocked: false,
      },
    ],
    submitConfig: {
      saveToDatabase: true,
      createCustomerRequest: true,
      sendAdminEmail: true,
      adminEmails: ['demo@techaz.com'],
      sendConfirmationEmail: true,
      confirmationEmailTemplate: 'vi-product_contact-customer',
      adminEmailTemplate: 'vi-product_contact-internal',
      successMessage: 'Chúng tôi sẽ liên hệ để hướng dẫn cài đặt.',
      submitButtonText: 'Đăng ký dùng thử',
      webhookUrl: '',
      crmSyncEnabled: false,
    },
    stats: {
      submissions: 300,
      conversionRate: 4.8,
    },
    analytics: {
      impressions: 0,
      clicks: 0,
      ctr: 0,
    },
    createdBy: 'Nguyễn Thị Lan',
    createdAt: '2026-02-05T09:15:00Z',
    updatedAt: '2026-02-05T09:15:00Z',
  },
];
