// Mock data for Form Module - Synchronized with genuine public website forms
import { FormItem } from './types';

export const MOCK_FORMS: FormItem[] = [
  // 1. Popup Đăng ký tư vấn giải pháp
  {
    id: '15',
    adminName: 'Biểu mẫu - Đăng ký tư vấn giải pháp',
    title: 'Đăng ký tư vấn giải pháp & phần mềm',
    description: 'Biểu mẫu tiếp nhận yêu cầu tư vấn sản phẩm, bản quyền phần mềm và giải pháp chuyển đổi số từ khách hàng.',
    code: 'form_home_consultation',
    status: 'active',
    currentVersion: 1,
    fields: [
      {
        id: 'f15_1',
        fieldKey: 'name',
        label: 'Họ và tên',
        fieldType: 'text',
        roleType: 'customer_name',
        placeholder: 'Nguyễn Văn A',
        isRequired: true,
        isLocked: true,
        position: 1,
        validation: { required: true, minLength: 2 },
      },
      {
        id: 'f15_2',
        fieldKey: 'phone',
        label: 'Số điện thoại',
        fieldType: 'phone',
        roleType: 'phone',
        placeholder: '0912 345 678',
        isRequired: true,
        isLocked: true,
        position: 2,
        validation: { required: true },
      },
      {
        id: 'f15_3',
        fieldKey: 'email',
        label: 'Email liên hệ',
        fieldType: 'email',
        roleType: 'email',
        placeholder: 'email@example.com',
        isRequired: false,
        isLocked: true,
        position: 3,
        validation: { required: false },
      },
      {
        id: 'f15_4',
        fieldKey: 'consultationNeed',
        label: 'Nhu cầu tư vấn',
        fieldType: 'select',
        roleType: 'other',
        isRequired: true,
        isLocked: false,
        position: 4,
        validation: { required: true },
        options: [
          { value: 'Tư vấn báo giá sản phẩm & giải pháp', label: 'Tư vấn báo giá sản phẩm & giải pháp' },
          { value: 'Tải phần mềm & dùng thử', label: 'Tải phần mềm & dùng thử' },
          { value: 'Đăng ký mua bản quyền / thiết bị', label: 'Đăng ký mua bản quyền / thiết bị' },
          { value: 'Tư vấn chuyển đổi số & BIM', label: 'Tư vấn chuyển đổi số & BIM' },
          { value: 'Đào tạo & Hỗ trợ kỹ thuật', label: 'Đào tạo & Hỗ trợ kỹ thuật' },
          { value: 'Nhu cầu khác', label: 'Nhu cầu khác' },
        ],
      },
      {
        id: 'f15_5',
        fieldKey: 'message',
        label: 'Nội dung yêu cầu chi tiết',
        fieldType: 'textarea',
        roleType: 'message',
        placeholder: 'Mô tả ngắn gọn nhu cầu của bạn...',
        isRequired: false,
        isLocked: false,
        position: 5,
        validation: { required: false },
      },
    ],
    submitConfig: {
      saveToDatabase: true,
      createCustomerRequest: true,
      sendAdminEmail: true,
      adminEmails: ['nampt@cic.com.vn', 'info@cic.com.vn'],
      sendConfirmationEmail: true,
      submitButtonText: 'Gửi yêu cầu tư vấn',
      successMessage: 'Cảm ơn bạn đã gửi yêu cầu tư vấn. Đội ngũ chuyên gia CIC sẽ liên hệ hỗ trợ trong vòng 24 giờ làm việc.',
      crmSyncEnabled: false,
    },
    analytics: { impressions: 1250, clicks: 310, ctr: 24.8 },
    governance: {
      origin: 'system',
      allowedPlacements: ['fixed_section', 'cta_action'],
      fixedPlacementKeys: ['header.consultation_cta', 'floating.consultation'],
    },
    createdBy: 'Hệ thống',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-25T00:00:00Z',
  },

  // 2. Khối Liên hệ cuối Trang chủ
  {
    id: '17',
    adminName: 'Biểu mẫu - Liên hệ Trang chủ',
    title: 'Tư vấn giải pháp trang chủ',
    description: 'Biểu mẫu liên hệ nhanh đặt tại phần chân trang chủ để khách hàng gửi nhu cầu tư vấn giải pháp số.',
    code: 'form_home_contact',
    status: 'active',
    currentVersion: 1,
    fields: [
      {
        id: 'f17_1',
        fieldKey: 'fullName',
        label: 'Họ và tên',
        fieldType: 'text',
        roleType: 'customer_name',
        placeholder: 'Nguyễn Văn A',
        isRequired: true,
        isLocked: true,
        position: 1,
        validation: { required: true },
      },
      {
        id: 'f17_2',
        fieldKey: 'phoneNumber',
        label: 'Số điện thoại',
        fieldType: 'phone',
        roleType: 'phone',
        placeholder: '0912 345 678',
        isRequired: true,
        isLocked: true,
        position: 2,
        validation: { required: true },
      },
      {
        id: 'f17_3',
        fieldKey: 'interestService',
        label: 'Dịch vụ quan tâm',
        fieldType: 'select',
        roleType: 'other',
        isRequired: true,
        isLocked: false,
        position: 3,
        validation: { required: true },
        options: [
          { value: 'Phần mềm kỹ thuật bản quyền', label: 'Phần mềm kỹ thuật bản quyền' },
          { value: 'Giải pháp BIM & Chuyển đổi số', label: 'Giải pháp BIM & Chuyển đổi số' },
          { value: 'Tư vấn & Đào tạo chuyên ngành', label: 'Tư vấn & Đào tạo chuyên ngành' },
          { value: 'Thiết bị & Chuyển giao công nghệ', label: 'Thiết bị & Chuyển giao công nghệ' },
        ],
      },
      {
        id: 'f17_4',
        fieldKey: 'message',
        label: 'Nội dung cần tư vấn',
        fieldType: 'textarea',
        roleType: 'message',
        placeholder: 'Mô tả nội dung cần tư vấn...',
        isRequired: false,
        isLocked: false,
        position: 4,
        validation: { required: false },
      },
    ],
    submitConfig: {
      saveToDatabase: true,
      createCustomerRequest: true,
      sendAdminEmail: true,
      adminEmails: ['nampt@cic.com.vn', 'info@cic.com.vn'],
      sendConfirmationEmail: true,
      submitButtonText: 'Gửi thông tin',
      successMessage: 'Cảm ơn bạn đã quan tâm. CIC sẽ liên hệ lại với bạn trong thời gian sớm nhất.',
      crmSyncEnabled: false,
    },
    analytics: { impressions: 840, clicks: 120, ctr: 14.2 },
    governance: {
      origin: 'system',
      allowedPlacements: ['fixed_section'],
      fixedPlacementKeys: ['home.contact_section'],
    },
    createdBy: 'Hệ thống',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-25T00:00:00Z',
  },

  // 3. Form Trang Liên hệ Chính thức (/lien-he)
  {
    id: '19',
    adminName: 'Biểu mẫu - Liên hệ Trực tuyến',
    title: 'Gửi yêu cầu liên hệ',
    description: 'Biểu mẫu liên hệ chính thức tại trang Liên hệ của CIC Technology.',
    code: 'form_contact_request',
    status: 'active',
    currentVersion: 1,
    fields: [
      {
        id: 'f19_1',
        fieldKey: 'fullName',
        label: 'Họ và tên',
        fieldType: 'text',
        roleType: 'customer_name',
        placeholder: 'Nguyễn Văn A',
        isRequired: true,
        isLocked: true,
        position: 1,
        validation: { required: true },
      },
      {
        id: 'f19_2',
        fieldKey: 'email',
        label: 'Email liên hệ',
        fieldType: 'email',
        roleType: 'email',
        placeholder: 'email@example.com',
        isRequired: true,
        isLocked: true,
        position: 2,
        validation: { required: true },
      },
      {
        id: 'f19_3',
        fieldKey: 'phone',
        label: 'Số điện thoại',
        fieldType: 'phone',
        roleType: 'phone',
        placeholder: '0912 345 678',
        isRequired: true,
        isLocked: true,
        position: 3,
        validation: { required: true },
      },
      {
        id: 'f19_4',
        fieldKey: 'subject',
        label: 'Tiêu đề yêu cầu',
        fieldType: 'text',
        placeholder: 'Ví dụ: Tư vấn hợp tác dự án / Bản quyền phần mềm',
        isRequired: false,
        isLocked: false,
        position: 4,
        validation: { required: false },
      },
      {
        id: 'f19_5',
        fieldKey: 'note',
        label: 'Nội dung tin nhắn',
        fieldType: 'textarea',
        roleType: 'message',
        placeholder: 'Chi tiết nội dung bạn muốn gửi tới CIC...',
        isRequired: true,
        isLocked: false,
        position: 5,
        validation: { required: true },
      },
    ],
    submitConfig: {
      saveToDatabase: true,
      createCustomerRequest: true,
      sendAdminEmail: true,
      adminEmails: ['nampt@cic.com.vn', 'info@cic.com.vn'],
      sendConfirmationEmail: true,
      submitButtonText: 'Gửi tin nhắn liên hệ',
      successMessage: 'Cảm ơn bạn đã liên hệ. Bộ phận tiếp nhận thông tin của CIC sẽ phản hồi sớm nhất.',
      crmSyncEnabled: false,
    },
    analytics: { impressions: 650, clicks: 95, ctr: 14.6 },
    governance: {
      origin: 'system',
      allowedPlacements: ['fixed_section'],
      fixedPlacementKeys: ['contact.page_form'],
    },
    createdBy: 'Hệ thống',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-25T00:00:00Z',
  },

  // 4. Modal Báo giá Sản phẩm (/products/[slug])
  {
    id: '21',
    adminName: 'Biểu mẫu - Báo giá Sản phẩm',
    title: 'Yêu cầu báo giá sản phẩm',
    description: 'Biểu mẫu yêu cầu cung cấp báo giá chi tiết cho các sản phẩm phần mềm và thiết bị công nghệ.',
    code: 'form_baogia_sanpham',
    status: 'active',
    currentVersion: 1,
    fields: [
      {
        id: 'f21_1',
        fieldKey: 'name',
        label: 'Họ và tên',
        fieldType: 'text',
        roleType: 'customer_name',
        placeholder: 'Nguyễn Văn A',
        isRequired: true,
        isLocked: true,
        position: 1,
        validation: { required: true },
      },
      {
        id: 'f21_2',
        fieldKey: 'phone',
        label: 'Số điện thoại',
        fieldType: 'phone',
        roleType: 'phone',
        placeholder: '0912 345 678',
        isRequired: true,
        isLocked: true,
        position: 2,
        validation: { required: true },
      },
      {
        id: 'f21_3',
        fieldKey: 'email',
        label: 'Email nhận báo giá',
        fieldType: 'email',
        roleType: 'email',
        placeholder: 'email@example.com',
        isRequired: false,
        isLocked: true,
        position: 3,
        validation: { required: false },
      },
      {
        id: 'f21_4',
        fieldKey: 'productName',
        label: 'Tên sản phẩm quan tâm',
        fieldType: 'text',
        placeholder: 'Tên phần mềm / Thiết bị',
        isRequired: false,
        isLocked: false,
        position: 4,
        validation: { required: false },
      },
      {
        id: 'f21_5',
        fieldKey: 'notes',
        label: 'Ghi chú thêm',
        fieldType: 'textarea',
        roleType: 'message',
        placeholder: 'Số lượng license, gói tính năng hoặc yêu cầu đặc thù...',
        isRequired: false,
        isLocked: false,
        position: 5,
        validation: { required: false },
      },
    ],
    submitConfig: {
      saveToDatabase: true,
      createCustomerRequest: true,
      sendAdminEmail: true,
      adminEmails: ['nampt@cic.com.vn', 'info@cic.com.vn'],
      sendConfirmationEmail: true,
      submitButtonText: 'Gửi yêu cầu báo giá',
      successMessage: 'Yêu cầu báo giá đã được ghi nhận. Chuyên viên kinh doanh sẽ gửi báo giá chi tiết qua email/điện thoại cho bạn.',
      crmSyncEnabled: false,
    },
    analytics: { impressions: 980, clicks: 145, ctr: 14.8 },
    governance: {
      origin: 'system',
      allowedPlacements: ['cta_action', 'fixed_section'],
      fixedPlacementKeys: ['product.quote_modal'],
    },
    createdBy: 'Hệ thống',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-25T00:00:00Z',
  },

  // 5. Đăng ký mua bản quyền
  {
    id: '23',
    adminName: 'Biểu mẫu - Đăng ký Mua Sản phẩm',
    title: 'Đăng ký mua bản quyền sản phẩm',
    description: 'Biểu mẫu đăng ký đặt mua bản quyền phần mềm chính hãng từ các hãng công nghệ do CIC phân phối.',
    code: 'form_dangky_mua',
    status: 'active',
    currentVersion: 1,
    fields: [
      {
        id: 'f23_1',
        fieldKey: 'name',
        label: 'Họ và tên',
        fieldType: 'text',
        roleType: 'customer_name',
        placeholder: 'Nguyễn Văn A',
        isRequired: true,
        isLocked: true,
        position: 1,
        validation: { required: true },
      },
      {
        id: 'f23_2',
        fieldKey: 'phone',
        label: 'Số điện thoại',
        fieldType: 'phone',
        roleType: 'phone',
        placeholder: '0912 345 678',
        isRequired: true,
        isLocked: true,
        position: 2,
        validation: { required: true },
      },
      {
        id: 'f23_3',
        fieldKey: 'email',
        label: 'Email liên hệ',
        fieldType: 'email',
        roleType: 'email',
        placeholder: 'email@example.com',
        isRequired: false,
        isLocked: true,
        position: 3,
        validation: { required: false },
      },
      {
        id: 'f23_4',
        fieldKey: 'company',
        label: 'Tên đơn vị / Doanh nghiệp',
        fieldType: 'text',
        roleType: 'company',
        placeholder: 'Công ty CP Xây dựng XYZ',
        isRequired: false,
        isLocked: false,
        position: 4,
        validation: { required: false },
      },
      {
        id: 'f23_5',
        fieldKey: 'notes',
        label: 'Ghi chú đơn hàng',
        fieldType: 'textarea',
        roleType: 'message',
        placeholder: 'Hình thức thanh toán, thông tin xuất hóa đơn VAT...',
        isRequired: false,
        isLocked: false,
        position: 5,
        validation: { required: false },
      },
    ],
    submitConfig: {
      saveToDatabase: true,
      createCustomerRequest: true,
      sendAdminEmail: true,
      adminEmails: ['nampt@cic.com.vn', 'info@cic.com.vn'],
      sendConfirmationEmail: true,
      submitButtonText: 'Xác nhận đăng ký mua',
      successMessage: 'Đăng ký mua hàng thành công. Bộ phận phụ trách sẽ liên hệ hoàn tất hợp đồng và kích hoạt bản quyền.',
      crmSyncEnabled: false,
    },
    analytics: { impressions: 420, clicks: 65, ctr: 15.5 },
    governance: {
      origin: 'custom',
      allowedPlacements: ['cta_action'],
    },
    createdBy: 'Quản trị viên',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-25T00:00:00Z',
  },

  // 6. Tải bản dùng thử
  {
    id: '25',
    adminName: 'Biểu mẫu - Tải bản dùng thử',
    title: 'Yêu cầu tải phần mềm & Dùng thử',
    description: 'Biểu mẫu đăng ký nhận bộ cài đặt và tài liệu hướng dẫn dùng thử phần mềm kỹ thuật.',
    code: 'form_taive_dungthu',
    status: 'active',
    currentVersion: 1,
    fields: [
      {
        id: 'f25_1',
        fieldKey: 'name',
        label: 'Họ và tên',
        fieldType: 'text',
        roleType: 'customer_name',
        placeholder: 'Nguyễn Văn A',
        isRequired: true,
        isLocked: true,
        position: 1,
        validation: { required: true },
      },
      {
        id: 'f25_2',
        fieldKey: 'phone',
        label: 'Số điện thoại',
        fieldType: 'phone',
        roleType: 'phone',
        placeholder: '0912 345 678',
        isRequired: true,
        isLocked: true,
        position: 2,
        validation: { required: true },
      },
      {
        id: 'f25_3',
        fieldKey: 'email',
        label: 'Email nhận link tải',
        fieldType: 'email',
        roleType: 'email',
        placeholder: 'email@example.com',
        isRequired: true,
        isLocked: true,
        position: 3,
        validation: { required: true },
      },
      {
        id: 'f25_4',
        fieldKey: 'version',
        label: 'Phiên bản quan tâm',
        fieldType: 'text',
        placeholder: 'Bản mới nhất / 64-bit',
        isRequired: false,
        isLocked: false,
        position: 4,
        validation: { required: false },
      },
      {
        id: 'f25_5',
        fieldKey: 'notes',
        label: 'Ghi chú hỗ trợ',
        fieldType: 'textarea',
        roleType: 'message',
        placeholder: 'Yêu cầu tài liệu hướng dẫn hoặc tư vấn cài đặt...',
        isRequired: false,
        isLocked: false,
        position: 5,
        validation: { required: false },
      },
    ],
    submitConfig: {
      saveToDatabase: true,
      createCustomerRequest: true,
      sendAdminEmail: true,
      adminEmails: ['nampt@cic.com.vn', 'info@cic.com.vn'],
      sendConfirmationEmail: true,
      submitButtonText: 'Tải về bản dùng thử',
      successMessage: 'Link tải bộ cài và hướng dẫn kích hoạt bản quyền thử nghiệm đã được chuẩn bị.',
      crmSyncEnabled: false,
    },
    analytics: { impressions: 720, clicks: 110, ctr: 15.3 },
    governance: {
      origin: 'custom',
      allowedPlacements: ['cta_action'],
    },
    createdBy: 'Quản trị viên',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-25T00:00:00Z',
  },

  // 7. Tư vấn Dịch vụ BIM & Đào tạo (/services)
  {
    id: '27',
    adminName: 'Biểu mẫu - Tư vấn Dịch vụ BIM & Đào tạo',
    title: 'Đăng ký Tư vấn & Demo Dịch vụ',
    description: 'Biểu mẫu đăng ký tư vấn giải pháp dịch vụ chuyên ngành xây dựng, BIM, Digital Twin và đào tạo kỹ thuật.',
    code: 'form_tuvan_dichvu',
    status: 'active',
    currentVersion: 1,
    fields: [
      {
        id: 'f27_1',
        fieldKey: 'fullname',
        label: 'Họ và tên',
        fieldType: 'text',
        roleType: 'customer_name',
        placeholder: 'Nguyễn Văn A',
        isRequired: true,
        isLocked: true,
        position: 1,
        validation: { required: true },
      },
      {
        id: 'f27_2',
        fieldKey: 'phone',
        label: 'Số điện thoại',
        fieldType: 'phone',
        roleType: 'phone',
        placeholder: '0912 345 678',
        isRequired: true,
        isLocked: true,
        position: 2,
        validation: { required: true },
      },
      {
        id: 'f27_3',
        fieldKey: 'email',
        label: 'Email liên hệ',
        fieldType: 'email',
        roleType: 'email',
        placeholder: 'email@example.com',
        isRequired: false,
        isLocked: true,
        position: 3,
        validation: { required: false },
      },
      {
        id: 'f27_4',
        fieldKey: 'service',
        label: 'Dịch vụ quan tâm',
        fieldType: 'select',
        roleType: 'other',
        isRequired: true,
        isLocked: false,
        position: 4,
        validation: { required: true },
        options: [
          { value: 'Tư vấn BIM & Quản lý thông tin công trình', label: 'Tư vấn BIM & Quản lý thông tin công trình' },
          { value: 'Chuyển đổi số & Tích hợp hệ thống Digital Twins', label: 'Chuyển đổi số & Tích hợp hệ thống Digital Twins' },
          { value: 'Đào tạo kỹ thuật chuyên ngành & Chuyển giao công nghệ', label: 'Đào tạo kỹ thuật chuyên ngành & Chuyển giao công nghệ' },
          { value: 'Dịch vụ phân tích kết cấu & Mô phỏng công trình', label: 'Dịch vụ phân tích kết cấu & Mô phỏng công trình' },
          { value: 'Khảo sát địa kỹ thuật & Thí nghiệm chuyên sâu', label: 'Khảo sát địa kỹ thuật & Thí nghiệm chuyên sâu' },
        ],
      },
      {
        id: 'f27_5',
        fieldKey: 'notes',
        label: 'Nội dung cần tư vấn',
        fieldType: 'textarea',
        roleType: 'message',
        placeholder: 'Mô tả phạm vi dự án hoặc yêu cầu cụ thể...',
        isRequired: false,
        isLocked: false,
        position: 5,
        validation: { required: false },
      },
    ],
    submitConfig: {
      saveToDatabase: true,
      createCustomerRequest: true,
      sendAdminEmail: true,
      adminEmails: ['nampt@cic.com.vn', 'info@cic.com.vn'],
      sendConfirmationEmail: true,
      submitButtonText: 'Gửi yêu cầu tư vấn dịch vụ',
      successMessage: 'Yêu cầu tư vấn dịch vụ đã được gửi thành công. Đội ngũ tư vấn CIC sẽ liên hệ trong 24h làm việc.',
      crmSyncEnabled: false,
    },
    analytics: { impressions: 530, clicks: 88, ctr: 16.6 },
    governance: {
      origin: 'custom',
      allowedPlacements: ['cta_action', 'fixed_section'],
    },
    createdBy: 'Quản trị viên',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-25T00:00:00Z',
  },

  // 8. Đăng ký Sự kiện & Hội thảo (/events/[slug])
  {
    id: '29',
    adminName: 'Biểu mẫu - Đăng ký Sự kiện & Hội thảo',
    title: 'Đăng ký tham gia sự kiện & Hội thảo',
    description: 'Biểu mẫu đăng ký tham dự hội thảo, workshop và các chương trình sự kiện chuyên đề của CIC.',
    code: 'form_dangky_sukien',
    status: 'active',
    currentVersion: 1,
    fields: [
      {
        id: 'f29_1',
        fieldKey: 'fullName',
        label: 'Họ và tên',
        fieldType: 'text',
        roleType: 'customer_name',
        placeholder: 'Nguyễn Văn A',
        isRequired: true,
        isLocked: true,
        position: 1,
        validation: { required: true },
      },
      {
        id: 'f29_2',
        fieldKey: 'company',
        label: 'Đơn vị / Doanh nghiệp',
        fieldType: 'text',
        roleType: 'company',
        placeholder: 'Công ty CP Xây dựng ABC',
        isRequired: true,
        isLocked: false,
        position: 2,
        validation: { required: true },
      },
      {
        id: 'f29_3',
        fieldKey: 'position',
        label: 'Chức danh / Vị trí công tác',
        fieldType: 'text',
        placeholder: 'Kỹ sư trưởng / Giám đốc kỹ thuật...',
        isRequired: true,
        isLocked: false,
        position: 3,
        validation: { required: true },
      },
      {
        id: 'f29_4',
        fieldKey: 'email',
        label: 'Email nhận vé tham dự',
        fieldType: 'email',
        roleType: 'email',
        placeholder: 'email@example.com',
        isRequired: true,
        isLocked: true,
        position: 4,
        validation: { required: true },
      },
      {
        id: 'f29_5',
        fieldKey: 'phone',
        label: 'Số điện thoại liên hệ',
        fieldType: 'phone',
        roleType: 'phone',
        placeholder: '0912 345 678',
        isRequired: true,
        isLocked: true,
        position: 5,
        validation: { required: true },
      },
      {
        id: 'f29_6',
        fieldKey: 'attendeesCount',
        label: 'Số lượng đại biểu tham dự',
        fieldType: 'number',
        placeholder: '1',
        isRequired: true,
        isLocked: false,
        position: 6,
        validation: { required: true, min: 1 },
      },
      {
        id: 'f29_7',
        fieldKey: 'note',
        label: 'Câu hỏi trao đổi cho diễn giả',
        fieldType: 'textarea',
        roleType: 'message',
        placeholder: 'Câu hỏi hoặc chủ đề bạn muốn được giải đáp tại hội thảo...',
        isRequired: false,
        isLocked: false,
        position: 7,
        validation: { required: false },
      },
    ],
    submitConfig: {
      saveToDatabase: true,
      createCustomerRequest: true,
      sendAdminEmail: true,
      adminEmails: ['nampt@cic.com.vn', 'info@cic.com.vn'],
      sendConfirmationEmail: true,
      submitButtonText: 'Xác nhận đăng ký tham dự',
      successMessage: 'Đăng ký tham gia thành công! Vé tham dự và thông tin chi tiết sự kiện đã được ghi nhận.',
      crmSyncEnabled: false,
    },
    analytics: { impressions: 1100, clicks: 230, ctr: 20.9 },
    governance: {
      origin: 'custom',
      allowedPlacements: ['cta_action', 'fixed_section'],
    },
    createdBy: 'Quản trị viên',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-25T00:00:00Z',
  },

  // 9. Tư vấn Tin tức & Công nghệ (/news/[slug])
  {
    id: '31',
    adminName: 'Biểu mẫu - Tư vấn Tin tức & Công nghệ',
    title: 'Đăng ký nhận tư vấn chuyên sâu từ bài viết',
    description: 'Biểu mẫu tiếp nhận câu hỏi và nhu cầu tư vấn từ bạn đọc bài viết tin tức, công nghệ trên website.',
    code: 'form_tuvan_tintuc',
    status: 'active',
    currentVersion: 1,
    fields: [
      {
        id: 'f31_1',
        fieldKey: 'fullname',
        label: 'Họ và tên',
        fieldType: 'text',
        roleType: 'customer_name',
        placeholder: 'Nguyễn Văn A',
        isRequired: true,
        isLocked: true,
        position: 1,
        validation: { required: true },
      },
      {
        id: 'f31_2',
        fieldKey: 'email',
        label: 'Email liên hệ',
        fieldType: 'email',
        roleType: 'email',
        placeholder: 'email@example.com',
        isRequired: true,
        isLocked: true,
        position: 2,
        validation: { required: true },
      },
      {
        id: 'f31_3',
        fieldKey: 'phone',
        label: 'Số điện thoại',
        fieldType: 'phone',
        roleType: 'phone',
        placeholder: '0912 345 678',
        isRequired: false,
        isLocked: true,
        position: 3,
        validation: { required: false },
      },
      {
        id: 'f31_4',
        fieldKey: 'message',
        label: 'Nội dung thắc mắc',
        fieldType: 'textarea',
        roleType: 'message',
        placeholder: 'Nội dung bạn muốn trao đổi thêm về giải pháp trong bài viết...',
        isRequired: false,
        isLocked: false,
        position: 4,
        validation: { required: false },
      },
    ],
    submitConfig: {
      saveToDatabase: true,
      createCustomerRequest: true,
      sendAdminEmail: true,
      adminEmails: ['nampt@cic.com.vn', 'info@cic.com.vn'],
      sendConfirmationEmail: true,
      submitButtonText: 'Gửi yêu cầu hỗ trợ',
      successMessage: 'Cảm ơn bạn đã gửi thắc mắc! Đội ngũ tư vấn giải pháp CIC sẽ phản hồi qua email hoặc số điện thoại trong 24 giờ.',
      crmSyncEnabled: false,
    },
    analytics: { impressions: 380, clicks: 52, ctr: 13.7 },
    governance: {
      origin: 'custom',
      allowedPlacements: ['cta_action', 'fixed_section'],
    },
    createdBy: 'Quản trị viên',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-25T00:00:00Z',
  },
];
