import {
  BannerContent,
  BannerPlacementConfig,
  ScheduleConflict,
  BannerVersion,
  BannerActivityLog,
} from './types';

export const mockPlacements: BannerPlacementConfig[] = [
  {
    id: 'plc_hero_home',
    name: 'Hero Trang Chủ (Main Slider)',
    code: 'HERO_HOME',
    site_id: 'main_site',
    max_capacity: 5,
    recommended_ratio: '21:9',
    recommended_resolution: '1920x650px',
    description: 'Vùng banner slideshow chính đỉnh trang chủ tập đoàn CIC.',
    active_count: 3,
  },
  {
    id: 'plc_sidebar_news',
    name: 'Sidebar Tin Tức & Sự Kiện',
    code: 'SIDEBAR_NEWS',
    site_id: 'main_site',
    max_capacity: 3,
    recommended_ratio: '4:3',
    recommended_resolution: '400x300px',
    description: 'Vùng banner quảng cáo cột bên phải chuyên mục tin tức.',
    active_count: 2,
  },
  {
    id: 'plc_product_top',
    name: 'Banner Top Danh Mục Sản Phẩm',
    code: 'PRODUCT_TOP',
    site_id: 'main_site',
    max_capacity: 2,
    recommended_ratio: '16:9',
    recommended_resolution: '1200x400px',
    description: 'Banner thương hiệu nổi bật trên cùng trang danh mục phần mềm.',
    active_count: 1,
  },
  {
    id: 'plc_footer_promo',
    name: 'Banner Khuyến Mãi Chân Trang',
    code: 'FOOTER_PROMO',
    site_id: 'main_site',
    max_capacity: 1,
    recommended_ratio: '21:9',
    recommended_resolution: '1440x250px',
    description: 'Dải banner kêu gọi hành động (CTA) ngay trước footer.',
    active_count: 1,
  },
  {
    id: 'plc_popup_event',
    name: 'Pop-up Sự Kiện & Hội Thảo',
    code: 'POPUP_EVENT',
    site_id: 'main_site',
    max_capacity: 1,
    recommended_ratio: '16:9',
    recommended_resolution: '800x450px',
    description: 'Cửa sổ pop-up tự động xuất hiện khi khách truy cập trang chủ.',
    active_count: 1,
  },
];

export const mockBanners: BannerContent[] = [
  {
    id: 'ban_001',
    type: 'slideshow',
    title: 'Slideshow Nổi Bật Chào Mừng 2026 - Giải Pháp BIM & SAP2000',
    alias: 'slideshow-noi-bat-2026',
    site_id: 'main_site',
    placement_id: 'plc_hero_home',
    placement_name: 'Hero Trang Chủ (Main Slider)',
    media_url: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?w=1200&auto=format&fit=crop&q=80',
    media_type: 'image',
    crop_focal_point: 'center',
    alt_text: 'CIC Technology Solutions 2026',
    caption: 'Tiên phong chuyển đổi số trong thiết kế & kiểm định công trình',
    copy_text: 'Tự hào là đối tác chiến lược hàng đầu phân phối phần mềm CSI, Bentley & EnjiCAD tại Việt Nam.',
    cta_text: 'Khám phá ngay',
    link_url: '/products',
    link_target: '_self',
    slides: [
      {
        id: 'sld_101',
        title: 'CSI ETABS V21 & SAP2000 V25 - Bản Quyền Chính Hãng',
        subtitle: 'Cập nhật tiêu chuẩn thiết kế kháng chấn mới nhất 2026',
        media_url: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?w=1200&auto=format&fit=crop&q=80',
        media_type: 'image',
        link_url: '/products/etabs',
        link_target: '_self',
        duration_sec: 5,
        transition_effect: 'fade',
        display_order: 1,
        focal_point: 'center',
      },
      {
        id: 'sld_102',
        title: 'Dự Toán ESCON 2026 - Đơn Giá & Định Mức Mới Bộ Xây Dựng',
        subtitle: 'Bản nâng cấp đột phá tự động kết xuất hồ sơ thầu',
        media_url: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=1200&auto=format&fit=crop&q=80',
        media_type: 'image',
        link_url: '/products/escon',
        link_target: '_self',
        duration_sec: 6,
        transition_effect: 'slide',
        display_order: 2,
        focal_point: 'center',
      },
      {
        id: 'sld_103',
        title: 'Hội Thảo Công Nghệ BIM & CDE Cho Công Trình Giao Thông',
        subtitle: 'Đăng ký tham dự miễn phí ngày 15/08/2026 tại Hà Nội',
        media_url: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&auto=format&fit=crop&q=80',
        media_type: 'image',
        link_url: '/events/bim-cde-2026',
        link_target: '_blank',
        duration_sec: 5,
        transition_effect: 'zoom',
        display_order: 3,
        focal_point: 'center',
      },
    ],
    slideshow_config: {
      auto_play: true,
      interval_ms: 5000,
      effect: 'fade',
      pause_on_hover: true,
      show_dots: true,
      show_arrows: true,
    },
    start_time: '2026-07-01 00:00',
    end_time: '2026-12-31 23:59',
    timezone: 'Asia/Ho_Chi_Minh',
    display_order: 1,
    priority_weight: 9,
    locale_status: { vi: 'complete', en: 'complete', ja: 'in_progress' },
    workflow_status: 'published',
    effective_status: 'running',
    live_version: 'v2.1.0',
    draft_version: 'v2.1.0',
    has_draft_changes: false,
    owner_name: 'Phạm Thị Hương (Marketing)',
    owner_avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    created_at: '2026-06-25 10:00:00',
    updated_at: '2026-07-28 14:30:00',
  },
  {
    id: 'ban_002',
    type: 'banner',
    title: 'Banner Đăng Ký Tư Vấn Bản Quyền EnjiCAD Enterprise 2026',
    alias: 'banner-enjicad-2026',
    site_id: 'main_site',
    placement_id: 'plc_sidebar_news',
    placement_name: 'Sidebar Tin Tức & Sự Kiện',
    media_url: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800&auto=format&fit=crop&q=80',
    media_type: 'image',
    crop_focal_point: 'center',
    alt_text: 'EnjiCAD CAD Software alternative',
    caption: 'Thay thế CAD chi phí thấp bản quyền vĩnh viễn',
    copy_text: 'Giảm 20% chi phí bản quyền khi mua từ 10 licence trở lên.',
    cta_text: 'Nhận báo giá ngay',
    link_url: '/products/enjicad',
    link_target: '_self',
    slides: [],
    slideshow_config: {
      auto_play: false,
      interval_ms: 0,
      effect: 'fade',
      pause_on_hover: false,
      show_dots: false,
      show_arrows: false,
    },
    start_time: '2026-07-15 08:00',
    end_time: '2026-08-31 23:59',
    timezone: 'Asia/Ho_Chi_Minh',
    display_order: 1,
    priority_weight: 8,
    locale_status: { vi: 'complete', en: 'in_progress' },
    workflow_status: 'published',
    effective_status: 'running',
    live_version: 'v1.0.0',
    draft_version: 'v1.1.0-draft',
    has_draft_changes: true,
    owner_name: 'Nguyễn Văn Mạnh (Editor)',
    owner_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    created_at: '2026-07-10 09:15:00',
    updated_at: '2026-07-30 11:20:00',
  },
  {
    id: 'ban_003',
    type: 'banner',
    title: 'Pop-up Thông Báo Mới: Giảm Giá Phần Mềm GEO-Slope Dịp Sinh Nhật',
    alias: 'popup-geoslope-promo',
    site_id: 'main_site',
    placement_id: 'plc_popup_event',
    placement_name: 'Pop-up Sự Kiện & Hội Thảo',
    media_url: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=800&auto=format&fit=crop&q=80',
    media_type: 'image',
    crop_focal_point: 'center',
    alt_text: 'GeoStudio Promotion 2026',
    caption: 'Ưu đãi đặc biệt dành cho các Viện nghiên cứu & Trường Đại học',
    copy_text: 'Tặng bộ thư viện mô hình địa chất 3D độc quyền từ CIC.',
    cta_text: 'Đăng ký ưu đãi',
    link_url: '/promotions/geostudio',
    link_target: '_modal',
    slides: [],
    slideshow_config: {
      auto_play: false,
      interval_ms: 0,
      effect: 'fade',
      pause_on_hover: false,
      show_dots: false,
      show_arrows: false,
    },
    start_time: '2026-08-01 00:00',
    end_time: '2026-08-15 23:59',
    timezone: 'Asia/Ho_Chi_Minh',
    display_order: 1,
    priority_weight: 10,
    locale_status: { vi: 'complete', en: 'outdated' },
    workflow_status: 'approved',
    effective_status: 'upcoming',
    live_version: 'v1.0.0',
    draft_version: 'v1.0.0',
    has_draft_changes: false,
    owner_name: 'Phạm Thị Hương (Marketing)',
    owner_avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    created_at: '2026-07-28 16:00:00',
    updated_at: '2026-07-31 09:00:00',
  },
  {
    id: 'ban_004',
    type: 'slideshow',
    title: 'Slideshow Các Dự Án Tiêu Biểu Ứng Dụng Phần Mềm CIC',
    alias: 'slideshow-du-an-tieu-bieu',
    site_id: 'main_site',
    placement_id: 'plc_product_top',
    placement_name: 'Banner Top Danh Mục Sản Phẩm',
    media_url: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&auto=format&fit=crop&q=80',
    media_type: 'image',
    crop_focal_point: 'center',
    alt_text: 'Projects Showcase',
    caption: 'Hơn 5,000 công trình hạ tầng & dân dụng lớn đã sử dụng sản phẩm CIC',
    copy_text: 'Từ cầu dây văng đến cao ốc 50 tầng đều có sự hiện diện của giải pháp phân tích kết cấu CIC.',
    cta_text: 'Xem hồ sơ năng lực',
    link_url: '/about/projects',
    link_target: '_self',
    slides: [
      {
        id: 'sld_201',
        title: 'Dự án Cầu Nhật Tân - Mô Phỏng Động Đất Với MIDAS',
        subtitle: 'Kiểm soát nội lực & biến dạng nhịp chính',
        media_url: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?w=1200&auto=format&fit=crop&q=80',
        media_type: 'image',
        link_url: '/projects/nhat-tan-bridge',
        link_target: '_self',
        duration_sec: 5,
        transition_effect: 'slide',
        display_order: 1,
        focal_point: 'center',
      },
      {
        id: 'sld_202',
        title: 'Tòa nhà Landmark 81 - Thiết Kế Kết Cấu Kháng Chấn ETABS',
        subtitle: 'Tối ưu hóa khối lượng thép & bê tông cột vách',
        media_url: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&auto=format&fit=crop&q=80',
        media_type: 'image',
        link_url: '/projects/landmark-81',
        link_target: '_self',
        duration_sec: 5,
        transition_effect: 'fade',
        display_order: 2,
        focal_point: 'center',
      },
    ],
    slideshow_config: {
      auto_play: true,
      interval_ms: 6000,
      effect: 'slide',
      pause_on_hover: true,
      show_dots: true,
      show_arrows: true,
    },
    start_time: '2026-06-01 00:00',
    end_time: '2026-08-01 00:00',
    timezone: 'Asia/Ho_Chi_Minh',
    display_order: 1,
    priority_weight: 7,
    locale_status: { vi: 'complete', en: 'complete' },
    workflow_status: 'published',
    effective_status: 'ended',
    live_version: 'v1.0.0',
    draft_version: 'v1.0.0',
    has_draft_changes: false,
    owner_name: 'Trần Văn Mạnh (Admin)',
    owner_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    created_at: '2026-05-20 11:00:00',
    updated_at: '2026-08-01 00:05:00',
  },
  {
    id: 'ban_005',
    type: 'banner',
    title: 'Dải Banner Chân Trang: Liên Hệ Bộ Phận Hỗ Trợ Kỹ Thuật 24/7',
    alias: 'footer-tech-support-banner',
    site_id: 'main_site',
    placement_id: 'plc_footer_promo',
    placement_name: 'Banner Khuyến Mãi Chân Trang',
    media_url: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1200&auto=format&fit=crop&q=80',
    media_type: 'image',
    crop_focal_point: 'center',
    alt_text: 'Support hotline 24/7',
    caption: 'Đội ngũ chuyên gia kỹ thuật CIC luôn sẵn sàng đồng hành',
    copy_text: 'Hotline: 024.3822.9988 | Email: support@cic.com.vn',
    cta_text: 'Gửi yêu cầu hỗ trợ',
    link_url: '/contact',
    link_target: '_self',
    slides: [],
    slideshow_config: {
      auto_play: false,
      interval_ms: 0,
      effect: 'fade',
      pause_on_hover: false,
      show_dots: false,
      show_arrows: false,
    },
    start_time: '2026-01-01 00:00',
    end_time: '2026-12-31 23:59',
    timezone: 'Asia/Ho_Chi_Minh',
    display_order: 1,
    priority_weight: 6,
    locale_status: { vi: 'complete', en: 'missing' },
    workflow_status: 'published',
    effective_status: 'running',
    live_version: 'v1.2.0',
    draft_version: 'v1.2.0',
    has_draft_changes: false,
    owner_name: 'Trần Văn Mạnh (Admin)',
    owner_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    created_at: '2026-01-05 08:30:00',
    updated_at: '2026-07-15 10:20:00',
  },
  {
    id: 'ban_006',
    type: 'banner',
    title: 'Banner Xung Đột Lịch: Khuyến Mãi Khóa Học CAD/BIM Tháng 8',
    alias: 'banner-conflict-cad-bim',
    site_id: 'main_site',
    placement_id: 'plc_popup_event',
    placement_name: 'Pop-up Sự Kiện & Hội Thảo',
    media_url: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&auto=format&fit=crop&q=80',
    media_type: 'image',
    crop_focal_point: 'center',
    alt_text: 'BIM Training course',
    caption: 'Xung đột thời gian với Pop-up GeoSlope (Chỉ cho phép 1 Pop-up chạy cùng lúc)',
    copy_text: 'Tặng 30% học phí cho học viên đăng ký nhóm 3 người trở lên.',
    cta_text: 'Xem lịch khai giảng',
    link_url: '/training/schedule',
    link_target: '_self',
    slides: [],
    slideshow_config: {
      auto_play: false,
      interval_ms: 0,
      effect: 'fade',
      pause_on_hover: false,
      show_dots: false,
      show_arrows: false,
    },
    start_time: '2026-08-05 08:00',
    end_time: '2026-08-20 23:59',
    timezone: 'Asia/Ho_Chi_Minh',
    display_order: 2,
    priority_weight: 9,
    locale_status: { vi: 'complete', en: 'missing' },
    workflow_status: 'pending_review',
    effective_status: 'conflict',
    live_version: 'v0.9.0',
    draft_version: 'v1.0.0-draft',
    has_draft_changes: true,
    owner_name: 'Lê Hoàng Anh (Editor)',
    owner_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    created_at: '2026-07-30 14:00:00',
    updated_at: '2026-07-31 08:30:00',
  },
];

export const mockConflicts: ScheduleConflict[] = [
  {
    id: 'cnf_001',
    placement_id: 'plc_popup_event',
    placement_name: 'Pop-up Sự Kiện & Hội Thảo',
    conflicting_item_ids: ['ban_003', 'ban_006'],
    conflicting_item_titles: [
      'Pop-up Thông Báo Mới: Giảm Giá Phần Mềm GEO-Slope Dịp Sinh Nhật',
      'Banner Xung Đột Lịch: Khuyến Mãi Khóa Học CAD/BIM Tháng 8',
    ],
    severity: 'critical',
    description: 'Vị trí Pop-up chỉ cho phép 1 nội dung hiển thị tối đa tại cùng thời điểm. Thời gian từ 05/08 - 15/08 bị trùng lặp.',
  },
];

export const mockVersions: BannerVersion[] = [
  {
    version_id: 'ver_101',
    version_number: 2.1,
    banner_id: 'ban_001',
    published_at: '2026-07-28 14:30:00',
    published_by: 'Phạm Thị Hương (Marketing)',
    change_summary: 'Thêm slide mới giới thiệu Hội thảo BIM/CDE 2026 & điều chỉnh hiệu ứng chuyển màu Fade sang Zoom.',
    is_current_live: true,
  },
  {
    version_id: 'ver_100',
    version_number: 2.0,
    banner_id: 'ban_001',
    published_at: '2026-07-01 00:00:00',
    published_by: 'Trần Văn Mạnh (Admin)',
    change_summary: 'Khởi tạo phiên bản Slideshow chính đầu quý III năm 2026.',
    is_current_live: false,
  },
];

export const mockActivityLogs: BannerActivityLog[] = [
  {
    id: 'act_001',
    timestamp: '2026-07-31 09:00:00',
    user_name: 'Phạm Thị Hương',
    user_avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    action_type: 'update',
    description: 'Phê duyệt bản thảo Pop-up GeoSlope và chuyển trạng thái sang Approved (Sắp chạy).',
  },
  {
    id: 'act_002',
    timestamp: '2026-07-30 14:00:00',
    user_name: 'Lê Hoàng Anh',
    user_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    action_type: 'create',
    description: 'Tạo bản thảo Banner khuyến mãi khóa học CAD/BIM tháng 8 gửi yêu cầu duyệt.',
  },
  {
    id: 'act_003',
    timestamp: '2026-07-28 14:30:00',
    user_name: 'Phạm Thị Hương',
    user_avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    action_type: 'publish',
    description: 'Xuất bản thành công phiên bản v2.1.0 của Hero Slideshow 2026.',
  },
];
