import 'server-only';
import type { Sql } from 'postgres';
import { withTransaction } from '@/server/db/postgres';
import type { CmsPrincipal } from '@/server/auth/guards';
import { AUDIT_ACTIONS,AUDIT_ENTITY_TYPES } from '@/server/audit/registry';
import { writeAuditEvent } from '@/server/audit/writer';
import type { ProductCategoryInput } from '../schemas/categoryInput';
import type { ProductCategoryLocale } from '../types';
import { moveProductCategoryToTrash } from '@/features/trash/server/adapters/product-category';
const names=(l:ProductCategoryLocale)=>({category:l==='en'?'cic_products_categories_en':'cic_products_categories'});
async function validate(sql:Sql,locale:ProductCategoryLocale,input:ProductCategoryInput,id?:number){const{category}=names(locale);if((await sql.unsafe(`SELECT 1 FROM ${category} WHERE lower(btrim(alias))=lower(btrim($1)) AND ($2::int IS NULL OR id<>$2) LIMIT 1`,[input.alias,id??null])).length)throw new Error('Alias đã được một danh mục khác sử dụng.');if(input.parentId!=null){if(id===input.parentId)throw new Error('Danh mục không thể là cha của chính nó.');if(!(await sql.unsafe(`SELECT 1 FROM ${category} WHERE id=$1`,[input.parentId])).length)throw new Error('Danh mục cha không tồn tại.');if(id&&(await sql.unsafe(`WITH RECURSIVE tree AS (SELECT id FROM ${category} WHERE parent_id=$1 UNION ALL SELECT c.id FROM ${category} c JOIN tree t ON c.parent_id=t.id) SELECT 1 FROM tree WHERE id=$2 LIMIT 1`,[id,input.parentId])).length)throw new Error('Không thể chọn một danh mục con làm danh mục cha.');}}
async function hierarchy(sql:Sql,locale:ProductCategoryLocale,parentId:number|null){if(parentId==null)return{level:1,rootId:null as number|null,rootAlias:null as string|null,listParents:null as string|null};const{category}=names(locale);const[parent]=await sql.unsafe(`SELECT id,alias,level,root_id,root_alias,list_parents FROM ${category} WHERE id=$1`,[parentId]);if(!parent)throw new Error('Danh mục cha không tồn tại.');return{level:Number(parent.level??1)+1,rootId:Number(parent.root_id??parent.id),rootAlias:String(parent.root_alias??parent.alias??'')||null,listParents:[String(parent.list_parents??'').replace(/^,|,$/g,''),String(parent.id)].filter(Boolean).join(',')}}
async function rebuildHierarchy(sql:Sql,locale:ProductCategoryLocale){const{category}=names(locale);await sql.unsafe(`WITH RECURSIVE tree AS (SELECT id,parent_id,alias,1 level,id root_id,alias root_alias,''::text list_parents FROM ${category} WHERE parent_id IS NULL UNION ALL SELECT c.id,c.parent_id,c.alias,t.level+1,t.root_id,t.root_alias,concat_ws(',',nullif(t.list_parents,''),t.id::text) FROM ${category} c JOIN tree t ON c.parent_id=t.id) UPDATE ${category} c SET level=t.level,root_id=CASE WHEN t.level=1 THEN NULL ELSE t.root_id END,root_alias=CASE WHEN t.level=1 THEN NULL ELSE t.root_alias END,list_parents=NULLIF(t.list_parents,'') FROM tree t WHERE c.id=t.id`);}
export async function saveProductCategory(locale:ProductCategoryLocale,id:number|null,input:ProductCategoryInput,actor:CmsPrincipal){return withTransaction(async sql=>{await validate(sql,locale,input,id??undefined);const{category}=names(locale),d=await hierarchy(sql,locale,input.parentId);const before=id?(await sql.unsafe(`SELECT id,name,alias,description,parent_id,ordering,published FROM ${category} WHERE id=$1 FOR UPDATE`,[id]))[0]:null;if(id&&!before)throw new Error('Không tìm thấy danh mục.');const v=[input.name,input.alias,input.description,input.parentId,input.ordering,input.published,d.level,d.rootId,d.rootAlias,d.listParents,id];const rows=id?await sql.unsafe(`UPDATE ${category} SET name=$1,alias=$2,description=$3,parent_id=$4,ordering=$5,published=$6,level=$7,root_id=$8,root_alias=$9,list_parents=$10,updated_time=now() WHERE id=$11 RETURNING id,name`,v):await sql.unsafe(`INSERT INTO ${category} (name,alias,description,parent_id,ordering,published,level,root_id,root_alias,list_parents,vat,created_time,updated_time) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,0,now(),now()) RETURNING id,name`,v.slice(0,10));await rebuildHierarchy(sql,locale);const row=rows[0],entityId=String(row.id);await writeAuditEvent(actor,{action:id?AUDIT_ACTIONS.PRODUCT_CATEGORY_UPDATED:AUDIT_ACTIONS.PRODUCT_CATEGORY_CREATED,entityType:AUDIT_ENTITY_TYPES.PRODUCT_CATEGORY,entityId,entityTitle:String(row.name),module:'product_settings',workspace:locale,result:'success',before,after:{name:input.name,alias:input.alias,parentId:input.parentId,ordering:input.ordering,published:input.published}},sql);return{id:entityId};});}
export async function setProductCategoriesPublished(locale:ProductCategoryLocale,ids:number[],published:boolean,actor:CmsPrincipal){return withTransaction(async sql=>{const{category}=names(locale);const rows=await sql.unsafe(`UPDATE ${category} SET published=$1,updated_time=now() WHERE id=ANY($2::int[]) RETURNING id,name`,[published,ids]);if(rows.length!==ids.length)throw new Error('Một hoặc nhiều danh mục không còn tồn tại.');for(const row of rows)await writeAuditEvent(actor,{action:AUDIT_ACTIONS.PRODUCT_CATEGORY_STATUS_CHANGED,entityType:AUDIT_ENTITY_TYPES.PRODUCT_CATEGORY,entityId:String(row.id),entityTitle:String(row.name),module:'product_settings',workspace:locale,result:'success',after:{published}},sql);});}
export async function trashProductCategory(locale:ProductCategoryLocale,id:number,actor:CmsPrincipal){return withTransaction(async sql=>{const moved=await moveProductCategoryToTrash(sql,locale,id,actor.legacyUserId);await writeAuditEvent(actor,{action:AUDIT_ACTIONS.PRODUCT_CATEGORY_TRASHED,entityType:AUDIT_ENTITY_TYPES.PRODUCT_CATEGORY,entityId:String(id),entityTitle:moved.title,module:'product_settings',workspace:locale,result:'success',before:{publishedSourceRemoved:true},after:{trashId:moved.trashId,state:'trashed'}},sql);return moved;});}
