import { AuditEvent, TrashedItem, ExportJob } from './types';

export const initialAuditLogsMock: AuditEvent[] = [
  {
    id: 'evt_20260804_001',
    timestamp: '2026-08-04 09:32:15',
    actor: {
      id: 'usr_admin_cic',
      name: 'Nguyễn Văn Minh (Admin)',
      email: 'minh.nguyen@cic.com.vn',
      role: 'Super Admin',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
      ipAddress: '118.70.182.95',
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
    },
    action: {
      code: 'SYSTEM_CONFIG_UPDATE',
      label: 'Cập nhật Cấu hình SMTP & API Key',
      category: 'config_publish',
      severity: 'critical',
      isSensitive: true,
    },
    target: {
      type: 'ConfigScope',
      id: 'site_cic',
      title: 'Tập đoàn CIC Technology (Default Scope)',
      module: 'Cấu hình Hệ thống',
    },
    scope: {
      siteId: 'site_cic',
      siteName: 'CIC Main Portal',
      locale: 'vi-VN',
    },
    result: 'success',
    resultMessage: 'Đã cập nhật giá trị bí mật SMTP Password & Gemini API Key.',
    context: {
      sessionId: 'sess_993820482',
      correlationId: 'corr_cfg_8832',
      sourceApp: 'CMS Admin Portal',
      environment: 'production',
    },
    changes: [
      {
        field: 'smtp_password',
        oldValue: '••••••••••••',
        newValue: '••••••••••••',
        isRedacted: true,
        redactionReason: 'Mật khẩu SMTP bị che khuất tuân thủ ISO 27001 Security Standard.',
      },
      {
        field: 'gemini_api_key',
        oldValue: 'AIzaSyA882...[REDACTED]',
        newValue: 'AIzaSyB994...[REDACTED]',
        isRedacted: true,
        redactionReason: 'Secret API Key không được hiển thị plain text trong Audit Logs.',
      },
      {
        field: 'site_title',
        oldValue: 'CIC Technology JSC',
        newValue: 'Tập đoàn Công nghệ CIC - Chuyển đổi số enjiCAD',
        isRedacted: false,
      },
    ],
    technicalRef: {
      httpMethod: 'PUT',
      endpoint: '/api/v2/system-config/scopes/site_cic',
      executionTimeMs: 142,
    },
  },
  {
    id: 'evt_20260804_002',
    timestamp: '2026-08-04 09:15:02',
    actor: {
      id: 'usr_sec_audit',
      name: 'Trần Thị Thu (Auditor)',
      email: 'thu.tran@cic.com.vn',
      role: 'Security Auditor',
      ipAddress: '27.72.60.18',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    },
    action: {
      code: 'PERMISSION_REVOKE',
      label: 'Thu hồi Quyền Xuất bản (Publishing Role)',
      category: 'permissions_users',
      severity: 'high',
      isSensitive: true,
    },
    target: {
      type: 'User',
      id: 'usr_editor_05',
      title: 'Lê Hoàng Nam (Biên tập viên)',
      module: 'Quản lý Phân quyền',
    },
    scope: {
      siteId: 'site_enjicad',
      siteName: 'Phần mềm enjiCAD Portal',
    },
    result: 'success',
    resultMessage: 'Thu hồi vai trò Publisher do thay đổi nhân sự.',
    context: {
      sessionId: 'sess_11203948',
      correlationId: 'corr_perm_1102',
      sourceApp: 'CMS Security Console',
      environment: 'production',
    },
    changes: [
      {
        field: 'assigned_roles',
        oldValue: ['ContentEditor', 'ContentPublisher'],
        newValue: ['ContentEditor'],
        isRedacted: false,
      },
    ],
  },
  {
    id: 'evt_20260804_003',
    timestamp: '2026-08-04 08:45:20',
    actor: {
      id: 'usr_editor_02',
      name: 'Phạm Thanh Hương',
      email: 'huong.pham@cic.com.vn',
      role: 'Content Manager',
      ipAddress: '14.232.208.12',
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
    },
    action: {
      code: 'ARTICLE_DELETE_SOFT',
      label: 'Xóa mềm Bài viết Tin tức (Move to Trash)',
      category: 'all',
      severity: 'medium',
      isSensitive: false,
    },
    target: {
      type: 'NewsArticle',
      id: 'news_9021',
      title: 'Hội thảo Công nghệ xây dựng BIM 2026 tại Hà Nội',
      url: '/tin-tuc/hoi-thao-bim-2026',
      module: 'Bài viết Tin tức',
    },
    scope: {
      siteId: 'site_cic',
      siteName: 'CIC Main Portal',
      locale: 'vi-VN',
    },
    result: 'success',
    resultMessage: 'Đã chuyển bài viết vào Thùng rác (Recycle Bin) kèm retention countdown 30 ngày.',
    context: {
      sessionId: 'sess_5510293',
      correlationId: 'corr_del_9021',
      sourceApp: 'CMS Content Editor',
      environment: 'production',
    },
    changes: [
      {
        field: 'status',
        oldValue: 'published',
        newValue: 'trashed',
        isRedacted: false,
      },
      {
        field: 'deleted_at',
        oldValue: null,
        newValue: '2026-08-04 08:45:20',
        isRedacted: false,
      },
    ],
  },
  {
    id: 'evt_20260804_004',
    timestamp: '2026-08-04 08:10:11',
    actor: {
      id: 'usr_system_job',
      name: 'Automated System Worker',
      email: 'system-worker@cic.internal',
      role: 'System Worker',
      ipAddress: '10.0.4.12',
      userAgent: 'CIC-CronWorker/2.4.0',
    },
    action: {
      code: 'EXPORT_AUDIT_LOGS',
      label: 'Tạo tệp Xuất dữ liệu Nhật ký Báo cáo (Export Audit Log)',
      category: 'export_jobs',
      severity: 'medium',
      isSensitive: false,
    },
    target: {
      type: 'ExportJob',
      id: 'job_exp_881',
      title: 'Audit_Logs_July_2026.xlsx',
      module: 'Export Manager',
    },
    scope: {
      siteId: 'global',
      siteName: 'Toàn bộ Scope Hệ thống',
    },
    result: 'success',
    resultMessage: 'Đã tạo xong file Excel 1,250 dòng nhật ký kiểm toán.',
    context: {
      sessionId: 'sess_cron_110',
      correlationId: 'corr_exp_881',
      sourceApp: 'Background Job Engine',
      environment: 'production',
    },
  },
  {
    id: 'evt_20260804_005',
    timestamp: '2026-08-03 17:40:00',
    actor: {
      id: 'usr_editor_05',
      name: 'Lê Hoàng Nam',
      email: 'nam.le@cic.com.vn',
      role: 'Content Editor',
      ipAddress: '113.190.22.81',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    },
    action: {
      code: 'LOGIN_FAILED_DENIED',
      label: 'Đăng nhập Thất bại (Sai Mật khẩu / Khóa tài khoản)',
      category: 'sensitive',
      severity: 'high',
      isSensitive: true,
    },
    target: {
      type: 'UserAccount',
      id: 'usr_editor_05',
      title: 'Tài khoản nam.le@cic.com.vn',
      module: 'Xác thực Đăng nhập',
    },
    scope: {
      siteId: 'global',
      siteName: 'Auth Service',
    },
    result: 'denied',
    resultMessage: 'Đăng nhập thất bại lần thứ 3 liên tiếp. IP đã bị đưa vào danh sách cảnh báo.',
    context: {
      sessionId: 'sess_failed_882',
      correlationId: 'corr_auth_882',
      sourceApp: 'OAuth Gateway',
      environment: 'production',
    },
    changes: [
      {
        field: 'failed_attempts_count',
        oldValue: 2,
        newValue: 3,
        isRedacted: false,
      },
    ],
  },
];

export const initialTrashedItemsMock: TrashedItem[] = [
  {
    id: 'trash_001',
    title: 'Hội thảo Công nghệ xây dựng BIM 2026 tại Hà Nội',
    itemType: 'Bài viết Tin tức',
    moduleName: 'Bài viết & Tin tức',
    scope: {
      siteId: 'site_cic',
      siteName: 'CIC Main Portal',
    },
    deletedBy: {
      id: 'usr_editor_02',
      name: 'Phạm Thanh Hương',
      role: 'Content Manager',
    },
    deletedAt: '2026-08-04 08:45:20',
    expiresAt: '2026-09-03 08:45:20',
    daysRemaining: 30,
    isLegalHold: false,
    dependencyStatus: 'clear',
    dependencyDetails: 'Không có liên kết phụ thuộc bị hỏng. Sẵn sàng phục hồi về Bản nháp (Draft).',
    originalUrl: '/tin-tuc/hoi-thao-bim-2026',
    targetRestoreState: 'draft',
    snapshotData: {
      slug: 'hoi-thao-bim-2026',
      author: 'Phạm Thanh Hương',
      category: 'Sự kiện & Hội thảo',
      featuredImage: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=600&auto=format&fit=crop&q=80',
      contentLength: '2,450 từ',
    },
  },
  {
    id: 'trash_002',
    title: 'Banner Khuyến mãi enjiCAD 2026 Pro Version',
    itemType: 'Media Banner',
    moduleName: 'Banners & Slideshow',
    scope: {
      siteId: 'site_enjicad',
      siteName: 'Phần mềm enjiCAD Portal',
    },
    deletedBy: {
      id: 'usr_admin_cic',
      name: 'Nguyễn Văn Minh',
      role: 'Super Admin',
    },
    deletedAt: '2026-08-01 14:20:10',
    expiresAt: '2026-08-08 14:20:10',
    daysRemaining: 4,
    isLegalHold: false,
    dependencyStatus: 'conflict',
    dependencyDetails: 'Cảnh báo: Tên nhóm Banner "Trang chủ enjiCAD" đã bị thay đổi hoặc liên kết bị đứt đoạn.',
    originalUrl: 'https://cdn.cic.com.vn/banners/enjicad_pro_2026.png',
    targetRestoreState: 'inactive',
    snapshotData: {
      dimensions: '1920x600px',
      fileSize: '1.4 MB',
      targetCategory: 'Homepage Hero Banner',
    },
  },
  {
    id: 'trash_003',
    title: 'Trang Giới thiệu Phòng Thử nghiệm Vật liệu Xây dựng LAS-XD',
    itemType: 'Trang tĩnh',
    moduleName: 'Trang tĩnh (Static Pages)',
    scope: {
      siteId: 'site_cic',
      siteName: 'CIC Main Portal',
    },
    deletedBy: {
      id: 'usr_editor_05',
      name: 'Lê Hoàng Nam',
      role: 'Content Editor',
    },
    deletedAt: '2026-07-10 11:00:00',
    expiresAt: '2026-08-09 11:00:00',
    daysRemaining: 5,
    isLegalHold: true,
    legalHoldReason: 'Đang thuộc diện giữ chân pháp lý (Legal Hold) phục vụ thanh tra hồ sơ năng lực 2026.',
    dependencyStatus: 'parent_trashed',
    dependencyDetails: 'Thư mục mẹ "Dịch vụ Thử nghiệm" hiện cũng đang nằm trong Thùng rác.',
    originalUrl: '/dich-vu/las-xd/gioi-thieu',
    targetRestoreState: 'draft',
    snapshotData: {
      template: 'Standard Article Layout',
      sectionsCount: 6,
    },
  },
  {
    id: 'trash_004',
    title: 'Cấu hình Tích hợp Zalopay Sandbox v1',
    itemType: 'Tài nguyên Quản trị',
    moduleName: 'Cấu hình Hệ thống',
    scope: {
      siteId: 'global',
      siteName: 'Global Scope',
    },
    deletedBy: {
      id: 'usr_admin_cic',
      name: 'Nguyễn Văn Minh',
      role: 'Super Admin',
    },
    deletedAt: '2026-07-28 09:12:00',
    expiresAt: '2026-08-27 09:12:00',
    daysRemaining: 23,
    isLegalHold: false,
    dependencyStatus: 'clear',
    dependencyDetails: 'Sẵn sàng khôi phục về trạng thái Cấu hình Nháp.',
    targetRestoreState: 'draft',
    snapshotData: {
      gateway: 'ZaloPay Payment Gateway',
      environment: 'sandbox',
    },
  },
];

export const initialExportJobsMock: ExportJob[] = [
  {
    id: 'job_exp_001',
    requestedAt: '2026-08-04 08:10:11',
    requestedBy: 'Nguyễn Văn Minh (Admin)',
    scopeName: 'Toàn bộ Scope Hệ thống',
    dateRange: '01/07/2026 - 31/07/2026',
    filterSummary: 'Hành động: Critical & Sensitive Audit Logs',
    status: 'completed',
    totalRecords: 1250,
    fileSizeMb: 2.8,
    downloadUrl: '#download_export_001',
    expiresAt: '2026-08-11 08:10:11',
  },
  {
    id: 'job_exp_002',
    requestedAt: '2026-08-03 16:22:00',
    requestedBy: 'Trần Thị Thu (Auditor)',
    scopeName: 'CIC Main Portal',
    dateRange: 'Hôm nay',
    filterSummary: 'Chỉ log Phân quyền & Thay đổi Người dùng',
    status: 'completed',
    totalRecords: 340,
    fileSizeMb: 0.9,
    downloadUrl: '#download_export_002',
    expiresAt: '2026-08-10 16:22:00',
  },
];
