export const AUDIT_ACTIONS = {
  SETTINGS_UPDATED: 'settings.updated',
  EXPORT_CREATED: 'audit.export_created',
  EXPORT_DOWNLOADED: 'audit.export_downloaded',
  ROLE_CREATED: 'role.created',
  ROLE_UPDATED: 'role.updated',
  ROLE_STATUS_CHANGED: 'role.status_changed',
  ROLE_ASSIGNED: 'role.assigned',
  ROLE_REVOKED: 'role.revoked',
  USER_CREATED: 'user.created',
  USER_UPDATED: 'user.updated',
  USER_STATUS_CHANGED: 'user.status_changed',
  USER_PASSWORD_RESET_REQUESTED: 'user.password_reset_requested',
  USER_TRASHED: 'user.trashed',
  ROLE_TRASHED: 'role.trashed',
  PROJECT_TRASHED: 'project.trashed',
  MEDIA_CREATED: 'media.created',
  MEDIA_UPDATED: 'media.updated',
  MEDIA_REPLACED: 'media.replaced',
  MEDIA_TRASHED: 'media.trashed',
  MEDIA_ALBUM_CREATED: 'media_album.created',
  MEDIA_ALBUM_UPDATED: 'media_album.updated',
  MEDIA_ALBUM_DELETED: 'media_album.deleted',
  MEDIA_FOLDER_CREATED: 'media_folder.created',
  PRODUCT_CATEGORY_CREATED: 'product_category.created',
  PRODUCT_CATEGORY_UPDATED: 'product_category.updated',
  PRODUCT_CATEGORY_STATUS_CHANGED: 'product_category.status_changed',
  PRODUCT_CATEGORY_TRASHED: 'product_category.trashed',
  PRODUCT_BRAND_CREATED: 'product_brand.created',
  PRODUCT_BRAND_UPDATED: 'product_brand.updated',
  PRODUCT_BRAND_STATUS_CHANGED: 'product_brand.status_changed',
  PRODUCT_BRAND_TRASHED: 'product_brand.trashed',
  PRODUCT_APPLICATION_CREATED: 'product_application.created',
  PRODUCT_APPLICATION_UPDATED: 'product_application.updated',
  PRODUCT_APPLICATION_STATUS_CHANGED: 'product_application.status_changed',
  PRODUCT_APPLICATION_TRASHED: 'product_application.trashed',
  PRODUCT_TYPE_CREATED: 'product_type.created',
  PRODUCT_TYPE_UPDATED: 'product_type.updated',
  PRODUCT_TYPE_STATUS_CHANGED: 'product_type.status_changed',
  PRODUCT_TYPE_TRASHED: 'product_type.trashed',
  PRODUCT_CREATED: 'product.created',
  PRODUCT_UPDATED: 'product.updated',
  PRODUCT_STATUS_CHANGED: 'product.status_changed',
  PRODUCT_TRASHED: 'product.trashed',
  SALES_OWNER_CREATED: 'sales_owner.created',
  SALES_OWNER_UPDATED: 'sales_owner.updated',
  SALES_OWNER_STATUS_CHANGED: 'sales_owner.status_changed',
  SALES_OWNER_TRASHED: 'sales_owner.trashed',
  NEWS_CREATED: 'news.created',
  NEWS_UPDATED: 'news.updated',
  NEWS_STATUS_CHANGED: 'news.status_changed',
  NEWS_TRASHED: 'news.trashed',
  NEWS_CATEGORY_CREATED: 'news_category.created',
  NEWS_CATEGORY_UPDATED: 'news_category.updated',
  NEWS_CATEGORY_STATUS_CHANGED: 'news_category.status_changed',
  NEWS_CATEGORY_TRASHED: 'news_category.trashed',
  EVENT_CREATED: 'event.created',
  EVENT_UPDATED: 'event.updated',
  EVENT_STATUS_CHANGED: 'event.status_changed',
  EVENT_TRASHED: 'event.trashed',
  PROJECT_CREATED: 'project.created',
  PROJECT_UPDATED: 'project.updated',
  PROJECT_STATUS_CHANGED: 'project.status_changed',
  SERVICE_CREATED: 'service.created',
  SERVICE_UPDATED: 'service.updated',
  SERVICE_STATUS_CHANGED: 'service.status_changed',
  SERVICE_TRASHED: 'service.trashed',
  STATIC_PAGE_CREATED: 'static_page.created',
  STATIC_PAGE_UPDATED: 'static_page.updated',
  STATIC_PAGE_STATUS_CHANGED: 'static_page.status_changed',
  STATIC_PAGE_TRASHED: 'static_page.trashed',
  MENU_CREATED: 'menu.created',
  MENU_UPDATED: 'menu.updated',
  MENU_TRASHED: 'menu.trashed',
  FORM_CREATED: 'form.created',
  FORM_UPDATED: 'form.updated',
  FORM_TRASHED: 'form.trashed',
  CUSTOMER_REQUEST_STATUS_CHANGED: 'customer_request.status_changed',
  EMAIL_TEMPLATE_CREATED: 'email_template.created',
  EMAIL_TEMPLATE_UPDATED: 'email_template.updated',
  EMAIL_TEMPLATE_PUBLISHED: 'email_template.published',
  EMAIL_TEMPLATE_TRASHED: 'email_template.trashed',
  TRASH_RESTORED: 'trash.restored',
  TRASH_PURGED: 'trash.purged',
} as const;

export const AUDIT_ENTITY_TYPES = {
  SYSTEM_SETTINGS: 'system_settings',
  AUDIT_EXPORT: 'audit_export',
  ROLE: 'role',
  ROLE_ASSIGNMENT: 'role_assignment',
  USER: 'user',
  PROJECT: 'project',
  MEDIA_ASSET: 'media_asset',
  MEDIA_ALBUM: 'media_album',
  MEDIA_FOLDER: 'media_folder',
  PRODUCT_CATEGORY: 'product_category',
  PRODUCT_BRAND: 'product_brand',
  PRODUCT_APPLICATION: 'product_application',
  PRODUCT_TYPE: 'product_type',
  PRODUCT: 'product',
  SALES_OWNER: 'sales_owner',
  NEWS: 'news',
  NEWS_CATEGORY: 'news_category',
  EVENT: 'event',
  SERVICE: 'service',
  STATIC_PAGE: 'static_page',
  MENU: 'menu',
  FORM: 'form',
  CUSTOMER_REQUEST: 'customer_request',
  EMAIL_TEMPLATE: 'email_template',
  TRASH_ITEM: 'trash_item',
} as const;

export const AUDIT_WORKSPACES = ['global', 'vi', 'en'] as const;
export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
export type AuditEntityType = (typeof AUDIT_ENTITY_TYPES)[keyof typeof AUDIT_ENTITY_TYPES];
export type AuditWorkspace = (typeof AUDIT_WORKSPACES)[number];

export const auditActionRegistry = {
  [AUDIT_ACTIONS.SETTINGS_UPDATED]: { category: 'config_publish', severity: 'high', entityType: AUDIT_ENTITY_TYPES.SYSTEM_SETTINGS },
  [AUDIT_ACTIONS.EXPORT_CREATED]: { category: 'export_jobs', severity: 'medium', entityType: AUDIT_ENTITY_TYPES.AUDIT_EXPORT },
  [AUDIT_ACTIONS.EXPORT_DOWNLOADED]: { category: 'export_jobs', severity: 'medium', entityType: AUDIT_ENTITY_TYPES.AUDIT_EXPORT },
  [AUDIT_ACTIONS.ROLE_CREATED]: { category: 'access_control', severity: 'high', entityType: AUDIT_ENTITY_TYPES.ROLE },
  [AUDIT_ACTIONS.ROLE_UPDATED]: { category: 'access_control', severity: 'high', entityType: AUDIT_ENTITY_TYPES.ROLE },
  [AUDIT_ACTIONS.ROLE_STATUS_CHANGED]: { category: 'access_control', severity: 'high', entityType: AUDIT_ENTITY_TYPES.ROLE },
  [AUDIT_ACTIONS.ROLE_ASSIGNED]: { category: 'access_control', severity: 'high', entityType: AUDIT_ENTITY_TYPES.ROLE_ASSIGNMENT },
  [AUDIT_ACTIONS.ROLE_REVOKED]: { category: 'access_control', severity: 'high', entityType: AUDIT_ENTITY_TYPES.ROLE_ASSIGNMENT },
  [AUDIT_ACTIONS.USER_CREATED]: { category: 'permissions_users', severity: 'high', entityType: AUDIT_ENTITY_TYPES.USER },
  [AUDIT_ACTIONS.USER_UPDATED]: { category: 'permissions_users', severity: 'high', entityType: AUDIT_ENTITY_TYPES.USER },
  [AUDIT_ACTIONS.USER_STATUS_CHANGED]: { category: 'permissions_users', severity: 'high', entityType: AUDIT_ENTITY_TYPES.USER },
  [AUDIT_ACTIONS.USER_PASSWORD_RESET_REQUESTED]: { category: 'permissions_users', severity: 'medium', entityType: AUDIT_ENTITY_TYPES.USER },
  [AUDIT_ACTIONS.USER_TRASHED]: { category: 'permissions_users', severity: 'critical', entityType: AUDIT_ENTITY_TYPES.USER },
  [AUDIT_ACTIONS.ROLE_TRASHED]: { category: 'access_control', severity: 'critical', entityType: AUDIT_ENTITY_TYPES.ROLE },
  [AUDIT_ACTIONS.PROJECT_TRASHED]: { category: 'config_publish', severity: 'high', entityType: AUDIT_ENTITY_TYPES.PROJECT },
  [AUDIT_ACTIONS.PROJECT_CREATED]: { category: 'config_publish', severity: 'medium', entityType: AUDIT_ENTITY_TYPES.PROJECT },
  [AUDIT_ACTIONS.PROJECT_UPDATED]: { category: 'config_publish', severity: 'medium', entityType: AUDIT_ENTITY_TYPES.PROJECT },
  [AUDIT_ACTIONS.PROJECT_STATUS_CHANGED]: { category: 'config_publish', severity: 'high', entityType: AUDIT_ENTITY_TYPES.PROJECT },
  [AUDIT_ACTIONS.MEDIA_CREATED]: { category: 'config_publish', severity: 'medium', entityType: AUDIT_ENTITY_TYPES.MEDIA_ASSET },
  [AUDIT_ACTIONS.MEDIA_UPDATED]: { category: 'config_publish', severity: 'medium', entityType: AUDIT_ENTITY_TYPES.MEDIA_ASSET },
  [AUDIT_ACTIONS.MEDIA_REPLACED]: { category: 'config_publish', severity: 'high', entityType: AUDIT_ENTITY_TYPES.MEDIA_ASSET },
  [AUDIT_ACTIONS.MEDIA_TRASHED]: { category: 'config_publish', severity: 'high', entityType: AUDIT_ENTITY_TYPES.MEDIA_ASSET },
  [AUDIT_ACTIONS.MEDIA_ALBUM_CREATED]: { category: 'config_publish', severity: 'medium', entityType: AUDIT_ENTITY_TYPES.MEDIA_ALBUM },
  [AUDIT_ACTIONS.MEDIA_ALBUM_UPDATED]: { category: 'config_publish', severity: 'medium', entityType: AUDIT_ENTITY_TYPES.MEDIA_ALBUM },
  [AUDIT_ACTIONS.MEDIA_ALBUM_DELETED]: { category: 'config_publish', severity: 'medium', entityType: AUDIT_ENTITY_TYPES.MEDIA_ALBUM },
  [AUDIT_ACTIONS.MEDIA_FOLDER_CREATED]: { category: 'config_publish', severity: 'medium', entityType: AUDIT_ENTITY_TYPES.MEDIA_FOLDER },
  [AUDIT_ACTIONS.PRODUCT_CATEGORY_CREATED]: { category: 'config_publish', severity: 'medium', entityType: AUDIT_ENTITY_TYPES.PRODUCT_CATEGORY },
  [AUDIT_ACTIONS.PRODUCT_CATEGORY_UPDATED]: { category: 'config_publish', severity: 'medium', entityType: AUDIT_ENTITY_TYPES.PRODUCT_CATEGORY },
  [AUDIT_ACTIONS.PRODUCT_CATEGORY_STATUS_CHANGED]: { category: 'config_publish', severity: 'high', entityType: AUDIT_ENTITY_TYPES.PRODUCT_CATEGORY },
  [AUDIT_ACTIONS.PRODUCT_CATEGORY_TRASHED]: { category: 'config_publish', severity: 'high', entityType: AUDIT_ENTITY_TYPES.PRODUCT_CATEGORY },
  [AUDIT_ACTIONS.PRODUCT_BRAND_CREATED]: { category: 'config_publish', severity: 'medium', entityType: AUDIT_ENTITY_TYPES.PRODUCT_BRAND },
  [AUDIT_ACTIONS.PRODUCT_BRAND_UPDATED]: { category: 'config_publish', severity: 'medium', entityType: AUDIT_ENTITY_TYPES.PRODUCT_BRAND },
  [AUDIT_ACTIONS.PRODUCT_BRAND_STATUS_CHANGED]: { category: 'config_publish', severity: 'high', entityType: AUDIT_ENTITY_TYPES.PRODUCT_BRAND },
  [AUDIT_ACTIONS.PRODUCT_BRAND_TRASHED]: { category: 'config_publish', severity: 'high', entityType: AUDIT_ENTITY_TYPES.PRODUCT_BRAND },
  [AUDIT_ACTIONS.PRODUCT_APPLICATION_CREATED]: { category: 'config_publish', severity: 'medium', entityType: AUDIT_ENTITY_TYPES.PRODUCT_APPLICATION },
  [AUDIT_ACTIONS.PRODUCT_APPLICATION_UPDATED]: { category: 'config_publish', severity: 'medium', entityType: AUDIT_ENTITY_TYPES.PRODUCT_APPLICATION },
  [AUDIT_ACTIONS.PRODUCT_APPLICATION_STATUS_CHANGED]: { category: 'config_publish', severity: 'high', entityType: AUDIT_ENTITY_TYPES.PRODUCT_APPLICATION },
  [AUDIT_ACTIONS.PRODUCT_APPLICATION_TRASHED]: { category: 'config_publish', severity: 'high', entityType: AUDIT_ENTITY_TYPES.PRODUCT_APPLICATION },
  [AUDIT_ACTIONS.PRODUCT_TYPE_CREATED]: { category: 'config_publish', severity: 'medium', entityType: AUDIT_ENTITY_TYPES.PRODUCT_TYPE },
  [AUDIT_ACTIONS.PRODUCT_TYPE_UPDATED]: { category: 'config_publish', severity: 'medium', entityType: AUDIT_ENTITY_TYPES.PRODUCT_TYPE },
  [AUDIT_ACTIONS.PRODUCT_TYPE_STATUS_CHANGED]: { category: 'config_publish', severity: 'high', entityType: AUDIT_ENTITY_TYPES.PRODUCT_TYPE },
  [AUDIT_ACTIONS.PRODUCT_TYPE_TRASHED]: { category: 'config_publish', severity: 'high', entityType: AUDIT_ENTITY_TYPES.PRODUCT_TYPE },
  [AUDIT_ACTIONS.PRODUCT_CREATED]: { category: 'config_publish', severity: 'medium', entityType: AUDIT_ENTITY_TYPES.PRODUCT },
  [AUDIT_ACTIONS.PRODUCT_UPDATED]: { category: 'config_publish', severity: 'medium', entityType: AUDIT_ENTITY_TYPES.PRODUCT },
  [AUDIT_ACTIONS.PRODUCT_STATUS_CHANGED]: { category: 'config_publish', severity: 'high', entityType: AUDIT_ENTITY_TYPES.PRODUCT },
  [AUDIT_ACTIONS.PRODUCT_TRASHED]: { category: 'config_publish', severity: 'high', entityType: AUDIT_ENTITY_TYPES.PRODUCT },
  [AUDIT_ACTIONS.SALES_OWNER_CREATED]: { category: 'config_publish', severity: 'medium', entityType: AUDIT_ENTITY_TYPES.SALES_OWNER },
  [AUDIT_ACTIONS.SALES_OWNER_UPDATED]: { category: 'config_publish', severity: 'medium', entityType: AUDIT_ENTITY_TYPES.SALES_OWNER },
  [AUDIT_ACTIONS.SALES_OWNER_STATUS_CHANGED]: { category: 'config_publish', severity: 'high', entityType: AUDIT_ENTITY_TYPES.SALES_OWNER },
  [AUDIT_ACTIONS.SALES_OWNER_TRASHED]: { category: 'config_publish', severity: 'high', entityType: AUDIT_ENTITY_TYPES.SALES_OWNER },
  [AUDIT_ACTIONS.NEWS_CREATED]: { category: 'config_publish', severity: 'medium', entityType: AUDIT_ENTITY_TYPES.NEWS },
  [AUDIT_ACTIONS.NEWS_UPDATED]: { category: 'config_publish', severity: 'medium', entityType: AUDIT_ENTITY_TYPES.NEWS },
  [AUDIT_ACTIONS.NEWS_STATUS_CHANGED]: { category: 'config_publish', severity: 'high', entityType: AUDIT_ENTITY_TYPES.NEWS },
  [AUDIT_ACTIONS.NEWS_TRASHED]: { category: 'config_publish', severity: 'high', entityType: AUDIT_ENTITY_TYPES.NEWS },
  [AUDIT_ACTIONS.NEWS_CATEGORY_CREATED]: { category: 'config_publish', severity: 'medium', entityType: AUDIT_ENTITY_TYPES.NEWS_CATEGORY },
  [AUDIT_ACTIONS.NEWS_CATEGORY_UPDATED]: { category: 'config_publish', severity: 'medium', entityType: AUDIT_ENTITY_TYPES.NEWS_CATEGORY },
  [AUDIT_ACTIONS.NEWS_CATEGORY_STATUS_CHANGED]: { category: 'config_publish', severity: 'high', entityType: AUDIT_ENTITY_TYPES.NEWS_CATEGORY },
  [AUDIT_ACTIONS.NEWS_CATEGORY_TRASHED]: { category: 'config_publish', severity: 'high', entityType: AUDIT_ENTITY_TYPES.NEWS_CATEGORY },
  [AUDIT_ACTIONS.EVENT_CREATED]: { category: 'config_publish', severity: 'medium', entityType: AUDIT_ENTITY_TYPES.EVENT },
  [AUDIT_ACTIONS.EVENT_UPDATED]: { category: 'config_publish', severity: 'medium', entityType: AUDIT_ENTITY_TYPES.EVENT },
  [AUDIT_ACTIONS.EVENT_STATUS_CHANGED]: { category: 'config_publish', severity: 'high', entityType: AUDIT_ENTITY_TYPES.EVENT },
  [AUDIT_ACTIONS.EVENT_TRASHED]: { category: 'config_publish', severity: 'high', entityType: AUDIT_ENTITY_TYPES.EVENT },
  [AUDIT_ACTIONS.SERVICE_CREATED]: { category: 'config_publish', severity: 'medium', entityType: AUDIT_ENTITY_TYPES.SERVICE },
  [AUDIT_ACTIONS.SERVICE_UPDATED]: { category: 'config_publish', severity: 'medium', entityType: AUDIT_ENTITY_TYPES.SERVICE },
  [AUDIT_ACTIONS.SERVICE_STATUS_CHANGED]: { category: 'config_publish', severity: 'high', entityType: AUDIT_ENTITY_TYPES.SERVICE },
  [AUDIT_ACTIONS.SERVICE_TRASHED]: { category: 'config_publish', severity: 'high', entityType: AUDIT_ENTITY_TYPES.SERVICE },
  [AUDIT_ACTIONS.STATIC_PAGE_CREATED]: { category: 'config_publish', severity: 'medium', entityType: AUDIT_ENTITY_TYPES.STATIC_PAGE },
  [AUDIT_ACTIONS.STATIC_PAGE_UPDATED]: { category: 'config_publish', severity: 'medium', entityType: AUDIT_ENTITY_TYPES.STATIC_PAGE },
  [AUDIT_ACTIONS.STATIC_PAGE_STATUS_CHANGED]: { category: 'config_publish', severity: 'high', entityType: AUDIT_ENTITY_TYPES.STATIC_PAGE },
  [AUDIT_ACTIONS.STATIC_PAGE_TRASHED]: { category: 'config_publish', severity: 'high', entityType: AUDIT_ENTITY_TYPES.STATIC_PAGE },
  [AUDIT_ACTIONS.MENU_CREATED]: { category: 'config_publish', severity: 'medium', entityType: AUDIT_ENTITY_TYPES.MENU },
  [AUDIT_ACTIONS.MENU_UPDATED]: { category: 'config_publish', severity: 'medium', entityType: AUDIT_ENTITY_TYPES.MENU },
  [AUDIT_ACTIONS.MENU_TRASHED]: { category: 'config_publish', severity: 'high', entityType: AUDIT_ENTITY_TYPES.MENU },
  [AUDIT_ACTIONS.FORM_CREATED]: { category: 'config_publish', severity: 'medium', entityType: AUDIT_ENTITY_TYPES.FORM },
  [AUDIT_ACTIONS.FORM_UPDATED]: { category: 'config_publish', severity: 'medium', entityType: AUDIT_ENTITY_TYPES.FORM },
  [AUDIT_ACTIONS.FORM_TRASHED]: { category: 'config_publish', severity: 'high', entityType: AUDIT_ENTITY_TYPES.FORM },
  [AUDIT_ACTIONS.CUSTOMER_REQUEST_STATUS_CHANGED]: { category: 'config_publish', severity: 'medium', entityType: AUDIT_ENTITY_TYPES.CUSTOMER_REQUEST },
  [AUDIT_ACTIONS.EMAIL_TEMPLATE_CREATED]: { category: 'config_publish', severity: 'medium', entityType: AUDIT_ENTITY_TYPES.EMAIL_TEMPLATE },
  [AUDIT_ACTIONS.EMAIL_TEMPLATE_UPDATED]: { category: 'config_publish', severity: 'medium', entityType: AUDIT_ENTITY_TYPES.EMAIL_TEMPLATE },
  [AUDIT_ACTIONS.EMAIL_TEMPLATE_PUBLISHED]: { category: 'config_publish', severity: 'high', entityType: AUDIT_ENTITY_TYPES.EMAIL_TEMPLATE },
  [AUDIT_ACTIONS.EMAIL_TEMPLATE_TRASHED]: { category: 'config_publish', severity: 'high', entityType: AUDIT_ENTITY_TYPES.EMAIL_TEMPLATE },
  [AUDIT_ACTIONS.TRASH_RESTORED]: { category: 'config_publish', severity: 'high', entityType: AUDIT_ENTITY_TYPES.TRASH_ITEM },
  [AUDIT_ACTIONS.TRASH_PURGED]: { category: 'config_publish', severity: 'critical', entityType: AUDIT_ENTITY_TYPES.TRASH_ITEM },
} as const;
