// Mock data for Customer Request Module

import { CustomerRequest } from './types';
import { RequestStatus, PriorityLevel } from '../shared/constants/statusTypes';

export const MOCK_CUSTOMER_REQUESTS: CustomerRequest[] = [
  {
    id: 'req_001',
    sourceConfig: {
      formId: 'form_001',
      formVersion: 2,
      formName: 'Biểu mẫu - Tư vấn ERP',
      ctaId: 'cta_001',
      ctaName: 'CTA - Tư vấn ERP',
      pageType: 'static_page',
      pageId: 'page_001',
      pageUrl: '/giai-phap-erp',
      pageTitle: 'Giải pháp ERP',
      placementKey: 'hero_primary_cta',
      submittedAt: '2026-08-06T09:15:00Z',
      utmSource: 'google',
      utmMedium: 'cpc',
      utmCampaign: 'erp-q1-2026',
      referrer: 'https://google.com',
      deviceInfo: {
        userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
        browser: 'Chrome',
        os: 'Windows 10',
        device: 'Desktop',
      },
    },
    submissionValues: [
      {
        fieldKey: 'full_name',
        fieldLabel: 'Họ và tên',
        fieldType: 'text',
        valueText: 'Nguyễn Văn A',
      },
      {
        fieldKey: 'email',
        fieldLabel: 'Email',
        fieldType: 'email',
        valueText: 'nguyenvana@gmail.com',
      },
      {
        fieldKey: 'phone',
        fieldLabel: 'Số điện thoại',
        fieldType: 'phone',
        valueText: '0981234567',
      },
      {
        fieldKey: 'company',
        fieldLabel: 'Công ty',
        fieldType: 'text',
        valueText: 'Công ty ABC',
      },
      {
        fieldKey: 'message',
        fieldLabel: 'Nhu cầu',
        fieldType: 'textarea',
        valueText: 'Muốn tư vấn triển khai ERP cho công ty sản xuất',
      },
    ],
    status: 'new',
    assignedUserId: 'user_001',
    assignedUserName: 'Nguyễn Văn B',
    priority: 'medium',
    tags: ['ERP', 'Sản xuất'],
    internalNotes: [],
    logs: [
      {
        id: 'log_001',
        actionType: 'created',
        createdBy: 'system',
        createdByName: 'Hệ thống',
        createdAt: '2026-08-06T09:15:00Z',
      },
    ],
    createdBy: 'system',
    createdAt: '2026-08-06T09:15:00Z',
    updatedAt: '2026-08-06T09:15:00Z',
  },
  {
    id: 'req_002',
    sourceConfig: {
      formId: 'form_002',
      formVersion: 1,
      formName: 'Biểu mẫu - Báo giá',
      ctaId: 'cta_002',
      ctaName: 'CTA - Báo giá CMS IntelliCAD',
      pageType: 'product',
      pageId: 'page_003',
      pageUrl: '/san-pham/intellicad',
      pageTitle: 'Chi tiết sản phẩm IntelliCAD',
      placementKey: 'product_primary_cta',
      submittedAt: '2026-08-06T10:30:00Z',
      utmSource: 'facebook',
      utmMedium: 'social',
      utmCampaign: 'intelligad-2026',
      referrer: 'https://facebook.com',
      deviceInfo: {
        userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 14_0 like Mac OS X) AppleWebKit/605.1.15',
        browser: 'Safari',
        os: 'iOS',
        device: 'Mobile',
      },
    },
    submissionValues: [
      {
        fieldKey: 'full_name',
        fieldLabel: 'Họ và tên',
        fieldType: 'text',
        valueText: 'Trần Văn B',
      },
      {
        fieldKey: 'email',
        fieldLabel: 'Email',
        fieldType: 'email',
        valueText: 'tranvanb@company.com',
      },
      {
        fieldKey: 'phone',
        fieldLabel: 'Số điện thoại',
        fieldType: 'phone',
        valueText: '0972345678',
      },
      {
        fieldKey: 'company',
        fieldLabel: 'Công ty',
        fieldType: 'text',
        valueText: 'Công ty XYZ',
      },
      {
        fieldKey: 'product_interest',
        fieldLabel: 'Sản phẩm quan tâm',
        fieldType: 'select',
        valueText: 'intellicad',
      },
      {
        fieldKey: 'budget',
        fieldLabel: 'Ngân sách dự kiến',
        fieldType: 'select',
        valueText: '100m_500m',
      },
    ],
    status: 'processing',
    assignedUserId: 'user_002',
    assignedUserName: 'Trần Thị C',
    priority: 'high',
    tags: ['IntelliCAD', 'Báo giá'],
    internalNotes: [
      {
        id: 'note_001',
        content: 'Khách quan tâm gói Professional',
        createdBy: 'user_002',
        createdByName: 'Trần Thị C',
        createdAt: '2026-08-06T11:00:00Z',
      },
    ],
    logs: [
      {
        id: 'log_002',
        actionType: 'created',
        createdBy: 'system',
        createdByName: 'Hệ thống',
        createdAt: '2026-08-06T10:30:00Z',
      },
      {
        id: 'log_003',
        actionType: 'assigned',
        oldValue: null,
        newValue: 'user_002',
        createdBy: 'user_001',
        createdByName: 'Nguyễn Văn B',
        createdAt: '2026-08-06T10:35:00Z',
      },
      {
        id: 'log_004',
        actionType: 'status_changed',
        oldValue: 'new',
        newValue: 'processing',
        createdBy: 'user_002',
        createdByName: 'Trần Thị C',
        createdAt: '2026-08-06T11:00:00Z',
      },
    ],
    createdBy: 'system',
    createdAt: '2026-08-06T10:30:00Z',
    updatedAt: '2026-08-06T11:00:00Z',
  },
  {
    id: 'req_003',
    sourceConfig: {
      formId: 'form_003',
      formVersion: 3,
      formName: 'Biểu mẫu - Liên hệ',
      ctaId: null,
      ctaName: null,
      pageType: 'static_page',
      pageId: 'page_008',
      pageUrl: '/gioi-thieu',
      pageTitle: 'Giới thiệu',
      placementKey: 'content_cta',
      submittedAt: '2026-08-05T14:20:00Z',
      utmSource: 'direct',
      utmMedium: 'none',
      utmCampaign: '',
      referrer: '',
      deviceInfo: {
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
        browser: 'Chrome',
        os: 'macOS',
        device: 'Desktop',
      },
    },
    submissionValues: [
      {
        fieldKey: 'full_name',
        fieldLabel: 'Họ và tên',
        fieldType: 'text',
        valueText: 'Lê Thị C',
      },
      {
        fieldKey: 'email',
        fieldLabel: 'Email',
        fieldType: 'email',
        valueText: 'lethic@gmail.com',
      },
      {
        fieldKey: 'phone',
        fieldLabel: 'Số điện thoại',
        fieldType: 'phone',
        valueText: '0963456789',
      },
      {
        fieldKey: 'subject',
        fieldLabel: 'Chủ đề',
        fieldType: 'select',
        valueText: 'partnership',
      },
      {
        fieldKey: 'message',
        fieldLabel: 'Nội dung',
        fieldType: 'textarea',
        valueText: 'Chúng tôi muốn tìm hiểu cơ hội hợp tác với CIC Technology',
      },
      {
        fieldKey: 'consent',
        fieldLabel: 'Tôi đồng ý với chính sách bảo mật',
        fieldType: 'consent',
        valueText: 'true',
      },
    ],
    status: 'completed',
    assignedUserId: 'user_003',
    assignedUserName: 'Lê Văn D',
    priority: 'low',
    tags: ['Hợp tác'],
    internalNotes: [
      {
        id: 'note_002',
        content: 'Đã gửi email thông tin hợp tác',
        createdBy: 'user_003',
        createdByName: 'Lê Văn D',
        createdAt: '2026-08-05T15:00:00Z',
      },
      {
        id: 'note_003',
        content: 'Khách đã phản hồi tích cực',
        createdBy: 'user_003',
        createdByName: 'Lê Văn D',
        createdAt: '2026-08-06T09:00:00Z',
      },
    ],
    logs: [
      {
        id: 'log_005',
        actionType: 'created',
        createdBy: 'system',
        createdByName: 'Hệ thống',
        createdAt: '2026-08-05T14:20:00Z',
      },
      {
        id: 'log_006',
        actionType: 'assigned',
        oldValue: null,
        newValue: 'user_003',
        createdBy: 'user_001',
        createdByName: 'Nguyễn Văn B',
        createdAt: '2026-08-05T14:25:00Z',
      },
      {
        id: 'log_007',
        actionType: 'status_changed',
        oldValue: 'new',
        newValue: 'completed',
        createdBy: 'user_003',
        createdByName: 'Lê Văn D',
        createdAt: '2026-08-06T09:00:00Z',
      },
    ],
    createdBy: 'system',
    createdAt: '2026-08-05T14:20:00Z',
    updatedAt: '2026-08-06T09:00:00Z',
  },
  {
    id: 'req_004',
    sourceConfig: {
      formId: 'form_001',
      formVersion: 2,
      formName: 'Biểu mẫu - Tư vấn ERP',
      ctaId: 'cta_001',
      ctaName: 'CTA - Tư vấn ERP',
      pageType: 'static_page',
      pageId: 'page_002',
      pageUrl: '/',
      pageTitle: 'Trang chủ',
      placementKey: 'hero_secondary_cta',
      submittedAt: '2026-08-06T08:00:00Z',
      utmSource: 'google',
      utmMedium: 'organic',
      utmCampaign: '',
      referrer: 'https://google.com',
      deviceInfo: {
        userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
        browser: 'Firefox',
        os: 'Windows 10',
        device: 'Desktop',
      },
    },
    submissionValues: [
      {
        fieldKey: 'full_name',
        fieldLabel: 'Họ và tên',
        fieldType: 'text',
        valueText: 'Phạm Văn E',
      },
      {
        fieldKey: 'email',
        fieldLabel: 'Email',
        fieldType: 'email',
        valueText: 'phamvane@yahoo.com',
      },
      {
        fieldKey: 'phone',
        fieldLabel: 'Số điện thoại',
        fieldType: 'phone',
        valueText: '0998765432',
      },
      {
        fieldKey: 'company',
        fieldLabel: 'Công ty',
        fieldType: 'text',
        valueText: 'Công ty DEF',
      },
      {
        fieldKey: 'message',
        fieldLabel: 'Nhu cầu',
        fieldType: 'textarea',
        valueText: 'Cần tư vấn gói ERP cho doanh nghiệp vừa và nhỏ',
      },
    ],
    status: 'new',
    assignedUserId: null,
    assignedUserName: null,
    priority: 'medium',
    tags: ['ERP', 'SME'],
    internalNotes: [],
    logs: [
      {
        id: 'log_008',
        actionType: 'created',
        createdBy: 'system',
        createdByName: 'Hệ thống',
        createdAt: '2026-08-06T08:00:00Z',
      },
    ],
    createdBy: 'system',
    createdAt: '2026-08-06T08:00:00Z',
    updatedAt: '2026-08-06T08:00:00Z',
  },
  {
    id: 'req_005',
    sourceConfig: {
      formId: 'form_002',
      formVersion: 1,
      formName: 'Biểu mẫu - Báo giá',
      ctaId: 'cta_002',
      ctaName: 'CTA - Báo giá CMS IntelliCAD',
      pageType: 'product',
      pageId: 'page_004',
      pageUrl: '/san-pham',
      pageTitle: 'Sản phẩm',
      placementKey: 'sidebar_cta',
      submittedAt: '2026-08-04T16:45:00Z',
      utmSource: 'newsletter',
      utmMedium: 'email',
      utmCampaign: 'q2-2026',
      referrer: '',
      deviceInfo: {
        userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
        browser: 'Edge',
        os: 'Windows 10',
        device: 'Desktop',
      },
    },
    submissionValues: [
      {
        fieldKey: 'full_name',
        fieldLabel: 'Họ và tên',
        fieldType: 'text',
        valueText: 'Hoàng Văn F',
      },
      {
        fieldKey: 'email',
        fieldLabel: 'Email',
        fieldType: 'email',
        valueText: 'hoangvanf@tech.vn',
      },
      {
        fieldKey: 'phone',
        fieldLabel: 'Số điện thoại',
        fieldType: 'phone',
        valueText: '0945678901',
      },
      {
        fieldKey: 'company',
        fieldLabel: 'Công ty',
        fieldType: 'text',
        valueText: 'Công ty GHI',
      },
      {
        fieldKey: 'product_interest',
        fieldLabel: 'Sản phẩm quan tâm',
        fieldType: 'select',
        valueText: 'bim_solution',
      },
      {
        fieldKey: 'budget',
        fieldLabel: 'Ngân sách dự kiến',
        fieldType: 'select',
        valueText: 'over_500m',
      },
    ],
    status: 'not_suitable',
    assignedUserId: 'user_001',
    assignedUserName: 'Nguyễn Văn B',
    priority: 'low',
    tags: ['BIM', 'Không phù hợp'],
    internalNotes: [
      {
        id: 'note_004',
        content: 'Ngân sách không phù hợp với gói BIM hiện tại',
        createdBy: 'user_001',
        createdByName: 'Nguyễn Văn B',
        createdAt: '2026-08-05T10:00:00Z',
      },
    ],
    logs: [
      {
        id: 'log_009',
        actionType: 'created',
        createdBy: 'system',
        createdByName: 'Hệ thống',
        createdAt: '2026-08-04T16:45:00Z',
      },
      {
        id: 'log_010',
        actionType: 'assigned',
        oldValue: null,
        newValue: 'user_001',
        createdBy: 'user_001',
        createdByName: 'Nguyễn Văn B',
        createdAt: '2026-08-05T09:00:00Z',
      },
      {
        id: 'log_011',
        actionType: 'status_changed',
        oldValue: 'new',
        newValue: 'not_suitable',
        createdBy: 'user_001',
        createdByName: 'Nguyễn Văn B',
        createdAt: '2026-08-05T10:00:00Z',
      },
    ],
    createdBy: 'system',
    createdAt: '2026-08-04T16:45:00Z',
    updatedAt: '2026-08-05T10:00:00Z',
  },
];
