"use client";

import { useState, type FormEvent } from "react";
import { ExternalLink, GitCompareArrows, PackageCheck, ReceiptText, X } from "lucide-react";

import { apiRequest } from "@/lib/api";

export interface ChatProduct {
  id: string; sku: string; name: string; category: string | null; brand: string | null;
  description: string | null; use_case: string | null; utility: string | null;
  power: string | null; weight: string | null; warranty: string | null;
  standards: string | null; price: number | null; unit: string | null; stock: number | null;
  image_link: string | null; product_link: string | null;
}

export function ProductCard({ product, onCompare, onQuote }: { product: ChatProduct; onCompare:(p:ChatProduct)=>void; onQuote:(p:ChatProduct)=>void }) {
  const stock = product.stock ?? 0;
  const stockText = stock === 0 ? "Hết hàng" : stock <= 5 ? "Sắp hết" : "Còn hàng";
  return <article className="w-80 shrink-0 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="grid h-24 place-items-center border-b border-blue-100 bg-blue-50"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-white text-blue-600 shadow-sm"><PackageCheck className="h-8 w-8"/></div></div><div className="space-y-4 p-4"><header><p className="font-mono text-[11px] font-bold tracking-wide text-blue-700">{product.sku}</p><h3 className="mt-1 text-base font-bold leading-6 text-slate-950">{product.name}</h3><p className="mt-1 line-clamp-2 text-xs leading-5 text-slate-500">{product.description||product.use_case||"Chưa có mô tả"}</p></header><div className="flex items-center justify-between gap-2"><strong className="text-xl text-blue-700">{product.price==null?"Liên hệ":`${product.price.toLocaleString("vi-VN")}đ`}</strong><span className={`rounded-full px-2.5 py-1 text-[11px] font-semibold ${stock===0?"bg-rose-50 text-rose-700":stock<=5?"bg-amber-50 text-amber-700":"bg-emerald-50 text-emerald-700"}`}>{stockText}: {stock}</span></div><dl className="grid grid-cols-2 gap-x-4 gap-y-3 rounded-xl bg-slate-50 p-3 text-xs"><Info label="Nhóm" value={product.category}/><Info label="Thương hiệu" value={product.brand}/><Info label="Đơn vị" value={product.unit}/><Info label="Công suất" value={product.power}/><Info label="Bảo hành" value={product.warranty}/><Info label="Trọng lượng" value={product.weight}/></dl><div className="grid grid-cols-2 gap-2 border-t pt-3"><button onClick={()=>onCompare(product)} className="flex min-h-10 items-center justify-center gap-1 rounded-lg border text-xs font-semibold hover:bg-slate-50"><GitCompareArrows className="h-3.5 w-3.5"/>So sánh</button><button onClick={()=>onQuote(product)} className="flex min-h-10 items-center justify-center gap-1 rounded-lg bg-blue-600 text-xs font-semibold text-white hover:bg-blue-700"><ReceiptText className="h-3.5 w-3.5"/>Báo giá</button><a href={product.product_link||undefined} target="_blank" rel="noopener noreferrer" aria-disabled={!product.product_link} className={`col-span-2 flex min-h-10 items-center justify-center gap-2 rounded-lg text-xs font-semibold ${product.product_link?"bg-slate-900 text-white hover:bg-slate-800":"pointer-events-none bg-slate-100 text-slate-400"}`}><ExternalLink className="h-3.5 w-3.5"/>{product.product_link?"Xem sản phẩm":"Chưa có link sản phẩm"}</a></div></div></article>;
}

function Info({ label, value }: { label: string; value: string | null }) {
  return <div><dt className="text-slate-400">{label}</dt><dd className="mt-0.5 truncate font-semibold text-slate-700" title={value||"Chưa cập nhật"}>{value||"Chưa cập nhật"}</dd></div>;
}

export function ComparisonTable({ products, onClose }: { products: ChatProduct[]; onClose:()=>void }) {
  const fields:[string,(p:ChatProduct)=>string][]=[["Thương hiệu",p=>p.brand||""],["Giá",p=>p.price==null?"Liên hệ":`${p.price.toLocaleString("vi-VN")}đ`],["Công suất",p=>p.power||""],["Trọng lượng",p=>p.weight||""],["Bảo hành",p=>p.warranty||""],["Tồn kho",p=>String(p.stock??0)],["Công dụng",p=>p.use_case||p.utility||""],["Tiêu chuẩn",p=>p.standards||""]];
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><div className="max-h-[90vh] w-full max-w-5xl overflow-auto rounded-2xl bg-white p-6"><div className="flex justify-between"><div><p className="text-sm font-semibold text-blue-700">Dữ liệu Supabase</p><h2 className="text-xl font-bold">So sánh sản phẩm</h2></div><button onClick={onClose}><X/></button></div><table className="mt-5 w-full min-w-[700px] text-sm"><thead><tr className="bg-slate-50"><th className="p-3 text-left">Tiêu chí</th>{products.map(p=><th key={p.id} className="p-3 text-left">{p.name}</th>)}</tr></thead><tbody className="divide-y">{fields.map(([label,get])=><tr key={label}><th className="p-3 text-left text-slate-500">{label}</th>{products.map(p=><td key={p.id} className="p-3">{get(p)||"Chưa có thông tin"}</td>)}</tr>)}</tbody></table></div></div>;
}

export function TransactionModal({ mode, product, conversationId, onClose, onSuccess }: { mode:"quote"|"appointment"; product?:ChatProduct; conversationId:string; onClose:()=>void; onSuccess:(text:string)=>void }) {
  const [name,setName]=useState(""); const [phone,setPhone]=useState(""); const [quantity,setQuantity]=useState(1); const [day,setDay]=useState(""); const [at,setAt]=useState("09:00"); const [channel,setChannel]=useState("Điện thoại"); const [error,setError]=useState(""); const [saving,setSaving]=useState(false);
  const submit=async(e:FormEvent)=>{e.preventDefault();setSaving(true);setError("");try{if(mode==="quote"&&product){const result=await apiRequest<{message:string}>("/engagements/quotations",{method:"POST",body:JSON.stringify({conversation_id:conversationId,product_id:product.id,customer_name:name,phone_number:phone,quantity})});onSuccess(result.message);}else{const result=await apiRequest<{message:string}>("/engagements/appointments",{method:"POST",body:JSON.stringify({conversation_id:conversationId,customer_name:name,phone_number:phone,appointment_date:day,appointment_time:at,channel})});onSuccess(result.message);}onClose();}catch(err){setError(err instanceof Error?err.message:"Không thể lưu yêu cầu");}finally{setSaving(false)}};
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><form onSubmit={submit} className="w-full max-w-lg space-y-4 rounded-2xl bg-white p-6"><div className="flex justify-between"><div><p className="text-sm font-semibold text-blue-700">Dữ liệu được lưu vào Supabase</p><h2 className="text-xl font-bold">{mode==="quote"?"Yêu cầu báo giá":"Đặt lịch tư vấn"}</h2></div><button type="button" onClick={onClose}><X/></button></div>{product&&<div className="rounded-lg bg-slate-50 p-3 text-sm"><strong>{product.name}</strong>{mode==="quote"&&<p className="mt-1 text-blue-700">Tạm tính: {product.price==null?"Liên hệ":`${(product.price*quantity).toLocaleString("vi-VN")}đ`}</p>}</div>}<label className="block text-sm font-medium">Họ tên<input value={name} onChange={e=>setName(e.target.value)} className="mt-1 h-10 w-full rounded-md border px-3" required minLength={2}/></label><label className="block text-sm font-medium">Số điện thoại<input value={phone} onChange={e=>setPhone(e.target.value)} className="mt-1 h-10 w-full rounded-md border px-3" required minLength={9}/></label>{mode==="quote"?<label className="block text-sm font-medium">Số lượng<input type="number" min={1} max={999} value={quantity} onChange={e=>setQuantity(Number(e.target.value))} className="mt-1 h-10 w-full rounded-md border px-3"/></label>:<div className="grid grid-cols-2 gap-3"><label className="text-sm font-medium">Ngày<input type="date" value={day} onChange={e=>setDay(e.target.value)} className="mt-1 h-10 w-full rounded-md border px-2" required/></label><label className="text-sm font-medium">Giờ<input type="time" value={at} onChange={e=>setAt(e.target.value)} className="mt-1 h-10 w-full rounded-md border px-2" required/></label><label className="col-span-2 text-sm font-medium">Hình thức<select value={channel} onChange={e=>setChannel(e.target.value)} className="mt-1 h-10 w-full rounded-md border px-2"><option>Điện thoại</option><option>Email</option><option>Zalo</option><option>Video call</option><option>Tư vấn trực tiếp</option></select></label></div>}{error&&<p className="text-sm text-rose-600">{error}</p>}<div className="flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-lg border px-4 py-2 text-sm">Hủy</button><button disabled={saving} className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white">{saving?"Đang lưu…":"Xác nhận"}</button></div></form></div>;
}
