// Mock data for CTA Module - Synchronized with genuine public website CTAs
import { CtaItem } from './types';

export const MOCK_CTAS: CtaItem[] = [
  // 1. Explore Products CTA
  {
    id: '1',
    adminName: 'CTA Hệ thống - Khám phá giải pháp',
    displayText: 'Khám phá giải pháp',
    description: 'Nút chuyển hướng chính trong Hero Carousel trang chủ và hệ sinh thái số.',
    code: 'cta_explore_products',
    icon: 'ArrowRight',
    styleVariant: 'primary',
    actionConfig: { type: 'redirect_internal', url: '/products', openInNewTab: false },
    status: 'active',
    usedByCount: 2,
    usedByPages: [
      { pageId: 'home', pageTitle: 'Trang chủ', pagePath: '/', placementKey: 'home.hero.primary' },
      { pageId: 'ecosystem', pageTitle: 'Hệ sinh thái số', pagePath: '/#ecosystem', placementKey: 'home.ecosystem.cta' },
    ],
    analytics: { impressions: 14200, clicks: 1850, ctr: 13.0, trend: 'up' },
    governance: { origin: 'system', allowedPlacements: ['fixed_section'], fixedPlacementKeys: ['home.hero.primary'] },
    createdBy: 'Hệ thống',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-25T00:00:00Z',
  },

  // 2. About CIC CTA
  {
    id: '3',
    adminName: 'CTA Hệ thống - Về chúng tôi',
    displayText: 'Về chúng tôi',
    description: 'Nút phụ trong Hero Carousel dẫn đến trang Giới thiệu năng lực CIC.',
    code: 'cta_about_cic',
    icon: 'Building',
    styleVariant: 'outline',
    actionConfig: { type: 'redirect_internal', url: '/about', openInNewTab: false },
    status: 'active',
    usedByCount: 2,
    usedByPages: [
      { pageId: 'home', pageTitle: 'Trang chủ', pagePath: '/', placementKey: 'home.hero.secondary' },
      { pageId: 'footer', pageTitle: 'Chân trang', pagePath: 'all', placementKey: 'footer.company_about' },
    ],
    analytics: { impressions: 9800, clicks: 760, ctr: 7.7, trend: 'flat' },
    governance: { origin: 'system', allowedPlacements: ['fixed_section'], fixedPlacementKeys: ['home.hero.secondary'] },
    createdBy: 'Hệ thống',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-25T00:00:00Z',
  },

  // 3. Consultation CTA (Opens Consultation Modal)
  {
    id: '5',
    adminName: 'CTA Hệ thống - Đăng ký tư vấn',
    displayText: 'Đăng ký tư vấn',
    description: 'Nút kích hoạt cửa sổ Đăng ký tư vấn tại Header góc trên bên phải và thanh công cụ nổi.',
    code: 'cta_contact',
    icon: 'MessageSquare',
    styleVariant: 'primary',
    actionConfig: { type: 'open_form', formId: '15' },
    status: 'active',
    usedByCount: 2,
    usedByPages: [
      { pageId: 'header', pageTitle: 'Header Toàn trang', pagePath: 'all', placementKey: 'header.consultation_cta' },
      { pageId: 'floating_bar', pageTitle: 'Thanh công cụ nổi', pagePath: 'all', placementKey: 'floating.consultation' },
    ],
    analytics: { impressions: 28500, clicks: 4120, ctr: 14.4, trend: 'up' },
    governance: { origin: 'system', allowedPlacements: ['fixed_section'], fixedPlacementKeys: ['header.consultation_cta'] },
    createdBy: 'Hệ thống',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-25T00:00:00Z',
  },

  // 4. Hotline Call CTA
  {
    id: '11',
    adminName: 'CTA Hệ thống - Gọi hotline tư vấn',
    displayText: 'Hotline: 024 3976 1381',
    description: 'Gọi trực tiếp đến số điện thoại tổng đài tư vấn của CIC.',
    code: 'cta_goi_hotline',
    icon: 'Phone',
    styleVariant: 'primary',
    actionConfig: { type: 'call_phone', phoneNumber: '024 3976 1381' },
    status: 'active',
    usedByCount: 3,
    usedByPages: [
      { pageId: 'floating_bar', pageTitle: 'Thanh công cụ nổi', pagePath: 'all', placementKey: 'floating.hotline' },
      { pageId: 'header', pageTitle: 'Header', pagePath: 'all', placementKey: 'header.hotline' },
      { pageId: 'footer', pageTitle: 'Footer', pagePath: 'all', placementKey: 'footer.hotline' },
    ],
    analytics: { impressions: 32000, clicks: 1250, ctr: 3.9, trend: 'flat' },
    governance: { origin: 'system', allowedPlacements: ['fixed_section'], fixedPlacementKeys: ['floating.hotline'] },
    createdBy: 'Hệ thống',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-25T00:00:00Z',
  },

  // 5. Service Consultation CTA
  {
    id: '16',
    adminName: 'CTA - Tư vấn dịch vụ BIM & Chuyển đổi số',
    displayText: 'Tư vấn dịch vụ',
    description: 'Kích hoạt form đăng ký tư vấn dịch vụ tại trang Dịch vụ.',
    code: 'cta_tuvan_dichvu',
    icon: 'Briefcase',
    styleVariant: 'primary',
    actionConfig: { type: 'open_form', formId: '27' },
    status: 'active',
    usedByCount: 2,
    usedByPages: [
      { pageId: 'services', pageTitle: 'Dịch vụ', pagePath: '/services', placementKey: 'services.catalog.cta' },
      { pageId: 'service_detail', pageTitle: 'Chi tiết dịch vụ', pagePath: '/services/[slug]', placementKey: 'services.detail.cta' },
    ],
    analytics: { impressions: 6400, clicks: 720, ctr: 11.2, trend: 'up' },
    governance: { origin: 'custom', allowedPlacements: ['rich_text', 'fixed_section'] },
    createdBy: 'Quản trị viên',
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-03-25T00:00:00Z',
  },

  // 6. Product Quotation CTA
  {
    id: '18',
    adminName: 'CTA - Nhận báo giá sản phẩm',
    displayText: 'Nhận báo giá',
    description: 'Nút mở modal yêu cầu báo giá trên trang chi tiết sản phẩm.',
    code: 'cta_baogia_sanpham',
    icon: 'Tag',
    styleVariant: 'primary',
    actionConfig: { type: 'open_form', formId: '21' },
    status: 'active',
    usedByCount: 2,
    usedByPages: [
      { pageId: 'products_list', pageTitle: 'Danh mục sản phẩm', pagePath: '/products', placementKey: 'products.card.quote' },
      { pageId: 'product_detail', pageTitle: 'Chi tiết sản phẩm', pagePath: '/products/[slug]', placementKey: 'product.detail.quote' },
    ],
    analytics: { impressions: 18200, clicks: 2310, ctr: 12.7, trend: 'up' },
    governance: { origin: 'custom', allowedPlacements: ['rich_text', 'fixed_section'] },
    createdBy: 'Quản trị viên',
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-03-25T00:00:00Z',
  },

  // 7. Product Purchase CTA
  {
    id: '20',
    adminName: 'CTA - Đăng ký mua bản quyền',
    displayText: 'Đăng ký mua',
    description: 'Nút đăng ký mua bản quyền chính hãng trên trang chi tiết sản phẩm.',
    code: 'cta_mua_sanpham',
    icon: 'ShoppingCart',
    styleVariant: 'primary',
    actionConfig: { type: 'open_form', formId: '23' },
    status: 'active',
    usedByCount: 1,
    usedByPages: [
      { pageId: 'product_detail', pageTitle: 'Chi tiết sản phẩm', pagePath: '/products/[slug]', placementKey: 'product.detail.buy' },
    ],
    analytics: { impressions: 7600, clicks: 610, ctr: 8.0, trend: 'flat' },
    governance: { origin: 'custom', allowedPlacements: ['rich_text', 'fixed_section'] },
    createdBy: 'Quản trị viên',
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-03-25T00:00:00Z',
  },

  // 8. Download Trial CTA
  {
    id: '22',
    adminName: 'CTA - Tải bản dùng thử',
    displayText: 'Tải bản dùng thử',
    description: 'Nút mở modal tải bản dùng thử và tài liệu kỹ thuật của sản phẩm.',
    code: 'cta_taive_dungthu',
    icon: 'Download',
    styleVariant: 'secondary',
    actionConfig: { type: 'open_form', formId: '25' },
    status: 'active',
    usedByCount: 1,
    usedByPages: [
      { pageId: 'product_detail', pageTitle: 'Chi tiết sản phẩm', pagePath: '/products/[slug]', placementKey: 'product.detail.download' },
    ],
    analytics: { impressions: 11400, clicks: 1720, ctr: 15.1, trend: 'up' },
    governance: { origin: 'custom', allowedPlacements: ['rich_text', 'fixed_section'] },
    createdBy: 'Quản trị viên',
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-03-25T00:00:00Z',
  },

  // 9. Event Registration CTA
  {
    id: '24',
    adminName: 'CTA - Đăng ký tham gia sự kiện',
    displayText: 'Đăng ký tham gia',
    description: 'Nút chuyển đến form đăng ký tham dự hội thảo, webinar trên trang sự kiện.',
    code: 'cta_dangky_sukien',
    icon: 'Calendar',
    styleVariant: 'primary',
    actionConfig: { type: 'open_form', formId: '29' },
    status: 'active',
    usedByCount: 2,
    usedByPages: [
      { pageId: 'events', pageTitle: 'Sự kiện & Hội thảo', pagePath: '/events', placementKey: 'events.card.register' },
      { pageId: 'event_detail', pageTitle: 'Chi tiết sự kiện', pagePath: '/events/[slug]', placementKey: 'events.detail.register' },
    ],
    analytics: { impressions: 8900, clicks: 1420, ctr: 16.0, trend: 'up' },
    governance: { origin: 'custom', allowedPlacements: ['rich_text', 'fixed_section'] },
    createdBy: 'Quản trị viên',
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-03-25T00:00:00Z',
  },

  // 10. Official Contact Page Redirect CTA
  {
    id: '26',
    adminName: 'CTA - Gửi yêu cầu liên hệ',
    displayText: 'Liên hệ với chúng tôi',
    description: 'Nút dẫn thẳng đến trang Liên hệ chính thức của CIC.',
    code: 'cta_lienhe_chinhthuc',
    icon: 'Mail',
    styleVariant: 'outline',
    actionConfig: { type: 'redirect_internal', url: '/lien-he', openInNewTab: false },
    status: 'active',
    usedByCount: 2,
    usedByPages: [
      { pageId: 'about', pageTitle: 'Giới thiệu', pagePath: '/about', placementKey: 'about.contact_block' },
      { pageId: 'footer', pageTitle: 'Chân trang', pagePath: 'all', placementKey: 'footer.branches_contact' },
    ],
    analytics: { impressions: 15300, clicks: 980, ctr: 6.4, trend: 'flat' },
    governance: { origin: 'custom', allowedPlacements: ['rich_text', 'fixed_section'] },
    createdBy: 'Quản trị viên',
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-03-25T00:00:00Z',
  },
];
