import { BlockItem, PlacementZone, PageTreeNode, ConflictIssue, BlockVersion } from './types';

export const MOCK_PLACEMENTS: PlacementZone[] = [
  {
    id: 'plc_header_top',
    code: 'HEADER_TOP_ANNOUNCEMENT',
    name: 'Thanh thông báo đầu trang (Header Top)',
    site_id: 'main_site',
    description: 'Hiển thị dải thông báo ưu đãi hoặc tin tức nóng ở vị trí trên cùng trang',
    max_capacity: 1,
    active_count: 1,
    recommended_aspect_ratio: 'Full width bar (h: 40px)',
  },
  {
    id: 'plc_home_hero',
    code: 'HOME_HERO_TOP',
    name: 'Khối Hero Banner & CTA Trang chủ',
    site_id: 'main_site',
    description: 'Vị trí trang chủ cao nhất, thu hút tương tác đầu tiên của khách hàng',
    max_capacity: 3,
    active_count: 2,
    recommended_aspect_ratio: '16:9 / 21:9',
  },
  {
    id: 'plc_features_section',
    code: 'FEATURES_GRID_MID',
    name: 'Khối tính năng & Giải pháp nổi bật',
    site_id: 'main_site',
    description: 'Lưới giới thiệu giá trị cốt lõi & dịch vụ trọng tâm',
    max_capacity: 2,
    active_count: 1,
    recommended_aspect_ratio: 'Grid 3x2 cards',
  },
  {
    id: 'plc_product_sidebar',
    code: 'PRODUCT_DETAIL_SIDEBAR',
    name: 'Cột bên trang chi tiết sản phẩm',
    site_id: 'main_site',
    description: 'Banner hỗ trợ mua hàng, hotline & form tư vấn đặt hàng',
    max_capacity: 2,
    active_count: 2,
    recommended_aspect_ratio: '1:1 / 3:4',
  },
  {
    id: 'plc_footer_cta',
    code: 'FOOTER_TOP_CTA',
    name: 'Khối CTA đăng ký nhận tin (Footer)',
    site_id: 'main_site',
    description: 'Khối chuyển đổi cuối trang trước khu vực thông tin bản quyền',
    max_capacity: 1,
    active_count: 1,
    recommended_aspect_ratio: 'Full width card (h: 220px)',
  },
  {
    id: 'plc_news_sidebar',
    code: 'NEWS_DETAIL_BANNER',
    name: 'Khối quảng bá trang Tin tức',
    site_id: 'main_site',
    description: 'Đặt trong danh mục tin tức và bài viết chi tiết',
    max_capacity: 3,
    active_count: 1,
    recommended_aspect_ratio: 'Banner dọc 300x600',
  },
];

export const MOCK_PAGE_TREE: PageTreeNode[] = [
  {
    id: 'node_home',
    path: '/',
    title: 'Trang chủ (Homepage)',
    type: 'page',
  },
  {
    id: 'node_products',
    path: '/products',
    title: 'Danh mục Sản phẩm',
    type: 'category',
    children: [
      { id: 'node_prod_industrial', path: '/products/industrial', title: 'Máy móc Công nghiệp', type: 'page' },
      { id: 'node_prod_automation', path: '/products/automation', title: 'Thiết bị Tự động hóa', type: 'page' },
      { id: 'node_prod_detail', path: '/products/*', title: 'Trang Chi tiết Sản phẩm (Tất cả)', type: 'page' },
    ],
  },
  {
    id: 'node_services',
    path: '/services',
    title: 'Dịch vụ & Giải pháp',
    type: 'category',
    children: [
      { id: 'node_serv_consulting', path: '/services/consulting', title: 'Tư vấn Thiết kế Hệ thống', type: 'page' },
      { id: 'node_serv_maintenance', path: '/services/maintenance', title: 'Bảo trì & Vận hành', type: 'page' },
    ],
  },
  {
    id: 'node_news',
    path: '/news',
    title: 'Tin tức & Sự kiện',
    type: 'page',
  },
  {
    id: 'node_about',
    path: '/about-us',
    title: 'Giới thiệu Doanh nghiệp',
    type: 'page',
  },
  {
    id: 'node_checkout',
    path: '/checkout',
    title: 'Trang Thanh toán & Giỏ hàng',
    type: 'module',
  },
];

export const INITIAL_BLOCKS: BlockItem[] = [
  {
    id: 'blk_001',
    title: 'Khối Banner Hero & Đăng ký Tư vấn 2026',
    code_alias: 'home-hero-cta-2026',
    type: 'hero_cta',
    description: 'Khối Hero đỉnh trang chủ giới thiệu giải pháp sản xuất tự động hóa mới nhất.',
    tags: ['Trang chủ', 'Chiến dịch Q1', 'Hero'],
    owner_name: 'Nguyễn Văn Minh',
    owner_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    show_title: true,
    layout_variant: 'standard',
    custom_css_class: 'hero-gradient-orange',
    site_id: 'main_site',
    placement_id: 'plc_home_hero',
    placement_name: 'Khối Hero Banner & CTA Trang chủ',
    scope: {
      site_id: 'main_site',
      apply_all_pages: false,
      included_pages: ['/'],
      excluded_pages: [],
    },
    used_by_count: 1,
    used_by_pages: [{ page_id: 'node_home', page_title: 'Trang chủ (Homepage)', page_path: '/' }],
    content: {
      headline: 'Đột Phá Năng Suất Với Giải Pháp Tự Động Hóa AI-Powered 2026',
      subtitle: 'Tối ưu đến 45% chi phí vận hành nhà máy với hệ thống điều khiển thông minh toàn diện.',
      cta_text: 'Đăng Ký Khảo Sát Miễn Phí',
      cta_url: '/services/consulting',
      secondary_cta_text: 'Xem Mô Phỏng 3D',
      secondary_cta_url: '/products/automation',
      media_url: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&auto=format&fit=crop&q=80',
      media_type: 'image',
    },
    display_order: 1,
    priority_weight: 10,
    start_time: '2026-01-01T00:00:00Z',
    end_time: '2026-12-31T23:59:59Z',
    auto_deactivate: true,
    workflow_status: 'published',
    effective_status: 'running',
    live_version: 'v2.0',
    draft_version: 'v2.1-draft',
    has_draft_changes: true,
    created_at: '2026-01-10T08:30:00Z',
    updated_at: '2026-02-01T10:15:00Z',
  },
  {
    id: 'blk_002',
    title: 'Thanh Thông Báo Ưu Đãi Đầu Trang Tết 2026',
    code_alias: 'announcement-top-tet',
    type: 'announcement_bar',
    description: 'Chạy ưu đãi chiết khấu 15% cho hợp đồng bảo trì quý 1.',
    tags: ['Khuyến mãi', 'Header', 'Nổi bật'],
    owner_name: 'Trần Thị Thu',
    owner_avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    show_title: false,
    layout_variant: 'fullwidth_dark',
    custom_css_class: 'bg-gradient-to-r from-orange-600 to-amber-600 text-white',
    site_id: 'main_site',
    placement_id: 'plc_header_top',
    placement_name: 'Thanh thông báo đầu trang (Header Top)',
    scope: {
      site_id: 'main_site',
      apply_all_pages: true,
      included_pages: [],
      excluded_pages: ['/checkout'],
    },
    used_by_count: 12,
    used_by_pages: [
      { page_id: 'node_home', page_title: 'Trang chủ', page_path: '/' },
      { page_id: 'node_products', page_title: 'Sản phẩm', page_path: '/products' },
      { page_id: 'node_services', page_title: 'Dịch vụ', page_path: '/services' },
    ],
    content: {
      headline: '🎉 ƯU ĐÃI ĐẶC BIỆT Q1: Giảm 15% gói tư vấn thiết kế hệ thống nhà máy cho khách hàng mới!',
      cta_text: 'Nhận Báo Giá Ngay',
      cta_url: '/services/consulting#quote',
    },
    display_order: 1,
    priority_weight: 9,
    start_time: '2026-02-01T00:00:00Z',
    end_time: '2026-03-15T23:59:59Z',
    auto_deactivate: true,
    workflow_status: 'published',
    effective_status: 'running',
    live_version: 'v1.2',
    draft_version: 'v1.2',
    has_draft_changes: false,
    created_at: '2026-01-25T09:00:00Z',
    updated_at: '2026-02-02T14:20:00Z',
  },
  {
    id: 'blk_003',
    title: 'Lưới 4 Giá Trị Nổi Bật Của Doanh Nghiệp',
    code_alias: 'features-grid-core-values',
    type: 'feature_grid',
    description: 'Trình bày 4 ưu thế cạnh tranh: Chuẩn ISO, Hỗ trợ 24/7, Bảo hành 36 tháng, Linh kiện chính hãng.',
    tags: ['Ưu thế', 'Trang chủ', 'Grid'],
    owner_name: 'Lê Hoàng Nam',
    owner_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    show_title: true,
    layout_variant: 'grid_3col',
    site_id: 'main_site',
    placement_id: 'plc_features_section',
    placement_name: 'Khối tính năng & Giải pháp nổi bật',
    scope: {
      site_id: 'main_site',
      apply_all_pages: false,
      included_pages: ['/', '/about-us'],
      excluded_pages: [],
    },
    used_by_count: 2,
    used_by_pages: [
      { page_id: 'node_home', page_title: 'Trang chủ', page_path: '/' },
      { page_id: 'node_about', page_title: 'Giới thiệu Doanh nghiệp', page_path: '/about-us' },
    ],
    content: {
      headline: 'Tại Sao Hơn 500+ Nhà Máy Tin Tưởng Lựa Chọn Chúng Tôi?',
      subtitle: 'Cam kết chất lượng và dịch vụ kỹ thuật tiêu chuẩn Châu Âu',
      items_list: [
        { id: 'item_1', title: 'Tiêu Chuẩn Châu Âu ISO 9001', description: 'Toàn bộ linh kiện và giải pháp kiểm định nghiêm ngặt.', icon: 'ShieldCheck' },
        { id: 'item_2', title: 'Kỹ Thuật Viên Hỗ Trợ 24/7', description: 'Đội ngũ sự cố phản ứng nhanh trong vòng 2 giờ tại công trình.', icon: 'Clock' },
        { id: 'item_3', title: 'Bảo Hành Chính Hãng 36 Tháng', description: 'Cam kết thay thế linh kiện mới 100% khi có lỗi từ nhà sản xuất.', icon: 'Award' },
        { id: 'item_4', title: 'Tối Ưu Chi Phí 30%', description: 'Tư vấn đúng quy mô, hạn chế lãng phí năng lượng.', icon: 'Zap' },
      ],
    },
    display_order: 1,
    priority_weight: 8,
    start_time: '2026-01-01T00:00:00Z',
    end_time: '2027-12-31T23:59:59Z',
    auto_deactivate: false,
    workflow_status: 'published',
    effective_status: 'running',
    live_version: 'v1.0',
    draft_version: 'v1.0',
    has_draft_changes: false,
    created_at: '2025-12-15T11:00:00Z',
    updated_at: '2026-01-10T16:45:00Z',
  },
  {
    id: 'blk_004',
    title: 'Form Đặt Hàng & Yêu Cầu Báo Giá Nhanh Sidebar',
    code_alias: 'sidebar-quick-quote-form',
    type: 'module_embed',
    description: 'Embedded Widget Form yêu cầu tư vấn kỹ thuật đặt tại cột phải các trang sản phẩm.',
    tags: ['Sidebar', 'Form', 'Báo giá'],
    owner_name: 'Pham Quoc Anh',
    owner_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    show_title: true,
    layout_variant: 'compact_card',
    site_id: 'main_site',
    placement_id: 'plc_product_sidebar',
    placement_name: 'Cột bên trang chi tiết sản phẩm',
    scope: {
      site_id: 'main_site',
      apply_all_pages: false,
      included_pages: ['/products/*'],
      excluded_pages: [],
    },
    used_by_count: 8,
    used_by_pages: [
      { page_id: 'node_prod_detail', page_title: 'Chi tiết sản phẩm', page_path: '/products/*' },
    ],
    content: {
      headline: 'Yêu Cầu Báo Giá Nhanh',
      subtitle: 'Kỹ sư của chúng tôi sẽ gọi lại tư vấn trong 15 phút.',
      embed_code: '<iframe src="/embed/quote-form" width="100%" height="380" frameborder="0"></iframe>',
      cta_text: 'Gửi Yêu Cầu',
    },
    display_order: 1,
    priority_weight: 9,
    start_time: '2026-01-01T00:00:00Z',
    end_time: '2026-12-31T23:59:59Z',
    auto_deactivate: false,
    workflow_status: 'pending_review',
    effective_status: 'upcoming',
    live_version: 'v1.0',
    draft_version: 'v1.1-draft',
    has_draft_changes: true,
    created_at: '2026-01-28T14:10:00Z',
    updated_at: '2026-02-03T09:12:00Z',
  },
  {
    id: 'blk_005',
    title: 'Khối FAQ Câu Hỏi Thường Gặp Khi Mua Máy',
    code_alias: 'faq-accordion-purchasing',
    type: 'faq_accordion',
    description: 'Giải đáp các thắc mắc về tiến độ giao hàng, phương thức thanh toán và thủ tục CO/CQ.',
    tags: ['FAQ', 'Hỗ trợ', 'Chính sách'],
    owner_name: 'Trần Thị Thu',
    owner_avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    show_title: true,
    layout_variant: 'standard',
    site_id: 'main_site',
    placement_id: 'plc_product_sidebar',
    placement_name: 'Cột bên trang chi tiết sản phẩm',
    scope: {
      site_id: 'main_site',
      apply_all_pages: false,
      included_pages: ['/products/*', '/services/*'],
      excluded_pages: [],
    },
    used_by_count: 10,
    used_by_pages: [
      { page_id: 'node_prod_detail', page_title: 'Sản phẩm chi tiết', page_path: '/products/*' },
      { page_id: 'node_serv_consulting', page_title: 'Tư vấn giải pháp', page_path: '/services/consulting' },
    ],
    content: {
      headline: 'Câu Hỏi Thường Gặp Về Dịch Vụ',
      subtitle: 'Giải đáp nhanh các thắc mắc phổ biến của doanh nghiệp',
      items_list: [
        { id: 'faq_1', title: 'Thời gian giao hàng và lắp đặt mất bao lâu?', description: 'Thời gian sản xuất và lắp đặt tiêu chuẩn từ 7 đến 14 ngày làm việc tùy thuộc vào quy mô hệ thống.' },
        { id: 'faq_2', title: 'Sản phẩm có đầy đủ chứng nhận CO/CQ không?', description: 'Chúng tôi cam kết cung cấp 100% chứng nhận xuất xứ (CO) và chất lượng (CQ) đi kèm thiết bị.' },
        { id: 'faq_3', title: 'Chính sách bảo trì định kỳ như thế nào?', description: 'Mỗi hợp đồng cung cấp thiết bị đều tặng kèm 4 lần bảo trì định kỳ miễn phí trong năm đầu tiên.' },
      ],
    },
    display_order: 2,
    priority_weight: 5,
    start_time: '2026-01-01T00:00:00Z',
    end_time: '2026-12-31T23:59:59Z',
    auto_deactivate: false,
    workflow_status: 'published',
    effective_status: 'running',
    live_version: 'v1.1',
    draft_version: 'v1.1',
    has_draft_changes: false,
    created_at: '2026-01-05T09:30:00Z',
    updated_at: '2026-01-20T11:00:00Z',
  },
  {
    id: 'blk_006',
    title: 'Slide Đánh Giá Từ Khách Hàng Tiêu Biểu (Testimonials)',
    code_alias: 'testimonials-client-stories',
    type: 'testimonial_slider',
    description: 'Trích dẫn nhận xét từ VinFast, TH True Milk, Hoaphat Group.',
    tags: ['Đánh giá', 'Đối tác', 'Trang chủ'],
    owner_name: 'Nguyễn Văn Minh',
    owner_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    show_title: true,
    layout_variant: 'centered',
    site_id: 'main_site',
    placement_id: 'plc_features_section',
    placement_name: 'Khối tính năng & Giải pháp nổi bật',
    scope: {
      site_id: 'main_site',
      apply_all_pages: false,
      included_pages: ['/', '/about-us'],
      excluded_pages: [],
    },
    used_by_count: 2,
    used_by_pages: [
      { page_id: 'node_home', page_title: 'Trang chủ', page_path: '/' },
      { page_id: 'node_about', page_title: 'Giới thiệu Doanh nghiệp', page_path: '/about-us' },
    ],
    content: {
      headline: 'Ý Kiến Khách Hàng Về Giải Pháp Của Chúng Tôi',
      subtitle: 'Sự hài lòng của đối tác là đo lường thành công lớn nhất',
      items_list: [
        { id: 't_1', title: 'Giám Đốc Vận Hành - VinFast Sub-plant', description: 'Hệ thống điều khiển giúp chúng tôi giảm 35% thời gian dừng máy ngoài sự kiến.' },
        { id: 't_2', title: 'Trưởng Phòng Kỹ Thuật - Tập Đoàn Hòa Phát', description: 'Thiết bị bền bỉ, đội ngũ kỹ thuật viên có mặt hỗ trợ cực kỳ nhanh chóng.' },
      ],
    },
    display_order: 2,
    priority_weight: 7,
    start_time: '2026-01-01T00:00:00Z',
    end_time: '2026-12-31T23:59:59Z',
    auto_deactivate: false,
    workflow_status: 'draft',
    effective_status: 'inactive',
    live_version: 'v0.9',
    draft_version: 'v1.0-draft',
    has_draft_changes: true,
    created_at: '2026-02-01T15:00:00Z',
    updated_at: '2026-02-03T11:40:00Z',
  },
  {
    id: 'blk_007',
    title: 'Khối Đăng Ký Nhận Bản Tin Kỹ Thuật (Footer Newsletter)',
    code_alias: 'footer-newsletter-sub',
    type: 'rich_text',
    description: 'Chân trang gom email nhận bản tin cập nhật xu hướng công nghệ hàng tháng.',
    tags: ['Footer', 'Newsletter', 'Lead generation'],
    owner_name: 'Lê Hoàng Nam',
    owner_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    show_title: true,
    layout_variant: 'light_neutral',
    site_id: 'main_site',
    placement_id: 'plc_footer_cta',
    placement_name: 'Khối CTA đăng ký nhận tin (Footer)',
    scope: {
      site_id: 'main_site',
      apply_all_pages: true,
      included_pages: [],
      excluded_pages: [],
    },
    used_by_count: 15,
    used_by_pages: [{ page_id: 'node_home', page_title: 'Toàn bộ website (All Pages)', page_path: '*' }],
    content: {
      headline: 'Cập Nhật Xu Hướng Tự Động Hóa Mới Nhất Hàng Tháng',
      subtitle: 'Đăng ký nhận bản tin kỹ thuật chuyên sâu từ đội ngũ chuyên gia hàng đầu.',
      body_html: '<p>Cam kết không spam. Bạn có thể hủy đăng ký bất kỳ lúc nào chỉ với 1-click.</p>',
      cta_text: 'Đăng Ký Bản Tin',
      cta_url: '/subscribe',
    },
    display_order: 1,
    priority_weight: 10,
    start_time: '2026-01-01T00:00:00Z',
    end_time: '2028-01-01T00:00:00Z',
    auto_deactivate: false,
    workflow_status: 'published',
    effective_status: 'running',
    live_version: 'v1.0',
    draft_version: 'v1.0',
    has_draft_changes: false,
    created_at: '2025-11-20T10:00:00Z',
    updated_at: '2026-01-05T08:00:00Z',
  },
  {
    id: 'blk_008',
    title: 'Khối Mồ Côi Chưa Được Gắn Vào Vị Trí Nào (Orphan Block)',
    code_alias: 'campaign-spring-promo-draft',
    type: 'highlight_banner',
    description: 'Bản thảo banner khuyến mãi mùa xuân chưa được chọn Vị trí hiển thị.',
    tags: ['Chưa dùng', 'Draft', 'Khuyến mãi'],
    owner_name: 'Nguyễn Văn Minh',
    owner_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    show_title: true,
    layout_variant: 'standard',
    site_id: 'main_site',
    placement_id: '',
    placement_name: '(Chưa chọn vị trí)',
    scope: {
      site_id: 'main_site',
      apply_all_pages: false,
      included_pages: [],
      excluded_pages: [],
    },
    used_by_count: 0,
    used_by_pages: [],
    content: {
      headline: 'Chương Trình Tri Ân Khách Hàng Thân Thiết 2026',
      subtitle: 'Tặng ngay bộ phụ kiện thay thế cho đơn hàng dịch vụ trên 100 triệu.',
      cta_text: 'Tìm Hiểu Chi Tiết',
      cta_url: '/promotions/spring-2026',
    },
    display_order: 99,
    priority_weight: 1,
    start_time: '2026-03-01T00:00:00Z',
    end_time: '2026-04-30T23:59:59Z',
    auto_deactivate: true,
    workflow_status: 'draft',
    effective_status: 'inactive',
    live_version: '-',
    draft_version: 'v0.1-draft',
    has_draft_changes: true,
    created_at: '2026-02-02T16:00:00Z',
    updated_at: '2026-02-02T16:00:00Z',
  }
];

export const MOCK_ISSUES: ConflictIssue[] = [
  {
    id: 'iss_001',
    block_id: 'blk_004',
    block_title: 'Form Đặt Hàng & Yêu Cầu Báo Giá Nhanh Sidebar',
    placement_id: 'plc_product_sidebar',
    placement_name: 'Cột bên trang chi tiết sản phẩm',
    severity: 'high',
    issue_type: 'capacity_exceeded',
    description: 'Vị trí Cột bên trang sản phẩm đã đạt giới hạn 2 khối song song. Khối này xếp ưu tiên thứ 3 sẽ bị ẩn.',
    affected_pages: ['/products/industrial', '/products/automation'],
  },
  {
    id: 'iss_002',
    block_id: 'blk_008',
    block_title: 'Khối Mồ Côi Chưa Được Gắn Vào Vị Trí Nào (Orphan Block)',
    placement_id: '',
    placement_name: '(Chưa chọn vị trí)',
    severity: 'medium',
    issue_type: 'orphan_unused',
    description: 'Khối nội dung được tạo nhưng chưa gán Vị trí (Placement) hoặc Phạm vi (Scope) sử dụng.',
    affected_pages: [],
  },
];

export const MOCK_VERSIONS: BlockVersion[] = [
  {
    version_id: 'ver_200',
    block_id: 'blk_001',
    version_number: 2.0,
    published_at: '2026-01-15T09:00:00Z',
    published_by: 'Nguyễn Văn Minh (Content Manager)',
    change_summary: 'Cập nhật headline khuyến mãi Q1 và thay đổi media banner ảnh chất lượng cao 4K.',
    is_current_live: true,
    snapshot_data: {
      title: 'Khối Banner Hero & Đăng ký Tư vấn 2026',
      live_version: 'v2.0',
    },
  },
  {
    version_id: 'ver_100',
    block_id: 'blk_001',
    version_number: 1.0,
    published_at: '2026-01-01T08:00:00Z',
    published_by: 'Trần Thị Thu (Editor)',
    change_summary: 'Phiên bản khởi tạo ban đầu cho giao diện năm mới 2026.',
    is_current_live: false,
    snapshot_data: {
      title: 'Khối Banner Hero Khởi Tạo 2026',
      live_version: 'v1.0',
    },
  },
];
