import 'server-only';
import type { Sql } from 'postgres';
import { z } from 'zod';
import type { ProductCategoryLocale } from '@/features/product-categories/types';
import type { TrashEntityAdapter,TrashInspection } from '../registry-types';
import type { TrashRestoreMode } from '../../types';

const snapshotSchema=z.object({version:z.literal(1),locale:z.enum(['vi','en']),record:z.record(z.string(),z.unknown())});
const table=(l:ProductCategoryLocale)=>l==='en'?'cic_products_categories_en':'cic_products_categories';
const columns=['id','code','level','parent_id','published','image','icon','ordering','created_time','updated_time','show_in_homepage','show_in_footer','root_id','root_alias','list_parents','alias_wrapper','tablename','tags_group','total_products','vat','is_accessories','banner','promotion_main','hotline','link','published_image','promotion','price','type','sizes','alias','name','description','seo_title','seo_keyword','seo_description','summary'] as const;
export async function moveProductCategoryToTrash(sql:Sql,locale:ProductCategoryLocale,id:number,actorId:number){const source=table(locale),rel=locale==='en'?'cic_products_categories_rel_en':'cic_products_categories_rel';const[row]=await sql.unsafe(`SELECT ${columns.join(',')} FROM ${source} WHERE id=$1 FOR UPDATE`,[id]);if(!row)throw new Error('Không tìm thấy danh mục sản phẩm.');const[{count:children}]=await sql.unsafe(`SELECT count(*)::int count FROM ${source} WHERE parent_id=$1`,[id]);const[{count:usage}]=await sql.unsafe(`SELECT count(*)::int count FROM ${rel} WHERE category_id=$1`,[id]);if(Number(children)>0)throw new Error(`Danh mục còn ${children} danh mục con; hãy chuyển cấp con trước khi xóa.`);if(Number(usage)>0)throw new Error(`Danh mục đang được ${usage} sản phẩm sử dụng; hãy đổi phân loại trước khi xóa.`);const record=Object.fromEntries(columns.map(c=>[c,row[c] instanceof Date?(row[c] as Date).toISOString():row[c]]));const snapshot=snapshotSchema.parse({version:1,locale,record});const entityType=locale==='en'?'product_category_en':'product_category';const[trash]=await sql`INSERT INTO cic_trash_items (workspace,entity_type,entity_id,module,title_snapshot,payload_snapshot,original_url,status,deleted_by,purge_after,restore_state) VALUES (${locale},${entityType},${String(id)},'product_settings',${String(row.name??row.alias??id)},${sql.json(snapshot as never)},${`/products?category=${String(row.alias??id)}`},'trashed',${actorId},now()+interval '30 days','inactive') RETURNING id`;await sql.unsafe(`DELETE FROM ${source} WHERE id=$1`,[id]);return{trashId:String(trash.id),title:String(row.name??row.alias??id)};}
async function inspect(sql:Sql,value:unknown):Promise<TrashInspection>{const parsed=snapshotSchema.safeParse(value);if(!parsed.success)return{status:'schema_mismatch',details:'Snapshot danh mục sản phẩm không đúng phiên bản.',restoreModes:[]};const source=table(parsed.data.locale),record=parsed.data.record,id=Number(record.id),alias=String(record.alias??'');if((await sql.unsafe(`SELECT 1 FROM ${source} WHERE id=$1 LIMIT 1`,[id])).length)return{status:'conflict',details:'ID danh mục đã được sử dụng.',restoreModes:[]};if((await sql.unsafe(`SELECT 1 FROM ${source} WHERE lower(alias)=lower($1) LIMIT 1`,[alias])).length)return{status:'conflict',details:'Alias danh mục đã được sử dụng.',restoreModes:[]};const parentId=record.parent_id==null?null:Number(record.parent_id);if(parentId&&(await sql.unsafe(`SELECT 1 FROM ${source} WHERE id=$1`,[parentId])).length===0)return{status:'conflict',details:'Danh mục cha không còn tồn tại.',restoreModes:[]};return{status:'clear',details:'Danh mục sẵn sàng phục hồi ở trạng thái ngừng hiển thị.',restoreModes:['as_draft']};}
async function restore(sql:Sql,value:unknown,mode:TrashRestoreMode){const s=snapshotSchema.parse(value),check=await inspect(sql,s);if(!check.restoreModes.includes(mode))throw new Error(check.details);const source=table(s.locale),r=s.record;const restored:Record<string,unknown>={...r,published:false,updated_time:new Date()};const values=columns.map(c=>(restored[c]??null) as never);await sql.unsafe(`INSERT INTO ${source} (${columns.join(',')}) OVERRIDING SYSTEM VALUE VALUES (${columns.map((_,i)=>`$${i+1}`).join(',')})`,values);return{title:String(r.name??r.alias??r.id),restoredEntityId:String(r.id),restoredState:'inactive' as const};}
export const productCategoryTrashAdapter:TrashEntityAdapter={entityType:'product_category',module:'product_settings',label:'Danh mục sản phẩm',itemType:'Danh mục sản phẩm',workspace:'vi',restoreState:'inactive',supportsPurge:true,getRevalidationTargets:()=>[{path:'/cms/product-categories'},{path:'/products'},{path:'/products/[slug]',type:'page'}],parseSnapshot:v=>snapshotSchema.parse(v),inspect,restore,purge:async()=>undefined,presentSnapshot:v=>{const s=snapshotSchema.parse(v);return{version:s.version,locale:s.locale,name:s.record.name,alias:s.record.alias,parentId:s.record.parent_id,publishedBeforeDelete:s.record.published}}};
export const productCategoryEnTrashAdapter:TrashEntityAdapter={...productCategoryTrashAdapter,entityType:'product_category_en',workspace:'en'};
