import 'server-only';
import type { Sql } from 'postgres';
import { z } from 'zod';
import type { ServiceLocale } from '@/features/services/types';
import type { TrashEntityAdapter,TrashInspection } from '../registry-types';
import type { TrashRestoreMode } from '../../types';
const schema=z.object({version:z.literal(1),locale:z.enum(['vi','en']),record:z.record(z.string(),z.unknown()),products:z.array(z.object({id:z.number().int(),ordering:z.number().int()}))});
const tables=(locale:ServiceLocale)=>locale==='en'?{service:'cic_services_en',relation:'cic_services_products_rel_en',product:'cic_products_en'}:{service:'cic_services',relation:'cic_services_products_rel',product:'cic_products'};
export async function moveServiceToTrash(sql:Sql,locale:ServiceLocale,id:number,actorId:number){const t=tables(locale),[row]=await sql.unsafe(`SELECT to_jsonb(s) record FROM ${t.service} s WHERE id=$1 FOR UPDATE`,[id]);if(!row)throw new Error('Không tìm thấy dịch vụ.');const products=await sql.unsafe(`SELECT product_id,ordering FROM ${t.relation} WHERE service_id=$1 ORDER BY ordering,product_id`,[id]);const snapshot=schema.parse({version:1,locale,record:row.record,products:products.map(value=>({id:Number(value.product_id),ordering:Number(value.ordering??0)}))});const title=String(snapshot.record.title??id);const[trash]=await sql`INSERT INTO cic_trash_items(workspace,entity_type,entity_id,module,title_snapshot,payload_snapshot,original_url,status,deleted_by,purge_after,restore_state) VALUES(${locale},${locale==='en'?'service_en':'service'},${String(id)},'services',${title},${sql.json(snapshot as never)},${`/services/${snapshot.record.alias??id}`},'trashed',${actorId},now()+interval '30 days','draft') RETURNING id`;await sql.unsafe(`DELETE FROM ${t.service} WHERE id=$1`,[id]);return{trashId:String(trash.id),title};}
async function inspect(sql:Sql,raw:unknown):Promise<TrashInspection>{const parsed=schema.safeParse(raw);if(!parsed.success)return{status:'schema_mismatch',details:'Snapshot Dịch vụ không hợp lệ.',restoreModes:[]};const t=tables(parsed.data.locale),id=Number(parsed.data.record.id),alias=String(parsed.data.record.alias??'');if((await sql.unsafe(`SELECT 1 FROM ${t.service} WHERE id=$1`,[id])).length)return{status:'conflict',details:'ID Dịch vụ đã được sử dụng.',restoreModes:[]};if((await sql.unsafe(`SELECT 1 FROM ${t.service} WHERE lower(btrim(alias))=lower(btrim($1))`,[alias])).length)return{status:'conflict',details:'Alias Dịch vụ đã được sử dụng.',restoreModes:[]};const productIds=[...new Set(parsed.data.products.map(value=>value.id))];if(productIds.length&&(await sql.unsafe(`SELECT id FROM ${t.product} WHERE id=ANY($1::int[])`,[productIds])).length!==productIds.length)return{status:'conflict',details:'Một số Sản phẩm liên quan không còn tồn tại.',restoreModes:[]};return{status:'clear',details:'Sẵn sàng phục hồi về bản nháp.',restoreModes:['as_draft']};}
async function restore(sql:Sql,raw:unknown,mode:TrashRestoreMode){const snapshot=schema.parse(raw),check=await inspect(sql,snapshot);if(!check.restoreModes.includes(mode))throw new Error(check.details);const t=tables(snapshot.locale),record:Record<string,unknown>={...snapshot.record,published:0,updated_time:new Date().toISOString()},columns=Object.keys(record);if(columns.some(column=>!/^[_a-z][_a-z0-9]*$/i.test(column)))throw new Error('Snapshot Dịch vụ chứa tên cột không hợp lệ.');await sql.unsafe(`INSERT INTO ${t.service} (${columns.map(column=>`"${column}"`).join(',')}) OVERRIDING SYSTEM VALUE VALUES (${columns.map((_,index)=>`$${index+1}`).join(',')})`,columns.map(column=>(record[column]??null) as never));for(const product of snapshot.products)await sql.unsafe(`INSERT INTO ${t.relation}(service_id,product_id,ordering) VALUES($1,$2,$3)`,[Number(record.id),product.id,product.ordering]);return{title:String(record.title??record.id),restoredEntityId:String(record.id),restoredState:'draft' as const};}
const adapter=(locale:ServiceLocale):TrashEntityAdapter=>({entityType:locale==='en'?'service_en':'service',module:'services',label:'Dịch vụ',itemType:'Dịch vụ',workspace:locale,restoreState:'draft',supportsPurge:true,getRevalidationTargets:()=>[{path:'/cms/services'},{path:'/services'},{path:'/services/[slug]',type:'page'}],parseSnapshot:value=>schema.parse(value),inspect,restore,purge:async()=>undefined,presentSnapshot:value=>{const snapshot=schema.parse(value);return{version:snapshot.version,title:snapshot.record.title,slug:snapshot.record.alias,products:snapshot.products.length};}});
export const serviceTrashAdapter=adapter('vi');export const serviceEnTrashAdapter=adapter('en');
