import {
  MasterCategoryItem,
  MasterBrandItem,
  MasterApplicationItem,
  MasterProductTypeItem,
  MasterSalesStaffItem,
  MasterRoutingRuleItem,
  UsageImpactRecord,
  MasterDataActivityLog,
  OverviewMetrics,
} from './types';

// 1. Categories (Hierarchical Taxonomy)
export const mockMasterCategories: MasterCategoryItem[] = [
  {
    id: 'cat_001',
    type: 'categories',
    name: 'Phần mềm Thiết kế Kết cấu & Xây dựng',
    code: 'CAT-KETCAU',
    slug: 'phan-mem-thiet-ke-ket-cau',
    status: 'active',
    ordering: 1,
    level: 1,
    parent_id: null,
    usage_count: 85,
    description: 'Bộ giải pháp phần mềm mô phỏng, phân tích và tính toán kết cấu bê tông, cốt thép, khung nhà cao tầng.',
    icon: 'Building2',
    image: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=300&auto=format&fit=crop&q=80',
    meta_title: 'Phần mềm Thiết kế Kết cấu | Công ty CIC',
    meta_description: 'Phân phối phần mềm ETABS, SAP2000, SAFE bản quyền chính hãng tại Việt Nam.',
    canonical_url: 'https://cic.com.vn/danh-muc/phan-mem-ket-cau',
    site_scope: ['main_website', 'portal_bim', 'store_software'],
    created_time: '2025-01-15 08:30:00',
    updated_time: '2026-07-28 14:20:00',
    updated_by: 'Lê Hoàng Nam',
  },
  {
    id: 'cat_002',
    type: 'categories',
    name: 'Tính toán nhà cao tầng & Động đất',
    code: 'CAT-CAOTANG',
    slug: 'tinh-toan-nha-cao-tang',
    status: 'active',
    ordering: 2,
    level: 2,
    parent_id: 'cat_001',
    parent_name: 'Phần mềm Thiết kế Kết cấu & Xây dựng',
    usage_count: 42,
    description: 'Chuyên biệt cho ETABS, SAP2000 tính toán phổ phản ứng động đất và tải trọng gió cơ học.',
    icon: 'Layers',
    site_scope: ['main_website', 'store_software'],
    created_time: '2025-02-10 10:15:00',
    updated_time: '2026-07-25 09:10:00',
    updated_by: 'Vũ Quốc Huy',
  },
  {
    id: 'cat_003',
    type: 'categories',
    name: 'Phần mềm Địa kỹ thuật & Móng cọc',
    code: 'CAT-DIAKYTHUAT',
    slug: 'phan-mem-dia-ky-thuat',
    status: 'active',
    ordering: 3,
    level: 1,
    parent_id: null,
    usage_count: 38,
    description: 'Mô phỏng ổn định mái dốc, xử lý nền đất yếu, móng cọc rời rạc và hầm ngầm đô thị.',
    icon: 'Cpu',
    image: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?w=300&auto=format&fit=crop&q=80',
    meta_title: 'Phần mềm Địa kỹ thuật & Công trình ngầm - PLAXIS Studio',
    meta_description: 'Phân tích ổn định đất nền, móng sâu và đập thủy điện.',
    site_scope: ['main_website', 'store_software'],
    created_time: '2025-01-20 11:00:00',
    updated_time: '2026-07-30 16:45:00',
    updated_by: 'Nguyễn Minh Quân',
  },
  {
    id: 'cat_004',
    type: 'categories',
    name: 'Giải pháp Mô hình hóa BIM & CDE',
    code: 'CAT-BIM-CDE',
    slug: 'giai-phap-bim-cde',
    status: 'active',
    ordering: 4,
    level: 1,
    parent_id: null,
    usage_count: 56,
    description: 'Hệ thống quản lý dữ liệu môi trường CDE chung, phần mềm EnjiCAD, Bentley iTwin và Revit add-ins.',
    icon: 'FolderTree',
    image: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=300&auto=format&fit=crop&q=80',
    meta_title: 'Tư vấn Chuyển đổi số BIM & CDE cho Doanh nghiệp Xây dựng',
    meta_description: 'Chuẩn hóa quy trình BIM ISO 19650.',
    site_scope: ['main_website', 'portal_bim'],
    created_time: '2025-03-01 09:00:00',
    updated_time: '2026-07-31 10:05:00',
    updated_by: 'Phạm Thị Hương',
  },
  {
    id: 'cat_005',
    type: 'categories',
    name: 'Phần mềm Dự toán & Quản lý Chi phí ESCON',
    code: 'CAT-DUTOAN',
    slug: 'phan-mem-du-toan-chi-phi',
    status: 'active',
    ordering: 5,
    level: 1,
    parent_id: null,
    usage_count: 64,
    description: 'Lập dự toán công trình xây dựng, thanh quyết toán vốn đầu tư công theo đơn giá Bộ Xây dựng.',
    icon: 'FileCheck',
    site_scope: ['main_website', 'store_software'],
    created_time: '2025-01-05 14:00:00',
    updated_time: '2026-07-29 11:30:00',
    updated_by: 'Trần Hoài Anh',
  },
  {
    id: 'cat_006',
    type: 'categories',
    name: 'Thiết bị Khảo sát Đo đạc & Cảm biến',
    code: 'CAT-THIETBI',
    slug: 'thiet-bi-khao-sat-do-dac',
    status: 'inactive',
    ordering: 6,
    level: 1,
    parent_id: null,
    usage_count: 12,
    description: 'Máy toàn đạc điện tử, cảm biến quan trắc chuyển vị công trình ngầm (tạm dừng nhập khẩu).',
    icon: 'Package',
    site_scope: ['main_website'],
    created_time: '2025-04-12 16:20:00',
    updated_time: '2026-07-15 13:00:00',
    updated_by: 'Admin CIC',
  },
];

// 2. Brands / Manufacturers
export const mockMasterBrands: MasterBrandItem[] = [
  {
    id: 'brd_001',
    type: 'brands',
    name: 'CSI Computers & Structures, Inc.',
    code: 'BRAND-CSI',
    status: 'active',
    ordering: 1,
    usage_count: 78,
    country: 'Mỹ (USA)',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=120&auto=format&fit=crop&q=80',
    website: 'https://www.csiamerica.com',
    is_featured: true,
    description: 'Hãng sản xuất hàng đầu thế giới về phần mềm phân tích kết cấu ETABS, SAP2000, SAFE, CSiBridge.',
    created_time: '2025-01-01 08:00:00',
    updated_time: '2026-07-31 09:00:00',
  },
  {
    id: 'brd_002',
    type: 'brands',
    name: 'Bentley Systems',
    code: 'BRAND-BENTLEY',
    status: 'active',
    ordering: 2,
    usage_count: 52,
    country: 'Mỹ (USA)',
    logo: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=120&auto=format&fit=crop&q=80',
    website: 'https://www.bentley.com',
    is_featured: true,
    description: 'Cung cấp hạ tầng kỹ thuật, phần mềm MicroStation, StaadPro, OpenRoads và PLAXIS.',
    created_time: '2025-01-02 09:30:00',
    updated_time: '2026-07-30 15:20:00',
  },
  {
    id: 'brd_003',
    type: 'brands',
    name: 'CIC Software Technology (ESCON / EnjiCAD)',
    code: 'BRAND-CIC-TECH',
    status: 'active',
    ordering: 3,
    usage_count: 95,
    country: 'Việt Nam',
    logo: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=120&auto=format&fit=crop&q=80',
    website: 'https://cic.com.vn',
    is_featured: true,
    description: 'Thương hiệu sản phẩm phần mềm tự phát triển bởi Công ty CIC: ESCON, EnjiCAD, PilesStudio.',
    created_time: '2025-01-01 08:00:00',
    updated_time: '2026-07-31 11:00:00',
  },
  {
    id: 'brd_004',
    type: 'brands',
    name: 'MIDAS IT Co., Ltd.',
    code: 'BRAND-MIDAS',
    status: 'active',
    ordering: 4,
    usage_count: 34,
    country: 'Hàn Quốc',
    logo: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=120&auto=format&fit=crop&q=80',
    website: 'https://www.midasit.com',
    is_featured: false,
    description: 'Giải pháp mô phỏng kết cấu cầu đường MIDAS Civil, MIDAS Gen và GTS NX.',
    created_time: '2025-02-15 11:20:00',
    updated_time: '2026-07-28 10:15:00',
  },
  {
    id: 'brd_005',
    type: 'brands',
    name: 'Glodon Company Limited',
    code: 'BRAND-GLODON',
    status: 'inactive',
    ordering: 5,
    usage_count: 8,
    country: 'Trung Quốc',
    logo: 'https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=120&auto=format&fit=crop&q=80',
    website: 'https://www.glodon.com',
    is_featured: false,
    description: 'Giải pháp đo bóc khối lượng Cubicost BIM 5D (Đang đàm phán lại hợp đồng hợp tác).',
    created_time: '2025-03-10 14:00:00',
    updated_time: '2026-06-20 09:00:00',
  },
];

// 3. Application Areas / Lĩnh vực ứng dụng
export const mockMasterApplications: MasterApplicationItem[] = [
  {
    id: 'app_001',
    type: 'applications',
    name: 'Kết cấu Nhà cao tầng & Đô thị',
    code: 'APP-CAOTANG',
    status: 'active',
    ordering: 1,
    usage_count: 92,
    sector_group: 'Kết cấu Dân dụng & Công nghiệp',
    color_badge: 'bg-blue-500/10 text-blue-600 border-blue-500/20',
    icon: 'Building2',
    description: 'Ứng dụng trong thiết kế khung vách bê tông cốt thép, chịu lực động đất & bão lũ.',
    created_time: '2025-01-05 09:00:00',
    updated_time: '2026-07-30 08:00:00',
  },
  {
    id: 'app_002',
    type: 'applications',
    name: 'Công trình Cầu đường & Giao thông',
    code: 'APP-CAUDUONG',
    status: 'active',
    ordering: 2,
    usage_count: 61,
    sector_group: 'Hạ tầng Giao thông',
    color_badge: 'bg-emerald-500/10 text-emerald-600 border-emerald-500/20',
    icon: 'Navigation',
    description: 'Thiết kế cầu dầm văng, cầu dây văng, hầm chui giao thông và tuyến đường cao tốc.',
    created_time: '2025-01-10 10:30:00',
    updated_time: '2026-07-29 14:00:00',
  },
  {
    id: 'app_003',
    type: 'applications',
    name: 'Địa kỹ thuật & Xử lý Nền móng',
    code: 'APP-NOMONG',
    status: 'active',
    ordering: 3,
    usage_count: 48,
    sector_group: 'Địa kỹ thuật & Môi trường',
    color_badge: 'bg-amber-500/10 text-amber-600 border-amber-500/20',
    icon: 'Cpu',
    description: 'Mô phỏng cơ học đất, hố đào sâu, tường vằn cọc nhồi và sạt lở đập chứa nước.',
    created_time: '2025-02-01 13:15:00',
    updated_time: '2026-07-31 10:30:00',
  },
  {
    id: 'app_004',
    type: 'applications',
    name: 'Lập Dự toán & Quản lý Chi phí Xây dựng',
    code: 'APP-DUTOAN',
    status: 'active',
    ordering: 4,
    usage_count: 80,
    sector_group: 'Quản lý Dự án & Chi phí',
    color_badge: 'bg-purple-500/10 text-purple-600 border-purple-500/20',
    icon: 'FileCheck',
    description: 'Tra cứu đơn giá, định mức Bộ Xây dựng, đấu thầu xây lắp công trình công cộng.',
    created_time: '2025-01-02 08:30:00',
    updated_time: '2026-07-30 15:00:00',
  },
  {
    id: 'app_005',
    type: 'applications',
    name: 'Tư vấn Đào tạo & Chuyển giao Công nghệ BIM',
    code: 'APP-DAOTAOBIM',
    status: 'active',
    ordering: 5,
    usage_count: 35,
    sector_group: 'Đào tạo & Tư vấn Chuyển đổi số',
    color_badge: 'bg-orange-500/10 text-orange-600 border-orange-500/20',
    icon: 'FolderTree',
    description: 'Đào tạo cấp chứng chỉ Revit, EnjiCAD, ETABS cho kỹ sư các Tổng công ty tư vấn.',
    created_time: '2025-03-05 11:00:00',
    updated_time: '2026-07-28 16:10:00',
  },
];

// 4. Product Types / Loại sản phẩm
export const mockMasterProductTypes: MasterProductTypeItem[] = [
  {
    id: 'type_001',
    type: 'product_types',
    name: 'Phần mềm Bản quyền Desktop (Single License)',
    code: 'TYPE-SOFT-DESKTOP',
    type_code: 'software_desktop',
    status: 'active',
    ordering: 1,
    usage_count: 120,
    requires_license_key: true,
    pricing_model_default: 'quote',
    icon: 'Package',
    description: 'Cài đặt trực tiếp trên máy tính cá nhân dùng khóa cứng USB hoặc Standalone Key.',
    created_time: '2025-01-01 08:00:00',
    updated_time: '2026-07-31 09:00:00',
  },
  {
    id: 'type_002',
    type: 'product_types',
    name: 'Phần mềm Mạng Doanh nghiệp (Network / Cloud License)',
    code: 'TYPE-SOFT-NETWORK',
    type_code: 'software_cloud',
    status: 'active',
    ordering: 2,
    usage_count: 65,
    requires_license_key: true,
    pricing_model_default: 'quote',
    icon: 'Globe',
    description: 'Quản lý số lượng concurrent license dùng chung trong mạng LAN / Cloud Server.',
    created_time: '2025-01-05 09:30:00',
    updated_time: '2026-07-30 11:20:00',
  },
  {
    id: 'type_003',
    type: 'product_types',
    name: 'Gói Dịch vụ Tư vấn, Đào tạo & Khảo sát',
    code: 'TYPE-SERVICE',
    type_code: 'service_consulting',
    status: 'active',
    ordering: 3,
    usage_count: 40,
    requires_license_key: false,
    pricing_model_default: 'fixed_price',
    icon: 'Layers',
    description: 'Đào tạo kỹ thuật chuyên sâu, chuyển giao công nghệ phần mềm và hỗ trợ thẩm tra dự án.',
    created_time: '2025-02-10 14:00:00',
    updated_time: '2026-07-29 10:00:00',
  },
  {
    id: 'type_004',
    type: 'product_types',
    name: 'Gói Bảo trì & Nâng cấp định kỳ (Maintenance Contract)',
    code: 'TYPE-MAINTENANCE',
    type_code: 'subscription',
    status: 'active',
    ordering: 4,
    usage_count: 32,
    requires_license_key: true,
    pricing_model_default: 'subscription',
    icon: 'RotateCcw',
    description: 'Gia hạn support kỹ thuật 1 năm, update phiên bản mới v21, v22 định kỳ.',
    created_time: '2025-03-01 10:00:00',
    updated_time: '2026-07-28 15:40:00',
  },
];

// 5. Sales Staff / Người phụ trách
export const mockMasterSalesStaff: MasterSalesStaffItem[] = [
  {
    id: '32', type: 'sales_staff', name: 'Đức Thành', code: 'duc-thanh', alias: 'duc-thanh',
    phone: '0966904015', skype: '', zalo: '0966904015', status: 'active', ordering: 27, usage_count: 0,
    contact_product_ids: ['prod_001', 'prod_demo_006'], sales_product_ids: ['prod_001', 'prod_demo_007'], technical_support_product_ids: ['prod_demo_008'],
    north_sales_product_ids: ['prod_001', 'prod_demo_006', 'prod_demo_007'], south_sales_product_ids: [],
    created_time: '2025-08-26 08:00:00', updated_time: '2025-08-26 08:00:00',
  },
  {
    id: '31', type: 'sales_staff', name: 'Hiền Phạm', code: 'hien-pham', alias: 'hien-pham',
    phone: '0949249315', skype: '', zalo: '0949249315', status: 'active', ordering: 26, usage_count: 0,
    contact_product_ids: ['prod_002', 'prod_demo_012'], sales_product_ids: ['prod_002', 'prod_demo_013'], technical_support_product_ids: ['prod_demo_012'],
    north_sales_product_ids: [], south_sales_product_ids: ['prod_002', 'prod_demo_012', 'prod_demo_013'],
    created_time: '2025-02-06 08:00:00', updated_time: '2025-02-06 08:00:00',
  },
  {
    id: '30', type: 'sales_staff', name: 'Tổng đài miền Bắc', code: 'tong-dai-mien-bac', alias: 'tong-dai-mien-bac',
    phone: '088 646 2020', skype: '', zalo: '', status: 'active', ordering: 25, usage_count: 0,
    contact_product_ids: [], sales_product_ids: [], technical_support_product_ids: [],
    north_sales_product_ids: ['prod_001', 'prod_003'], south_sales_product_ids: [],
    created_time: '2025-02-06 08:00:00', updated_time: '2025-02-06 08:00:00',
  },
  {
    id: '24', type: 'sales_staff', name: 'Trọng Tiến', code: 'trong-tien', alias: 'trong-tien',
    phone: '032 927 1885', skype: '0329271885', zalo: '0329271885', status: 'active', ordering: 19, usage_count: 0,
    contact_product_ids: ['prod_003'], sales_product_ids: ['prod_003'], technical_support_product_ids: ['prod_003'],
    north_sales_product_ids: ['prod_003'], south_sales_product_ids: [],
    created_time: '2020-02-28 08:00:00', updated_time: '2020-02-28 08:00:00',
  },
  {
    id: '23', type: 'sales_staff', name: 'Hoàng Yến', code: 'hoang-yen', alias: 'hoang-yen',
    phone: '0934 045 088', skype: 'yen.nguyen4311', zalo: '0934 045 088', status: 'active', ordering: 18, usage_count: 0,
    contact_product_ids: ['prod_001', 'prod_002'], sales_product_ids: ['prod_001', 'prod_002'], technical_support_product_ids: [],
    north_sales_product_ids: ['prod_001', 'prod_002'], south_sales_product_ids: [],
    created_time: '2020-02-28 08:00:00', updated_time: '2020-02-28 08:00:00',
  },
];

// 6. Contact Email & Order Routing Rules
export const mockMasterRoutingRules: MasterRoutingRuleItem[] = [
  {
    id: 'rule_001',
    type: 'routing_rules',
    name: 'Phân luồng Báo giá CSI America (ETABS / SAP2000)',
    code: 'RULE-CSI-ETABS',
    priority: 1,
    status: 'active',
    ordering: 1,
    usage_count: 145,
    scope_category_ids: ['cat_001', 'cat_002'],
    scope_brand_ids: ['brd_001'],
    trigger_keywords: ['etabs', 'sap2000', 'safe', 'csibridge', 'mô hình kết cấu'],
    primary_sales_id: 'staff_001',
    primary_sales_name: 'Lê Hoàng Nam',
    fallback_email: 'etabs-sales@cic.com.vn',
    notify_cc_emails: ['phongkinhdoanh@cic.com.vn', 'admin@cic.com.vn'],
    working_version: false,
    last_test_passed: true,
    description: 'Tự động gửi thông tin liên hệ mua ETABS cho Trưởng phòng Lê Hoàng Nam xử lý trong 15 phút.',
    created_time: '2025-01-01 08:00:00',
    updated_time: '2026-07-31 09:00:00',
  },
  {
    id: 'rule_002',
    type: 'routing_rules',
    name: 'Phân luồng Địa kỹ thuật Bentley PLAXIS & MIDAS',
    code: 'RULE-PLAXIS-MIDAS',
    priority: 2,
    status: 'active',
    ordering: 2,
    usage_count: 82,
    scope_category_ids: ['cat_003'],
    scope_brand_ids: ['brd_002', 'brd_004'],
    trigger_keywords: ['plaxis', 'midas', 'móng cọc', 'mái dốc', 'địa kỹ thuật'],
    primary_sales_id: 'staff_002',
    primary_sales_name: 'Vũ Quốc Huy',
    fallback_email: 'tech-geotech@cic.com.vn',
    notify_cc_emails: ['phongkinhdoanh@cic.com.vn'],
    working_version: false,
    last_test_passed: true,
    description: 'Gửi yêu cầu tư vấn kỹ thuật đất nền cho chuyên viên Vũ Quốc Huy.',
    created_time: '2025-01-10 10:00:00',
    updated_time: '2026-07-30 16:30:00',
  },
  {
    id: 'rule_003',
    type: 'routing_rules',
    name: 'Phân luồng Dự toán ESCON & Phần mềm Việt',
    code: 'RULE-ESCON-ENJICAD',
    priority: 3,
    status: 'active',
    ordering: 3,
    usage_count: 110,
    scope_category_ids: ['cat_005'],
    scope_brand_ids: ['brd_003'],
    trigger_keywords: ['escon', 'dự toán', 'enjicad', 'khóa cứng', 'đơn giá'],
    primary_sales_id: 'staff_003',
    primary_sales_name: 'Trần Hoài Anh',
    fallback_email: 'escon@dutoan.vn',
    notify_cc_emails: ['hotro@cic.com.vn'],
    working_version: false,
    last_test_passed: true,
    description: 'Chuyển thông tin yêu cầu mua khóa USB Escon cho Trần Hoài Anh.',
    created_time: '2025-01-15 11:30:00',
    updated_time: '2026-07-29 11:15:00',
  },
  {
    id: 'rule_004',
    type: 'routing_rules',
    name: 'Phân luồng Tư vấn Chuyển đổi số & Khóa học BIM',
    code: 'RULE-BIM-CONSULTING',
    priority: 4,
    status: 'active',
    ordering: 4,
    usage_count: 65,
    scope_category_ids: ['cat_004'],
    scope_brand_ids: [],
    trigger_keywords: ['bim', 'cde', 'đào tạo', 'chứng chỉ', 'revit'],
    primary_sales_id: 'staff_004',
    primary_sales_name: 'Phạm Thị Hương',
    fallback_email: 'bim@cic.com.vn',
    notify_cc_emails: ['daotao@cic.com.vn'],
    working_version: false,
    last_test_passed: true,
    description: 'Gửi đăng ký hội thảo & tư vấn quy trình CDE cho bộ phận BIM.',
    created_time: '2025-02-01 14:00:00',
    updated_time: '2026-07-31 10:10:00',
  },
  {
    id: 'rule_005',
    type: 'routing_rules',
    name: 'Quy tắc Mặc định (Fallback Default Routing)',
    code: 'RULE-DEFAULT-FALLBACK',
    priority: 99,
    status: 'active',
    ordering: 5,
    usage_count: 310,
    scope_category_ids: [],
    scope_brand_ids: [],
    trigger_keywords: ['*'],
    primary_sales_id: 'staff_001',
    primary_sales_name: 'Lê Hoàng Nam',
    fallback_email: 'phongkinhdoanh@cic.com.vn',
    notify_cc_emails: ['admin@cic.com.vn', 'cskh@cic.com.vn'],
    working_version: false,
    last_test_passed: true,
    description: 'Tiếp nhận tất cả các liên hệ chung hoặc sản phẩm không trùng các quy tắc ưu tiên trên.',
    created_time: '2025-01-01 08:00:00',
    updated_time: '2026-07-31 09:00:00',
  },
];

// Usage Impact Records Mock
export const mockUsageImpactRecords: UsageImpactRecord[] = [
  {
    id: 'prod_etabs_01',
    type: 'product',
    title: 'CSI ETABS Ultimate v21 (Bản quyền vĩnh viễn)',
    sku_or_code: 'ETABS-ULT-21',
    category_name: 'Phần mềm Thiết kế Kết cấu & Xây dựng',
    owner_name: 'Lê Hoàng Nam',
    status: 'PUBLISHED',
    updated_time: '2026-07-31 08:45',
  },
  {
    id: 'prod_sap2000_02',
    type: 'product',
    title: 'CSI SAP2000 Advanced v25 (Network License)',
    sku_or_code: 'SAP2000-ADV-25',
    category_name: 'Phần mềm Thiết kế Kết cấu & Xây dựng',
    owner_name: 'Lê Hoàng Nam',
    status: 'PUBLISHED',
    updated_time: '2026-07-30 14:20',
  },
  {
    id: 'prod_plaxis_03',
    type: 'product',
    title: 'Bentley PLAXIS 3D Ultimate 2026',
    sku_or_code: 'PLAXIS-3D-2026',
    category_name: 'Phần mềm Địa kỹ thuật & Móng cọc',
    owner_name: 'Vũ Quốc Huy',
    status: 'PUBLISHED',
    updated_time: '2026-07-29 16:00',
  },
  {
    id: 'prod_escon_04',
    type: 'product',
    title: 'Dự toán ESCON Professional (Khóa USB)',
    sku_or_code: 'ESCON-PRO-2026',
    category_name: 'Phần mềm Dự toán & Quản lý Chi phí ESCON',
    owner_name: 'Trần Hoài Anh',
    status: 'PUBLISHED',
    updated_time: '2026-07-28 11:30',
  },
  {
    id: 'inq_901',
    type: 'contact_inquiry',
    title: 'Yêu cầu báo giá ETABS 35 chỗ cho Tập đoàn Vinaconex',
    sku_or_code: 'INQ-VINACONEX-01',
    category_name: 'Tính toán nhà cao tầng & Động đất',
    owner_name: 'Lê Hoàng Nam',
    status: 'PROCESSING',
    updated_time: '2026-07-31 08:50',
  },
];

// Activity Logs Mock
export const mockMasterActivityLogs: MasterDataActivityLog[] = [
  {
    id: 'log_m01',
    item_type: 'categories',
    item_id: 'cat_001',
    item_name: 'Phần mềm Thiết kế Kết cấu & Xây dựng',
    user_name: 'Lê Hoàng Nam',
    user_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    action: 'update',
    details: 'Cập nhật thẻ Meta Description SEO và cấu hình site scope',
    impact_count: 85,
    timestamp: '2026-07-31 10:30:15',
  },
  {
    id: 'log_m03',
    item_type: 'sales_staff',
    item_id: 'staff_005',
    item_name: 'Nguyễn Minh Quân',
    user_name: 'Admin CIC',
    action: 'deactivate',
    details: 'Chuyển trạng thái Inactive do nghỉ thai sản và bàn giao phụ trách tạm thời cho Lê Hoàng Nam',
    impact_count: 12,
    timestamp: '2026-07-10 13:30:00',
  },
  {
    id: 'log_m04',
    item_type: 'brands',
    item_id: 'brd_005',
    item_name: 'Glodon Company Limited',
    user_name: 'Admin CIC',
    action: 'deactivate',
    details: 'Tạm ngưng hiển thị thương hiệu Glodon do chờ đàm phán gia hạn hợp đồng distributor',
    impact_count: 8,
    timestamp: '2026-06-20 09:00:00',
  },
];

// Summary Overview Metrics
export const mockOverviewMetrics: OverviewMetrics = {
  total_categories: 6,
  total_brands: 5,
  total_applications: 5,
  total_product_types: 4,
  total_sales_staff: 5,
  total_routing_rules: 5,
  issue_dependency_count: 1, // Glodon or Equipment inactive but used
  inactive_items_count: 3,
  archived_items_count: 0,
};
